<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
/* क्रम use by sys-$SUBARCH/kernel-offsets.c */
#समावेश <stub-data.h>

DEFINE(KERNEL_MADV_REMOVE, MADV_REMOVE);

DEFINE(UM_KERN_PAGE_SIZE, PAGE_SIZE);
DEFINE(UM_KERN_PAGE_MASK, PAGE_MASK);
DEFINE(UM_KERN_PAGE_SHIFT, PAGE_SHIFT);
DEFINE(UM_NSEC_PER_SEC, NSEC_PER_SEC);

DEFINE(UM_ELF_CLASS, ELF_CLASS);
DEFINE(UM_ELFCLASS32, ELFCLASS32);
DEFINE(UM_ELFCLASS64, ELFCLASS64);

DEFINE(UM_NR_CPUS, NR_CPUS);

DEFINE(UM_GFP_KERNEL, GFP_KERNEL);
DEFINE(UM_GFP_ATOMIC, GFP_ATOMIC);

/* For crypto assembler code. */
DEFINE(crypto_tfm_ctx_offset, दुरत्व(काष्ठा crypto_tfm, __crt_ctx));

DEFINE(UM_THREAD_SIZE, THREAD_SIZE);

DEFINE(UM_HZ, HZ);

DEFINE(UM_USEC_PER_SEC, USEC_PER_SEC);
DEFINE(UM_NSEC_PER_SEC, NSEC_PER_SEC);
DEFINE(UM_NSEC_PER_USEC, NSEC_PER_USEC);

#अगर_घोषित CONFIG_PRINTK
DEFINE(UML_CONFIG_PRINTK, CONFIG_PRINTK);
#पूर्ण_अगर
#अगर_घोषित CONFIG_NO_HZ_COMMON
DEFINE(UML_CONFIG_NO_HZ_COMMON, CONFIG_NO_HZ_COMMON);
#पूर्ण_अगर
#अगर_घोषित CONFIG_UML_X86
DEFINE(UML_CONFIG_UML_X86, CONFIG_UML_X86);
#पूर्ण_अगर
#अगर_घोषित CONFIG_64BIT
DEFINE(UML_CONFIG_64BIT, CONFIG_64BIT);
#पूर्ण_अगर
#अगर_घोषित CONFIG_UML_TIME_TRAVEL_SUPPORT
DEFINE(UML_CONFIG_UML_TIME_TRAVEL_SUPPORT, CONFIG_UML_TIME_TRAVEL_SUPPORT);
#पूर्ण_अगर

/* क्रम stub */
DEFINE(UML_STUB_FIELD_OFFSET, दुरत्व(काष्ठा stub_data, offset));
DEFINE(UML_STUB_FIELD_CHILD_ERR, दुरत्व(काष्ठा stub_data, child_err));
DEFINE(UML_STUB_FIELD_FD, दुरत्व(काष्ठा stub_data, fd));
