<शैली गुरु>
#अगर_अघोषित ADRENO_PM4_XML
#घोषणा ADRENO_PM4_XML

/* Autogenerated file, DO NOT EDIT manually!

This file was generated by the rules-ng-ng headergen tool in this git repository:
http://github.com/मुक्तdreno/envytools/
git clone https://github.com/मुक्तdreno/envytools.git

The rules-ng-ng source files this header was generated from are:
- /home/robclark/src/envytools/rnndb/adreno.xml                     (    594 bytes, from 2020-07-23 21:58:14)
- /home/robclark/src/envytools/rnndb/मुक्तdreno_copyright.xml        (   1572 bytes, from 2020-07-23 21:58:14)
- /home/robclark/src/envytools/rnndb/adreno/a2xx.xml                (  90159 bytes, from 2020-07-23 21:58:14)
- /home/robclark/src/envytools/rnndb/adreno/adreno_common.xml       (  14386 bytes, from 2020-07-23 21:58:14)
- /home/robclark/src/envytools/rnndb/adreno/adreno_pm4.xml          (  65048 bytes, from 2020-07-23 21:58:14)
- /home/robclark/src/envytools/rnndb/adreno/a3xx.xml                (  84226 bytes, from 2020-07-23 21:58:14)
- /home/robclark/src/envytools/rnndb/adreno/a4xx.xml                ( 112556 bytes, from 2020-07-23 21:58:14)
- /home/robclark/src/envytools/rnndb/adreno/a5xx.xml                ( 149461 bytes, from 2020-07-23 21:58:14)
- /home/robclark/src/envytools/rnndb/adreno/a6xx.xml                ( 184695 bytes, from 2020-07-23 21:58:14)
- /home/robclark/src/envytools/rnndb/adreno/a6xx_gmu.xml            (  11218 bytes, from 2020-07-23 21:58:14)
- /home/robclark/src/envytools/rnndb/adreno/ocmem.xml               (   1773 bytes, from 2020-07-23 21:58:14)
- /home/robclark/src/envytools/rnndb/adreno/adreno_control_regs.xml (   4559 bytes, from 2020-07-23 21:58:14)
- /home/robclark/src/envytools/rnndb/adreno/adreno_pipe_regs.xml    (   2872 bytes, from 2020-07-23 21:58:14)

Copyright (C) 2013-2020 by the following authors:
- Rob Clark <robdclark@gmail.com> (robclark)
- Ilia Mirkin <imirkin@alum.mit.edu> (imirkin)

Permission is hereby granted, मुक्त of अक्षरge, to any person obtaining
a copy of this software and associated करोcumentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modअगरy, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to करो so, subject to
the following conditions:

The above copyright notice and this permission notice (including the
next paragraph) shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE COPYRIGHT OWNER(S) AND/OR ITS SUPPLIERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


क्रमागत vgt_event_type अणु
	VS_DEALLOC = 0,
	PS_DEALLOC = 1,
	VS_DONE_TS = 2,
	PS_DONE_TS = 3,
	CACHE_FLUSH_TS = 4,
	CONTEXT_DONE = 5,
	CACHE_FLUSH = 6,
	VIZQUERY_START = 7,
	HLSQ_FLUSH = 7,
	VIZQUERY_END = 8,
	SC_WAIT_WC = 9,
	WRITE_PRIMITIVE_COUNTS = 9,
	START_PRIMITIVE_CTRS = 11,
	STOP_PRIMITIVE_CTRS = 12,
	RST_PIX_CNT = 13,
	RST_VTX_CNT = 14,
	TILE_FLUSH = 15,
	STAT_EVENT = 16,
	CACHE_FLUSH_AND_INV_TS_EVENT = 20,
	ZPASS_DONE = 21,
	CACHE_FLUSH_AND_INV_EVENT = 22,
	RB_DONE_TS = 22,
	PERFCOUNTER_START = 23,
	PERFCOUNTER_STOP = 24,
	VS_FETCH_DONE = 27,
	FACENESS_FLUSH = 28,
	WT_DONE_TS = 8,
	FLUSH_SO_0 = 17,
	FLUSH_SO_1 = 18,
	FLUSH_SO_2 = 19,
	FLUSH_SO_3 = 20,
	PC_CCU_INVALIDATE_DEPTH = 24,
	PC_CCU_INVALIDATE_COLOR = 25,
	PC_CCU_RESOLVE_TS = 26,
	PC_CCU_FLUSH_DEPTH_TS = 28,
	PC_CCU_FLUSH_COLOR_TS = 29,
	BLIT = 30,
	UNK_25 = 37,
	LRZ_FLUSH = 38,
	BLIT_OP_FILL_2D = 39,
	BLIT_OP_COPY_2D = 40,
	BLIT_OP_SCALE_2D = 42,
	CONTEXT_DONE_2D = 43,
	UNK_2C = 44,
	UNK_2D = 45,
	CACHE_INVALIDATE = 49,
पूर्ण;

क्रमागत pc_di_primtype अणु
	DI_PT_NONE = 0,
	DI_PT_POINTLIST_PSIZE = 1,
	DI_PT_LINELIST = 2,
	DI_PT_LINESTRIP = 3,
	DI_PT_TRILIST = 4,
	DI_PT_TRIFAN = 5,
	DI_PT_TRISTRIP = 6,
	DI_PT_LINELOOP = 7,
	DI_PT_RECTLIST = 8,
	DI_PT_POINTLIST = 9,
	DI_PT_LINE_ADJ = 10,
	DI_PT_LINESTRIP_ADJ = 11,
	DI_PT_TRI_ADJ = 12,
	DI_PT_TRISTRIP_ADJ = 13,
	DI_PT_PATCHES0 = 31,
	DI_PT_PATCHES1 = 32,
	DI_PT_PATCHES2 = 33,
	DI_PT_PATCHES3 = 34,
	DI_PT_PATCHES4 = 35,
	DI_PT_PATCHES5 = 36,
	DI_PT_PATCHES6 = 37,
	DI_PT_PATCHES7 = 38,
	DI_PT_PATCHES8 = 39,
	DI_PT_PATCHES9 = 40,
	DI_PT_PATCHES10 = 41,
	DI_PT_PATCHES11 = 42,
	DI_PT_PATCHES12 = 43,
	DI_PT_PATCHES13 = 44,
	DI_PT_PATCHES14 = 45,
	DI_PT_PATCHES15 = 46,
	DI_PT_PATCHES16 = 47,
	DI_PT_PATCHES17 = 48,
	DI_PT_PATCHES18 = 49,
	DI_PT_PATCHES19 = 50,
	DI_PT_PATCHES20 = 51,
	DI_PT_PATCHES21 = 52,
	DI_PT_PATCHES22 = 53,
	DI_PT_PATCHES23 = 54,
	DI_PT_PATCHES24 = 55,
	DI_PT_PATCHES25 = 56,
	DI_PT_PATCHES26 = 57,
	DI_PT_PATCHES27 = 58,
	DI_PT_PATCHES28 = 59,
	DI_PT_PATCHES29 = 60,
	DI_PT_PATCHES30 = 61,
	DI_PT_PATCHES31 = 62,
पूर्ण;

क्रमागत pc_di_src_sel अणु
	DI_SRC_SEL_DMA = 0,
	DI_SRC_SEL_IMMEDIATE = 1,
	DI_SRC_SEL_AUTO_INDEX = 2,
	DI_SRC_SEL_AUTO_XFB = 3,
पूर्ण;

क्रमागत pc_di_face_cull_sel अणु
	DI_FACE_CULL_NONE = 0,
	DI_FACE_CULL_FETCH = 1,
	DI_FACE_BACKFACE_CULL = 2,
	DI_FACE_FRONTFACE_CULL = 3,
पूर्ण;

क्रमागत pc_di_index_size अणु
	INDEX_SIZE_IGN = 0,
	INDEX_SIZE_16_BIT = 0,
	INDEX_SIZE_32_BIT = 1,
	INDEX_SIZE_8_BIT = 2,
	INDEX_SIZE_INVALID = 0,
पूर्ण;

क्रमागत pc_di_vis_cull_mode अणु
	IGNORE_VISIBILITY = 0,
	USE_VISIBILITY = 1,
पूर्ण;

क्रमागत adreno_pm4_packet_type अणु
	CP_TYPE0_PKT = 0,
	CP_TYPE1_PKT = 0x40000000,
	CP_TYPE2_PKT = 0x80000000,
	CP_TYPE3_PKT = 0xc0000000,
	CP_TYPE4_PKT = 0x40000000,
	CP_TYPE7_PKT = 0x70000000,
पूर्ण;

क्रमागत adreno_pm4_type3_packets अणु
	CP_ME_INIT = 72,
	CP_NOP = 16,
	CP_PREEMPT_ENABLE = 28,
	CP_PREEMPT_TOKEN = 30,
	CP_INसूचीECT_BUFFER = 63,
	CP_INसूचीECT_BUFFER_CHAIN = 87,
	CP_INसूचीECT_BUFFER_PFD = 55,
	CP_WAIT_FOR_IDLE = 38,
	CP_WAIT_REG_MEM = 60,
	CP_WAIT_REG_EQ = 82,
	CP_WAIT_REG_GTE = 83,
	CP_WAIT_UNTIL_READ = 92,
	CP_WAIT_IB_PFD_COMPLETE = 93,
	CP_REG_RMW = 33,
	CP_SET_BIN_DATA = 47,
	CP_SET_BIN_DATA5 = 47,
	CP_REG_TO_MEM = 62,
	CP_MEM_WRITE = 61,
	CP_MEM_WRITE_CNTR = 79,
	CP_COND_EXEC = 68,
	CP_COND_WRITE = 69,
	CP_COND_WRITE5 = 69,
	CP_EVENT_WRITE = 70,
	CP_EVENT_WRITE_SHD = 88,
	CP_EVENT_WRITE_CFL = 89,
	CP_EVENT_WRITE_ZPD = 91,
	CP_RUN_OPENCL = 49,
	CP_DRAW_INDX = 34,
	CP_DRAW_INDX_2 = 54,
	CP_DRAW_INDX_BIN = 52,
	CP_DRAW_INDX_2_BIN = 53,
	CP_VIZ_QUERY = 35,
	CP_SET_STATE = 37,
	CP_SET_CONSTANT = 45,
	CP_IM_LOAD = 39,
	CP_IM_LOAD_IMMEDIATE = 43,
	CP_LOAD_CONSTANT_CONTEXT = 46,
	CP_INVALIDATE_STATE = 59,
	CP_SET_SHADER_BASES = 74,
	CP_SET_BIN_MASK = 80,
	CP_SET_BIN_SELECT = 81,
	CP_CONTEXT_UPDATE = 94,
	CP_INTERRUPT = 64,
	CP_IM_STORE = 44,
	CP_SET_DRAW_INIT_FLAGS = 75,
	CP_SET_PROTECTED_MODE = 95,
	CP_BOOTSTRAP_UCODE = 111,
	CP_LOAD_STATE = 48,
	CP_LOAD_STATE4 = 48,
	CP_COND_INसूचीECT_BUFFER_PFE = 58,
	CP_COND_INसूचीECT_BUFFER_PFD = 50,
	CP_INसूचीECT_BUFFER_PFE = 63,
	CP_SET_BIN = 76,
	CP_TEST_TWO_MEMS = 113,
	CP_REG_WR_NO_CTXT = 120,
	CP_RECORD_PFP_TIMESTAMP = 17,
	CP_SET_SECURE_MODE = 102,
	CP_WAIT_FOR_ME = 19,
	CP_SET_DRAW_STATE = 67,
	CP_DRAW_INDX_OFFSET = 56,
	CP_DRAW_INसूचीECT = 40,
	CP_DRAW_INDX_INसूचीECT = 41,
	CP_DRAW_INसूचीECT_MULTI = 42,
	CP_DRAW_AUTO = 36,
	CP_UNKNOWN_19 = 25,
	CP_UNKNOWN_1A = 26,
	CP_UNKNOWN_4E = 78,
	CP_WIDE_REG_WRITE = 116,
	CP_SCRATCH_TO_REG = 77,
	CP_REG_TO_SCRATCH = 74,
	CP_WAIT_MEM_WRITES = 18,
	CP_COND_REG_EXEC = 71,
	CP_MEM_TO_REG = 66,
	CP_EXEC_CS_INसूचीECT = 65,
	CP_EXEC_CS = 51,
	CP_PERFCOUNTER_ACTION = 80,
	CP_SMMU_TABLE_UPDATE = 83,
	CP_SET_MARKER = 101,
	CP_SET_PSEUDO_REG = 86,
	CP_CONTEXT_REG_BUNCH = 92,
	CP_YIELD_ENABLE = 28,
	CP_SKIP_IB2_ENABLE_GLOBAL = 29,
	CP_SKIP_IB2_ENABLE_LOCAL = 35,
	CP_SET_SUBDRAW_SIZE = 53,
	CP_SET_VISIBILITY_OVERRIDE = 100,
	CP_PREEMPT_ENABLE_GLOBAL = 105,
	CP_PREEMPT_ENABLE_LOCAL = 106,
	CP_CONTEXT_SWITCH_YIELD = 107,
	CP_SET_RENDER_MODE = 108,
	CP_COMPUTE_CHECKPOINT = 110,
	CP_MEM_TO_MEM = 115,
	CP_BLIT = 44,
	CP_REG_TEST = 57,
	CP_SET_MODE = 99,
	CP_LOAD_STATE6_GEOM = 50,
	CP_LOAD_STATE6_FRAG = 52,
	CP_LOAD_STATE6 = 54,
	IN_IB_PREFETCH_END = 23,
	IN_SUBBLK_PREFETCH = 31,
	IN_INSTR_PREFETCH = 32,
	IN_INSTR_MATCH = 71,
	IN_CONST_PREFETCH = 73,
	IN_INCR_UPDT_STATE = 85,
	IN_INCR_UPDT_CONST = 86,
	IN_INCR_UPDT_INSTR = 87,
	PKT4 = 4,
	CP_SCRATCH_WRITE = 76,
	CP_REG_TO_MEM_OFFSET_MEM = 116,
	CP_REG_TO_MEM_OFFSET_REG = 114,
	CP_WAIT_MEM_GTE = 20,
	CP_WAIT_TWO_REGS = 112,
	CP_MEMCPY = 117,
	CP_SET_BIN_DATA5_OFFSET = 46,
	CP_SET_CTXSWITCH_IB = 85,
	CP_REG_WRITE = 109,
	CP_WHERE_AM_I = 98,
पूर्ण;

क्रमागत adreno_state_block अणु
	SB_VERT_TEX = 0,
	SB_VERT_MIPADDR = 1,
	SB_FRAG_TEX = 2,
	SB_FRAG_MIPADDR = 3,
	SB_VERT_SHADER = 4,
	SB_GEOM_SHADER = 5,
	SB_FRAG_SHADER = 6,
	SB_COMPUTE_SHADER = 7,
पूर्ण;

क्रमागत adreno_state_type अणु
	ST_SHADER = 0,
	ST_CONSTANTS = 1,
पूर्ण;

क्रमागत adreno_state_src अणु
	SS_सूचीECT = 0,
	SS_INVALID_ALL_IC = 2,
	SS_INVALID_PART_IC = 3,
	SS_INसूचीECT = 4,
	SS_INसूचीECT_TCM = 5,
	SS_INसूचीECT_STM = 6,
पूर्ण;

क्रमागत a4xx_state_block अणु
	SB4_VS_TEX = 0,
	SB4_HS_TEX = 1,
	SB4_DS_TEX = 2,
	SB4_GS_TEX = 3,
	SB4_FS_TEX = 4,
	SB4_CS_TEX = 5,
	SB4_VS_SHADER = 8,
	SB4_HS_SHADER = 9,
	SB4_DS_SHADER = 10,
	SB4_GS_SHADER = 11,
	SB4_FS_SHADER = 12,
	SB4_CS_SHADER = 13,
	SB4_SSBO = 14,
	SB4_CS_SSBO = 15,
पूर्ण;

क्रमागत a4xx_state_type अणु
	ST4_SHADER = 0,
	ST4_CONSTANTS = 1,
	ST4_UBO = 2,
पूर्ण;

क्रमागत a4xx_state_src अणु
	SS4_सूचीECT = 0,
	SS4_INसूचीECT = 2,
पूर्ण;

क्रमागत a6xx_state_block अणु
	SB6_VS_TEX = 0,
	SB6_HS_TEX = 1,
	SB6_DS_TEX = 2,
	SB6_GS_TEX = 3,
	SB6_FS_TEX = 4,
	SB6_CS_TEX = 5,
	SB6_VS_SHADER = 8,
	SB6_HS_SHADER = 9,
	SB6_DS_SHADER = 10,
	SB6_GS_SHADER = 11,
	SB6_FS_SHADER = 12,
	SB6_CS_SHADER = 13,
	SB6_IBO = 14,
	SB6_CS_IBO = 15,
पूर्ण;

क्रमागत a6xx_state_type अणु
	ST6_SHADER = 0,
	ST6_CONSTANTS = 1,
	ST6_UBO = 2,
	ST6_IBO = 3,
पूर्ण;

क्रमागत a6xx_state_src अणु
	SS6_सूचीECT = 0,
	SS6_BINDLESS = 1,
	SS6_INसूचीECT = 2,
	SS6_UBO = 3,
पूर्ण;

क्रमागत a4xx_index_size अणु
	INDEX4_SIZE_8_BIT = 0,
	INDEX4_SIZE_16_BIT = 1,
	INDEX4_SIZE_32_BIT = 2,
पूर्ण;

क्रमागत a6xx_patch_type अणु
	TESS_QUADS = 0,
	TESS_TRIANGLES = 1,
	TESS_ISOLINES = 2,
पूर्ण;

क्रमागत a6xx_draw_indirect_opcode अणु
	INसूचीECT_OP_NORMAL = 2,
	INसूचीECT_OP_INDEXED = 4,
पूर्ण;

क्रमागत cp_cond_function अणु
	WRITE_ALWAYS = 0,
	WRITE_LT = 1,
	WRITE_LE = 2,
	WRITE_EQ = 3,
	WRITE_NE = 4,
	WRITE_GE = 5,
	WRITE_GT = 6,
पूर्ण;

क्रमागत render_mode_cmd अणु
	BYPASS = 1,
	BINNING = 2,
	GMEM = 3,
	BLIT2D = 5,
	BLIT2DSCALE = 7,
	END2D = 8,
पूर्ण;

क्रमागत cp_blit_cmd अणु
	BLIT_OP_FILL = 0,
	BLIT_OP_COPY = 1,
	BLIT_OP_SCALE = 3,
पूर्ण;

क्रमागत a6xx_render_mode अणु
	RM6_BYPASS = 1,
	RM6_BINNING = 2,
	RM6_GMEM = 4,
	RM6_ENDVIS = 5,
	RM6_RESOLVE = 6,
	RM6_YIELD = 7,
	RM6_COMPUTE = 8,
	RM6_BLIT2DSCALE = 12,
	RM6_IB1LIST_START = 13,
	RM6_IB1LIST_END = 14,
	RM6_IFPC_ENABLE = 256,
	RM6_IFPC_DISABLE = 257,
पूर्ण;

क्रमागत pseuकरो_reg अणु
	SMMU_INFO = 0,
	NON_SECURE_SAVE_ADDR = 1,
	SECURE_SAVE_ADDR = 2,
	NON_PRIV_SAVE_ADDR = 3,
	COUNTER = 4,
पूर्ण;

क्रमागत compare_mode अणु
	PRED_TEST = 1,
	REG_COMPARE = 2,
	RENDER_MODE = 3,
पूर्ण;

क्रमागत ctxचयन_ib अणु
	RESTORE_IB = 0,
	YIELD_RESTORE_IB = 1,
	SAVE_IB = 2,
	RB_SAVE_IB = 3,
पूर्ण;

क्रमागत reg_tracker अणु
	TRACK_CNTL_REG = 1,
	TRACK_RENDER_CNTL = 2,
	UNK_EVENT_WRITE = 4,
पूर्ण;

#घोषणा REG_CP_LOAD_STATE_0					0x00000000
#घोषणा CP_LOAD_STATE_0_DST_OFF__MASK				0x0000ffff
#घोषणा CP_LOAD_STATE_0_DST_OFF__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE_0_DST_OFF(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_LOAD_STATE_0_DST_OFF__SHIFT) & CP_LOAD_STATE_0_DST_OFF__MASK;
पूर्ण
#घोषणा CP_LOAD_STATE_0_STATE_SRC__MASK				0x00070000
#घोषणा CP_LOAD_STATE_0_STATE_SRC__SHIFT			16
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE_0_STATE_SRC(क्रमागत adreno_state_src val)
अणु
	वापस ((val) << CP_LOAD_STATE_0_STATE_SRC__SHIFT) & CP_LOAD_STATE_0_STATE_SRC__MASK;
पूर्ण
#घोषणा CP_LOAD_STATE_0_STATE_BLOCK__MASK			0x00380000
#घोषणा CP_LOAD_STATE_0_STATE_BLOCK__SHIFT			19
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE_0_STATE_BLOCK(क्रमागत adreno_state_block val)
अणु
	वापस ((val) << CP_LOAD_STATE_0_STATE_BLOCK__SHIFT) & CP_LOAD_STATE_0_STATE_BLOCK__MASK;
पूर्ण
#घोषणा CP_LOAD_STATE_0_NUM_UNIT__MASK				0xffc00000
#घोषणा CP_LOAD_STATE_0_NUM_UNIT__SHIFT				22
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE_0_NUM_UNIT(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_LOAD_STATE_0_NUM_UNIT__SHIFT) & CP_LOAD_STATE_0_NUM_UNIT__MASK;
पूर्ण

#घोषणा REG_CP_LOAD_STATE_1					0x00000001
#घोषणा CP_LOAD_STATE_1_STATE_TYPE__MASK			0x00000003
#घोषणा CP_LOAD_STATE_1_STATE_TYPE__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE_1_STATE_TYPE(क्रमागत adreno_state_type val)
अणु
	वापस ((val) << CP_LOAD_STATE_1_STATE_TYPE__SHIFT) & CP_LOAD_STATE_1_STATE_TYPE__MASK;
पूर्ण
#घोषणा CP_LOAD_STATE_1_EXT_SRC_ADDR__MASK			0xfffffffc
#घोषणा CP_LOAD_STATE_1_EXT_SRC_ADDR__SHIFT			2
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE_1_EXT_SRC_ADDR(uपूर्णांक32_t val)
अणु
	वापस ((val >> 2) << CP_LOAD_STATE_1_EXT_SRC_ADDR__SHIFT) & CP_LOAD_STATE_1_EXT_SRC_ADDR__MASK;
पूर्ण

#घोषणा REG_CP_LOAD_STATE4_0					0x00000000
#घोषणा CP_LOAD_STATE4_0_DST_OFF__MASK				0x00003fff
#घोषणा CP_LOAD_STATE4_0_DST_OFF__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE4_0_DST_OFF(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_LOAD_STATE4_0_DST_OFF__SHIFT) & CP_LOAD_STATE4_0_DST_OFF__MASK;
पूर्ण
#घोषणा CP_LOAD_STATE4_0_STATE_SRC__MASK			0x00030000
#घोषणा CP_LOAD_STATE4_0_STATE_SRC__SHIFT			16
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE4_0_STATE_SRC(क्रमागत a4xx_state_src val)
अणु
	वापस ((val) << CP_LOAD_STATE4_0_STATE_SRC__SHIFT) & CP_LOAD_STATE4_0_STATE_SRC__MASK;
पूर्ण
#घोषणा CP_LOAD_STATE4_0_STATE_BLOCK__MASK			0x003c0000
#घोषणा CP_LOAD_STATE4_0_STATE_BLOCK__SHIFT			18
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE4_0_STATE_BLOCK(क्रमागत a4xx_state_block val)
अणु
	वापस ((val) << CP_LOAD_STATE4_0_STATE_BLOCK__SHIFT) & CP_LOAD_STATE4_0_STATE_BLOCK__MASK;
पूर्ण
#घोषणा CP_LOAD_STATE4_0_NUM_UNIT__MASK				0xffc00000
#घोषणा CP_LOAD_STATE4_0_NUM_UNIT__SHIFT			22
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE4_0_NUM_UNIT(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_LOAD_STATE4_0_NUM_UNIT__SHIFT) & CP_LOAD_STATE4_0_NUM_UNIT__MASK;
पूर्ण

#घोषणा REG_CP_LOAD_STATE4_1					0x00000001
#घोषणा CP_LOAD_STATE4_1_STATE_TYPE__MASK			0x00000003
#घोषणा CP_LOAD_STATE4_1_STATE_TYPE__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE4_1_STATE_TYPE(क्रमागत a4xx_state_type val)
अणु
	वापस ((val) << CP_LOAD_STATE4_1_STATE_TYPE__SHIFT) & CP_LOAD_STATE4_1_STATE_TYPE__MASK;
पूर्ण
#घोषणा CP_LOAD_STATE4_1_EXT_SRC_ADDR__MASK			0xfffffffc
#घोषणा CP_LOAD_STATE4_1_EXT_SRC_ADDR__SHIFT			2
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE4_1_EXT_SRC_ADDR(uपूर्णांक32_t val)
अणु
	वापस ((val >> 2) << CP_LOAD_STATE4_1_EXT_SRC_ADDR__SHIFT) & CP_LOAD_STATE4_1_EXT_SRC_ADDR__MASK;
पूर्ण

#घोषणा REG_CP_LOAD_STATE4_2					0x00000002
#घोषणा CP_LOAD_STATE4_2_EXT_SRC_ADDR_HI__MASK			0xffffffff
#घोषणा CP_LOAD_STATE4_2_EXT_SRC_ADDR_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE4_2_EXT_SRC_ADDR_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_LOAD_STATE4_2_EXT_SRC_ADDR_HI__SHIFT) & CP_LOAD_STATE4_2_EXT_SRC_ADDR_HI__MASK;
पूर्ण

#घोषणा REG_CP_LOAD_STATE6_0					0x00000000
#घोषणा CP_LOAD_STATE6_0_DST_OFF__MASK				0x00003fff
#घोषणा CP_LOAD_STATE6_0_DST_OFF__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE6_0_DST_OFF(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_LOAD_STATE6_0_DST_OFF__SHIFT) & CP_LOAD_STATE6_0_DST_OFF__MASK;
पूर्ण
#घोषणा CP_LOAD_STATE6_0_STATE_TYPE__MASK			0x0000c000
#घोषणा CP_LOAD_STATE6_0_STATE_TYPE__SHIFT			14
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE6_0_STATE_TYPE(क्रमागत a6xx_state_type val)
अणु
	वापस ((val) << CP_LOAD_STATE6_0_STATE_TYPE__SHIFT) & CP_LOAD_STATE6_0_STATE_TYPE__MASK;
पूर्ण
#घोषणा CP_LOAD_STATE6_0_STATE_SRC__MASK			0x00030000
#घोषणा CP_LOAD_STATE6_0_STATE_SRC__SHIFT			16
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE6_0_STATE_SRC(क्रमागत a6xx_state_src val)
अणु
	वापस ((val) << CP_LOAD_STATE6_0_STATE_SRC__SHIFT) & CP_LOAD_STATE6_0_STATE_SRC__MASK;
पूर्ण
#घोषणा CP_LOAD_STATE6_0_STATE_BLOCK__MASK			0x003c0000
#घोषणा CP_LOAD_STATE6_0_STATE_BLOCK__SHIFT			18
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE6_0_STATE_BLOCK(क्रमागत a6xx_state_block val)
अणु
	वापस ((val) << CP_LOAD_STATE6_0_STATE_BLOCK__SHIFT) & CP_LOAD_STATE6_0_STATE_BLOCK__MASK;
पूर्ण
#घोषणा CP_LOAD_STATE6_0_NUM_UNIT__MASK				0xffc00000
#घोषणा CP_LOAD_STATE6_0_NUM_UNIT__SHIFT			22
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE6_0_NUM_UNIT(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_LOAD_STATE6_0_NUM_UNIT__SHIFT) & CP_LOAD_STATE6_0_NUM_UNIT__MASK;
पूर्ण

#घोषणा REG_CP_LOAD_STATE6_1					0x00000001
#घोषणा CP_LOAD_STATE6_1_EXT_SRC_ADDR__MASK			0xfffffffc
#घोषणा CP_LOAD_STATE6_1_EXT_SRC_ADDR__SHIFT			2
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE6_1_EXT_SRC_ADDR(uपूर्णांक32_t val)
अणु
	वापस ((val >> 2) << CP_LOAD_STATE6_1_EXT_SRC_ADDR__SHIFT) & CP_LOAD_STATE6_1_EXT_SRC_ADDR__MASK;
पूर्ण

#घोषणा REG_CP_LOAD_STATE6_2					0x00000002
#घोषणा CP_LOAD_STATE6_2_EXT_SRC_ADDR_HI__MASK			0xffffffff
#घोषणा CP_LOAD_STATE6_2_EXT_SRC_ADDR_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_LOAD_STATE6_2_EXT_SRC_ADDR_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_LOAD_STATE6_2_EXT_SRC_ADDR_HI__SHIFT) & CP_LOAD_STATE6_2_EXT_SRC_ADDR_HI__MASK;
पूर्ण

#घोषणा REG_CP_LOAD_STATE6_EXT_SRC_ADDR				0x00000001

#घोषणा REG_CP_DRAW_INDX_0					0x00000000
#घोषणा CP_DRAW_INDX_0_VIZ_QUERY__MASK				0xffffffff
#घोषणा CP_DRAW_INDX_0_VIZ_QUERY__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_0_VIZ_QUERY(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_0_VIZ_QUERY__SHIFT) & CP_DRAW_INDX_0_VIZ_QUERY__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_1					0x00000001
#घोषणा CP_DRAW_INDX_1_PRIM_TYPE__MASK				0x0000003f
#घोषणा CP_DRAW_INDX_1_PRIM_TYPE__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_1_PRIM_TYPE(क्रमागत pc_di_primtype val)
अणु
	वापस ((val) << CP_DRAW_INDX_1_PRIM_TYPE__SHIFT) & CP_DRAW_INDX_1_PRIM_TYPE__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_1_SOURCE_SELECT__MASK			0x000000c0
#घोषणा CP_DRAW_INDX_1_SOURCE_SELECT__SHIFT			6
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_1_SOURCE_SELECT(क्रमागत pc_di_src_sel val)
अणु
	वापस ((val) << CP_DRAW_INDX_1_SOURCE_SELECT__SHIFT) & CP_DRAW_INDX_1_SOURCE_SELECT__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_1_VIS_CULL__MASK				0x00000600
#घोषणा CP_DRAW_INDX_1_VIS_CULL__SHIFT				9
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_1_VIS_CULL(क्रमागत pc_di_vis_cull_mode val)
अणु
	वापस ((val) << CP_DRAW_INDX_1_VIS_CULL__SHIFT) & CP_DRAW_INDX_1_VIS_CULL__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_1_INDEX_SIZE__MASK				0x00000800
#घोषणा CP_DRAW_INDX_1_INDEX_SIZE__SHIFT			11
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_1_INDEX_SIZE(क्रमागत pc_di_index_size val)
अणु
	वापस ((val) << CP_DRAW_INDX_1_INDEX_SIZE__SHIFT) & CP_DRAW_INDX_1_INDEX_SIZE__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_1_NOT_EOP					0x00001000
#घोषणा CP_DRAW_INDX_1_SMALL_INDEX				0x00002000
#घोषणा CP_DRAW_INDX_1_PRE_DRAW_INITIATOR_ENABLE		0x00004000
#घोषणा CP_DRAW_INDX_1_NUM_INSTANCES__MASK			0xff000000
#घोषणा CP_DRAW_INDX_1_NUM_INSTANCES__SHIFT			24
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_1_NUM_INSTANCES(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_1_NUM_INSTANCES__SHIFT) & CP_DRAW_INDX_1_NUM_INSTANCES__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_2					0x00000002
#घोषणा CP_DRAW_INDX_2_NUM_INDICES__MASK			0xffffffff
#घोषणा CP_DRAW_INDX_2_NUM_INDICES__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_2_NUM_INDICES(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_2_NUM_INDICES__SHIFT) & CP_DRAW_INDX_2_NUM_INDICES__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_3					0x00000003
#घोषणा CP_DRAW_INDX_3_INDX_BASE__MASK				0xffffffff
#घोषणा CP_DRAW_INDX_3_INDX_BASE__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_3_INDX_BASE(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_3_INDX_BASE__SHIFT) & CP_DRAW_INDX_3_INDX_BASE__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_4					0x00000004
#घोषणा CP_DRAW_INDX_4_INDX_SIZE__MASK				0xffffffff
#घोषणा CP_DRAW_INDX_4_INDX_SIZE__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_4_INDX_SIZE(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_4_INDX_SIZE__SHIFT) & CP_DRAW_INDX_4_INDX_SIZE__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_2_0					0x00000000
#घोषणा CP_DRAW_INDX_2_0_VIZ_QUERY__MASK			0xffffffff
#घोषणा CP_DRAW_INDX_2_0_VIZ_QUERY__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_2_0_VIZ_QUERY(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_2_0_VIZ_QUERY__SHIFT) & CP_DRAW_INDX_2_0_VIZ_QUERY__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_2_1					0x00000001
#घोषणा CP_DRAW_INDX_2_1_PRIM_TYPE__MASK			0x0000003f
#घोषणा CP_DRAW_INDX_2_1_PRIM_TYPE__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_2_1_PRIM_TYPE(क्रमागत pc_di_primtype val)
अणु
	वापस ((val) << CP_DRAW_INDX_2_1_PRIM_TYPE__SHIFT) & CP_DRAW_INDX_2_1_PRIM_TYPE__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_2_1_SOURCE_SELECT__MASK			0x000000c0
#घोषणा CP_DRAW_INDX_2_1_SOURCE_SELECT__SHIFT			6
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_2_1_SOURCE_SELECT(क्रमागत pc_di_src_sel val)
अणु
	वापस ((val) << CP_DRAW_INDX_2_1_SOURCE_SELECT__SHIFT) & CP_DRAW_INDX_2_1_SOURCE_SELECT__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_2_1_VIS_CULL__MASK				0x00000600
#घोषणा CP_DRAW_INDX_2_1_VIS_CULL__SHIFT			9
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_2_1_VIS_CULL(क्रमागत pc_di_vis_cull_mode val)
अणु
	वापस ((val) << CP_DRAW_INDX_2_1_VIS_CULL__SHIFT) & CP_DRAW_INDX_2_1_VIS_CULL__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_2_1_INDEX_SIZE__MASK			0x00000800
#घोषणा CP_DRAW_INDX_2_1_INDEX_SIZE__SHIFT			11
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_2_1_INDEX_SIZE(क्रमागत pc_di_index_size val)
अणु
	वापस ((val) << CP_DRAW_INDX_2_1_INDEX_SIZE__SHIFT) & CP_DRAW_INDX_2_1_INDEX_SIZE__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_2_1_NOT_EOP				0x00001000
#घोषणा CP_DRAW_INDX_2_1_SMALL_INDEX				0x00002000
#घोषणा CP_DRAW_INDX_2_1_PRE_DRAW_INITIATOR_ENABLE		0x00004000
#घोषणा CP_DRAW_INDX_2_1_NUM_INSTANCES__MASK			0xff000000
#घोषणा CP_DRAW_INDX_2_1_NUM_INSTANCES__SHIFT			24
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_2_1_NUM_INSTANCES(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_2_1_NUM_INSTANCES__SHIFT) & CP_DRAW_INDX_2_1_NUM_INSTANCES__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_2_2					0x00000002
#घोषणा CP_DRAW_INDX_2_2_NUM_INDICES__MASK			0xffffffff
#घोषणा CP_DRAW_INDX_2_2_NUM_INDICES__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_2_2_NUM_INDICES(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_2_2_NUM_INDICES__SHIFT) & CP_DRAW_INDX_2_2_NUM_INDICES__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_OFFSET_0				0x00000000
#घोषणा CP_DRAW_INDX_OFFSET_0_PRIM_TYPE__MASK			0x0000003f
#घोषणा CP_DRAW_INDX_OFFSET_0_PRIM_TYPE__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_0_PRIM_TYPE(क्रमागत pc_di_primtype val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_0_PRIM_TYPE__SHIFT) & CP_DRAW_INDX_OFFSET_0_PRIM_TYPE__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_OFFSET_0_SOURCE_SELECT__MASK		0x000000c0
#घोषणा CP_DRAW_INDX_OFFSET_0_SOURCE_SELECT__SHIFT		6
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_0_SOURCE_SELECT(क्रमागत pc_di_src_sel val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_0_SOURCE_SELECT__SHIFT) & CP_DRAW_INDX_OFFSET_0_SOURCE_SELECT__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_OFFSET_0_VIS_CULL__MASK			0x00000300
#घोषणा CP_DRAW_INDX_OFFSET_0_VIS_CULL__SHIFT			8
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_0_VIS_CULL(क्रमागत pc_di_vis_cull_mode val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_0_VIS_CULL__SHIFT) & CP_DRAW_INDX_OFFSET_0_VIS_CULL__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_OFFSET_0_INDEX_SIZE__MASK			0x00000c00
#घोषणा CP_DRAW_INDX_OFFSET_0_INDEX_SIZE__SHIFT			10
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_0_INDEX_SIZE(क्रमागत a4xx_index_size val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_0_INDEX_SIZE__SHIFT) & CP_DRAW_INDX_OFFSET_0_INDEX_SIZE__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_OFFSET_0_PATCH_TYPE__MASK			0x00003000
#घोषणा CP_DRAW_INDX_OFFSET_0_PATCH_TYPE__SHIFT			12
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_0_PATCH_TYPE(क्रमागत a6xx_patch_type val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_0_PATCH_TYPE__SHIFT) & CP_DRAW_INDX_OFFSET_0_PATCH_TYPE__MASK;
पूर्ण
#घोषणा CP_DRAW_INDX_OFFSET_0_GS_ENABLE				0x00010000
#घोषणा CP_DRAW_INDX_OFFSET_0_TESS_ENABLE			0x00020000

#घोषणा REG_CP_DRAW_INDX_OFFSET_1				0x00000001
#घोषणा CP_DRAW_INDX_OFFSET_1_NUM_INSTANCES__MASK		0xffffffff
#घोषणा CP_DRAW_INDX_OFFSET_1_NUM_INSTANCES__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_1_NUM_INSTANCES(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_1_NUM_INSTANCES__SHIFT) & CP_DRAW_INDX_OFFSET_1_NUM_INSTANCES__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_OFFSET_2				0x00000002
#घोषणा CP_DRAW_INDX_OFFSET_2_NUM_INDICES__MASK			0xffffffff
#घोषणा CP_DRAW_INDX_OFFSET_2_NUM_INDICES__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_2_NUM_INDICES(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_2_NUM_INDICES__SHIFT) & CP_DRAW_INDX_OFFSET_2_NUM_INDICES__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_OFFSET_3				0x00000003
#घोषणा CP_DRAW_INDX_OFFSET_3_FIRST_INDX__MASK			0xffffffff
#घोषणा CP_DRAW_INDX_OFFSET_3_FIRST_INDX__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_3_FIRST_INDX(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_3_FIRST_INDX__SHIFT) & CP_DRAW_INDX_OFFSET_3_FIRST_INDX__MASK;
पूर्ण


#घोषणा REG_CP_DRAW_INDX_OFFSET_4				0x00000004
#घोषणा CP_DRAW_INDX_OFFSET_4_INDX_BASE_LO__MASK		0xffffffff
#घोषणा CP_DRAW_INDX_OFFSET_4_INDX_BASE_LO__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_4_INDX_BASE_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_4_INDX_BASE_LO__SHIFT) & CP_DRAW_INDX_OFFSET_4_INDX_BASE_LO__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_OFFSET_5				0x00000005
#घोषणा CP_DRAW_INDX_OFFSET_5_INDX_BASE_HI__MASK		0xffffffff
#घोषणा CP_DRAW_INDX_OFFSET_5_INDX_BASE_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_5_INDX_BASE_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_5_INDX_BASE_HI__SHIFT) & CP_DRAW_INDX_OFFSET_5_INDX_BASE_HI__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_OFFSET_INDX_BASE			0x00000004

#घोषणा REG_CP_DRAW_INDX_OFFSET_6				0x00000006
#घोषणा CP_DRAW_INDX_OFFSET_6_MAX_INDICES__MASK			0xffffffff
#घोषणा CP_DRAW_INDX_OFFSET_6_MAX_INDICES__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_6_MAX_INDICES(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_6_MAX_INDICES__SHIFT) & CP_DRAW_INDX_OFFSET_6_MAX_INDICES__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_OFFSET_4				0x00000004
#घोषणा CP_DRAW_INDX_OFFSET_4_INDX_BASE__MASK			0xffffffff
#घोषणा CP_DRAW_INDX_OFFSET_4_INDX_BASE__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_4_INDX_BASE(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_4_INDX_BASE__SHIFT) & CP_DRAW_INDX_OFFSET_4_INDX_BASE__MASK;
पूर्ण

#घोषणा REG_CP_DRAW_INDX_OFFSET_5				0x00000005
#घोषणा CP_DRAW_INDX_OFFSET_5_INDX_SIZE__MASK			0xffffffff
#घोषणा CP_DRAW_INDX_OFFSET_5_INDX_SIZE__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_DRAW_INDX_OFFSET_5_INDX_SIZE(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DRAW_INDX_OFFSET_5_INDX_SIZE__SHIFT) & CP_DRAW_INDX_OFFSET_5_INDX_SIZE__MASK;
पूर्ण

#घोषणा REG_A4XX_CP_DRAW_INसूचीECT_0				0x00000000
#घोषणा A4XX_CP_DRAW_INसूचीECT_0_PRIM_TYPE__MASK			0x0000003f
#घोषणा A4XX_CP_DRAW_INसूचीECT_0_PRIM_TYPE__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INसूचीECT_0_PRIM_TYPE(क्रमागत pc_di_primtype val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INसूचीECT_0_PRIM_TYPE__SHIFT) & A4XX_CP_DRAW_INसूचीECT_0_PRIM_TYPE__MASK;
पूर्ण
#घोषणा A4XX_CP_DRAW_INसूचीECT_0_SOURCE_SELECT__MASK		0x000000c0
#घोषणा A4XX_CP_DRAW_INसूचीECT_0_SOURCE_SELECT__SHIFT		6
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INसूचीECT_0_SOURCE_SELECT(क्रमागत pc_di_src_sel val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INसूचीECT_0_SOURCE_SELECT__SHIFT) & A4XX_CP_DRAW_INसूचीECT_0_SOURCE_SELECT__MASK;
पूर्ण
#घोषणा A4XX_CP_DRAW_INसूचीECT_0_VIS_CULL__MASK			0x00000300
#घोषणा A4XX_CP_DRAW_INसूचीECT_0_VIS_CULL__SHIFT			8
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INसूचीECT_0_VIS_CULL(क्रमागत pc_di_vis_cull_mode val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INसूचीECT_0_VIS_CULL__SHIFT) & A4XX_CP_DRAW_INसूचीECT_0_VIS_CULL__MASK;
पूर्ण
#घोषणा A4XX_CP_DRAW_INसूचीECT_0_INDEX_SIZE__MASK		0x00000c00
#घोषणा A4XX_CP_DRAW_INसूचीECT_0_INDEX_SIZE__SHIFT		10
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INसूचीECT_0_INDEX_SIZE(क्रमागत a4xx_index_size val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INसूचीECT_0_INDEX_SIZE__SHIFT) & A4XX_CP_DRAW_INसूचीECT_0_INDEX_SIZE__MASK;
पूर्ण
#घोषणा A4XX_CP_DRAW_INसूचीECT_0_PATCH_TYPE__MASK		0x00003000
#घोषणा A4XX_CP_DRAW_INसूचीECT_0_PATCH_TYPE__SHIFT		12
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INसूचीECT_0_PATCH_TYPE(क्रमागत a6xx_patch_type val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INसूचीECT_0_PATCH_TYPE__SHIFT) & A4XX_CP_DRAW_INसूचीECT_0_PATCH_TYPE__MASK;
पूर्ण
#घोषणा A4XX_CP_DRAW_INसूचीECT_0_GS_ENABLE			0x00010000
#घोषणा A4XX_CP_DRAW_INसूचीECT_0_TESS_ENABLE			0x00020000


#घोषणा REG_A4XX_CP_DRAW_INसूचीECT_1				0x00000001
#घोषणा A4XX_CP_DRAW_INसूचीECT_1_INसूचीECT__MASK			0xffffffff
#घोषणा A4XX_CP_DRAW_INसूचीECT_1_INसूचीECT__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INसूचीECT_1_INसूचीECT(uपूर्णांक32_t val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INसूचीECT_1_INसूचीECT__SHIFT) & A4XX_CP_DRAW_INसूचीECT_1_INसूचीECT__MASK;
पूर्ण


#घोषणा REG_A5XX_CP_DRAW_INसूचीECT_1				0x00000001
#घोषणा A5XX_CP_DRAW_INसूचीECT_1_INसूचीECT_LO__MASK		0xffffffff
#घोषणा A5XX_CP_DRAW_INसूचीECT_1_INसूचीECT_LO__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A5XX_CP_DRAW_INसूचीECT_1_INसूचीECT_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << A5XX_CP_DRAW_INसूचीECT_1_INसूचीECT_LO__SHIFT) & A5XX_CP_DRAW_INसूचीECT_1_INसूचीECT_LO__MASK;
पूर्ण

#घोषणा REG_A5XX_CP_DRAW_INसूचीECT_2				0x00000002
#घोषणा A5XX_CP_DRAW_INसूचीECT_2_INसूचीECT_HI__MASK		0xffffffff
#घोषणा A5XX_CP_DRAW_INसूचीECT_2_INसूचीECT_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A5XX_CP_DRAW_INसूचीECT_2_INसूचीECT_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << A5XX_CP_DRAW_INसूचीECT_2_INसूचीECT_HI__SHIFT) & A5XX_CP_DRAW_INसूचीECT_2_INसूचीECT_HI__MASK;
पूर्ण

#घोषणा REG_A5XX_CP_DRAW_INसूचीECT_INसूचीECT			0x00000001

#घोषणा REG_A4XX_CP_DRAW_INDX_INसूचीECT_0			0x00000000
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_0_PRIM_TYPE__MASK		0x0000003f
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_0_PRIM_TYPE__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INDX_INसूचीECT_0_PRIM_TYPE(क्रमागत pc_di_primtype val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INDX_INसूचीECT_0_PRIM_TYPE__SHIFT) & A4XX_CP_DRAW_INDX_INसूचीECT_0_PRIM_TYPE__MASK;
पूर्ण
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_0_SOURCE_SELECT__MASK	0x000000c0
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_0_SOURCE_SELECT__SHIFT	6
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INDX_INसूचीECT_0_SOURCE_SELECT(क्रमागत pc_di_src_sel val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INDX_INसूचीECT_0_SOURCE_SELECT__SHIFT) & A4XX_CP_DRAW_INDX_INसूचीECT_0_SOURCE_SELECT__MASK;
पूर्ण
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_0_VIS_CULL__MASK		0x00000300
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_0_VIS_CULL__SHIFT		8
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INDX_INसूचीECT_0_VIS_CULL(क्रमागत pc_di_vis_cull_mode val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INDX_INसूचीECT_0_VIS_CULL__SHIFT) & A4XX_CP_DRAW_INDX_INसूचीECT_0_VIS_CULL__MASK;
पूर्ण
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_0_INDEX_SIZE__MASK		0x00000c00
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_0_INDEX_SIZE__SHIFT		10
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INDX_INसूचीECT_0_INDEX_SIZE(क्रमागत a4xx_index_size val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INDX_INसूचीECT_0_INDEX_SIZE__SHIFT) & A4XX_CP_DRAW_INDX_INसूचीECT_0_INDEX_SIZE__MASK;
पूर्ण
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_0_PATCH_TYPE__MASK		0x00003000
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_0_PATCH_TYPE__SHIFT		12
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INDX_INसूचीECT_0_PATCH_TYPE(क्रमागत a6xx_patch_type val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INDX_INसूचीECT_0_PATCH_TYPE__SHIFT) & A4XX_CP_DRAW_INDX_INसूचीECT_0_PATCH_TYPE__MASK;
पूर्ण
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_0_GS_ENABLE			0x00010000
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_0_TESS_ENABLE		0x00020000


#घोषणा REG_A4XX_CP_DRAW_INDX_INसूचीECT_1			0x00000001
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_1_INDX_BASE__MASK		0xffffffff
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_1_INDX_BASE__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INDX_INसूचीECT_1_INDX_BASE(uपूर्णांक32_t val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INDX_INसूचीECT_1_INDX_BASE__SHIFT) & A4XX_CP_DRAW_INDX_INसूचीECT_1_INDX_BASE__MASK;
पूर्ण

#घोषणा REG_A4XX_CP_DRAW_INDX_INसूचीECT_2			0x00000002
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_2_INDX_SIZE__MASK		0xffffffff
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_2_INDX_SIZE__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INDX_INसूचीECT_2_INDX_SIZE(uपूर्णांक32_t val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INDX_INसूचीECT_2_INDX_SIZE__SHIFT) & A4XX_CP_DRAW_INDX_INसूचीECT_2_INDX_SIZE__MASK;
पूर्ण

#घोषणा REG_A4XX_CP_DRAW_INDX_INसूचीECT_3			0x00000003
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_3_INसूचीECT__MASK		0xffffffff
#घोषणा A4XX_CP_DRAW_INDX_INसूचीECT_3_INसूचीECT__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_DRAW_INDX_INसूचीECT_3_INसूचीECT(uपूर्णांक32_t val)
अणु
	वापस ((val) << A4XX_CP_DRAW_INDX_INसूचीECT_3_INसूचीECT__SHIFT) & A4XX_CP_DRAW_INDX_INसूचीECT_3_INसूचीECT__MASK;
पूर्ण


#घोषणा REG_A5XX_CP_DRAW_INDX_INसूचीECT_1			0x00000001
#घोषणा A5XX_CP_DRAW_INDX_INसूचीECT_1_INDX_BASE_LO__MASK		0xffffffff
#घोषणा A5XX_CP_DRAW_INDX_INसूचीECT_1_INDX_BASE_LO__SHIFT	0
अटल अंतरभूत uपूर्णांक32_t A5XX_CP_DRAW_INDX_INसूचीECT_1_INDX_BASE_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << A5XX_CP_DRAW_INDX_INसूचीECT_1_INDX_BASE_LO__SHIFT) & A5XX_CP_DRAW_INDX_INसूचीECT_1_INDX_BASE_LO__MASK;
पूर्ण

#घोषणा REG_A5XX_CP_DRAW_INDX_INसूचीECT_2			0x00000002
#घोषणा A5XX_CP_DRAW_INDX_INसूचीECT_2_INDX_BASE_HI__MASK		0xffffffff
#घोषणा A5XX_CP_DRAW_INDX_INसूचीECT_2_INDX_BASE_HI__SHIFT	0
अटल अंतरभूत uपूर्णांक32_t A5XX_CP_DRAW_INDX_INसूचीECT_2_INDX_BASE_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << A5XX_CP_DRAW_INDX_INसूचीECT_2_INDX_BASE_HI__SHIFT) & A5XX_CP_DRAW_INDX_INसूचीECT_2_INDX_BASE_HI__MASK;
पूर्ण

#घोषणा REG_A5XX_CP_DRAW_INDX_INसूचीECT_INDX_BASE		0x00000001

#घोषणा REG_A5XX_CP_DRAW_INDX_INसूचीECT_3			0x00000003
#घोषणा A5XX_CP_DRAW_INDX_INसूचीECT_3_MAX_INDICES__MASK		0xffffffff
#घोषणा A5XX_CP_DRAW_INDX_INसूचीECT_3_MAX_INDICES__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A5XX_CP_DRAW_INDX_INसूचीECT_3_MAX_INDICES(uपूर्णांक32_t val)
अणु
	वापस ((val) << A5XX_CP_DRAW_INDX_INसूचीECT_3_MAX_INDICES__SHIFT) & A5XX_CP_DRAW_INDX_INसूचीECT_3_MAX_INDICES__MASK;
पूर्ण

#घोषणा REG_A5XX_CP_DRAW_INDX_INसूचीECT_4			0x00000004
#घोषणा A5XX_CP_DRAW_INDX_INसूचीECT_4_INसूचीECT_LO__MASK		0xffffffff
#घोषणा A5XX_CP_DRAW_INDX_INसूचीECT_4_INसूचीECT_LO__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A5XX_CP_DRAW_INDX_INसूचीECT_4_INसूचीECT_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << A5XX_CP_DRAW_INDX_INसूचीECT_4_INसूचीECT_LO__SHIFT) & A5XX_CP_DRAW_INDX_INसूचीECT_4_INसूचीECT_LO__MASK;
पूर्ण

#घोषणा REG_A5XX_CP_DRAW_INDX_INसूचीECT_5			0x00000005
#घोषणा A5XX_CP_DRAW_INDX_INसूचीECT_5_INसूचीECT_HI__MASK		0xffffffff
#घोषणा A5XX_CP_DRAW_INDX_INसूचीECT_5_INसूचीECT_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A5XX_CP_DRAW_INDX_INसूचीECT_5_INसूचीECT_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << A5XX_CP_DRAW_INDX_INसूचीECT_5_INसूचीECT_HI__SHIFT) & A5XX_CP_DRAW_INDX_INसूचीECT_5_INसूचीECT_HI__MASK;
पूर्ण

#घोषणा REG_A5XX_CP_DRAW_INDX_INसूचीECT_INसूचीECT			0x00000004

#घोषणा REG_A6XX_CP_DRAW_INसूचीECT_MULTI_0			0x00000000
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_0_PRIM_TYPE__MASK		0x0000003f
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_0_PRIM_TYPE__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_DRAW_INसूचीECT_MULTI_0_PRIM_TYPE(क्रमागत pc_di_primtype val)
अणु
	वापस ((val) << A6XX_CP_DRAW_INसूचीECT_MULTI_0_PRIM_TYPE__SHIFT) & A6XX_CP_DRAW_INसूचीECT_MULTI_0_PRIM_TYPE__MASK;
पूर्ण
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_0_SOURCE_SELECT__MASK	0x000000c0
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_0_SOURCE_SELECT__SHIFT	6
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_DRAW_INसूचीECT_MULTI_0_SOURCE_SELECT(क्रमागत pc_di_src_sel val)
अणु
	वापस ((val) << A6XX_CP_DRAW_INसूचीECT_MULTI_0_SOURCE_SELECT__SHIFT) & A6XX_CP_DRAW_INसूचीECT_MULTI_0_SOURCE_SELECT__MASK;
पूर्ण
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_0_VIS_CULL__MASK		0x00000300
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_0_VIS_CULL__SHIFT		8
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_DRAW_INसूचीECT_MULTI_0_VIS_CULL(क्रमागत pc_di_vis_cull_mode val)
अणु
	वापस ((val) << A6XX_CP_DRAW_INसूचीECT_MULTI_0_VIS_CULL__SHIFT) & A6XX_CP_DRAW_INसूचीECT_MULTI_0_VIS_CULL__MASK;
पूर्ण
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_0_INDEX_SIZE__MASK		0x00000c00
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_0_INDEX_SIZE__SHIFT		10
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_DRAW_INसूचीECT_MULTI_0_INDEX_SIZE(क्रमागत a4xx_index_size val)
अणु
	वापस ((val) << A6XX_CP_DRAW_INसूचीECT_MULTI_0_INDEX_SIZE__SHIFT) & A6XX_CP_DRAW_INसूचीECT_MULTI_0_INDEX_SIZE__MASK;
पूर्ण
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_0_PATCH_TYPE__MASK		0x00003000
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_0_PATCH_TYPE__SHIFT		12
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_DRAW_INसूचीECT_MULTI_0_PATCH_TYPE(क्रमागत a6xx_patch_type val)
अणु
	वापस ((val) << A6XX_CP_DRAW_INसूचीECT_MULTI_0_PATCH_TYPE__SHIFT) & A6XX_CP_DRAW_INसूचीECT_MULTI_0_PATCH_TYPE__MASK;
पूर्ण
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_0_GS_ENABLE			0x00010000
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_0_TESS_ENABLE		0x00020000

#घोषणा REG_A6XX_CP_DRAW_INसूचीECT_MULTI_1			0x00000001
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_1_OPCODE__MASK		0x0000000f
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_1_OPCODE__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_DRAW_INसूचीECT_MULTI_1_OPCODE(क्रमागत a6xx_draw_indirect_opcode val)
अणु
	वापस ((val) << A6XX_CP_DRAW_INसूचीECT_MULTI_1_OPCODE__SHIFT) & A6XX_CP_DRAW_INसूचीECT_MULTI_1_OPCODE__MASK;
पूर्ण
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_1_DST_OFF__MASK		0x003fff00
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_1_DST_OFF__SHIFT		8
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_DRAW_INसूचीECT_MULTI_1_DST_OFF(uपूर्णांक32_t val)
अणु
	वापस ((val) << A6XX_CP_DRAW_INसूचीECT_MULTI_1_DST_OFF__SHIFT) & A6XX_CP_DRAW_INसूचीECT_MULTI_1_DST_OFF__MASK;
पूर्ण

#घोषणा REG_A6XX_CP_DRAW_INसूचीECT_MULTI_2			0x00000002
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_2_DRAW_COUNT__MASK		0xffffffff
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_2_DRAW_COUNT__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_DRAW_INसूचीECT_MULTI_2_DRAW_COUNT(uपूर्णांक32_t val)
अणु
	वापस ((val) << A6XX_CP_DRAW_INसूचीECT_MULTI_2_DRAW_COUNT__SHIFT) & A6XX_CP_DRAW_INसूचीECT_MULTI_2_DRAW_COUNT__MASK;
पूर्ण

#घोषणा REG_A6XX_CP_DRAW_INसूचीECT_MULTI_ADDRESS_0		0x00000003

#घोषणा REG_A6XX_CP_DRAW_INसूचीECT_MULTI_5			0x00000005
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_5_PARAM_0__MASK		0xffffffff
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_5_PARAM_0__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_DRAW_INसूचीECT_MULTI_5_PARAM_0(uपूर्णांक32_t val)
अणु
	वापस ((val) << A6XX_CP_DRAW_INसूचीECT_MULTI_5_PARAM_0__SHIFT) & A6XX_CP_DRAW_INसूचीECT_MULTI_5_PARAM_0__MASK;
पूर्ण

#घोषणा REG_A6XX_CP_DRAW_INसूचीECT_MULTI_INसूचीECT		0x00000006

#घोषणा REG_A6XX_CP_DRAW_INसूचीECT_MULTI_8			0x00000008
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_8_STRIDE__MASK		0xffffffff
#घोषणा A6XX_CP_DRAW_INसूचीECT_MULTI_8_STRIDE__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_DRAW_INसूचीECT_MULTI_8_STRIDE(uपूर्णांक32_t val)
अणु
	वापस ((val) << A6XX_CP_DRAW_INसूचीECT_MULTI_8_STRIDE__SHIFT) & A6XX_CP_DRAW_INसूचीECT_MULTI_8_STRIDE__MASK;
पूर्ण

अटल अंतरभूत uपूर्णांक32_t REG_CP_SET_DRAW_STATE_(uपूर्णांक32_t i0) अणु वापस 0x00000000 + 0x3*i0; पूर्ण

अटल अंतरभूत uपूर्णांक32_t REG_CP_SET_DRAW_STATE__0(uपूर्णांक32_t i0) अणु वापस 0x00000000 + 0x3*i0; पूर्ण
#घोषणा CP_SET_DRAW_STATE__0_COUNT__MASK			0x0000ffff
#घोषणा CP_SET_DRAW_STATE__0_COUNT__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_DRAW_STATE__0_COUNT(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_DRAW_STATE__0_COUNT__SHIFT) & CP_SET_DRAW_STATE__0_COUNT__MASK;
पूर्ण
#घोषणा CP_SET_DRAW_STATE__0_सूचीTY				0x00010000
#घोषणा CP_SET_DRAW_STATE__0_DISABLE				0x00020000
#घोषणा CP_SET_DRAW_STATE__0_DISABLE_ALL_GROUPS			0x00040000
#घोषणा CP_SET_DRAW_STATE__0_LOAD_IMMED				0x00080000
#घोषणा CP_SET_DRAW_STATE__0_BINNING				0x00100000
#घोषणा CP_SET_DRAW_STATE__0_GMEM				0x00200000
#घोषणा CP_SET_DRAW_STATE__0_SYSMEM				0x00400000
#घोषणा CP_SET_DRAW_STATE__0_GROUP_ID__MASK			0x1f000000
#घोषणा CP_SET_DRAW_STATE__0_GROUP_ID__SHIFT			24
अटल अंतरभूत uपूर्णांक32_t CP_SET_DRAW_STATE__0_GROUP_ID(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_DRAW_STATE__0_GROUP_ID__SHIFT) & CP_SET_DRAW_STATE__0_GROUP_ID__MASK;
पूर्ण

अटल अंतरभूत uपूर्णांक32_t REG_CP_SET_DRAW_STATE__1(uपूर्णांक32_t i0) अणु वापस 0x00000001 + 0x3*i0; पूर्ण
#घोषणा CP_SET_DRAW_STATE__1_ADDR_LO__MASK			0xffffffff
#घोषणा CP_SET_DRAW_STATE__1_ADDR_LO__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_DRAW_STATE__1_ADDR_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_DRAW_STATE__1_ADDR_LO__SHIFT) & CP_SET_DRAW_STATE__1_ADDR_LO__MASK;
पूर्ण

अटल अंतरभूत uपूर्णांक32_t REG_CP_SET_DRAW_STATE__2(uपूर्णांक32_t i0) अणु वापस 0x00000002 + 0x3*i0; पूर्ण
#घोषणा CP_SET_DRAW_STATE__2_ADDR_HI__MASK			0xffffffff
#घोषणा CP_SET_DRAW_STATE__2_ADDR_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_DRAW_STATE__2_ADDR_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_DRAW_STATE__2_ADDR_HI__SHIFT) & CP_SET_DRAW_STATE__2_ADDR_HI__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_0					0x00000000

#घोषणा REG_CP_SET_BIN_1					0x00000001
#घोषणा CP_SET_BIN_1_X1__MASK					0x0000ffff
#घोषणा CP_SET_BIN_1_X1__SHIFT					0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_1_X1(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_1_X1__SHIFT) & CP_SET_BIN_1_X1__MASK;
पूर्ण
#घोषणा CP_SET_BIN_1_Y1__MASK					0xffff0000
#घोषणा CP_SET_BIN_1_Y1__SHIFT					16
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_1_Y1(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_1_Y1__SHIFT) & CP_SET_BIN_1_Y1__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_2					0x00000002
#घोषणा CP_SET_BIN_2_X2__MASK					0x0000ffff
#घोषणा CP_SET_BIN_2_X2__SHIFT					0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_2_X2(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_2_X2__SHIFT) & CP_SET_BIN_2_X2__MASK;
पूर्ण
#घोषणा CP_SET_BIN_2_Y2__MASK					0xffff0000
#घोषणा CP_SET_BIN_2_Y2__SHIFT					16
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_2_Y2(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_2_Y2__SHIFT) & CP_SET_BIN_2_Y2__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA_0					0x00000000
#घोषणा CP_SET_BIN_DATA_0_BIN_DATA_ADDR__MASK			0xffffffff
#घोषणा CP_SET_BIN_DATA_0_BIN_DATA_ADDR__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA_0_BIN_DATA_ADDR(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA_0_BIN_DATA_ADDR__SHIFT) & CP_SET_BIN_DATA_0_BIN_DATA_ADDR__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA_1					0x00000001
#घोषणा CP_SET_BIN_DATA_1_BIN_SIZE_ADDRESS__MASK		0xffffffff
#घोषणा CP_SET_BIN_DATA_1_BIN_SIZE_ADDRESS__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA_1_BIN_SIZE_ADDRESS(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA_1_BIN_SIZE_ADDRESS__SHIFT) & CP_SET_BIN_DATA_1_BIN_SIZE_ADDRESS__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA5_0					0x00000000
#घोषणा CP_SET_BIN_DATA5_0_VSC_SIZE__MASK			0x003f0000
#घोषणा CP_SET_BIN_DATA5_0_VSC_SIZE__SHIFT			16
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_0_VSC_SIZE(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_0_VSC_SIZE__SHIFT) & CP_SET_BIN_DATA5_0_VSC_SIZE__MASK;
पूर्ण
#घोषणा CP_SET_BIN_DATA5_0_VSC_N__MASK				0x07c00000
#घोषणा CP_SET_BIN_DATA5_0_VSC_N__SHIFT				22
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_0_VSC_N(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_0_VSC_N__SHIFT) & CP_SET_BIN_DATA5_0_VSC_N__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA5_1					0x00000001
#घोषणा CP_SET_BIN_DATA5_1_BIN_DATA_ADDR_LO__MASK		0xffffffff
#घोषणा CP_SET_BIN_DATA5_1_BIN_DATA_ADDR_LO__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_1_BIN_DATA_ADDR_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_1_BIN_DATA_ADDR_LO__SHIFT) & CP_SET_BIN_DATA5_1_BIN_DATA_ADDR_LO__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA5_2					0x00000002
#घोषणा CP_SET_BIN_DATA5_2_BIN_DATA_ADDR_HI__MASK		0xffffffff
#घोषणा CP_SET_BIN_DATA5_2_BIN_DATA_ADDR_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_2_BIN_DATA_ADDR_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_2_BIN_DATA_ADDR_HI__SHIFT) & CP_SET_BIN_DATA5_2_BIN_DATA_ADDR_HI__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA5_3					0x00000003
#घोषणा CP_SET_BIN_DATA5_3_BIN_SIZE_ADDRESS_LO__MASK		0xffffffff
#घोषणा CP_SET_BIN_DATA5_3_BIN_SIZE_ADDRESS_LO__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_3_BIN_SIZE_ADDRESS_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_3_BIN_SIZE_ADDRESS_LO__SHIFT) & CP_SET_BIN_DATA5_3_BIN_SIZE_ADDRESS_LO__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA5_4					0x00000004
#घोषणा CP_SET_BIN_DATA5_4_BIN_SIZE_ADDRESS_HI__MASK		0xffffffff
#घोषणा CP_SET_BIN_DATA5_4_BIN_SIZE_ADDRESS_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_4_BIN_SIZE_ADDRESS_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_4_BIN_SIZE_ADDRESS_HI__SHIFT) & CP_SET_BIN_DATA5_4_BIN_SIZE_ADDRESS_HI__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA5_5					0x00000005
#घोषणा CP_SET_BIN_DATA5_5_BIN_PRIM_STRM_LO__MASK		0xffffffff
#घोषणा CP_SET_BIN_DATA5_5_BIN_PRIM_STRM_LO__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_5_BIN_PRIM_STRM_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_5_BIN_PRIM_STRM_LO__SHIFT) & CP_SET_BIN_DATA5_5_BIN_PRIM_STRM_LO__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA5_6					0x00000006
#घोषणा CP_SET_BIN_DATA5_6_BIN_PRIM_STRM_HI__MASK		0xffffffff
#घोषणा CP_SET_BIN_DATA5_6_BIN_PRIM_STRM_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_6_BIN_PRIM_STRM_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_6_BIN_PRIM_STRM_HI__SHIFT) & CP_SET_BIN_DATA5_6_BIN_PRIM_STRM_HI__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA5_OFFSET_0				0x00000000
#घोषणा CP_SET_BIN_DATA5_OFFSET_0_VSC_SIZE__MASK		0x003f0000
#घोषणा CP_SET_BIN_DATA5_OFFSET_0_VSC_SIZE__SHIFT		16
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_OFFSET_0_VSC_SIZE(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_OFFSET_0_VSC_SIZE__SHIFT) & CP_SET_BIN_DATA5_OFFSET_0_VSC_SIZE__MASK;
पूर्ण
#घोषणा CP_SET_BIN_DATA5_OFFSET_0_VSC_N__MASK			0x07c00000
#घोषणा CP_SET_BIN_DATA5_OFFSET_0_VSC_N__SHIFT			22
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_OFFSET_0_VSC_N(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_OFFSET_0_VSC_N__SHIFT) & CP_SET_BIN_DATA5_OFFSET_0_VSC_N__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA5_OFFSET_1				0x00000001
#घोषणा CP_SET_BIN_DATA5_OFFSET_1_BIN_DATA_OFFSET__MASK		0xffffffff
#घोषणा CP_SET_BIN_DATA5_OFFSET_1_BIN_DATA_OFFSET__SHIFT	0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_OFFSET_1_BIN_DATA_OFFSET(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_OFFSET_1_BIN_DATA_OFFSET__SHIFT) & CP_SET_BIN_DATA5_OFFSET_1_BIN_DATA_OFFSET__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA5_OFFSET_2				0x00000002
#घोषणा CP_SET_BIN_DATA5_OFFSET_2_BIN_SIZE_OFFSET__MASK		0xffffffff
#घोषणा CP_SET_BIN_DATA5_OFFSET_2_BIN_SIZE_OFFSET__SHIFT	0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_OFFSET_2_BIN_SIZE_OFFSET(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_OFFSET_2_BIN_SIZE_OFFSET__SHIFT) & CP_SET_BIN_DATA5_OFFSET_2_BIN_SIZE_OFFSET__MASK;
पूर्ण

#घोषणा REG_CP_SET_BIN_DATA5_OFFSET_3				0x00000003
#घोषणा CP_SET_BIN_DATA5_OFFSET_3_BIN_DATA2_OFFSET__MASK	0xffffffff
#घोषणा CP_SET_BIN_DATA5_OFFSET_3_BIN_DATA2_OFFSET__SHIFT	0
अटल अंतरभूत uपूर्णांक32_t CP_SET_BIN_DATA5_OFFSET_3_BIN_DATA2_OFFSET(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_BIN_DATA5_OFFSET_3_BIN_DATA2_OFFSET__SHIFT) & CP_SET_BIN_DATA5_OFFSET_3_BIN_DATA2_OFFSET__MASK;
पूर्ण

#घोषणा REG_CP_REG_RMW_0					0x00000000
#घोषणा CP_REG_RMW_0_DST_REG__MASK				0x0003ffff
#घोषणा CP_REG_RMW_0_DST_REG__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_REG_RMW_0_DST_REG(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_RMW_0_DST_REG__SHIFT) & CP_REG_RMW_0_DST_REG__MASK;
पूर्ण
#घोषणा CP_REG_RMW_0_ROTATE__MASK				0x1f000000
#घोषणा CP_REG_RMW_0_ROTATE__SHIFT				24
अटल अंतरभूत uपूर्णांक32_t CP_REG_RMW_0_ROTATE(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_RMW_0_ROTATE__SHIFT) & CP_REG_RMW_0_ROTATE__MASK;
पूर्ण
#घोषणा CP_REG_RMW_0_SRC1_ADD					0x20000000
#घोषणा CP_REG_RMW_0_SRC1_IS_REG				0x40000000
#घोषणा CP_REG_RMW_0_SRC0_IS_REG				0x80000000

#घोषणा REG_CP_REG_RMW_1					0x00000001
#घोषणा CP_REG_RMW_1_SRC0__MASK					0xffffffff
#घोषणा CP_REG_RMW_1_SRC0__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_REG_RMW_1_SRC0(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_RMW_1_SRC0__SHIFT) & CP_REG_RMW_1_SRC0__MASK;
पूर्ण

#घोषणा REG_CP_REG_RMW_2					0x00000002
#घोषणा CP_REG_RMW_2_SRC1__MASK					0xffffffff
#घोषणा CP_REG_RMW_2_SRC1__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_REG_RMW_2_SRC1(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_RMW_2_SRC1__SHIFT) & CP_REG_RMW_2_SRC1__MASK;
पूर्ण

#घोषणा REG_CP_REG_TO_MEM_0					0x00000000
#घोषणा CP_REG_TO_MEM_0_REG__MASK				0x0003ffff
#घोषणा CP_REG_TO_MEM_0_REG__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_0_REG(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_0_REG__SHIFT) & CP_REG_TO_MEM_0_REG__MASK;
पूर्ण
#घोषणा CP_REG_TO_MEM_0_CNT__MASK				0x3ffc0000
#घोषणा CP_REG_TO_MEM_0_CNT__SHIFT				18
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_0_CNT(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_0_CNT__SHIFT) & CP_REG_TO_MEM_0_CNT__MASK;
पूर्ण
#घोषणा CP_REG_TO_MEM_0_64B					0x40000000
#घोषणा CP_REG_TO_MEM_0_ACCUMULATE				0x80000000

#घोषणा REG_CP_REG_TO_MEM_1					0x00000001
#घोषणा CP_REG_TO_MEM_1_DEST__MASK				0xffffffff
#घोषणा CP_REG_TO_MEM_1_DEST__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_1_DEST(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_1_DEST__SHIFT) & CP_REG_TO_MEM_1_DEST__MASK;
पूर्ण

#घोषणा REG_CP_REG_TO_MEM_2					0x00000002
#घोषणा CP_REG_TO_MEM_2_DEST_HI__MASK				0xffffffff
#घोषणा CP_REG_TO_MEM_2_DEST_HI__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_2_DEST_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_2_DEST_HI__SHIFT) & CP_REG_TO_MEM_2_DEST_HI__MASK;
पूर्ण

#घोषणा REG_CP_REG_TO_MEM_OFFSET_REG_0				0x00000000
#घोषणा CP_REG_TO_MEM_OFFSET_REG_0_REG__MASK			0x0003ffff
#घोषणा CP_REG_TO_MEM_OFFSET_REG_0_REG__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_OFFSET_REG_0_REG(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_OFFSET_REG_0_REG__SHIFT) & CP_REG_TO_MEM_OFFSET_REG_0_REG__MASK;
पूर्ण
#घोषणा CP_REG_TO_MEM_OFFSET_REG_0_CNT__MASK			0x3ffc0000
#घोषणा CP_REG_TO_MEM_OFFSET_REG_0_CNT__SHIFT			18
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_OFFSET_REG_0_CNT(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_OFFSET_REG_0_CNT__SHIFT) & CP_REG_TO_MEM_OFFSET_REG_0_CNT__MASK;
पूर्ण
#घोषणा CP_REG_TO_MEM_OFFSET_REG_0_64B				0x40000000
#घोषणा CP_REG_TO_MEM_OFFSET_REG_0_ACCUMULATE			0x80000000

#घोषणा REG_CP_REG_TO_MEM_OFFSET_REG_1				0x00000001
#घोषणा CP_REG_TO_MEM_OFFSET_REG_1_DEST__MASK			0xffffffff
#घोषणा CP_REG_TO_MEM_OFFSET_REG_1_DEST__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_OFFSET_REG_1_DEST(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_OFFSET_REG_1_DEST__SHIFT) & CP_REG_TO_MEM_OFFSET_REG_1_DEST__MASK;
पूर्ण

#घोषणा REG_CP_REG_TO_MEM_OFFSET_REG_2				0x00000002
#घोषणा CP_REG_TO_MEM_OFFSET_REG_2_DEST_HI__MASK		0xffffffff
#घोषणा CP_REG_TO_MEM_OFFSET_REG_2_DEST_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_OFFSET_REG_2_DEST_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_OFFSET_REG_2_DEST_HI__SHIFT) & CP_REG_TO_MEM_OFFSET_REG_2_DEST_HI__MASK;
पूर्ण

#घोषणा REG_CP_REG_TO_MEM_OFFSET_REG_3				0x00000003
#घोषणा CP_REG_TO_MEM_OFFSET_REG_3_OFFSET0__MASK		0x0003ffff
#घोषणा CP_REG_TO_MEM_OFFSET_REG_3_OFFSET0__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_OFFSET_REG_3_OFFSET0(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_OFFSET_REG_3_OFFSET0__SHIFT) & CP_REG_TO_MEM_OFFSET_REG_3_OFFSET0__MASK;
पूर्ण
#घोषणा CP_REG_TO_MEM_OFFSET_REG_3_OFFSET0_SCRATCH		0x00080000

#घोषणा REG_CP_REG_TO_MEM_OFFSET_MEM_0				0x00000000
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_0_REG__MASK			0x0003ffff
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_0_REG__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_OFFSET_MEM_0_REG(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_OFFSET_MEM_0_REG__SHIFT) & CP_REG_TO_MEM_OFFSET_MEM_0_REG__MASK;
पूर्ण
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_0_CNT__MASK			0x3ffc0000
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_0_CNT__SHIFT			18
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_OFFSET_MEM_0_CNT(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_OFFSET_MEM_0_CNT__SHIFT) & CP_REG_TO_MEM_OFFSET_MEM_0_CNT__MASK;
पूर्ण
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_0_64B				0x40000000
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_0_ACCUMULATE			0x80000000

#घोषणा REG_CP_REG_TO_MEM_OFFSET_MEM_1				0x00000001
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_1_DEST__MASK			0xffffffff
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_1_DEST__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_OFFSET_MEM_1_DEST(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_OFFSET_MEM_1_DEST__SHIFT) & CP_REG_TO_MEM_OFFSET_MEM_1_DEST__MASK;
पूर्ण

#घोषणा REG_CP_REG_TO_MEM_OFFSET_MEM_2				0x00000002
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_2_DEST_HI__MASK		0xffffffff
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_2_DEST_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_OFFSET_MEM_2_DEST_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_OFFSET_MEM_2_DEST_HI__SHIFT) & CP_REG_TO_MEM_OFFSET_MEM_2_DEST_HI__MASK;
पूर्ण

#घोषणा REG_CP_REG_TO_MEM_OFFSET_MEM_3				0x00000003
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_3_OFFSET_LO__MASK		0xffffffff
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_3_OFFSET_LO__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_OFFSET_MEM_3_OFFSET_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_OFFSET_MEM_3_OFFSET_LO__SHIFT) & CP_REG_TO_MEM_OFFSET_MEM_3_OFFSET_LO__MASK;
पूर्ण

#घोषणा REG_CP_REG_TO_MEM_OFFSET_MEM_4				0x00000004
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_4_OFFSET_HI__MASK		0xffffffff
#घोषणा CP_REG_TO_MEM_OFFSET_MEM_4_OFFSET_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_MEM_OFFSET_MEM_4_OFFSET_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_MEM_OFFSET_MEM_4_OFFSET_HI__SHIFT) & CP_REG_TO_MEM_OFFSET_MEM_4_OFFSET_HI__MASK;
पूर्ण

#घोषणा REG_CP_MEM_TO_REG_0					0x00000000
#घोषणा CP_MEM_TO_REG_0_REG__MASK				0x0003ffff
#घोषणा CP_MEM_TO_REG_0_REG__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_MEM_TO_REG_0_REG(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_MEM_TO_REG_0_REG__SHIFT) & CP_MEM_TO_REG_0_REG__MASK;
पूर्ण
#घोषणा CP_MEM_TO_REG_0_CNT__MASK				0x3ff80000
#घोषणा CP_MEM_TO_REG_0_CNT__SHIFT				19
अटल अंतरभूत uपूर्णांक32_t CP_MEM_TO_REG_0_CNT(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_MEM_TO_REG_0_CNT__SHIFT) & CP_MEM_TO_REG_0_CNT__MASK;
पूर्ण
#घोषणा CP_MEM_TO_REG_0_SHIFT_BY_2				0x40000000
#घोषणा CP_MEM_TO_REG_0_UNK31					0x80000000

#घोषणा REG_CP_MEM_TO_REG_1					0x00000001
#घोषणा CP_MEM_TO_REG_1_SRC__MASK				0xffffffff
#घोषणा CP_MEM_TO_REG_1_SRC__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_MEM_TO_REG_1_SRC(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_MEM_TO_REG_1_SRC__SHIFT) & CP_MEM_TO_REG_1_SRC__MASK;
पूर्ण

#घोषणा REG_CP_MEM_TO_REG_2					0x00000002
#घोषणा CP_MEM_TO_REG_2_SRC_HI__MASK				0xffffffff
#घोषणा CP_MEM_TO_REG_2_SRC_HI__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_MEM_TO_REG_2_SRC_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_MEM_TO_REG_2_SRC_HI__SHIFT) & CP_MEM_TO_REG_2_SRC_HI__MASK;
पूर्ण

#घोषणा REG_CP_MEM_TO_MEM_0					0x00000000
#घोषणा CP_MEM_TO_MEM_0_NEG_A					0x00000001
#घोषणा CP_MEM_TO_MEM_0_NEG_B					0x00000002
#घोषणा CP_MEM_TO_MEM_0_NEG_C					0x00000004
#घोषणा CP_MEM_TO_MEM_0_DOUBLE					0x20000000
#घोषणा CP_MEM_TO_MEM_0_WAIT_FOR_MEM_WRITES			0x40000000
#घोषणा CP_MEM_TO_MEM_0_UNK31					0x80000000

#घोषणा REG_CP_MEMCPY_0						0x00000000
#घोषणा CP_MEMCPY_0_DWORDS__MASK				0xffffffff
#घोषणा CP_MEMCPY_0_DWORDS__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_MEMCPY_0_DWORDS(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_MEMCPY_0_DWORDS__SHIFT) & CP_MEMCPY_0_DWORDS__MASK;
पूर्ण

#घोषणा REG_CP_MEMCPY_1						0x00000001
#घोषणा CP_MEMCPY_1_SRC_LO__MASK				0xffffffff
#घोषणा CP_MEMCPY_1_SRC_LO__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_MEMCPY_1_SRC_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_MEMCPY_1_SRC_LO__SHIFT) & CP_MEMCPY_1_SRC_LO__MASK;
पूर्ण

#घोषणा REG_CP_MEMCPY_2						0x00000002
#घोषणा CP_MEMCPY_2_SRC_HI__MASK				0xffffffff
#घोषणा CP_MEMCPY_2_SRC_HI__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_MEMCPY_2_SRC_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_MEMCPY_2_SRC_HI__SHIFT) & CP_MEMCPY_2_SRC_HI__MASK;
पूर्ण

#घोषणा REG_CP_MEMCPY_3						0x00000003
#घोषणा CP_MEMCPY_3_DST_LO__MASK				0xffffffff
#घोषणा CP_MEMCPY_3_DST_LO__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_MEMCPY_3_DST_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_MEMCPY_3_DST_LO__SHIFT) & CP_MEMCPY_3_DST_LO__MASK;
पूर्ण

#घोषणा REG_CP_MEMCPY_4						0x00000004
#घोषणा CP_MEMCPY_4_DST_HI__MASK				0xffffffff
#घोषणा CP_MEMCPY_4_DST_HI__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_MEMCPY_4_DST_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_MEMCPY_4_DST_HI__SHIFT) & CP_MEMCPY_4_DST_HI__MASK;
पूर्ण

#घोषणा REG_CP_REG_TO_SCRATCH_0					0x00000000
#घोषणा CP_REG_TO_SCRATCH_0_REG__MASK				0x0003ffff
#घोषणा CP_REG_TO_SCRATCH_0_REG__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_SCRATCH_0_REG(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_SCRATCH_0_REG__SHIFT) & CP_REG_TO_SCRATCH_0_REG__MASK;
पूर्ण
#घोषणा CP_REG_TO_SCRATCH_0_SCRATCH__MASK			0x00700000
#घोषणा CP_REG_TO_SCRATCH_0_SCRATCH__SHIFT			20
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_SCRATCH_0_SCRATCH(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_SCRATCH_0_SCRATCH__SHIFT) & CP_REG_TO_SCRATCH_0_SCRATCH__MASK;
पूर्ण
#घोषणा CP_REG_TO_SCRATCH_0_CNT__MASK				0x07000000
#घोषणा CP_REG_TO_SCRATCH_0_CNT__SHIFT				24
अटल अंतरभूत uपूर्णांक32_t CP_REG_TO_SCRATCH_0_CNT(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_REG_TO_SCRATCH_0_CNT__SHIFT) & CP_REG_TO_SCRATCH_0_CNT__MASK;
पूर्ण

#घोषणा REG_CP_SCRATCH_TO_REG_0					0x00000000
#घोषणा CP_SCRATCH_TO_REG_0_REG__MASK				0x0003ffff
#घोषणा CP_SCRATCH_TO_REG_0_REG__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_SCRATCH_TO_REG_0_REG(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SCRATCH_TO_REG_0_REG__SHIFT) & CP_SCRATCH_TO_REG_0_REG__MASK;
पूर्ण
#घोषणा CP_SCRATCH_TO_REG_0_UNK18				0x00040000
#घोषणा CP_SCRATCH_TO_REG_0_SCRATCH__MASK			0x00700000
#घोषणा CP_SCRATCH_TO_REG_0_SCRATCH__SHIFT			20
अटल अंतरभूत uपूर्णांक32_t CP_SCRATCH_TO_REG_0_SCRATCH(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SCRATCH_TO_REG_0_SCRATCH__SHIFT) & CP_SCRATCH_TO_REG_0_SCRATCH__MASK;
पूर्ण
#घोषणा CP_SCRATCH_TO_REG_0_CNT__MASK				0x07000000
#घोषणा CP_SCRATCH_TO_REG_0_CNT__SHIFT				24
अटल अंतरभूत uपूर्णांक32_t CP_SCRATCH_TO_REG_0_CNT(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SCRATCH_TO_REG_0_CNT__SHIFT) & CP_SCRATCH_TO_REG_0_CNT__MASK;
पूर्ण

#घोषणा REG_CP_SCRATCH_WRITE_0					0x00000000
#घोषणा CP_SCRATCH_WRITE_0_SCRATCH__MASK			0x00700000
#घोषणा CP_SCRATCH_WRITE_0_SCRATCH__SHIFT			20
अटल अंतरभूत uपूर्णांक32_t CP_SCRATCH_WRITE_0_SCRATCH(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SCRATCH_WRITE_0_SCRATCH__SHIFT) & CP_SCRATCH_WRITE_0_SCRATCH__MASK;
पूर्ण

#घोषणा REG_CP_MEM_WRITE_0					0x00000000
#घोषणा CP_MEM_WRITE_0_ADDR_LO__MASK				0xffffffff
#घोषणा CP_MEM_WRITE_0_ADDR_LO__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_MEM_WRITE_0_ADDR_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_MEM_WRITE_0_ADDR_LO__SHIFT) & CP_MEM_WRITE_0_ADDR_LO__MASK;
पूर्ण

#घोषणा REG_CP_MEM_WRITE_1					0x00000001
#घोषणा CP_MEM_WRITE_1_ADDR_HI__MASK				0xffffffff
#घोषणा CP_MEM_WRITE_1_ADDR_HI__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_MEM_WRITE_1_ADDR_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_MEM_WRITE_1_ADDR_HI__SHIFT) & CP_MEM_WRITE_1_ADDR_HI__MASK;
पूर्ण

#घोषणा REG_CP_COND_WRITE_0					0x00000000
#घोषणा CP_COND_WRITE_0_FUNCTION__MASK				0x00000007
#घोषणा CP_COND_WRITE_0_FUNCTION__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE_0_FUNCTION(क्रमागत cp_cond_function val)
अणु
	वापस ((val) << CP_COND_WRITE_0_FUNCTION__SHIFT) & CP_COND_WRITE_0_FUNCTION__MASK;
पूर्ण
#घोषणा CP_COND_WRITE_0_POLL_MEMORY				0x00000010
#घोषणा CP_COND_WRITE_0_WRITE_MEMORY				0x00000100

#घोषणा REG_CP_COND_WRITE_1					0x00000001
#घोषणा CP_COND_WRITE_1_POLL_ADDR__MASK				0xffffffff
#घोषणा CP_COND_WRITE_1_POLL_ADDR__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE_1_POLL_ADDR(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_WRITE_1_POLL_ADDR__SHIFT) & CP_COND_WRITE_1_POLL_ADDR__MASK;
पूर्ण

#घोषणा REG_CP_COND_WRITE_2					0x00000002
#घोषणा CP_COND_WRITE_2_REF__MASK				0xffffffff
#घोषणा CP_COND_WRITE_2_REF__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE_2_REF(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_WRITE_2_REF__SHIFT) & CP_COND_WRITE_2_REF__MASK;
पूर्ण

#घोषणा REG_CP_COND_WRITE_3					0x00000003
#घोषणा CP_COND_WRITE_3_MASK__MASK				0xffffffff
#घोषणा CP_COND_WRITE_3_MASK__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE_3_MASK(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_WRITE_3_MASK__SHIFT) & CP_COND_WRITE_3_MASK__MASK;
पूर्ण

#घोषणा REG_CP_COND_WRITE_4					0x00000004
#घोषणा CP_COND_WRITE_4_WRITE_ADDR__MASK			0xffffffff
#घोषणा CP_COND_WRITE_4_WRITE_ADDR__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE_4_WRITE_ADDR(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_WRITE_4_WRITE_ADDR__SHIFT) & CP_COND_WRITE_4_WRITE_ADDR__MASK;
पूर्ण

#घोषणा REG_CP_COND_WRITE_5					0x00000005
#घोषणा CP_COND_WRITE_5_WRITE_DATA__MASK			0xffffffff
#घोषणा CP_COND_WRITE_5_WRITE_DATA__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE_5_WRITE_DATA(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_WRITE_5_WRITE_DATA__SHIFT) & CP_COND_WRITE_5_WRITE_DATA__MASK;
पूर्ण

#घोषणा REG_CP_COND_WRITE5_0					0x00000000
#घोषणा CP_COND_WRITE5_0_FUNCTION__MASK				0x00000007
#घोषणा CP_COND_WRITE5_0_FUNCTION__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE5_0_FUNCTION(क्रमागत cp_cond_function val)
अणु
	वापस ((val) << CP_COND_WRITE5_0_FUNCTION__SHIFT) & CP_COND_WRITE5_0_FUNCTION__MASK;
पूर्ण
#घोषणा CP_COND_WRITE5_0_SIGNED_COMPARE				0x00000008
#घोषणा CP_COND_WRITE5_0_POLL_MEMORY				0x00000010
#घोषणा CP_COND_WRITE5_0_POLL_SCRATCH				0x00000020
#घोषणा CP_COND_WRITE5_0_WRITE_MEMORY				0x00000100

#घोषणा REG_CP_COND_WRITE5_1					0x00000001
#घोषणा CP_COND_WRITE5_1_POLL_ADDR_LO__MASK			0xffffffff
#घोषणा CP_COND_WRITE5_1_POLL_ADDR_LO__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE5_1_POLL_ADDR_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_WRITE5_1_POLL_ADDR_LO__SHIFT) & CP_COND_WRITE5_1_POLL_ADDR_LO__MASK;
पूर्ण

#घोषणा REG_CP_COND_WRITE5_2					0x00000002
#घोषणा CP_COND_WRITE5_2_POLL_ADDR_HI__MASK			0xffffffff
#घोषणा CP_COND_WRITE5_2_POLL_ADDR_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE5_2_POLL_ADDR_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_WRITE5_2_POLL_ADDR_HI__SHIFT) & CP_COND_WRITE5_2_POLL_ADDR_HI__MASK;
पूर्ण

#घोषणा REG_CP_COND_WRITE5_3					0x00000003
#घोषणा CP_COND_WRITE5_3_REF__MASK				0xffffffff
#घोषणा CP_COND_WRITE5_3_REF__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE5_3_REF(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_WRITE5_3_REF__SHIFT) & CP_COND_WRITE5_3_REF__MASK;
पूर्ण

#घोषणा REG_CP_COND_WRITE5_4					0x00000004
#घोषणा CP_COND_WRITE5_4_MASK__MASK				0xffffffff
#घोषणा CP_COND_WRITE5_4_MASK__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE5_4_MASK(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_WRITE5_4_MASK__SHIFT) & CP_COND_WRITE5_4_MASK__MASK;
पूर्ण

#घोषणा REG_CP_COND_WRITE5_5					0x00000005
#घोषणा CP_COND_WRITE5_5_WRITE_ADDR_LO__MASK			0xffffffff
#घोषणा CP_COND_WRITE5_5_WRITE_ADDR_LO__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE5_5_WRITE_ADDR_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_WRITE5_5_WRITE_ADDR_LO__SHIFT) & CP_COND_WRITE5_5_WRITE_ADDR_LO__MASK;
पूर्ण

#घोषणा REG_CP_COND_WRITE5_6					0x00000006
#घोषणा CP_COND_WRITE5_6_WRITE_ADDR_HI__MASK			0xffffffff
#घोषणा CP_COND_WRITE5_6_WRITE_ADDR_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE5_6_WRITE_ADDR_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_WRITE5_6_WRITE_ADDR_HI__SHIFT) & CP_COND_WRITE5_6_WRITE_ADDR_HI__MASK;
पूर्ण

#घोषणा REG_CP_COND_WRITE5_7					0x00000007
#घोषणा CP_COND_WRITE5_7_WRITE_DATA__MASK			0xffffffff
#घोषणा CP_COND_WRITE5_7_WRITE_DATA__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_COND_WRITE5_7_WRITE_DATA(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_WRITE5_7_WRITE_DATA__SHIFT) & CP_COND_WRITE5_7_WRITE_DATA__MASK;
पूर्ण

#घोषणा REG_CP_WAIT_MEM_GTE_0					0x00000000
#घोषणा CP_WAIT_MEM_GTE_0_RESERVED__MASK			0xffffffff
#घोषणा CP_WAIT_MEM_GTE_0_RESERVED__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_MEM_GTE_0_RESERVED(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_WAIT_MEM_GTE_0_RESERVED__SHIFT) & CP_WAIT_MEM_GTE_0_RESERVED__MASK;
पूर्ण

#घोषणा REG_CP_WAIT_MEM_GTE_1					0x00000001
#घोषणा CP_WAIT_MEM_GTE_1_POLL_ADDR_LO__MASK			0xffffffff
#घोषणा CP_WAIT_MEM_GTE_1_POLL_ADDR_LO__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_MEM_GTE_1_POLL_ADDR_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_WAIT_MEM_GTE_1_POLL_ADDR_LO__SHIFT) & CP_WAIT_MEM_GTE_1_POLL_ADDR_LO__MASK;
पूर्ण

#घोषणा REG_CP_WAIT_MEM_GTE_2					0x00000002
#घोषणा CP_WAIT_MEM_GTE_2_POLL_ADDR_HI__MASK			0xffffffff
#घोषणा CP_WAIT_MEM_GTE_2_POLL_ADDR_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_MEM_GTE_2_POLL_ADDR_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_WAIT_MEM_GTE_2_POLL_ADDR_HI__SHIFT) & CP_WAIT_MEM_GTE_2_POLL_ADDR_HI__MASK;
पूर्ण

#घोषणा REG_CP_WAIT_MEM_GTE_3					0x00000003
#घोषणा CP_WAIT_MEM_GTE_3_REF__MASK				0xffffffff
#घोषणा CP_WAIT_MEM_GTE_3_REF__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_MEM_GTE_3_REF(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_WAIT_MEM_GTE_3_REF__SHIFT) & CP_WAIT_MEM_GTE_3_REF__MASK;
पूर्ण

#घोषणा REG_CP_WAIT_REG_MEM_0					0x00000000
#घोषणा CP_WAIT_REG_MEM_0_FUNCTION__MASK			0x00000007
#घोषणा CP_WAIT_REG_MEM_0_FUNCTION__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_REG_MEM_0_FUNCTION(क्रमागत cp_cond_function val)
अणु
	वापस ((val) << CP_WAIT_REG_MEM_0_FUNCTION__SHIFT) & CP_WAIT_REG_MEM_0_FUNCTION__MASK;
पूर्ण
#घोषणा CP_WAIT_REG_MEM_0_SIGNED_COMPARE			0x00000008
#घोषणा CP_WAIT_REG_MEM_0_POLL_MEMORY				0x00000010
#घोषणा CP_WAIT_REG_MEM_0_POLL_SCRATCH				0x00000020
#घोषणा CP_WAIT_REG_MEM_0_WRITE_MEMORY				0x00000100

#घोषणा REG_CP_WAIT_REG_MEM_1					0x00000001
#घोषणा CP_WAIT_REG_MEM_1_POLL_ADDR_LO__MASK			0xffffffff
#घोषणा CP_WAIT_REG_MEM_1_POLL_ADDR_LO__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_REG_MEM_1_POLL_ADDR_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_WAIT_REG_MEM_1_POLL_ADDR_LO__SHIFT) & CP_WAIT_REG_MEM_1_POLL_ADDR_LO__MASK;
पूर्ण

#घोषणा REG_CP_WAIT_REG_MEM_2					0x00000002
#घोषणा CP_WAIT_REG_MEM_2_POLL_ADDR_HI__MASK			0xffffffff
#घोषणा CP_WAIT_REG_MEM_2_POLL_ADDR_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_REG_MEM_2_POLL_ADDR_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_WAIT_REG_MEM_2_POLL_ADDR_HI__SHIFT) & CP_WAIT_REG_MEM_2_POLL_ADDR_HI__MASK;
पूर्ण

#घोषणा REG_CP_WAIT_REG_MEM_3					0x00000003
#घोषणा CP_WAIT_REG_MEM_3_REF__MASK				0xffffffff
#घोषणा CP_WAIT_REG_MEM_3_REF__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_REG_MEM_3_REF(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_WAIT_REG_MEM_3_REF__SHIFT) & CP_WAIT_REG_MEM_3_REF__MASK;
पूर्ण

#घोषणा REG_CP_WAIT_REG_MEM_4					0x00000004
#घोषणा CP_WAIT_REG_MEM_4_MASK__MASK				0xffffffff
#घोषणा CP_WAIT_REG_MEM_4_MASK__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_REG_MEM_4_MASK(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_WAIT_REG_MEM_4_MASK__SHIFT) & CP_WAIT_REG_MEM_4_MASK__MASK;
पूर्ण

#घोषणा REG_CP_WAIT_REG_MEM_5					0x00000005
#घोषणा CP_WAIT_REG_MEM_5_DELAY_LOOP_CYCLES__MASK		0xffffffff
#घोषणा CP_WAIT_REG_MEM_5_DELAY_LOOP_CYCLES__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_REG_MEM_5_DELAY_LOOP_CYCLES(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_WAIT_REG_MEM_5_DELAY_LOOP_CYCLES__SHIFT) & CP_WAIT_REG_MEM_5_DELAY_LOOP_CYCLES__MASK;
पूर्ण

#घोषणा REG_CP_WAIT_TWO_REGS_0					0x00000000
#घोषणा CP_WAIT_TWO_REGS_0_REG0__MASK				0x0003ffff
#घोषणा CP_WAIT_TWO_REGS_0_REG0__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_TWO_REGS_0_REG0(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_WAIT_TWO_REGS_0_REG0__SHIFT) & CP_WAIT_TWO_REGS_0_REG0__MASK;
पूर्ण

#घोषणा REG_CP_WAIT_TWO_REGS_1					0x00000001
#घोषणा CP_WAIT_TWO_REGS_1_REG1__MASK				0x0003ffff
#घोषणा CP_WAIT_TWO_REGS_1_REG1__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_TWO_REGS_1_REG1(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_WAIT_TWO_REGS_1_REG1__SHIFT) & CP_WAIT_TWO_REGS_1_REG1__MASK;
पूर्ण

#घोषणा REG_CP_WAIT_TWO_REGS_2					0x00000002
#घोषणा CP_WAIT_TWO_REGS_2_REF__MASK				0xffffffff
#घोषणा CP_WAIT_TWO_REGS_2_REF__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_WAIT_TWO_REGS_2_REF(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_WAIT_TWO_REGS_2_REF__SHIFT) & CP_WAIT_TWO_REGS_2_REF__MASK;
पूर्ण

#घोषणा REG_CP_DISPATCH_COMPUTE_0				0x00000000

#घोषणा REG_CP_DISPATCH_COMPUTE_1				0x00000001
#घोषणा CP_DISPATCH_COMPUTE_1_X__MASK				0xffffffff
#घोषणा CP_DISPATCH_COMPUTE_1_X__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_DISPATCH_COMPUTE_1_X(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DISPATCH_COMPUTE_1_X__SHIFT) & CP_DISPATCH_COMPUTE_1_X__MASK;
पूर्ण

#घोषणा REG_CP_DISPATCH_COMPUTE_2				0x00000002
#घोषणा CP_DISPATCH_COMPUTE_2_Y__MASK				0xffffffff
#घोषणा CP_DISPATCH_COMPUTE_2_Y__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_DISPATCH_COMPUTE_2_Y(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DISPATCH_COMPUTE_2_Y__SHIFT) & CP_DISPATCH_COMPUTE_2_Y__MASK;
पूर्ण

#घोषणा REG_CP_DISPATCH_COMPUTE_3				0x00000003
#घोषणा CP_DISPATCH_COMPUTE_3_Z__MASK				0xffffffff
#घोषणा CP_DISPATCH_COMPUTE_3_Z__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_DISPATCH_COMPUTE_3_Z(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_DISPATCH_COMPUTE_3_Z__SHIFT) & CP_DISPATCH_COMPUTE_3_Z__MASK;
पूर्ण

#घोषणा REG_CP_SET_RENDER_MODE_0				0x00000000
#घोषणा CP_SET_RENDER_MODE_0_MODE__MASK				0x000001ff
#घोषणा CP_SET_RENDER_MODE_0_MODE__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_RENDER_MODE_0_MODE(क्रमागत render_mode_cmd val)
अणु
	वापस ((val) << CP_SET_RENDER_MODE_0_MODE__SHIFT) & CP_SET_RENDER_MODE_0_MODE__MASK;
पूर्ण

#घोषणा REG_CP_SET_RENDER_MODE_1				0x00000001
#घोषणा CP_SET_RENDER_MODE_1_ADDR_0_LO__MASK			0xffffffff
#घोषणा CP_SET_RENDER_MODE_1_ADDR_0_LO__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_RENDER_MODE_1_ADDR_0_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_RENDER_MODE_1_ADDR_0_LO__SHIFT) & CP_SET_RENDER_MODE_1_ADDR_0_LO__MASK;
पूर्ण

#घोषणा REG_CP_SET_RENDER_MODE_2				0x00000002
#घोषणा CP_SET_RENDER_MODE_2_ADDR_0_HI__MASK			0xffffffff
#घोषणा CP_SET_RENDER_MODE_2_ADDR_0_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_RENDER_MODE_2_ADDR_0_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_RENDER_MODE_2_ADDR_0_HI__SHIFT) & CP_SET_RENDER_MODE_2_ADDR_0_HI__MASK;
पूर्ण

#घोषणा REG_CP_SET_RENDER_MODE_3				0x00000003
#घोषणा CP_SET_RENDER_MODE_3_VSC_ENABLE				0x00000008
#घोषणा CP_SET_RENDER_MODE_3_GMEM_ENABLE			0x00000010

#घोषणा REG_CP_SET_RENDER_MODE_4				0x00000004

#घोषणा REG_CP_SET_RENDER_MODE_5				0x00000005
#घोषणा CP_SET_RENDER_MODE_5_ADDR_1_LEN__MASK			0xffffffff
#घोषणा CP_SET_RENDER_MODE_5_ADDR_1_LEN__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_RENDER_MODE_5_ADDR_1_LEN(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_RENDER_MODE_5_ADDR_1_LEN__SHIFT) & CP_SET_RENDER_MODE_5_ADDR_1_LEN__MASK;
पूर्ण

#घोषणा REG_CP_SET_RENDER_MODE_6				0x00000006
#घोषणा CP_SET_RENDER_MODE_6_ADDR_1_LO__MASK			0xffffffff
#घोषणा CP_SET_RENDER_MODE_6_ADDR_1_LO__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_RENDER_MODE_6_ADDR_1_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_RENDER_MODE_6_ADDR_1_LO__SHIFT) & CP_SET_RENDER_MODE_6_ADDR_1_LO__MASK;
पूर्ण

#घोषणा REG_CP_SET_RENDER_MODE_7				0x00000007
#घोषणा CP_SET_RENDER_MODE_7_ADDR_1_HI__MASK			0xffffffff
#घोषणा CP_SET_RENDER_MODE_7_ADDR_1_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_RENDER_MODE_7_ADDR_1_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_RENDER_MODE_7_ADDR_1_HI__SHIFT) & CP_SET_RENDER_MODE_7_ADDR_1_HI__MASK;
पूर्ण

#घोषणा REG_CP_COMPUTE_CHECKPOINT_0				0x00000000
#घोषणा CP_COMPUTE_CHECKPOINT_0_ADDR_0_LO__MASK			0xffffffff
#घोषणा CP_COMPUTE_CHECKPOINT_0_ADDR_0_LO__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_COMPUTE_CHECKPOINT_0_ADDR_0_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COMPUTE_CHECKPOINT_0_ADDR_0_LO__SHIFT) & CP_COMPUTE_CHECKPOINT_0_ADDR_0_LO__MASK;
पूर्ण

#घोषणा REG_CP_COMPUTE_CHECKPOINT_1				0x00000001
#घोषणा CP_COMPUTE_CHECKPOINT_1_ADDR_0_HI__MASK			0xffffffff
#घोषणा CP_COMPUTE_CHECKPOINT_1_ADDR_0_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_COMPUTE_CHECKPOINT_1_ADDR_0_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COMPUTE_CHECKPOINT_1_ADDR_0_HI__SHIFT) & CP_COMPUTE_CHECKPOINT_1_ADDR_0_HI__MASK;
पूर्ण

#घोषणा REG_CP_COMPUTE_CHECKPOINT_2				0x00000002

#घोषणा REG_CP_COMPUTE_CHECKPOINT_3				0x00000003
#घोषणा CP_COMPUTE_CHECKPOINT_3_ADDR_1_LEN__MASK		0xffffffff
#घोषणा CP_COMPUTE_CHECKPOINT_3_ADDR_1_LEN__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_COMPUTE_CHECKPOINT_3_ADDR_1_LEN(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COMPUTE_CHECKPOINT_3_ADDR_1_LEN__SHIFT) & CP_COMPUTE_CHECKPOINT_3_ADDR_1_LEN__MASK;
पूर्ण

#घोषणा REG_CP_COMPUTE_CHECKPOINT_4				0x00000004

#घोषणा REG_CP_COMPUTE_CHECKPOINT_5				0x00000005
#घोषणा CP_COMPUTE_CHECKPOINT_5_ADDR_1_LO__MASK			0xffffffff
#घोषणा CP_COMPUTE_CHECKPOINT_5_ADDR_1_LO__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_COMPUTE_CHECKPOINT_5_ADDR_1_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COMPUTE_CHECKPOINT_5_ADDR_1_LO__SHIFT) & CP_COMPUTE_CHECKPOINT_5_ADDR_1_LO__MASK;
पूर्ण

#घोषणा REG_CP_COMPUTE_CHECKPOINT_6				0x00000006
#घोषणा CP_COMPUTE_CHECKPOINT_6_ADDR_1_HI__MASK			0xffffffff
#घोषणा CP_COMPUTE_CHECKPOINT_6_ADDR_1_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_COMPUTE_CHECKPOINT_6_ADDR_1_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COMPUTE_CHECKPOINT_6_ADDR_1_HI__SHIFT) & CP_COMPUTE_CHECKPOINT_6_ADDR_1_HI__MASK;
पूर्ण

#घोषणा REG_CP_COMPUTE_CHECKPOINT_7				0x00000007

#घोषणा REG_CP_PERFCOUNTER_ACTION_0				0x00000000

#घोषणा REG_CP_PERFCOUNTER_ACTION_1				0x00000001
#घोषणा CP_PERFCOUNTER_ACTION_1_ADDR_0_LO__MASK			0xffffffff
#घोषणा CP_PERFCOUNTER_ACTION_1_ADDR_0_LO__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_PERFCOUNTER_ACTION_1_ADDR_0_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_PERFCOUNTER_ACTION_1_ADDR_0_LO__SHIFT) & CP_PERFCOUNTER_ACTION_1_ADDR_0_LO__MASK;
पूर्ण

#घोषणा REG_CP_PERFCOUNTER_ACTION_2				0x00000002
#घोषणा CP_PERFCOUNTER_ACTION_2_ADDR_0_HI__MASK			0xffffffff
#घोषणा CP_PERFCOUNTER_ACTION_2_ADDR_0_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_PERFCOUNTER_ACTION_2_ADDR_0_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_PERFCOUNTER_ACTION_2_ADDR_0_HI__SHIFT) & CP_PERFCOUNTER_ACTION_2_ADDR_0_HI__MASK;
पूर्ण

#घोषणा REG_CP_EVENT_WRITE_0					0x00000000
#घोषणा CP_EVENT_WRITE_0_EVENT__MASK				0x000000ff
#घोषणा CP_EVENT_WRITE_0_EVENT__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_EVENT_WRITE_0_EVENT(क्रमागत vgt_event_type val)
अणु
	वापस ((val) << CP_EVENT_WRITE_0_EVENT__SHIFT) & CP_EVENT_WRITE_0_EVENT__MASK;
पूर्ण
#घोषणा CP_EVENT_WRITE_0_TIMESTAMP				0x40000000
#घोषणा CP_EVENT_WRITE_0_IRQ					0x80000000

#घोषणा REG_CP_EVENT_WRITE_1					0x00000001
#घोषणा CP_EVENT_WRITE_1_ADDR_0_LO__MASK			0xffffffff
#घोषणा CP_EVENT_WRITE_1_ADDR_0_LO__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_EVENT_WRITE_1_ADDR_0_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_EVENT_WRITE_1_ADDR_0_LO__SHIFT) & CP_EVENT_WRITE_1_ADDR_0_LO__MASK;
पूर्ण

#घोषणा REG_CP_EVENT_WRITE_2					0x00000002
#घोषणा CP_EVENT_WRITE_2_ADDR_0_HI__MASK			0xffffffff
#घोषणा CP_EVENT_WRITE_2_ADDR_0_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_EVENT_WRITE_2_ADDR_0_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_EVENT_WRITE_2_ADDR_0_HI__SHIFT) & CP_EVENT_WRITE_2_ADDR_0_HI__MASK;
पूर्ण

#घोषणा REG_CP_EVENT_WRITE_3					0x00000003

#घोषणा REG_CP_BLIT_0						0x00000000
#घोषणा CP_BLIT_0_OP__MASK					0x0000000f
#घोषणा CP_BLIT_0_OP__SHIFT					0
अटल अंतरभूत uपूर्णांक32_t CP_BLIT_0_OP(क्रमागत cp_blit_cmd val)
अणु
	वापस ((val) << CP_BLIT_0_OP__SHIFT) & CP_BLIT_0_OP__MASK;
पूर्ण

#घोषणा REG_CP_BLIT_1						0x00000001
#घोषणा CP_BLIT_1_SRC_X1__MASK					0x00003fff
#घोषणा CP_BLIT_1_SRC_X1__SHIFT					0
अटल अंतरभूत uपूर्णांक32_t CP_BLIT_1_SRC_X1(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_BLIT_1_SRC_X1__SHIFT) & CP_BLIT_1_SRC_X1__MASK;
पूर्ण
#घोषणा CP_BLIT_1_SRC_Y1__MASK					0x3fff0000
#घोषणा CP_BLIT_1_SRC_Y1__SHIFT					16
अटल अंतरभूत uपूर्णांक32_t CP_BLIT_1_SRC_Y1(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_BLIT_1_SRC_Y1__SHIFT) & CP_BLIT_1_SRC_Y1__MASK;
पूर्ण

#घोषणा REG_CP_BLIT_2						0x00000002
#घोषणा CP_BLIT_2_SRC_X2__MASK					0x00003fff
#घोषणा CP_BLIT_2_SRC_X2__SHIFT					0
अटल अंतरभूत uपूर्णांक32_t CP_BLIT_2_SRC_X2(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_BLIT_2_SRC_X2__SHIFT) & CP_BLIT_2_SRC_X2__MASK;
पूर्ण
#घोषणा CP_BLIT_2_SRC_Y2__MASK					0x3fff0000
#घोषणा CP_BLIT_2_SRC_Y2__SHIFT					16
अटल अंतरभूत uपूर्णांक32_t CP_BLIT_2_SRC_Y2(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_BLIT_2_SRC_Y2__SHIFT) & CP_BLIT_2_SRC_Y2__MASK;
पूर्ण

#घोषणा REG_CP_BLIT_3						0x00000003
#घोषणा CP_BLIT_3_DST_X1__MASK					0x00003fff
#घोषणा CP_BLIT_3_DST_X1__SHIFT					0
अटल अंतरभूत uपूर्णांक32_t CP_BLIT_3_DST_X1(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_BLIT_3_DST_X1__SHIFT) & CP_BLIT_3_DST_X1__MASK;
पूर्ण
#घोषणा CP_BLIT_3_DST_Y1__MASK					0x3fff0000
#घोषणा CP_BLIT_3_DST_Y1__SHIFT					16
अटल अंतरभूत uपूर्णांक32_t CP_BLIT_3_DST_Y1(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_BLIT_3_DST_Y1__SHIFT) & CP_BLIT_3_DST_Y1__MASK;
पूर्ण

#घोषणा REG_CP_BLIT_4						0x00000004
#घोषणा CP_BLIT_4_DST_X2__MASK					0x00003fff
#घोषणा CP_BLIT_4_DST_X2__SHIFT					0
अटल अंतरभूत uपूर्णांक32_t CP_BLIT_4_DST_X2(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_BLIT_4_DST_X2__SHIFT) & CP_BLIT_4_DST_X2__MASK;
पूर्ण
#घोषणा CP_BLIT_4_DST_Y2__MASK					0x3fff0000
#घोषणा CP_BLIT_4_DST_Y2__SHIFT					16
अटल अंतरभूत uपूर्णांक32_t CP_BLIT_4_DST_Y2(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_BLIT_4_DST_Y2__SHIFT) & CP_BLIT_4_DST_Y2__MASK;
पूर्ण

#घोषणा REG_CP_EXEC_CS_0					0x00000000

#घोषणा REG_CP_EXEC_CS_1					0x00000001
#घोषणा CP_EXEC_CS_1_NGROUPS_X__MASK				0xffffffff
#घोषणा CP_EXEC_CS_1_NGROUPS_X__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_EXEC_CS_1_NGROUPS_X(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_EXEC_CS_1_NGROUPS_X__SHIFT) & CP_EXEC_CS_1_NGROUPS_X__MASK;
पूर्ण

#घोषणा REG_CP_EXEC_CS_2					0x00000002
#घोषणा CP_EXEC_CS_2_NGROUPS_Y__MASK				0xffffffff
#घोषणा CP_EXEC_CS_2_NGROUPS_Y__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_EXEC_CS_2_NGROUPS_Y(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_EXEC_CS_2_NGROUPS_Y__SHIFT) & CP_EXEC_CS_2_NGROUPS_Y__MASK;
पूर्ण

#घोषणा REG_CP_EXEC_CS_3					0x00000003
#घोषणा CP_EXEC_CS_3_NGROUPS_Z__MASK				0xffffffff
#घोषणा CP_EXEC_CS_3_NGROUPS_Z__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_EXEC_CS_3_NGROUPS_Z(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_EXEC_CS_3_NGROUPS_Z__SHIFT) & CP_EXEC_CS_3_NGROUPS_Z__MASK;
पूर्ण

#घोषणा REG_A4XX_CP_EXEC_CS_INसूचीECT_0				0x00000000


#घोषणा REG_A4XX_CP_EXEC_CS_INसूचीECT_1				0x00000001
#घोषणा A4XX_CP_EXEC_CS_INसूचीECT_1_ADDR__MASK			0xffffffff
#घोषणा A4XX_CP_EXEC_CS_INसूचीECT_1_ADDR__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_EXEC_CS_INसूचीECT_1_ADDR(uपूर्णांक32_t val)
अणु
	वापस ((val) << A4XX_CP_EXEC_CS_INसूचीECT_1_ADDR__SHIFT) & A4XX_CP_EXEC_CS_INसूचीECT_1_ADDR__MASK;
पूर्ण

#घोषणा REG_A4XX_CP_EXEC_CS_INसूचीECT_2				0x00000002
#घोषणा A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEX__MASK		0x00000ffc
#घोषणा A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEX__SHIFT		2
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEX(uपूर्णांक32_t val)
अणु
	वापस ((val) << A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEX__SHIFT) & A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEX__MASK;
पूर्ण
#घोषणा A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEY__MASK		0x003ff000
#घोषणा A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEY__SHIFT		12
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEY(uपूर्णांक32_t val)
अणु
	वापस ((val) << A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEY__SHIFT) & A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEY__MASK;
पूर्ण
#घोषणा A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEZ__MASK		0xffc00000
#घोषणा A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEZ__SHIFT		22
अटल अंतरभूत uपूर्णांक32_t A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEZ(uपूर्णांक32_t val)
अणु
	वापस ((val) << A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEZ__SHIFT) & A4XX_CP_EXEC_CS_INसूचीECT_2_LOCALSIZEZ__MASK;
पूर्ण


#घोषणा REG_A5XX_CP_EXEC_CS_INसूचीECT_1				0x00000001
#घोषणा A5XX_CP_EXEC_CS_INसूचीECT_1_ADDR_LO__MASK		0xffffffff
#घोषणा A5XX_CP_EXEC_CS_INसूचीECT_1_ADDR_LO__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A5XX_CP_EXEC_CS_INसूचीECT_1_ADDR_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << A5XX_CP_EXEC_CS_INसूचीECT_1_ADDR_LO__SHIFT) & A5XX_CP_EXEC_CS_INसूचीECT_1_ADDR_LO__MASK;
पूर्ण

#घोषणा REG_A5XX_CP_EXEC_CS_INसूचीECT_2				0x00000002
#घोषणा A5XX_CP_EXEC_CS_INसूचीECT_2_ADDR_HI__MASK		0xffffffff
#घोषणा A5XX_CP_EXEC_CS_INसूचीECT_2_ADDR_HI__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A5XX_CP_EXEC_CS_INसूचीECT_2_ADDR_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << A5XX_CP_EXEC_CS_INसूचीECT_2_ADDR_HI__SHIFT) & A5XX_CP_EXEC_CS_INसूचीECT_2_ADDR_HI__MASK;
पूर्ण

#घोषणा REG_A5XX_CP_EXEC_CS_INसूचीECT_3				0x00000003
#घोषणा A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEX__MASK		0x00000ffc
#घोषणा A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEX__SHIFT		2
अटल अंतरभूत uपूर्णांक32_t A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEX(uपूर्णांक32_t val)
अणु
	वापस ((val) << A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEX__SHIFT) & A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEX__MASK;
पूर्ण
#घोषणा A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEY__MASK		0x003ff000
#घोषणा A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEY__SHIFT		12
अटल अंतरभूत uपूर्णांक32_t A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEY(uपूर्णांक32_t val)
अणु
	वापस ((val) << A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEY__SHIFT) & A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEY__MASK;
पूर्ण
#घोषणा A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEZ__MASK		0xffc00000
#घोषणा A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEZ__SHIFT		22
अटल अंतरभूत uपूर्णांक32_t A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEZ(uपूर्णांक32_t val)
अणु
	वापस ((val) << A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEZ__SHIFT) & A5XX_CP_EXEC_CS_INसूचीECT_3_LOCALSIZEZ__MASK;
पूर्ण

#घोषणा REG_A6XX_CP_SET_MARKER_0				0x00000000
#घोषणा A6XX_CP_SET_MARKER_0_MODE__MASK				0x000001ff
#घोषणा A6XX_CP_SET_MARKER_0_MODE__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_SET_MARKER_0_MODE(क्रमागत a6xx_render_mode val)
अणु
	वापस ((val) << A6XX_CP_SET_MARKER_0_MODE__SHIFT) & A6XX_CP_SET_MARKER_0_MODE__MASK;
पूर्ण
#घोषणा A6XX_CP_SET_MARKER_0_MARKER__MASK			0x0000000f
#घोषणा A6XX_CP_SET_MARKER_0_MARKER__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_SET_MARKER_0_MARKER(क्रमागत a6xx_render_mode val)
अणु
	वापस ((val) << A6XX_CP_SET_MARKER_0_MARKER__SHIFT) & A6XX_CP_SET_MARKER_0_MARKER__MASK;
पूर्ण

अटल अंतरभूत uपूर्णांक32_t REG_A6XX_CP_SET_PSEUDO_REG_(uपूर्णांक32_t i0) अणु वापस 0x00000000 + 0x3*i0; पूर्ण

अटल अंतरभूत uपूर्णांक32_t REG_A6XX_CP_SET_PSEUDO_REG__0(uपूर्णांक32_t i0) अणु वापस 0x00000000 + 0x3*i0; पूर्ण
#घोषणा A6XX_CP_SET_PSEUDO_REG__0_PSEUDO_REG__MASK		0x00000007
#घोषणा A6XX_CP_SET_PSEUDO_REG__0_PSEUDO_REG__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_SET_PSEUDO_REG__0_PSEUDO_REG(क्रमागत pseuकरो_reg val)
अणु
	वापस ((val) << A6XX_CP_SET_PSEUDO_REG__0_PSEUDO_REG__SHIFT) & A6XX_CP_SET_PSEUDO_REG__0_PSEUDO_REG__MASK;
पूर्ण

अटल अंतरभूत uपूर्णांक32_t REG_A6XX_CP_SET_PSEUDO_REG__1(uपूर्णांक32_t i0) अणु वापस 0x00000001 + 0x3*i0; पूर्ण
#घोषणा A6XX_CP_SET_PSEUDO_REG__1_LO__MASK			0xffffffff
#घोषणा A6XX_CP_SET_PSEUDO_REG__1_LO__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_SET_PSEUDO_REG__1_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << A6XX_CP_SET_PSEUDO_REG__1_LO__SHIFT) & A6XX_CP_SET_PSEUDO_REG__1_LO__MASK;
पूर्ण

अटल अंतरभूत uपूर्णांक32_t REG_A6XX_CP_SET_PSEUDO_REG__2(uपूर्णांक32_t i0) अणु वापस 0x00000002 + 0x3*i0; पूर्ण
#घोषणा A6XX_CP_SET_PSEUDO_REG__2_HI__MASK			0xffffffff
#घोषणा A6XX_CP_SET_PSEUDO_REG__2_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_SET_PSEUDO_REG__2_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << A6XX_CP_SET_PSEUDO_REG__2_HI__SHIFT) & A6XX_CP_SET_PSEUDO_REG__2_HI__MASK;
पूर्ण

#घोषणा REG_A6XX_CP_REG_TEST_0					0x00000000
#घोषणा A6XX_CP_REG_TEST_0_REG__MASK				0x0003ffff
#घोषणा A6XX_CP_REG_TEST_0_REG__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_REG_TEST_0_REG(uपूर्णांक32_t val)
अणु
	वापस ((val) << A6XX_CP_REG_TEST_0_REG__SHIFT) & A6XX_CP_REG_TEST_0_REG__MASK;
पूर्ण
#घोषणा A6XX_CP_REG_TEST_0_BIT__MASK				0x01f00000
#घोषणा A6XX_CP_REG_TEST_0_BIT__SHIFT				20
अटल अंतरभूत uपूर्णांक32_t A6XX_CP_REG_TEST_0_BIT(uपूर्णांक32_t val)
अणु
	वापस ((val) << A6XX_CP_REG_TEST_0_BIT__SHIFT) & A6XX_CP_REG_TEST_0_BIT__MASK;
पूर्ण
#घोषणा A6XX_CP_REG_TEST_0_WAIT_FOR_ME				0x02000000

#घोषणा REG_CP_COND_REG_EXEC_0					0x00000000
#घोषणा CP_COND_REG_EXEC_0_REG0__MASK				0x0003ffff
#घोषणा CP_COND_REG_EXEC_0_REG0__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_COND_REG_EXEC_0_REG0(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_REG_EXEC_0_REG0__SHIFT) & CP_COND_REG_EXEC_0_REG0__MASK;
पूर्ण
#घोषणा CP_COND_REG_EXEC_0_BINNING				0x02000000
#घोषणा CP_COND_REG_EXEC_0_GMEM					0x04000000
#घोषणा CP_COND_REG_EXEC_0_SYSMEM				0x08000000
#घोषणा CP_COND_REG_EXEC_0_MODE__MASK				0xf0000000
#घोषणा CP_COND_REG_EXEC_0_MODE__SHIFT				28
अटल अंतरभूत uपूर्णांक32_t CP_COND_REG_EXEC_0_MODE(क्रमागत compare_mode val)
अणु
	वापस ((val) << CP_COND_REG_EXEC_0_MODE__SHIFT) & CP_COND_REG_EXEC_0_MODE__MASK;
पूर्ण

#घोषणा REG_CP_COND_REG_EXEC_1					0x00000001
#घोषणा CP_COND_REG_EXEC_1_DWORDS__MASK				0xffffffff
#घोषणा CP_COND_REG_EXEC_1_DWORDS__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_COND_REG_EXEC_1_DWORDS(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_REG_EXEC_1_DWORDS__SHIFT) & CP_COND_REG_EXEC_1_DWORDS__MASK;
पूर्ण

#घोषणा REG_CP_COND_EXEC_0					0x00000000
#घोषणा CP_COND_EXEC_0_ADDR0_LO__MASK				0xffffffff
#घोषणा CP_COND_EXEC_0_ADDR0_LO__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_COND_EXEC_0_ADDR0_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_EXEC_0_ADDR0_LO__SHIFT) & CP_COND_EXEC_0_ADDR0_LO__MASK;
पूर्ण

#घोषणा REG_CP_COND_EXEC_1					0x00000001
#घोषणा CP_COND_EXEC_1_ADDR0_HI__MASK				0xffffffff
#घोषणा CP_COND_EXEC_1_ADDR0_HI__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_COND_EXEC_1_ADDR0_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_EXEC_1_ADDR0_HI__SHIFT) & CP_COND_EXEC_1_ADDR0_HI__MASK;
पूर्ण

#घोषणा REG_CP_COND_EXEC_2					0x00000002
#घोषणा CP_COND_EXEC_2_ADDR1_LO__MASK				0xffffffff
#घोषणा CP_COND_EXEC_2_ADDR1_LO__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_COND_EXEC_2_ADDR1_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_EXEC_2_ADDR1_LO__SHIFT) & CP_COND_EXEC_2_ADDR1_LO__MASK;
पूर्ण

#घोषणा REG_CP_COND_EXEC_3					0x00000003
#घोषणा CP_COND_EXEC_3_ADDR1_HI__MASK				0xffffffff
#घोषणा CP_COND_EXEC_3_ADDR1_HI__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_COND_EXEC_3_ADDR1_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_EXEC_3_ADDR1_HI__SHIFT) & CP_COND_EXEC_3_ADDR1_HI__MASK;
पूर्ण

#घोषणा REG_CP_COND_EXEC_4					0x00000004
#घोषणा CP_COND_EXEC_4_REF__MASK				0xffffffff
#घोषणा CP_COND_EXEC_4_REF__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_COND_EXEC_4_REF(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_EXEC_4_REF__SHIFT) & CP_COND_EXEC_4_REF__MASK;
पूर्ण

#घोषणा REG_CP_COND_EXEC_5					0x00000005
#घोषणा CP_COND_EXEC_5_DWORDS__MASK				0xffffffff
#घोषणा CP_COND_EXEC_5_DWORDS__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_COND_EXEC_5_DWORDS(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_COND_EXEC_5_DWORDS__SHIFT) & CP_COND_EXEC_5_DWORDS__MASK;
पूर्ण

#घोषणा REG_CP_SET_CTXSWITCH_IB_0				0x00000000
#घोषणा CP_SET_CTXSWITCH_IB_0_ADDR_LO__MASK			0xffffffff
#घोषणा CP_SET_CTXSWITCH_IB_0_ADDR_LO__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_CTXSWITCH_IB_0_ADDR_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_CTXSWITCH_IB_0_ADDR_LO__SHIFT) & CP_SET_CTXSWITCH_IB_0_ADDR_LO__MASK;
पूर्ण

#घोषणा REG_CP_SET_CTXSWITCH_IB_1				0x00000001
#घोषणा CP_SET_CTXSWITCH_IB_1_ADDR_HI__MASK			0xffffffff
#घोषणा CP_SET_CTXSWITCH_IB_1_ADDR_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_CTXSWITCH_IB_1_ADDR_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_CTXSWITCH_IB_1_ADDR_HI__SHIFT) & CP_SET_CTXSWITCH_IB_1_ADDR_HI__MASK;
पूर्ण

#घोषणा REG_CP_SET_CTXSWITCH_IB_2				0x00000002
#घोषणा CP_SET_CTXSWITCH_IB_2_DWORDS__MASK			0x000fffff
#घोषणा CP_SET_CTXSWITCH_IB_2_DWORDS__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SET_CTXSWITCH_IB_2_DWORDS(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SET_CTXSWITCH_IB_2_DWORDS__SHIFT) & CP_SET_CTXSWITCH_IB_2_DWORDS__MASK;
पूर्ण
#घोषणा CP_SET_CTXSWITCH_IB_2_TYPE__MASK			0x00300000
#घोषणा CP_SET_CTXSWITCH_IB_2_TYPE__SHIFT			20
अटल अंतरभूत uपूर्णांक32_t CP_SET_CTXSWITCH_IB_2_TYPE(क्रमागत ctxचयन_ib val)
अणु
	वापस ((val) << CP_SET_CTXSWITCH_IB_2_TYPE__SHIFT) & CP_SET_CTXSWITCH_IB_2_TYPE__MASK;
पूर्ण

#घोषणा REG_CP_REG_WRITE_0					0x00000000
#घोषणा CP_REG_WRITE_0_TRACKER__MASK				0x00000007
#घोषणा CP_REG_WRITE_0_TRACKER__SHIFT				0
अटल अंतरभूत uपूर्णांक32_t CP_REG_WRITE_0_TRACKER(क्रमागत reg_tracker val)
अणु
	वापस ((val) << CP_REG_WRITE_0_TRACKER__SHIFT) & CP_REG_WRITE_0_TRACKER__MASK;
पूर्ण

#घोषणा REG_CP_SMMU_TABLE_UPDATE_0				0x00000000
#घोषणा CP_SMMU_TABLE_UPDATE_0_TTBR0_LO__MASK			0xffffffff
#घोषणा CP_SMMU_TABLE_UPDATE_0_TTBR0_LO__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SMMU_TABLE_UPDATE_0_TTBR0_LO(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SMMU_TABLE_UPDATE_0_TTBR0_LO__SHIFT) & CP_SMMU_TABLE_UPDATE_0_TTBR0_LO__MASK;
पूर्ण

#घोषणा REG_CP_SMMU_TABLE_UPDATE_1				0x00000001
#घोषणा CP_SMMU_TABLE_UPDATE_1_TTBR0_HI__MASK			0x0000ffff
#घोषणा CP_SMMU_TABLE_UPDATE_1_TTBR0_HI__SHIFT			0
अटल अंतरभूत uपूर्णांक32_t CP_SMMU_TABLE_UPDATE_1_TTBR0_HI(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SMMU_TABLE_UPDATE_1_TTBR0_HI__SHIFT) & CP_SMMU_TABLE_UPDATE_1_TTBR0_HI__MASK;
पूर्ण
#घोषणा CP_SMMU_TABLE_UPDATE_1_ASID__MASK			0xffff0000
#घोषणा CP_SMMU_TABLE_UPDATE_1_ASID__SHIFT			16
अटल अंतरभूत uपूर्णांक32_t CP_SMMU_TABLE_UPDATE_1_ASID(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SMMU_TABLE_UPDATE_1_ASID__SHIFT) & CP_SMMU_TABLE_UPDATE_1_ASID__MASK;
पूर्ण

#घोषणा REG_CP_SMMU_TABLE_UPDATE_2				0x00000002
#घोषणा CP_SMMU_TABLE_UPDATE_2_CONTEXTIDR__MASK			0xffffffff
#घोषणा CP_SMMU_TABLE_UPDATE_2_CONTEXTIDR__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_SMMU_TABLE_UPDATE_2_CONTEXTIDR(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SMMU_TABLE_UPDATE_2_CONTEXTIDR__SHIFT) & CP_SMMU_TABLE_UPDATE_2_CONTEXTIDR__MASK;
पूर्ण

#घोषणा REG_CP_SMMU_TABLE_UPDATE_3				0x00000003
#घोषणा CP_SMMU_TABLE_UPDATE_3_CONTEXTBANK__MASK		0xffffffff
#घोषणा CP_SMMU_TABLE_UPDATE_3_CONTEXTBANK__SHIFT		0
अटल अंतरभूत uपूर्णांक32_t CP_SMMU_TABLE_UPDATE_3_CONTEXTBANK(uपूर्णांक32_t val)
अणु
	वापस ((val) << CP_SMMU_TABLE_UPDATE_3_CONTEXTBANK__SHIFT) & CP_SMMU_TABLE_UPDATE_3_CONTEXTBANK__MASK;
पूर्ण


#पूर्ण_अगर /* ADRENO_PM4_XML */
