<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0-only */
/*
 * Copyright (C) 2013 NVIDIA Corporation
 */

#अगर_अघोषित DRM_TEGRA_DPAUX_H
#घोषणा DRM_TEGRA_DPAUX_H

#घोषणा DPAUX_CTXSW 0x00

#घोषणा DPAUX_INTR_EN_AUX 0x01
#घोषणा DPAUX_INTR_AUX 0x05
#घोषणा DPAUX_INTR_AUX_DONE (1 << 3)
#घोषणा DPAUX_INTR_IRQ_EVENT (1 << 2)
#घोषणा DPAUX_INTR_UNPLUG_EVENT (1 << 1)
#घोषणा DPAUX_INTR_PLUG_EVENT (1 << 0)

#घोषणा DPAUX_DP_AUXDATA_WRITE(x) (0x09 + ((x) << 2))
#घोषणा DPAUX_DP_AUXDATA_READ(x) (0x19 + ((x) << 2))
#घोषणा DPAUX_DP_AUXADDR 0x29

#घोषणा DPAUX_DP_AUXCTL 0x2d
#घोषणा DPAUX_DP_AUXCTL_TRANSACTREQ (1 << 16)
#घोषणा DPAUX_DP_AUXCTL_CMD_AUX_RD (9 << 12)
#घोषणा DPAUX_DP_AUXCTL_CMD_AUX_WR (8 << 12)
#घोषणा DPAUX_DP_AUXCTL_CMD_MOT_RQ (6 << 12)
#घोषणा DPAUX_DP_AUXCTL_CMD_MOT_RD (5 << 12)
#घोषणा DPAUX_DP_AUXCTL_CMD_MOT_WR (4 << 12)
#घोषणा DPAUX_DP_AUXCTL_CMD_I2C_RQ (2 << 12)
#घोषणा DPAUX_DP_AUXCTL_CMD_I2C_RD (1 << 12)
#घोषणा DPAUX_DP_AUXCTL_CMD_I2C_WR (0 << 12)
#घोषणा DPAUX_DP_AUXCTL_CMD_ADDRESS_ONLY (1 << 8)
#घोषणा DPAUX_DP_AUXCTL_CMDLEN(x) ((x) & 0xff)

#घोषणा DPAUX_DP_AUXSTAT 0x31
#घोषणा DPAUX_DP_AUXSTAT_HPD_STATUS (1 << 28)
#घोषणा DPAUX_DP_AUXSTAT_REPLY_TYPE_MASK (0xf0000)
#घोषणा DPAUX_DP_AUXSTAT_NO_STOP_ERROR (1 << 11)
#घोषणा DPAUX_DP_AUXSTAT_SINKSTAT_ERROR (1 << 10)
#घोषणा DPAUX_DP_AUXSTAT_RX_ERROR (1 << 9)
#घोषणा DPAUX_DP_AUXSTAT_TIMEOUT_ERROR (1 << 8)
#घोषणा DPAUX_DP_AUXSTAT_REPLY_MASK (0xff)

#घोषणा DPAUX_DP_AUX_SINKSTAT_LO 0x35
#घोषणा DPAUX_DP_AUX_SINKSTAT_HI 0x39

#घोषणा DPAUX_HPD_CONFIG 0x3d
#घोषणा DPAUX_HPD_CONFIG_UNPLUG_MIN_TIME(x) (((x) & 0xffff) << 16)
#घोषणा DPAUX_HPD_CONFIG_PLUG_MIN_TIME(x) ((x) & 0xffff)

#घोषणा DPAUX_HPD_IRQ_CONFIG 0x41
#घोषणा DPAUX_HPD_IRQ_CONFIG_MIN_LOW_TIME(x) ((x) & 0xffff)

#घोषणा DPAUX_DP_AUX_CONFIG 0x45

#घोषणा DPAUX_HYBRID_PADCTL 0x49
#घोषणा DPAUX_HYBRID_PADCTL_I2C_SDA_INPUT_RCV (1 << 15)
#घोषणा DPAUX_HYBRID_PADCTL_I2C_SCL_INPUT_RCV (1 << 14)
#घोषणा DPAUX_HYBRID_PADCTL_AUX_CMH(x) (((x) & 0x3) << 12)
#घोषणा DPAUX_HYBRID_PADCTL_AUX_DRVZ(x) (((x) & 0x7) << 8)
#घोषणा DPAUX_HYBRID_PADCTL_AUX_DRVI(x) (((x) & 0x3f) << 2)
#घोषणा DPAUX_HYBRID_PADCTL_AUX_INPUT_RCV (1 << 1)
#घोषणा DPAUX_HYBRID_PADCTL_MODE_I2C (1 << 0)
#घोषणा DPAUX_HYBRID_PADCTL_MODE_AUX (0 << 0)

#घोषणा DPAUX_HYBRID_SPARE 0x4d
#घोषणा DPAUX_HYBRID_SPARE_PAD_POWER_DOWN (1 << 0)

#घोषणा DPAUX_SCRATCH_REG0 0x51
#घोषणा DPAUX_SCRATCH_REG1 0x55
#घोषणा DPAUX_SCRATCH_REG2 0x59

#पूर्ण_अगर
