<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */

#अगर_अघोषित _DT_BINDINGS_TEMPERATURE_THERMOCOUPLE_H
#घोषणा _DT_BINDINGS_TEMPERATURE_THERMOCOUPLE_H


#घोषणा THERMOCOUPLE_TYPE_B	0x00
#घोषणा THERMOCOUPLE_TYPE_E	0x01
#घोषणा THERMOCOUPLE_TYPE_J	0x02
#घोषणा THERMOCOUPLE_TYPE_K	0x03
#घोषणा THERMOCOUPLE_TYPE_N	0x04
#घोषणा THERMOCOUPLE_TYPE_R	0x05
#घोषणा THERMOCOUPLE_TYPE_S	0x06
#घोषणा THERMOCOUPLE_TYPE_T	0x07

#पूर्ण_अगर /* _DT_BINDINGS_TEMPERATURE_THERMOCOUPLE_H */
