<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
/*
 * Support क्रम Intel Camera Imaging ISP subप्रणाली.
 * Copyright (c) 2015, Intel Corporation.
 *
 * This program is मुक्त software; you can redistribute it and/or modअगरy it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License क्रम
 * more details.
 */

/* Generated code: करो not edit or commmit. */

#अगर_अघोषित _IA_CSS_ISP_PARAM_H
#घोषणा _IA_CSS_ISP_PARAM_H

/* Code generated by genparam/gencode.c:gen_param_क्रमागत() */

क्रमागत ia_css_parameter_ids अणु
	IA_CSS_AA_ID,
	IA_CSS_ANR_ID,
	IA_CSS_ANR2_ID,
	IA_CSS_BH_ID,
	IA_CSS_CNR_ID,
	IA_CSS_CROP_ID,
	IA_CSS_CSC_ID,
	IA_CSS_DP_ID,
	IA_CSS_BNR_ID,
	IA_CSS_DE_ID,
	IA_CSS_ECD_ID,
	IA_CSS_FORMATS_ID,
	IA_CSS_FPN_ID,
	IA_CSS_GC_ID,
	IA_CSS_CE_ID,
	IA_CSS_YUV2RGB_ID,
	IA_CSS_RGB2YUV_ID,
	IA_CSS_R_GAMMA_ID,
	IA_CSS_G_GAMMA_ID,
	IA_CSS_B_GAMMA_ID,
	IA_CSS_UDS_ID,
	IA_CSS_RAA_ID,
	IA_CSS_S3A_ID,
	IA_CSS_OB_ID,
	IA_CSS_OUTPUT_ID,
	IA_CSS_SC_ID,
	IA_CSS_BDS_ID,
	IA_CSS_TNR_ID,
	IA_CSS_MACC_ID,
	IA_CSS_SDIS_HORICOEF_ID,
	IA_CSS_SDIS_VERTCOEF_ID,
	IA_CSS_SDIS_HORIPROJ_ID,
	IA_CSS_SDIS_VERTPROJ_ID,
	IA_CSS_SDIS2_HORICOEF_ID,
	IA_CSS_SDIS2_VERTCOEF_ID,
	IA_CSS_SDIS2_HORIPROJ_ID,
	IA_CSS_SDIS2_VERTPROJ_ID,
	IA_CSS_WB_ID,
	IA_CSS_NR_ID,
	IA_CSS_YEE_ID,
	IA_CSS_YNR_ID,
	IA_CSS_FC_ID,
	IA_CSS_CTC_ID,
	IA_CSS_XNR_TABLE_ID,
	IA_CSS_XNR_ID,
	IA_CSS_XNR3_ID,
	IA_CSS_NUM_PARAMETER_IDS
पूर्ण;

/* Code generated by genparam/gencode.c:gen_param_offsets() */

काष्ठा ia_css_memory_offsets अणु
	काष्ठा अणु
		काष्ठा ia_css_isp_parameter aa;
		काष्ठा ia_css_isp_parameter anr;
		काष्ठा ia_css_isp_parameter bh;
		काष्ठा ia_css_isp_parameter cnr;
		काष्ठा ia_css_isp_parameter crop;
		काष्ठा ia_css_isp_parameter csc;
		काष्ठा ia_css_isp_parameter dp;
		काष्ठा ia_css_isp_parameter bnr;
		काष्ठा ia_css_isp_parameter de;
		काष्ठा ia_css_isp_parameter ecd;
		काष्ठा ia_css_isp_parameter क्रमmats;
		काष्ठा ia_css_isp_parameter fpn;
		काष्ठा ia_css_isp_parameter gc;
		काष्ठा ia_css_isp_parameter ce;
		काष्ठा ia_css_isp_parameter yuv2rgb;
		काष्ठा ia_css_isp_parameter rgb2yuv;
		काष्ठा ia_css_isp_parameter uds;
		काष्ठा ia_css_isp_parameter raa;
		काष्ठा ia_css_isp_parameter s3a;
		काष्ठा ia_css_isp_parameter ob;
		काष्ठा ia_css_isp_parameter output;
		काष्ठा ia_css_isp_parameter sc;
		काष्ठा ia_css_isp_parameter bds;
		काष्ठा ia_css_isp_parameter tnr;
		काष्ठा ia_css_isp_parameter macc;
		काष्ठा ia_css_isp_parameter sdis_horiproj;
		काष्ठा ia_css_isp_parameter sdis_vertproj;
		काष्ठा ia_css_isp_parameter sdis2_horiproj;
		काष्ठा ia_css_isp_parameter sdis2_vertproj;
		काष्ठा ia_css_isp_parameter wb;
		काष्ठा ia_css_isp_parameter nr;
		काष्ठा ia_css_isp_parameter yee;
		काष्ठा ia_css_isp_parameter ynr;
		काष्ठा ia_css_isp_parameter fc;
		काष्ठा ia_css_isp_parameter ctc;
		काष्ठा ia_css_isp_parameter xnr;
		काष्ठा ia_css_isp_parameter xnr3;
		काष्ठा ia_css_isp_parameter get;
		काष्ठा ia_css_isp_parameter put;
	पूर्ण dmem;
	काष्ठा अणु
		काष्ठा ia_css_isp_parameter anr2;
		काष्ठा ia_css_isp_parameter ob;
		काष्ठा ia_css_isp_parameter sdis_horicoef;
		काष्ठा ia_css_isp_parameter sdis_vertcoef;
		काष्ठा ia_css_isp_parameter sdis2_horicoef;
		काष्ठा ia_css_isp_parameter sdis2_vertcoef;

		/* ISP2401 */
		काष्ठा ia_css_isp_parameter xnr3;
	पूर्ण vmem;
	काष्ठा अणु
		काष्ठा ia_css_isp_parameter bh;
	पूर्ण hmem0;
	काष्ठा अणु
		काष्ठा ia_css_isp_parameter gc;
		काष्ठा ia_css_isp_parameter g_gamma;
		काष्ठा ia_css_isp_parameter xnr_table;
	पूर्ण vamem1;
	काष्ठा अणु
		काष्ठा ia_css_isp_parameter r_gamma;
		काष्ठा ia_css_isp_parameter ctc;
	पूर्ण vamem0;
	काष्ठा अणु
		काष्ठा ia_css_isp_parameter b_gamma;
	पूर्ण vamem2;
पूर्ण;

#अगर defined(IA_CSS_INCLUDE_PARAMETERS)

#समावेश "ia_css_stream.h"   /* काष्ठा ia_css_stream */
#समावेश "ia_css_binary.h"   /* काष्ठा ia_css_binary */
/* Code generated by genparam/gencode.c:gen_param_process_table() */

काष्ठा ia_css_pipeline_stage; /* क्रमward declaration */

बाह्य व्योम (*ia_css_kernel_process_param[IA_CSS_NUM_PARAMETER_IDS])(
    अचिन्हित पूर्णांक pipe_id,
    स्थिर काष्ठा ia_css_pipeline_stage *stage,
    काष्ठा ia_css_isp_parameters *params);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_dp_config(काष्ठा ia_css_isp_parameters *params,
		     स्थिर काष्ठा ia_css_dp_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_wb_config(काष्ठा ia_css_isp_parameters *params,
		     स्थिर काष्ठा ia_css_wb_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_tnr_config(काष्ठा ia_css_isp_parameters *params,
		      स्थिर काष्ठा ia_css_tnr_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_ob_config(काष्ठा ia_css_isp_parameters *params,
		     स्थिर काष्ठा ia_css_ob_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_de_config(काष्ठा ia_css_isp_parameters *params,
		     स्थिर काष्ठा ia_css_de_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_anr_config(काष्ठा ia_css_isp_parameters *params,
		      स्थिर काष्ठा ia_css_anr_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_anr2_config(काष्ठा ia_css_isp_parameters *params,
		       स्थिर काष्ठा ia_css_anr_thres *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_ce_config(काष्ठा ia_css_isp_parameters *params,
		     स्थिर काष्ठा ia_css_ce_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_ecd_config(काष्ठा ia_css_isp_parameters *params,
		      स्थिर काष्ठा ia_css_ecd_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_ynr_config(काष्ठा ia_css_isp_parameters *params,
		      स्थिर काष्ठा ia_css_ynr_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_fc_config(काष्ठा ia_css_isp_parameters *params,
		     स्थिर काष्ठा ia_css_fc_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_cnr_config(काष्ठा ia_css_isp_parameters *params,
		      स्थिर काष्ठा ia_css_cnr_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_macc_config(काष्ठा ia_css_isp_parameters *params,
		       स्थिर काष्ठा ia_css_macc_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_ctc_config(काष्ठा ia_css_isp_parameters *params,
		      स्थिर काष्ठा ia_css_ctc_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_aa_config(काष्ठा ia_css_isp_parameters *params,
		     स्थिर काष्ठा ia_css_aa_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_yuv2rgb_config(काष्ठा ia_css_isp_parameters *params,
			  स्थिर काष्ठा ia_css_cc_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_rgb2yuv_config(काष्ठा ia_css_isp_parameters *params,
			  स्थिर काष्ठा ia_css_cc_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_csc_config(काष्ठा ia_css_isp_parameters *params,
		      स्थिर काष्ठा ia_css_cc_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_nr_config(काष्ठा ia_css_isp_parameters *params,
		     स्थिर काष्ठा ia_css_nr_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_gc_config(काष्ठा ia_css_isp_parameters *params,
		     स्थिर काष्ठा ia_css_gc_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_sdis_horicoef_config(काष्ठा ia_css_isp_parameters *params,
				स्थिर काष्ठा ia_css_dvs_coefficients *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_sdis_vertcoef_config(काष्ठा ia_css_isp_parameters *params,
				स्थिर काष्ठा ia_css_dvs_coefficients *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_sdis_horiproj_config(काष्ठा ia_css_isp_parameters *params,
				स्थिर काष्ठा ia_css_dvs_coefficients *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_sdis_vertproj_config(काष्ठा ia_css_isp_parameters *params,
				स्थिर काष्ठा ia_css_dvs_coefficients *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_sdis2_horicoef_config(काष्ठा ia_css_isp_parameters *params,
				 स्थिर काष्ठा ia_css_dvs2_coefficients *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_sdis2_vertcoef_config(काष्ठा ia_css_isp_parameters *params,
				 स्थिर काष्ठा ia_css_dvs2_coefficients *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_sdis2_horiproj_config(काष्ठा ia_css_isp_parameters *params,
				 स्थिर काष्ठा ia_css_dvs2_coefficients *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_sdis2_vertproj_config(काष्ठा ia_css_isp_parameters *params,
				 स्थिर काष्ठा ia_css_dvs2_coefficients *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_r_gamma_config(काष्ठा ia_css_isp_parameters *params,
			  स्थिर काष्ठा ia_css_rgb_gamma_table *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_g_gamma_config(काष्ठा ia_css_isp_parameters *params,
			  स्थिर काष्ठा ia_css_rgb_gamma_table *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_b_gamma_config(काष्ठा ia_css_isp_parameters *params,
			  स्थिर काष्ठा ia_css_rgb_gamma_table *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_xnr_table_config(काष्ठा ia_css_isp_parameters *params,
			    स्थिर काष्ठा ia_css_xnr_table *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_क्रमmats_config(काष्ठा ia_css_isp_parameters *params,
			  स्थिर काष्ठा ia_css_क्रमmats_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_xnr_config(काष्ठा ia_css_isp_parameters *params,
		      स्थिर काष्ठा ia_css_xnr_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_xnr3_config(काष्ठा ia_css_isp_parameters *params,
		       स्थिर काष्ठा ia_css_xnr3_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_s3a_config(काष्ठा ia_css_isp_parameters *params,
		      स्थिर काष्ठा ia_css_3a_config *config);

/* Code generated by genparam/gencode.c:gen_set_function() */

व्योम
ia_css_set_output_config(काष्ठा ia_css_isp_parameters *params,
			 स्थिर काष्ठा ia_css_output_config *config);

/* Code generated by genparam/gencode.c:gen_global_access_function() */

व्योम
ia_css_get_configs(काष्ठा ia_css_isp_parameters *params,
		   स्थिर काष्ठा ia_css_isp_config *config)
;

/* Code generated by genparam/gencode.c:gen_global_access_function() */

व्योम
ia_css_set_configs(काष्ठा ia_css_isp_parameters *params,
		   स्थिर काष्ठा ia_css_isp_config *config)
;

#पूर्ण_अगर /* IA_CSS_INCLUDE_PARAMETER */
#पूर्ण_अगर /* _IA_CSS_ISP_PARAM_H */
