<शैली गुरु>
/*
 * ACP_2_2 Register करोcumentation
 *
 * Copyright (C) 2014  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, मुक्त of अक्षरge, to any person obtaining a
 * copy of this software and associated करोcumentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modअगरy, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to करो so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#अगर_अघोषित ACP_2_2_D_H
#घोषणा ACP_2_2_D_H

#घोषणा mmACP_DMA_CNTL_0                                                        0x5000
#घोषणा mmACP_DMA_CNTL_1                                                        0x5001
#घोषणा mmACP_DMA_CNTL_2                                                        0x5002
#घोषणा mmACP_DMA_CNTL_3                                                        0x5003
#घोषणा mmACP_DMA_CNTL_4                                                        0x5004
#घोषणा mmACP_DMA_CNTL_5                                                        0x5005
#घोषणा mmACP_DMA_CNTL_6                                                        0x5006
#घोषणा mmACP_DMA_CNTL_7                                                        0x5007
#घोषणा mmACP_DMA_CNTL_8                                                        0x5008
#घोषणा mmACP_DMA_CNTL_9                                                        0x5009
#घोषणा mmACP_DMA_CNTL_10                                                       0x500a
#घोषणा mmACP_DMA_CNTL_11                                                       0x500b
#घोषणा mmACP_DMA_CNTL_12                                                       0x500c
#घोषणा mmACP_DMA_CNTL_13                                                       0x500d
#घोषणा mmACP_DMA_CNTL_14                                                       0x500e
#घोषणा mmACP_DMA_CNTL_15                                                       0x500f
#घोषणा mmACP_DMA_DSCR_STRT_IDX_0                                               0x5010
#घोषणा mmACP_DMA_DSCR_STRT_IDX_1                                               0x5011
#घोषणा mmACP_DMA_DSCR_STRT_IDX_2                                               0x5012
#घोषणा mmACP_DMA_DSCR_STRT_IDX_3                                               0x5013
#घोषणा mmACP_DMA_DSCR_STRT_IDX_4                                               0x5014
#घोषणा mmACP_DMA_DSCR_STRT_IDX_5                                               0x5015
#घोषणा mmACP_DMA_DSCR_STRT_IDX_6                                               0x5016
#घोषणा mmACP_DMA_DSCR_STRT_IDX_7                                               0x5017
#घोषणा mmACP_DMA_DSCR_STRT_IDX_8                                               0x5018
#घोषणा mmACP_DMA_DSCR_STRT_IDX_9                                               0x5019
#घोषणा mmACP_DMA_DSCR_STRT_IDX_10                                              0x501a
#घोषणा mmACP_DMA_DSCR_STRT_IDX_11                                              0x501b
#घोषणा mmACP_DMA_DSCR_STRT_IDX_12                                              0x501c
#घोषणा mmACP_DMA_DSCR_STRT_IDX_13                                              0x501d
#घोषणा mmACP_DMA_DSCR_STRT_IDX_14                                              0x501e
#घोषणा mmACP_DMA_DSCR_STRT_IDX_15                                              0x501f
#घोषणा mmACP_DMA_DSCR_CNT_0                                                    0x5020
#घोषणा mmACP_DMA_DSCR_CNT_1                                                    0x5021
#घोषणा mmACP_DMA_DSCR_CNT_2                                                    0x5022
#घोषणा mmACP_DMA_DSCR_CNT_3                                                    0x5023
#घोषणा mmACP_DMA_DSCR_CNT_4                                                    0x5024
#घोषणा mmACP_DMA_DSCR_CNT_5                                                    0x5025
#घोषणा mmACP_DMA_DSCR_CNT_6                                                    0x5026
#घोषणा mmACP_DMA_DSCR_CNT_7                                                    0x5027
#घोषणा mmACP_DMA_DSCR_CNT_8                                                    0x5028
#घोषणा mmACP_DMA_DSCR_CNT_9                                                    0x5029
#घोषणा mmACP_DMA_DSCR_CNT_10                                                   0x502a
#घोषणा mmACP_DMA_DSCR_CNT_11                                                   0x502b
#घोषणा mmACP_DMA_DSCR_CNT_12                                                   0x502c
#घोषणा mmACP_DMA_DSCR_CNT_13                                                   0x502d
#घोषणा mmACP_DMA_DSCR_CNT_14                                                   0x502e
#घोषणा mmACP_DMA_DSCR_CNT_15                                                   0x502f
#घोषणा mmACP_DMA_PRIO_0                                                        0x5030
#घोषणा mmACP_DMA_PRIO_1                                                        0x5031
#घोषणा mmACP_DMA_PRIO_2                                                        0x5032
#घोषणा mmACP_DMA_PRIO_3                                                        0x5033
#घोषणा mmACP_DMA_PRIO_4                                                        0x5034
#घोषणा mmACP_DMA_PRIO_5                                                        0x5035
#घोषणा mmACP_DMA_PRIO_6                                                        0x5036
#घोषणा mmACP_DMA_PRIO_7                                                        0x5037
#घोषणा mmACP_DMA_PRIO_8                                                        0x5038
#घोषणा mmACP_DMA_PRIO_9                                                        0x5039
#घोषणा mmACP_DMA_PRIO_10                                                       0x503a
#घोषणा mmACP_DMA_PRIO_11                                                       0x503b
#घोषणा mmACP_DMA_PRIO_12                                                       0x503c
#घोषणा mmACP_DMA_PRIO_13                                                       0x503d
#घोषणा mmACP_DMA_PRIO_14                                                       0x503e
#घोषणा mmACP_DMA_PRIO_15                                                       0x503f
#घोषणा mmACP_DMA_CUR_DSCR_0                                                    0x5040
#घोषणा mmACP_DMA_CUR_DSCR_1                                                    0x5041
#घोषणा mmACP_DMA_CUR_DSCR_2                                                    0x5042
#घोषणा mmACP_DMA_CUR_DSCR_3                                                    0x5043
#घोषणा mmACP_DMA_CUR_DSCR_4                                                    0x5044
#घोषणा mmACP_DMA_CUR_DSCR_5                                                    0x5045
#घोषणा mmACP_DMA_CUR_DSCR_6                                                    0x5046
#घोषणा mmACP_DMA_CUR_DSCR_7                                                    0x5047
#घोषणा mmACP_DMA_CUR_DSCR_8                                                    0x5048
#घोषणा mmACP_DMA_CUR_DSCR_9                                                    0x5049
#घोषणा mmACP_DMA_CUR_DSCR_10                                                   0x504a
#घोषणा mmACP_DMA_CUR_DSCR_11                                                   0x504b
#घोषणा mmACP_DMA_CUR_DSCR_12                                                   0x504c
#घोषणा mmACP_DMA_CUR_DSCR_13                                                   0x504d
#घोषणा mmACP_DMA_CUR_DSCR_14                                                   0x504e
#घोषणा mmACP_DMA_CUR_DSCR_15                                                   0x504f
#घोषणा mmACP_DMA_CUR_TRANS_CNT_0                                               0x5050
#घोषणा mmACP_DMA_CUR_TRANS_CNT_1                                               0x5051
#घोषणा mmACP_DMA_CUR_TRANS_CNT_2                                               0x5052
#घोषणा mmACP_DMA_CUR_TRANS_CNT_3                                               0x5053
#घोषणा mmACP_DMA_CUR_TRANS_CNT_4                                               0x5054
#घोषणा mmACP_DMA_CUR_TRANS_CNT_5                                               0x5055
#घोषणा mmACP_DMA_CUR_TRANS_CNT_6                                               0x5056
#घोषणा mmACP_DMA_CUR_TRANS_CNT_7                                               0x5057
#घोषणा mmACP_DMA_CUR_TRANS_CNT_8                                               0x5058
#घोषणा mmACP_DMA_CUR_TRANS_CNT_9                                               0x5059
#घोषणा mmACP_DMA_CUR_TRANS_CNT_10                                              0x505a
#घोषणा mmACP_DMA_CUR_TRANS_CNT_11                                              0x505b
#घोषणा mmACP_DMA_CUR_TRANS_CNT_12                                              0x505c
#घोषणा mmACP_DMA_CUR_TRANS_CNT_13                                              0x505d
#घोषणा mmACP_DMA_CUR_TRANS_CNT_14                                              0x505e
#घोषणा mmACP_DMA_CUR_TRANS_CNT_15                                              0x505f
#घोषणा mmACP_DMA_ERR_STS_0                                                     0x5060
#घोषणा mmACP_DMA_ERR_STS_1                                                     0x5061
#घोषणा mmACP_DMA_ERR_STS_2                                                     0x5062
#घोषणा mmACP_DMA_ERR_STS_3                                                     0x5063
#घोषणा mmACP_DMA_ERR_STS_4                                                     0x5064
#घोषणा mmACP_DMA_ERR_STS_5                                                     0x5065
#घोषणा mmACP_DMA_ERR_STS_6                                                     0x5066
#घोषणा mmACP_DMA_ERR_STS_7                                                     0x5067
#घोषणा mmACP_DMA_ERR_STS_8                                                     0x5068
#घोषणा mmACP_DMA_ERR_STS_9                                                     0x5069
#घोषणा mmACP_DMA_ERR_STS_10                                                    0x506a
#घोषणा mmACP_DMA_ERR_STS_11                                                    0x506b
#घोषणा mmACP_DMA_ERR_STS_12                                                    0x506c
#घोषणा mmACP_DMA_ERR_STS_13                                                    0x506d
#घोषणा mmACP_DMA_ERR_STS_14                                                    0x506e
#घोषणा mmACP_DMA_ERR_STS_15                                                    0x506f
#घोषणा mmACP_DMA_DESC_BASE_ADDR                                                0x5070
#घोषणा mmACP_DMA_DESC_MAX_NUM_DSCR                                             0x5071
#घोषणा mmACP_DMA_CH_STS                                                        0x5072
#घोषणा mmACP_DMA_CH_GROUP                                                      0x5073
#घोषणा mmACP_DSP0_CACHE_OFFSET0                                                0x5078
#घोषणा mmACP_DSP0_CACHE_SIZE0                                                  0x5079
#घोषणा mmACP_DSP0_CACHE_OFFSET1                                                0x507a
#घोषणा mmACP_DSP0_CACHE_SIZE1                                                  0x507b
#घोषणा mmACP_DSP0_CACHE_OFFSET2                                                0x507c
#घोषणा mmACP_DSP0_CACHE_SIZE2                                                  0x507d
#घोषणा mmACP_DSP0_CACHE_OFFSET3                                                0x507e
#घोषणा mmACP_DSP0_CACHE_SIZE3                                                  0x507f
#घोषणा mmACP_DSP0_CACHE_OFFSET4                                                0x5080
#घोषणा mmACP_DSP0_CACHE_SIZE4                                                  0x5081
#घोषणा mmACP_DSP0_CACHE_OFFSET5                                                0x5082
#घोषणा mmACP_DSP0_CACHE_SIZE5                                                  0x5083
#घोषणा mmACP_DSP0_CACHE_OFFSET6                                                0x5084
#घोषणा mmACP_DSP0_CACHE_SIZE6                                                  0x5085
#घोषणा mmACP_DSP0_CACHE_OFFSET7                                                0x5086
#घोषणा mmACP_DSP0_CACHE_SIZE7                                                  0x5087
#घोषणा mmACP_DSP0_CACHE_OFFSET8                                                0x5088
#घोषणा mmACP_DSP0_CACHE_SIZE8                                                  0x5089
#घोषणा mmACP_DSP0_NONCACHE_OFFSET0                                             0x508a
#घोषणा mmACP_DSP0_NONCACHE_SIZE0                                               0x508b
#घोषणा mmACP_DSP0_NONCACHE_OFFSET1                                             0x508c
#घोषणा mmACP_DSP0_NONCACHE_SIZE1                                               0x508d
#घोषणा mmACP_DSP0_DEBUG_PC                                                     0x508e
#घोषणा mmACP_DSP0_NMI_SEL                                                      0x508f
#घोषणा mmACP_DSP0_CLKRST_CNTL                                                  0x5090
#घोषणा mmACP_DSP0_RUNSTALL                                                     0x5091
#घोषणा mmACP_DSP0_OCD_HALT_ON_RST                                              0x5092
#घोषणा mmACP_DSP0_WAIT_MODE                                                    0x5093
#घोषणा mmACP_DSP0_VECT_SEL                                                     0x5094
#घोषणा mmACP_DSP0_DEBUG_REG1                                                   0x5095
#घोषणा mmACP_DSP0_DEBUG_REG2                                                   0x5096
#घोषणा mmACP_DSP0_DEBUG_REG3                                                   0x5097
#घोषणा mmACP_DSP1_CACHE_OFFSET0                                                0x509d
#घोषणा mmACP_DSP1_CACHE_SIZE0                                                  0x509e
#घोषणा mmACP_DSP1_CACHE_OFFSET1                                                0x509f
#घोषणा mmACP_DSP1_CACHE_SIZE1                                                  0x50a0
#घोषणा mmACP_DSP1_CACHE_OFFSET2                                                0x50a1
#घोषणा mmACP_DSP1_CACHE_SIZE2                                                  0x50a2
#घोषणा mmACP_DSP1_CACHE_OFFSET3                                                0x50a3
#घोषणा mmACP_DSP1_CACHE_SIZE3                                                  0x50a4
#घोषणा mmACP_DSP1_CACHE_OFFSET4                                                0x50a5
#घोषणा mmACP_DSP1_CACHE_SIZE4                                                  0x50a6
#घोषणा mmACP_DSP1_CACHE_OFFSET5                                                0x50a7
#घोषणा mmACP_DSP1_CACHE_SIZE5                                                  0x50a8
#घोषणा mmACP_DSP1_CACHE_OFFSET6                                                0x50a9
#घोषणा mmACP_DSP1_CACHE_SIZE6                                                  0x50aa
#घोषणा mmACP_DSP1_CACHE_OFFSET7                                                0x50ab
#घोषणा mmACP_DSP1_CACHE_SIZE7                                                  0x50ac
#घोषणा mmACP_DSP1_CACHE_OFFSET8                                                0x50ad
#घोषणा mmACP_DSP1_CACHE_SIZE8                                                  0x50ae
#घोषणा mmACP_DSP1_NONCACHE_OFFSET0                                             0x50af
#घोषणा mmACP_DSP1_NONCACHE_SIZE0                                               0x50b0
#घोषणा mmACP_DSP1_NONCACHE_OFFSET1                                             0x50b1
#घोषणा mmACP_DSP1_NONCACHE_SIZE1                                               0x50b2
#घोषणा mmACP_DSP1_DEBUG_PC                                                     0x50b3
#घोषणा mmACP_DSP1_NMI_SEL                                                      0x50b4
#घोषणा mmACP_DSP1_CLKRST_CNTL                                                  0x50b5
#घोषणा mmACP_DSP1_RUNSTALL                                                     0x50b6
#घोषणा mmACP_DSP1_OCD_HALT_ON_RST                                              0x50b7
#घोषणा mmACP_DSP1_WAIT_MODE                                                    0x50b8
#घोषणा mmACP_DSP1_VECT_SEL                                                     0x50b9
#घोषणा mmACP_DSP1_DEBUG_REG1                                                   0x50ba
#घोषणा mmACP_DSP1_DEBUG_REG2                                                   0x50bb
#घोषणा mmACP_DSP1_DEBUG_REG3                                                   0x50bc
#घोषणा mmACP_DSP2_CACHE_OFFSET0                                                0x50c2
#घोषणा mmACP_DSP2_CACHE_SIZE0                                                  0x50c3
#घोषणा mmACP_DSP2_CACHE_OFFSET1                                                0x50c4
#घोषणा mmACP_DSP2_CACHE_SIZE1                                                  0x50c5
#घोषणा mmACP_DSP2_CACHE_OFFSET2                                                0x50c6
#घोषणा mmACP_DSP2_CACHE_SIZE2                                                  0x50c7
#घोषणा mmACP_DSP2_CACHE_OFFSET3                                                0x50c8
#घोषणा mmACP_DSP2_CACHE_SIZE3                                                  0x50c9
#घोषणा mmACP_DSP2_CACHE_OFFSET4                                                0x50ca
#घोषणा mmACP_DSP2_CACHE_SIZE4                                                  0x50cb
#घोषणा mmACP_DSP2_CACHE_OFFSET5                                                0x50cc
#घोषणा mmACP_DSP2_CACHE_SIZE5                                                  0x50cd
#घोषणा mmACP_DSP2_CACHE_OFFSET6                                                0x50ce
#घोषणा mmACP_DSP2_CACHE_SIZE6                                                  0x50cf
#घोषणा mmACP_DSP2_CACHE_OFFSET7                                                0x50d0
#घोषणा mmACP_DSP2_CACHE_SIZE7                                                  0x50d1
#घोषणा mmACP_DSP2_CACHE_OFFSET8                                                0x50d2
#घोषणा mmACP_DSP2_CACHE_SIZE8                                                  0x50d3
#घोषणा mmACP_DSP2_NONCACHE_OFFSET0                                             0x50d4
#घोषणा mmACP_DSP2_NONCACHE_SIZE0                                               0x50d5
#घोषणा mmACP_DSP2_NONCACHE_OFFSET1                                             0x50d6
#घोषणा mmACP_DSP2_NONCACHE_SIZE1                                               0x50d7
#घोषणा mmACP_DSP2_DEBUG_PC                                                     0x50d8
#घोषणा mmACP_DSP2_NMI_SEL                                                      0x50d9
#घोषणा mmACP_DSP2_CLKRST_CNTL                                                  0x50da
#घोषणा mmACP_DSP2_RUNSTALL                                                     0x50db
#घोषणा mmACP_DSP2_OCD_HALT_ON_RST                                              0x50dc
#घोषणा mmACP_DSP2_WAIT_MODE                                                    0x50dd
#घोषणा mmACP_DSP2_VECT_SEL                                                     0x50de
#घोषणा mmACP_DSP2_DEBUG_REG1                                                   0x50df
#घोषणा mmACP_DSP2_DEBUG_REG2                                                   0x50e0
#घोषणा mmACP_DSP2_DEBUG_REG3                                                   0x50e1
#घोषणा mmACP_AXI2DAGB_ONION_CNTL                                               0x50e7
#घोषणा mmACP_AXI2DAGB_ONION_ERR_STATUS_WR                                      0x50e8
#घोषणा mmACP_AXI2DAGB_ONION_ERR_STATUS_RD                                      0x50e9
#घोषणा mmACP_DAGB_Onion_TransPerf_Counter_Control                              0x50ea
#घोषणा mmACP_DAGB_Onion_Wr_TransPerf_Counter_Current                           0x50eb
#घोषणा mmACP_DAGB_Onion_Wr_TransPerf_Counter_Peak                              0x50ec
#घोषणा mmACP_DAGB_Onion_Rd_TransPerf_Counter_Current                           0x50ed
#घोषणा mmACP_DAGB_Onion_Rd_TransPerf_Counter_Peak                              0x50ee
#घोषणा mmACP_AXI2DAGB_GARLIC_CNTL                                              0x50f3
#घोषणा mmACP_AXI2DAGB_GARLIC_ERR_STATUS_WR                                     0x50f4
#घोषणा mmACP_AXI2DAGB_GARLIC_ERR_STATUS_RD                                     0x50f5
#घोषणा mmACP_DAGB_Garlic_TransPerf_Counter_Control                             0x50f6
#घोषणा mmACP_DAGB_Garlic_Wr_TransPerf_Counter_Current                          0x50f7
#घोषणा mmACP_DAGB_Garlic_Wr_TransPerf_Counter_Peak                             0x50f8
#घोषणा mmACP_DAGB_Garlic_Rd_TransPerf_Counter_Current                          0x50f9
#घोषणा mmACP_DAGB_Garlic_Rd_TransPerf_Counter_Peak                             0x50fa
#घोषणा mmACP_DAGB_PAGE_SIZE_GRP_1                                              0x50ff
#घोषणा mmACP_DAGB_BASE_ADDR_GRP_1                                              0x5100
#घोषणा mmACP_DAGB_PAGE_SIZE_GRP_2                                              0x5101
#घोषणा mmACP_DAGB_BASE_ADDR_GRP_2                                              0x5102
#घोषणा mmACP_DAGB_PAGE_SIZE_GRP_3                                              0x5103
#घोषणा mmACP_DAGB_BASE_ADDR_GRP_3                                              0x5104
#घोषणा mmACP_DAGB_PAGE_SIZE_GRP_4                                              0x5105
#घोषणा mmACP_DAGB_BASE_ADDR_GRP_4                                              0x5106
#घोषणा mmACP_DAGB_PAGE_SIZE_GRP_5                                              0x5107
#घोषणा mmACP_DAGB_BASE_ADDR_GRP_5                                              0x5108
#घोषणा mmACP_DAGB_PAGE_SIZE_GRP_6                                              0x5109
#घोषणा mmACP_DAGB_BASE_ADDR_GRP_6                                              0x510a
#घोषणा mmACP_DAGB_PAGE_SIZE_GRP_7                                              0x510b
#घोषणा mmACP_DAGB_BASE_ADDR_GRP_7                                              0x510c
#घोषणा mmACP_DAGB_PAGE_SIZE_GRP_8                                              0x510d
#घोषणा mmACP_DAGB_BASE_ADDR_GRP_8                                              0x510e
#घोषणा mmACP_DAGB_ATU_CTRL                                                     0x510f
#घोषणा mmACP_CONTROL                                                           0x5131
#घोषणा mmACP_STATUS                                                            0x5133
#घोषणा mmACP_SOFT_RESET                                                        0x5134
#घोषणा mmACP_PwrMgmt_CNTL                                                      0x5135
#घोषणा mmACP_CAC_INDICATOR_CONTROL                                             0x5136
#घोषणा mmACP_SMU_MAILBOX                                                       0x5137
#घोषणा mmACP_FUTURE_REG_SCLK_0                                                 0x5138
#घोषणा mmACP_FUTURE_REG_SCLK_1                                                 0x5139
#घोषणा mmACP_FUTURE_REG_SCLK_2                                                 0x513a
#घोषणा mmACP_FUTURE_REG_SCLK_3                                                 0x513b
#घोषणा mmACP_FUTURE_REG_SCLK_4                                                 0x513c
#घोषणा mmACP_DAGB_DEBUG_CNT_ENABLE                                             0x513d
#घोषणा mmACP_DAGBG_WR_ASK_CNT                                                  0x513e
#घोषणा mmACP_DAGBG_WR_GO_CNT                                                   0x513f
#घोषणा mmACP_DAGBG_WR_EXP_RESP_CNT                                             0x5140
#घोषणा mmACP_DAGBG_WR_ACTUAL_RESP_CNT                                          0x5141
#घोषणा mmACP_DAGBG_RD_ASK_CNT                                                  0x5142
#घोषणा mmACP_DAGBG_RD_GO_CNT                                                   0x5143
#घोषणा mmACP_DAGBG_RD_EXP_RESP_CNT                                             0x5144
#घोषणा mmACP_DAGBG_RD_ACTUAL_RESP_CNT                                          0x5145
#घोषणा mmACP_DAGBO_WR_ASK_CNT                                                  0x5146
#घोषणा mmACP_DAGBO_WR_GO_CNT                                                   0x5147
#घोषणा mmACP_DAGBO_WR_EXP_RESP_CNT                                             0x5148
#घोषणा mmACP_DAGBO_WR_ACTUAL_RESP_CNT                                          0x5149
#घोषणा mmACP_DAGBO_RD_ASK_CNT                                                  0x514a
#घोषणा mmACP_DAGBO_RD_GO_CNT                                                   0x514b
#घोषणा mmACP_DAGBO_RD_EXP_RESP_CNT                                             0x514c
#घोषणा mmACP_DAGBO_RD_ACTUAL_RESP_CNT                                          0x514d
#घोषणा mmACP_BRB_CONTROL                                                       0x5156
#घोषणा mmACP_EXTERNAL_INTR_ENB                                                 0x5157
#घोषणा mmACP_EXTERNAL_INTR_CNTL                                                0x5158
#घोषणा mmACP_ERROR_SOURCE_STS                                                  0x5159
#घोषणा mmACP_DSP_SW_INTR_TRIG                                                  0x515a
#घोषणा mmACP_DSP_SW_INTR_CNTL                                                  0x515b
#घोषणा mmACP_DAGBG_TIMEOUT_CNTL                                                0x515c
#घोषणा mmACP_DAGBO_TIMEOUT_CNTL                                                0x515d
#घोषणा mmACP_EXTERNAL_INTR_STAT                                                0x515e
#घोषणा mmACP_DSP_SW_INTR_STAT                                                  0x515f
#घोषणा mmACP_DSP0_INTR_CNTL                                                    0x5160
#घोषणा mmACP_DSP0_INTR_STAT                                                    0x5161
#घोषणा mmACP_DSP0_TIMEOUT_CNTL                                                 0x5162
#घोषणा mmACP_DSP1_INTR_CNTL                                                    0x5163
#घोषणा mmACP_DSP1_INTR_STAT                                                    0x5164
#घोषणा mmACP_DSP1_TIMEOUT_CNTL                                                 0x5165
#घोषणा mmACP_DSP2_INTR_CNTL                                                    0x5166
#घोषणा mmACP_DSP2_INTR_STAT                                                    0x5167
#घोषणा mmACP_DSP2_TIMEOUT_CNTL                                                 0x5168
#घोषणा mmACP_DSP0_EXT_TIMER_CNTL                                               0x5169
#घोषणा mmACP_DSP1_EXT_TIMER_CNTL                                               0x516a
#घोषणा mmACP_DSP2_EXT_TIMER_CNTL                                               0x516b
#घोषणा mmACP_AXI2DAGB_SEM_0                                                    0x516c
#घोषणा mmACP_AXI2DAGB_SEM_1                                                    0x516d
#घोषणा mmACP_AXI2DAGB_SEM_2                                                    0x516e
#घोषणा mmACP_AXI2DAGB_SEM_3                                                    0x516f
#घोषणा mmACP_AXI2DAGB_SEM_4                                                    0x5170
#घोषणा mmACP_AXI2DAGB_SEM_5                                                    0x5171
#घोषणा mmACP_AXI2DAGB_SEM_6                                                    0x5172
#घोषणा mmACP_AXI2DAGB_SEM_7                                                    0x5173
#घोषणा mmACP_AXI2DAGB_SEM_8                                                    0x5174
#घोषणा mmACP_AXI2DAGB_SEM_9                                                    0x5175
#घोषणा mmACP_AXI2DAGB_SEM_10                                                   0x5176
#घोषणा mmACP_AXI2DAGB_SEM_11                                                   0x5177
#घोषणा mmACP_AXI2DAGB_SEM_12                                                   0x5178
#घोषणा mmACP_AXI2DAGB_SEM_13                                                   0x5179
#घोषणा mmACP_AXI2DAGB_SEM_14                                                   0x517a
#घोषणा mmACP_AXI2DAGB_SEM_15                                                   0x517b
#घोषणा mmACP_AXI2DAGB_SEM_16                                                   0x517c
#घोषणा mmACP_AXI2DAGB_SEM_17                                                   0x517d
#घोषणा mmACP_AXI2DAGB_SEM_18                                                   0x517e
#घोषणा mmACP_AXI2DAGB_SEM_19                                                   0x517f
#घोषणा mmACP_AXI2DAGB_SEM_20                                                   0x5180
#घोषणा mmACP_AXI2DAGB_SEM_21                                                   0x5181
#घोषणा mmACP_AXI2DAGB_SEM_22                                                   0x5182
#घोषणा mmACP_AXI2DAGB_SEM_23                                                   0x5183
#घोषणा mmACP_AXI2DAGB_SEM_24                                                   0x5184
#घोषणा mmACP_AXI2DAGB_SEM_25                                                   0x5185
#घोषणा mmACP_AXI2DAGB_SEM_26                                                   0x5186
#घोषणा mmACP_AXI2DAGB_SEM_27                                                   0x5187
#घोषणा mmACP_AXI2DAGB_SEM_28                                                   0x5188
#घोषणा mmACP_AXI2DAGB_SEM_29                                                   0x5189
#घोषणा mmACP_AXI2DAGB_SEM_30                                                   0x518a
#घोषणा mmACP_AXI2DAGB_SEM_31                                                   0x518b
#घोषणा mmACP_AXI2DAGB_SEM_32                                                   0x518c
#घोषणा mmACP_AXI2DAGB_SEM_33                                                   0x518d
#घोषणा mmACP_AXI2DAGB_SEM_34                                                   0x518e
#घोषणा mmACP_AXI2DAGB_SEM_35                                                   0x518f
#घोषणा mmACP_AXI2DAGB_SEM_36                                                   0x5190
#घोषणा mmACP_AXI2DAGB_SEM_37                                                   0x5191
#घोषणा mmACP_AXI2DAGB_SEM_38                                                   0x5192
#घोषणा mmACP_AXI2DAGB_SEM_39                                                   0x5193
#घोषणा mmACP_AXI2DAGB_SEM_40                                                   0x5194
#घोषणा mmACP_AXI2DAGB_SEM_41                                                   0x5195
#घोषणा mmACP_AXI2DAGB_SEM_42                                                   0x5196
#घोषणा mmACP_AXI2DAGB_SEM_43                                                   0x5197
#घोषणा mmACP_AXI2DAGB_SEM_44                                                   0x5198
#घोषणा mmACP_AXI2DAGB_SEM_45                                                   0x5199
#घोषणा mmACP_AXI2DAGB_SEM_46                                                   0x519a
#घोषणा mmACP_AXI2DAGB_SEM_47                                                   0x519b
#घोषणा mmACP_SRBM_Client_Base_Addr                                             0x519c
#घोषणा mmACP_SRBM_Client_RDDATA                                                0x519d
#घोषणा mmACP_SRBM_Cycle_Sts                                                    0x519e
#घोषणा mmACP_SRBM_Targ_Idx_Addr                                                0x519f
#घोषणा mmACP_SRBM_Targ_Idx_Data                                                0x51a0
#घोषणा mmACP_SEMA_ADDR_LOW                                                     0x51a1
#घोषणा mmACP_SEMA_ADDR_HIGH                                                    0x51a2
#घोषणा mmACP_SEMA_CMD                                                          0x51a3
#घोषणा mmACP_SEMA_STS                                                          0x51a4
#घोषणा mmACP_SEMA_REQ                                                          0x51a5
#घोषणा mmACP_FW_STATUS                                                         0x51a6
#घोषणा mmACP_FUTURE_REG_ACLK_0                                                 0x51a7
#घोषणा mmACP_FUTURE_REG_ACLK_1                                                 0x51a8
#घोषणा mmACP_FUTURE_REG_ACLK_2                                                 0x51a9
#घोषणा mmACP_FUTURE_REG_ACLK_3                                                 0x51aa
#घोषणा mmACP_FUTURE_REG_ACLK_4                                                 0x51ab
#घोषणा mmACP_TIMER                                                             0x51ac
#घोषणा mmACP_TIMER_CNTL                                                        0x51ad
#घोषणा mmACP_DSP0_TIMER                                                        0x51ae
#घोषणा mmACP_DSP1_TIMER                                                        0x51af
#घोषणा mmACP_DSP2_TIMER                                                        0x51b0
#घोषणा mmACP_I2S_TRANSMIT_BYTE_CNT_HIGH                                        0x51b1
#घोषणा mmACP_I2S_TRANSMIT_BYTE_CNT_LOW                                         0x51b2
#घोषणा mmACP_I2S_BT_TRANSMIT_BYTE_CNT_HIGH                                     0x51b3
#घोषणा mmACP_I2S_BT_TRANSMIT_BYTE_CNT_LOW                                      0x51b4
#घोषणा mmACP_I2S_BT_RECEIVE_BYTE_CNT_HIGH                                      0x51b5
#घोषणा mmACP_I2S_BT_RECEIVE_BYTE_CNT_LOW                                       0x51b6
#घोषणा mmACP_DSP0_CS_STATE                                                     0x51b7
#घोषणा mmACP_DSP1_CS_STATE                                                     0x51b8
#घोषणा mmACP_DSP2_CS_STATE                                                     0x51b9
#घोषणा mmACP_SCRATCH_REG_BASE_ADDR                                             0x51ba
#घोषणा mmCC_ACP_EFUSE                                                          0x51c8
#घोषणा mmACP_PGFSM_RETAIN_REG                                                  0x51c9
#घोषणा mmACP_PGFSM_CONFIG_REG                                                  0x51ca
#घोषणा mmACP_PGFSM_WRITE_REG                                                   0x51cb
#घोषणा mmACP_PGFSM_READ_REG_0                                                  0x51cc
#घोषणा mmACP_PGFSM_READ_REG_1                                                  0x51cd
#घोषणा mmACP_PGFSM_READ_REG_2                                                  0x51ce
#घोषणा mmACP_PGFSM_READ_REG_3                                                  0x51cf
#घोषणा mmACP_PGFSM_READ_REG_4                                                  0x51d0
#घोषणा mmACP_PGFSM_READ_REG_5                                                  0x51d1
#घोषणा mmACP_IP_PGFSM_ENABLE                                                   0x51d2
#घोषणा mmACP_I2S_PIN_CONFIG                                                    0x51d3
#घोषणा mmACP_AZALIA_I2S_SELECT                                                 0x51d4
#घोषणा mmACP_CHIP_PKG_FOR_PAD_ISOLATION                                        0x51d5
#घोषणा mmACP_AUDIO_PAD_PULLUP_PULLDOWN_CTRL                                    0x51d6
#घोषणा mmACP_BT_UART_PAD_SEL                                                   0x51d7
#घोषणा mmACP_SCRATCH_REG_0                                                     0x52c0
#घोषणा mmACP_SCRATCH_REG_1                                                     0x52c1
#घोषणा mmACP_SCRATCH_REG_2                                                     0x52c2
#घोषणा mmACP_SCRATCH_REG_3                                                     0x52c3
#घोषणा mmACP_SCRATCH_REG_4                                                     0x52c4
#घोषणा mmACP_SCRATCH_REG_5                                                     0x52c5
#घोषणा mmACP_SCRATCH_REG_6                                                     0x52c6
#घोषणा mmACP_SCRATCH_REG_7                                                     0x52c7
#घोषणा mmACP_SCRATCH_REG_8                                                     0x52c8
#घोषणा mmACP_SCRATCH_REG_9                                                     0x52c9
#घोषणा mmACP_SCRATCH_REG_10                                                    0x52ca
#घोषणा mmACP_SCRATCH_REG_11                                                    0x52cb
#घोषणा mmACP_SCRATCH_REG_12                                                    0x52cc
#घोषणा mmACP_SCRATCH_REG_13                                                    0x52cd
#घोषणा mmACP_SCRATCH_REG_14                                                    0x52ce
#घोषणा mmACP_SCRATCH_REG_15                                                    0x52cf
#घोषणा mmACP_SCRATCH_REG_16                                                    0x52d0
#घोषणा mmACP_SCRATCH_REG_17                                                    0x52d1
#घोषणा mmACP_SCRATCH_REG_18                                                    0x52d2
#घोषणा mmACP_SCRATCH_REG_19                                                    0x52d3
#घोषणा mmACP_SCRATCH_REG_20                                                    0x52d4
#घोषणा mmACP_SCRATCH_REG_21                                                    0x52d5
#घोषणा mmACP_SCRATCH_REG_22                                                    0x52d6
#घोषणा mmACP_SCRATCH_REG_23                                                    0x52d7
#घोषणा mmACP_SCRATCH_REG_24                                                    0x52d8
#घोषणा mmACP_SCRATCH_REG_25                                                    0x52d9
#घोषणा mmACP_SCRATCH_REG_26                                                    0x52da
#घोषणा mmACP_SCRATCH_REG_27                                                    0x52db
#घोषणा mmACP_SCRATCH_REG_28                                                    0x52dc
#घोषणा mmACP_SCRATCH_REG_29                                                    0x52dd
#घोषणा mmACP_SCRATCH_REG_30                                                    0x52de
#घोषणा mmACP_SCRATCH_REG_31                                                    0x52df
#घोषणा mmACP_SCRATCH_REG_32                                                    0x52e0
#घोषणा mmACP_SCRATCH_REG_33                                                    0x52e1
#घोषणा mmACP_SCRATCH_REG_34                                                    0x52e2
#घोषणा mmACP_SCRATCH_REG_35                                                    0x52e3
#घोषणा mmACP_SCRATCH_REG_36                                                    0x52e4
#घोषणा mmACP_SCRATCH_REG_37                                                    0x52e5
#घोषणा mmACP_SCRATCH_REG_38                                                    0x52e6
#घोषणा mmACP_SCRATCH_REG_39                                                    0x52e7
#घोषणा mmACP_SCRATCH_REG_40                                                    0x52e8
#घोषणा mmACP_SCRATCH_REG_41                                                    0x52e9
#घोषणा mmACP_SCRATCH_REG_42                                                    0x52ea
#घोषणा mmACP_SCRATCH_REG_43                                                    0x52eb
#घोषणा mmACP_SCRATCH_REG_44                                                    0x52ec
#घोषणा mmACP_SCRATCH_REG_45                                                    0x52ed
#घोषणा mmACP_SCRATCH_REG_46                                                    0x52ee
#घोषणा mmACP_SCRATCH_REG_47                                                    0x52ef
#घोषणा mmACP_VOICE_WAKEUP_ENABLE                                               0x51e8
#घोषणा mmACP_VOICE_WAKEUP_STATUS                                               0x51e9
#घोषणा mmI2S_VOICE_WAKEUP_LOWER_THRESHOLD                                      0x51ea
#घोषणा mmI2S_VOICE_WAKEUP_HIGHER_THRESHOLD                                     0x51eb
#घोषणा mmI2S_VOICE_WAKEUP_NO_OF_SAMPLES                                        0x51ec
#घोषणा mmI2S_VOICE_WAKEUP_NO_OF_PEAKS                                          0x51ed
#घोषणा mmI2S_VOICE_WAKEUP_DURATION_OF_N_PEAKS                                  0x51ee
#घोषणा mmI2S_VOICE_WAKEUP_BITCLK_TOGGLE_DETECTION                              0x51ef
#घोषणा mmI2S_VOICE_WAKEUP_DATA_PATH_SWITCH                                     0x51f0
#घोषणा mmI2S_VOICE_WAKEUP_DATA_POINTER                                         0x51f1
#घोषणा mmI2S_VOICE_WAKEUP_AUTH_MATCH                                           0x51f2
#घोषणा mmI2S_VOICE_WAKEUP_8KB_WRAP                                             0x51f3
#घोषणा mmACP_I2S_RECEIVED_BYTE_CNT_HIGH                                        0x51f4
#घोषणा mmACP_I2S_RECEIVED_BYTE_CNT_LOW                                         0x51f5
#घोषणा mmACP_I2S_MICSP_TRANSMIT_BYTE_CNT_HIGH                                  0x51f6
#घोषणा mmACP_I2S_MICSP_TRANSMIT_BYTE_CNT_LOW                                   0x51f7
#घोषणा mmACP_MEM_SHUT_DOWN_REQ_LO                                              0x51f8
#घोषणा mmACP_MEM_SHUT_DOWN_REQ_HI                                              0x51f9
#घोषणा mmACP_MEM_SHUT_DOWN_STS_LO                                              0x51fa
#घोषणा mmACP_MEM_SHUT_DOWN_STS_HI                                              0x51fb
#घोषणा mmACP_MEM_DEEP_SLEEP_REQ_LO                                             0x51fc
#घोषणा mmACP_MEM_DEEP_SLEEP_REQ_HI                                             0x51fd
#घोषणा mmACP_MEM_DEEP_SLEEP_STS_LO                                             0x51fe
#घोषणा mmACP_MEM_DEEP_SLEEP_STS_HI                                             0x51ff
#घोषणा mmACP_MEM_WAKEUP_FROM_SHUT_DOWN_LO                                      0x5200
#घोषणा mmACP_MEM_WAKEUP_FROM_SHUT_DOWN_HI                                      0x5201
#घोषणा mmACP_MEM_WAKEUP_FROM_SLEEP_LO                                          0x5202
#घोषणा mmACP_MEM_WAKEUP_FROM_SLEEP_HI                                          0x5203
#घोषणा mmACP_I2SSP_IER                                                         0x5210
#घोषणा mmACP_I2SSP_IRER                                                        0x5211
#घोषणा mmACP_I2SSP_ITER                                                        0x5212
#घोषणा mmACP_I2SSP_CER                                                         0x5213
#घोषणा mmACP_I2SSP_CCR                                                         0x5214
#घोषणा mmACP_I2SSP_RXFFR                                                       0x5215
#घोषणा mmACP_I2SSP_TXFFR                                                       0x5216
#घोषणा mmACP_I2SSP_LRBR0                                                       0x5218
#घोषणा mmACP_I2SSP_RRBR0                                                       0x5219
#घोषणा mmACP_I2SSP_RER0                                                        0x521a
#घोषणा mmACP_I2SSP_TER0                                                        0x521b
#घोषणा mmACP_I2SSP_RCR0                                                        0x521c
#घोषणा mmACP_I2SSP_TCR0                                                        0x521d
#घोषणा mmACP_I2SSP_ISR0                                                        0x521e
#घोषणा mmACP_I2SSP_IMR0                                                        0x521f
#घोषणा mmACP_I2SSP_ROR0                                                        0x5220
#घोषणा mmACP_I2SSP_TOR0                                                        0x5221
#घोषणा mmACP_I2SSP_RFCR0                                                       0x5222
#घोषणा mmACP_I2SSP_TFCR0                                                       0x5223
#घोषणा mmACP_I2SSP_RFF0                                                        0x5224
#घोषणा mmACP_I2SSP_TFF0                                                        0x5225
#घोषणा mmACP_I2SSP_RXDMA                                                       0x5226
#घोषणा mmACP_I2SSP_RRXDMA                                                      0x5227
#घोषणा mmACP_I2SSP_TXDMA                                                       0x5228
#घोषणा mmACP_I2SSP_RTXDMA                                                      0x5229
#घोषणा mmACP_I2SSP_COMP_PARAM_2                                                0x522a
#घोषणा mmACP_I2SSP_COMP_PARAM_1                                                0x522b
#घोषणा mmACP_I2SSP_COMP_VERSION                                                0x522c
#घोषणा mmACP_I2SSP_COMP_TYPE                                                   0x522d
#घोषणा mmACP_I2SMICSP_IER                                                      0x522e
#घोषणा mmACP_I2SMICSP_IRER                                                     0x522f
#घोषणा mmACP_I2SMICSP_ITER                                                     0x5230
#घोषणा mmACP_I2SMICSP_CER                                                      0x5231
#घोषणा mmACP_I2SMICSP_CCR                                                      0x5232
#घोषणा mmACP_I2SMICSP_RXFFR                                                    0x5233
#घोषणा mmACP_I2SMICSP_TXFFR                                                    0x5234
#घोषणा mmACP_I2SMICSP_LRBR0                                                    0x5236
#घोषणा mmACP_I2SMICSP_RRBR0                                                    0x5237
#घोषणा mmACP_I2SMICSP_RER0                                                     0x5238
#घोषणा mmACP_I2SMICSP_TER0                                                     0x5239
#घोषणा mmACP_I2SMICSP_RCR0                                                     0x523a
#घोषणा mmACP_I2SMICSP_TCR0                                                     0x523b
#घोषणा mmACP_I2SMICSP_ISR0                                                     0x523c
#घोषणा mmACP_I2SMICSP_IMR0                                                     0x523d
#घोषणा mmACP_I2SMICSP_ROR0                                                     0x523e
#घोषणा mmACP_I2SMICSP_TOR0                                                     0x523f
#घोषणा mmACP_I2SMICSP_RFCR0                                                    0x5240
#घोषणा mmACP_I2SMICSP_TFCR0                                                    0x5241
#घोषणा mmACP_I2SMICSP_RFF0                                                     0x5242
#घोषणा mmACP_I2SMICSP_TFF0                                                     0x5243
#घोषणा mmACP_I2SMICSP_LRBR1                                                    0x5246
#घोषणा mmACP_I2SMICSP_RRBR1                                                    0x5247
#घोषणा mmACP_I2SMICSP_RER1                                                     0x5248
#घोषणा mmACP_I2SMICSP_TER1                                                     0x5249
#घोषणा mmACP_I2SMICSP_RCR1                                                     0x524a
#घोषणा mmACP_I2SMICSP_TCR1                                                     0x524b
#घोषणा mmACP_I2SMICSP_ISR1                                                     0x524c
#घोषणा mmACP_I2SMICSP_IMR1                                                     0x524d
#घोषणा mmACP_I2SMICSP_ROR1                                                     0x524e
#घोषणा mmACP_I2SMICSP_TOR1                                                     0x524f
#घोषणा mmACP_I2SMICSP_RFCR1                                                    0x5250
#घोषणा mmACP_I2SMICSP_TFCR1                                                    0x5251
#घोषणा mmACP_I2SMICSP_RFF1                                                     0x5252
#घोषणा mmACP_I2SMICSP_TFF1                                                     0x5253
#घोषणा mmACP_I2SMICSP_RXDMA                                                    0x5254
#घोषणा mmACP_I2SMICSP_RRXDMA                                                   0x5255
#घोषणा mmACP_I2SMICSP_TXDMA                                                    0x5256
#घोषणा mmACP_I2SMICSP_RTXDMA                                                   0x5257
#घोषणा mmACP_I2SMICSP_COMP_PARAM_2                                             0x5258
#घोषणा mmACP_I2SMICSP_COMP_PARAM_1                                             0x5259
#घोषणा mmACP_I2SMICSP_COMP_VERSION                                             0x525a
#घोषणा mmACP_I2SMICSP_COMP_TYPE                                                0x525b
#घोषणा mmACP_I2SBT_IER                                                         0x525c
#घोषणा mmACP_I2SBT_IRER                                                        0x525d
#घोषणा mmACP_I2SBT_ITER                                                        0x525e
#घोषणा mmACP_I2SBT_CER                                                         0x525f
#घोषणा mmACP_I2SBT_CCR                                                         0x5260
#घोषणा mmACP_I2SBT_RXFFR                                                       0x5261
#घोषणा mmACP_I2SBT_TXFFR                                                       0x5262
#घोषणा mmACP_I2SBT_LRBR0                                                       0x5264
#घोषणा mmACP_I2SBT_RRBR0                                                       0x5265
#घोषणा mmACP_I2SBT_RER0                                                        0x5266
#घोषणा mmACP_I2SBT_TER0                                                        0x5267
#घोषणा mmACP_I2SBT_RCR0                                                        0x5268
#घोषणा mmACP_I2SBT_TCR0                                                        0x5269
#घोषणा mmACP_I2SBT_ISR0                                                        0x526a
#घोषणा mmACP_I2SBT_IMR0                                                        0x526b
#घोषणा mmACP_I2SBT_ROR0                                                        0x526c
#घोषणा mmACP_I2SBT_TOR0                                                        0x526d
#घोषणा mmACP_I2SBT_RFCR0                                                       0x526e
#घोषणा mmACP_I2SBT_TFCR0                                                       0x526f
#घोषणा mmACP_I2SBT_RFF0                                                        0x5270
#घोषणा mmACP_I2SBT_TFF0                                                        0x5271
#घोषणा mmACP_I2SBT_LRBR1                                                       0x5274
#घोषणा mmACP_I2SBT_RRBR1                                                       0x5275
#घोषणा mmACP_I2SBT_RER1                                                        0x5276
#घोषणा mmACP_I2SBT_TER1                                                        0x5277
#घोषणा mmACP_I2SBT_RCR1                                                        0x5278
#घोषणा mmACP_I2SBT_TCR1                                                        0x5279
#घोषणा mmACP_I2SBT_ISR1                                                        0x527a
#घोषणा mmACP_I2SBT_IMR1                                                        0x527b
#घोषणा mmACP_I2SBT_ROR1                                                        0x527c
#घोषणा mmACP_I2SBT_TOR1                                                        0x527d
#घोषणा mmACP_I2SBT_RFCR1                                                       0x527e
#घोषणा mmACP_I2SBT_TFCR1                                                       0x527f
#घोषणा mmACP_I2SBT_RFF1                                                        0x5280
#घोषणा mmACP_I2SBT_TFF1                                                        0x5281
#घोषणा mmACP_I2SBT_RXDMA                                                       0x5282
#घोषणा mmACP_I2SBT_RRXDMA                                                      0x5283
#घोषणा mmACP_I2SBT_TXDMA                                                       0x5284
#घोषणा mmACP_I2SBT_RTXDMA                                                      0x5285
#घोषणा mmACP_I2SBT_COMP_PARAM_2                                                0x5286
#घोषणा mmACP_I2SBT_COMP_PARAM_1                                                0x5287
#घोषणा mmACP_I2SBT_COMP_VERSION                                                0x5288
#घोषणा mmACP_I2SBT_COMP_TYPE                                                   0x5289

#पूर्ण_अगर /* ACP_2_2_D_H */
