<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
/*
 * This header provides स्थिरants क्रम binding nvidia,tegra124-soctherm.
 */

#अगर_अघोषित _DT_BINDINGS_THERMAL_TEGRA124_SOCTHERM_H
#घोषणा _DT_BINDINGS_THERMAL_TEGRA124_SOCTHERM_H

#घोषणा TEGRA124_SOCTHERM_SENSOR_CPU 0
#घोषणा TEGRA124_SOCTHERM_SENSOR_MEM 1
#घोषणा TEGRA124_SOCTHERM_SENSOR_GPU 2
#घोषणा TEGRA124_SOCTHERM_SENSOR_PLLX 3
#घोषणा TEGRA124_SOCTHERM_SENSOR_NUM 4

#घोषणा TEGRA_SOCTHERM_THROT_LEVEL_NONE 0
#घोषणा TEGRA_SOCTHERM_THROT_LEVEL_LOW  1
#घोषणा TEGRA_SOCTHERM_THROT_LEVEL_MED  2
#घोषणा TEGRA_SOCTHERM_THROT_LEVEL_HIGH 3

#पूर्ण_अगर
