<शैली गुरु>
/*
 * Copyright (C) 2020  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, मुक्त of अक्षरge, to any person obtaining a
 * copy of this software and associated करोcumentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modअगरy, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to करो so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#अगर_अघोषित _mp_11_5_0_OFFSET_HEADER
#घोषणा _mp_11_5_0_OFFSET_HEADER



// addressBlock: mp_SmuMp0_SmnDec
// base address: 0x0
#घोषणा mmMP0_SMN_C2PMSG_32                                                                            0x0060
#घोषणा mmMP0_SMN_C2PMSG_32_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_33                                                                            0x0061
#घोषणा mmMP0_SMN_C2PMSG_33_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_34                                                                            0x0062
#घोषणा mmMP0_SMN_C2PMSG_34_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_35                                                                            0x0063
#घोषणा mmMP0_SMN_C2PMSG_35_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_36                                                                            0x0064
#घोषणा mmMP0_SMN_C2PMSG_36_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_37                                                                            0x0065
#घोषणा mmMP0_SMN_C2PMSG_37_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_38                                                                            0x0066
#घोषणा mmMP0_SMN_C2PMSG_38_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_39                                                                            0x0067
#घोषणा mmMP0_SMN_C2PMSG_39_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_40                                                                            0x0068
#घोषणा mmMP0_SMN_C2PMSG_40_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_41                                                                            0x0069
#घोषणा mmMP0_SMN_C2PMSG_41_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_42                                                                            0x006a
#घोषणा mmMP0_SMN_C2PMSG_42_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_43                                                                            0x006b
#घोषणा mmMP0_SMN_C2PMSG_43_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_44                                                                            0x006c
#घोषणा mmMP0_SMN_C2PMSG_44_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_45                                                                            0x006d
#घोषणा mmMP0_SMN_C2PMSG_45_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_46                                                                            0x006e
#घोषणा mmMP0_SMN_C2PMSG_46_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_47                                                                            0x006f
#घोषणा mmMP0_SMN_C2PMSG_47_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_48                                                                            0x0070
#घोषणा mmMP0_SMN_C2PMSG_48_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_49                                                                            0x0071
#घोषणा mmMP0_SMN_C2PMSG_49_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_50                                                                            0x0072
#घोषणा mmMP0_SMN_C2PMSG_50_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_51                                                                            0x0073
#घोषणा mmMP0_SMN_C2PMSG_51_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_52                                                                            0x0074
#घोषणा mmMP0_SMN_C2PMSG_52_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_53                                                                            0x0075
#घोषणा mmMP0_SMN_C2PMSG_53_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_54                                                                            0x0076
#घोषणा mmMP0_SMN_C2PMSG_54_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_55                                                                            0x0077
#घोषणा mmMP0_SMN_C2PMSG_55_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_56                                                                            0x0078
#घोषणा mmMP0_SMN_C2PMSG_56_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_57                                                                            0x0079
#घोषणा mmMP0_SMN_C2PMSG_57_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_58                                                                            0x007a
#घोषणा mmMP0_SMN_C2PMSG_58_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_59                                                                            0x007b
#घोषणा mmMP0_SMN_C2PMSG_59_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_60                                                                            0x007c
#घोषणा mmMP0_SMN_C2PMSG_60_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_61                                                                            0x007d
#घोषणा mmMP0_SMN_C2PMSG_61_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_62                                                                            0x007e
#घोषणा mmMP0_SMN_C2PMSG_62_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_63                                                                            0x007f
#घोषणा mmMP0_SMN_C2PMSG_63_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_64                                                                            0x0080
#घोषणा mmMP0_SMN_C2PMSG_64_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_65                                                                            0x0081
#घोषणा mmMP0_SMN_C2PMSG_65_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_66                                                                            0x0082
#घोषणा mmMP0_SMN_C2PMSG_66_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_67                                                                            0x0083
#घोषणा mmMP0_SMN_C2PMSG_67_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_68                                                                            0x0084
#घोषणा mmMP0_SMN_C2PMSG_68_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_69                                                                            0x0085
#घोषणा mmMP0_SMN_C2PMSG_69_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_70                                                                            0x0086
#घोषणा mmMP0_SMN_C2PMSG_70_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_71                                                                            0x0087
#घोषणा mmMP0_SMN_C2PMSG_71_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_72                                                                            0x0088
#घोषणा mmMP0_SMN_C2PMSG_72_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_73                                                                            0x0089
#घोषणा mmMP0_SMN_C2PMSG_73_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_74                                                                            0x008a
#घोषणा mmMP0_SMN_C2PMSG_74_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_75                                                                            0x008b
#घोषणा mmMP0_SMN_C2PMSG_75_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_76                                                                            0x008c
#घोषणा mmMP0_SMN_C2PMSG_76_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_77                                                                            0x008d
#घोषणा mmMP0_SMN_C2PMSG_77_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_78                                                                            0x008e
#घोषणा mmMP0_SMN_C2PMSG_78_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_79                                                                            0x008f
#घोषणा mmMP0_SMN_C2PMSG_79_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_80                                                                            0x0090
#घोषणा mmMP0_SMN_C2PMSG_80_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_81                                                                            0x0091
#घोषणा mmMP0_SMN_C2PMSG_81_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_82                                                                            0x0092
#घोषणा mmMP0_SMN_C2PMSG_82_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_83                                                                            0x0093
#घोषणा mmMP0_SMN_C2PMSG_83_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_84                                                                            0x0094
#घोषणा mmMP0_SMN_C2PMSG_84_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_85                                                                            0x0095
#घोषणा mmMP0_SMN_C2PMSG_85_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_86                                                                            0x0096
#घोषणा mmMP0_SMN_C2PMSG_86_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_87                                                                            0x0097
#घोषणा mmMP0_SMN_C2PMSG_87_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_88                                                                            0x0098
#घोषणा mmMP0_SMN_C2PMSG_88_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_89                                                                            0x0099
#घोषणा mmMP0_SMN_C2PMSG_89_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_90                                                                            0x009a
#घोषणा mmMP0_SMN_C2PMSG_90_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_91                                                                            0x009b
#घोषणा mmMP0_SMN_C2PMSG_91_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_92                                                                            0x009c
#घोषणा mmMP0_SMN_C2PMSG_92_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_93                                                                            0x009d
#घोषणा mmMP0_SMN_C2PMSG_93_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_94                                                                            0x009e
#घोषणा mmMP0_SMN_C2PMSG_94_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_95                                                                            0x009f
#घोषणा mmMP0_SMN_C2PMSG_95_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_96                                                                            0x00a0
#घोषणा mmMP0_SMN_C2PMSG_96_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_97                                                                            0x00a1
#घोषणा mmMP0_SMN_C2PMSG_97_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_98                                                                            0x00a2
#घोषणा mmMP0_SMN_C2PMSG_98_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_99                                                                            0x00a3
#घोषणा mmMP0_SMN_C2PMSG_99_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_C2PMSG_100                                                                           0x00a4
#घोषणा mmMP0_SMN_C2PMSG_100_BASE_IDX                                                                  0
#घोषणा mmMP0_SMN_C2PMSG_101                                                                           0x00a5
#घोषणा mmMP0_SMN_C2PMSG_101_BASE_IDX                                                                  0
#घोषणा mmMP0_SMN_C2PMSG_102                                                                           0x00a6
#घोषणा mmMP0_SMN_C2PMSG_102_BASE_IDX                                                                  0
#घोषणा mmMP0_SMN_C2PMSG_103                                                                           0x00a7
#घोषणा mmMP0_SMN_C2PMSG_103_BASE_IDX                                                                  0
#घोषणा mmMP0_SMN_IH_CREDIT                                                                            0x00c1
#घोषणा mmMP0_SMN_IH_CREDIT_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_IH_SW_INT                                                                            0x00c2
#घोषणा mmMP0_SMN_IH_SW_INT_BASE_IDX                                                                   0
#घोषणा mmMP0_SMN_IH_SW_INT_CTRL                                                                       0x00c3
#घोषणा mmMP0_SMN_IH_SW_INT_CTRL_BASE_IDX                                                              0


// addressBlock: mp_SmuMp1_SmnDec
// base address: 0x0
#घोषणा mmMP1_SMN_C2PMSG_32                                                                            0x0260
#घोषणा mmMP1_SMN_C2PMSG_32_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_33                                                                            0x0261
#घोषणा mmMP1_SMN_C2PMSG_33_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_34                                                                            0x0262
#घोषणा mmMP1_SMN_C2PMSG_34_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_35                                                                            0x0263
#घोषणा mmMP1_SMN_C2PMSG_35_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_36                                                                            0x0264
#घोषणा mmMP1_SMN_C2PMSG_36_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_37                                                                            0x0265
#घोषणा mmMP1_SMN_C2PMSG_37_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_38                                                                            0x0266
#घोषणा mmMP1_SMN_C2PMSG_38_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_39                                                                            0x0267
#घोषणा mmMP1_SMN_C2PMSG_39_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_40                                                                            0x0268
#घोषणा mmMP1_SMN_C2PMSG_40_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_41                                                                            0x0269
#घोषणा mmMP1_SMN_C2PMSG_41_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_42                                                                            0x026a
#घोषणा mmMP1_SMN_C2PMSG_42_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_43                                                                            0x026b
#घोषणा mmMP1_SMN_C2PMSG_43_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_44                                                                            0x026c
#घोषणा mmMP1_SMN_C2PMSG_44_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_45                                                                            0x026d
#घोषणा mmMP1_SMN_C2PMSG_45_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_46                                                                            0x026e
#घोषणा mmMP1_SMN_C2PMSG_46_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_47                                                                            0x026f
#घोषणा mmMP1_SMN_C2PMSG_47_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_48                                                                            0x0270
#घोषणा mmMP1_SMN_C2PMSG_48_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_49                                                                            0x0271
#घोषणा mmMP1_SMN_C2PMSG_49_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_50                                                                            0x0272
#घोषणा mmMP1_SMN_C2PMSG_50_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_51                                                                            0x0273
#घोषणा mmMP1_SMN_C2PMSG_51_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_52                                                                            0x0274
#घोषणा mmMP1_SMN_C2PMSG_52_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_53                                                                            0x0275
#घोषणा mmMP1_SMN_C2PMSG_53_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_54                                                                            0x0276
#घोषणा mmMP1_SMN_C2PMSG_54_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_55                                                                            0x0277
#घोषणा mmMP1_SMN_C2PMSG_55_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_56                                                                            0x0278
#घोषणा mmMP1_SMN_C2PMSG_56_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_57                                                                            0x0279
#घोषणा mmMP1_SMN_C2PMSG_57_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_58                                                                            0x027a
#घोषणा mmMP1_SMN_C2PMSG_58_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_59                                                                            0x027b
#घोषणा mmMP1_SMN_C2PMSG_59_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_60                                                                            0x027c
#घोषणा mmMP1_SMN_C2PMSG_60_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_61                                                                            0x027d
#घोषणा mmMP1_SMN_C2PMSG_61_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_62                                                                            0x027e
#घोषणा mmMP1_SMN_C2PMSG_62_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_63                                                                            0x027f
#घोषणा mmMP1_SMN_C2PMSG_63_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_64                                                                            0x0280
#घोषणा mmMP1_SMN_C2PMSG_64_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_65                                                                            0x0281
#घोषणा mmMP1_SMN_C2PMSG_65_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_66                                                                            0x0282
#घोषणा mmMP1_SMN_C2PMSG_66_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_67                                                                            0x0283
#घोषणा mmMP1_SMN_C2PMSG_67_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_68                                                                            0x0284
#घोषणा mmMP1_SMN_C2PMSG_68_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_69                                                                            0x0285
#घोषणा mmMP1_SMN_C2PMSG_69_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_70                                                                            0x0286
#घोषणा mmMP1_SMN_C2PMSG_70_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_71                                                                            0x0287
#घोषणा mmMP1_SMN_C2PMSG_71_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_72                                                                            0x0288
#घोषणा mmMP1_SMN_C2PMSG_72_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_73                                                                            0x0289
#घोषणा mmMP1_SMN_C2PMSG_73_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_74                                                                            0x028a
#घोषणा mmMP1_SMN_C2PMSG_74_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_75                                                                            0x028b
#घोषणा mmMP1_SMN_C2PMSG_75_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_76                                                                            0x028c
#घोषणा mmMP1_SMN_C2PMSG_76_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_77                                                                            0x028d
#घोषणा mmMP1_SMN_C2PMSG_77_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_78                                                                            0x028e
#घोषणा mmMP1_SMN_C2PMSG_78_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_79                                                                            0x028f
#घोषणा mmMP1_SMN_C2PMSG_79_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_80                                                                            0x0290
#घोषणा mmMP1_SMN_C2PMSG_80_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_81                                                                            0x0291
#घोषणा mmMP1_SMN_C2PMSG_81_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_82                                                                            0x0292
#घोषणा mmMP1_SMN_C2PMSG_82_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_83                                                                            0x0293
#घोषणा mmMP1_SMN_C2PMSG_83_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_84                                                                            0x0294
#घोषणा mmMP1_SMN_C2PMSG_84_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_85                                                                            0x0295
#घोषणा mmMP1_SMN_C2PMSG_85_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_86                                                                            0x0296
#घोषणा mmMP1_SMN_C2PMSG_86_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_87                                                                            0x0297
#घोषणा mmMP1_SMN_C2PMSG_87_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_88                                                                            0x0298
#घोषणा mmMP1_SMN_C2PMSG_88_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_89                                                                            0x0299
#घोषणा mmMP1_SMN_C2PMSG_89_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_90                                                                            0x029a
#घोषणा mmMP1_SMN_C2PMSG_90_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_91                                                                            0x029b
#घोषणा mmMP1_SMN_C2PMSG_91_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_92                                                                            0x029c
#घोषणा mmMP1_SMN_C2PMSG_92_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_93                                                                            0x029d
#घोषणा mmMP1_SMN_C2PMSG_93_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_94                                                                            0x029e
#घोषणा mmMP1_SMN_C2PMSG_94_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_95                                                                            0x029f
#घोषणा mmMP1_SMN_C2PMSG_95_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_96                                                                            0x02a0
#घोषणा mmMP1_SMN_C2PMSG_96_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_97                                                                            0x02a1
#घोषणा mmMP1_SMN_C2PMSG_97_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_98                                                                            0x02a2
#घोषणा mmMP1_SMN_C2PMSG_98_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_99                                                                            0x02a3
#घोषणा mmMP1_SMN_C2PMSG_99_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_C2PMSG_100                                                                           0x02a4
#घोषणा mmMP1_SMN_C2PMSG_100_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_101                                                                           0x02a5
#घोषणा mmMP1_SMN_C2PMSG_101_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_102                                                                           0x02a6
#घोषणा mmMP1_SMN_C2PMSG_102_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_103                                                                           0x02a7
#घोषणा mmMP1_SMN_C2PMSG_103_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_104                                                                           0x02a8
#घोषणा mmMP1_SMN_C2PMSG_104_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_105                                                                           0x02a9
#घोषणा mmMP1_SMN_C2PMSG_105_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_106                                                                           0x02aa
#घोषणा mmMP1_SMN_C2PMSG_106_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_107                                                                           0x02ab
#घोषणा mmMP1_SMN_C2PMSG_107_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_108                                                                           0x02ac
#घोषणा mmMP1_SMN_C2PMSG_108_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_109                                                                           0x02ad
#घोषणा mmMP1_SMN_C2PMSG_109_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_110                                                                           0x02ae
#घोषणा mmMP1_SMN_C2PMSG_110_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_111                                                                           0x02af
#घोषणा mmMP1_SMN_C2PMSG_111_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_112                                                                           0x02b0
#घोषणा mmMP1_SMN_C2PMSG_112_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_113                                                                           0x02b1
#घोषणा mmMP1_SMN_C2PMSG_113_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_114                                                                           0x02b2
#घोषणा mmMP1_SMN_C2PMSG_114_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_115                                                                           0x02b3
#घोषणा mmMP1_SMN_C2PMSG_115_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_116                                                                           0x02b4
#घोषणा mmMP1_SMN_C2PMSG_116_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_117                                                                           0x02b5
#घोषणा mmMP1_SMN_C2PMSG_117_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_118                                                                           0x02b6
#घोषणा mmMP1_SMN_C2PMSG_118_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_119                                                                           0x02b7
#घोषणा mmMP1_SMN_C2PMSG_119_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_120                                                                           0x02b8
#घोषणा mmMP1_SMN_C2PMSG_120_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_121                                                                           0x02b9
#घोषणा mmMP1_SMN_C2PMSG_121_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_122                                                                           0x02ba
#घोषणा mmMP1_SMN_C2PMSG_122_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_123                                                                           0x02bb
#घोषणा mmMP1_SMN_C2PMSG_123_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_124                                                                           0x02bc
#घोषणा mmMP1_SMN_C2PMSG_124_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_125                                                                           0x02bd
#घोषणा mmMP1_SMN_C2PMSG_125_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_126                                                                           0x02be
#घोषणा mmMP1_SMN_C2PMSG_126_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_C2PMSG_127                                                                           0x02bf
#घोषणा mmMP1_SMN_C2PMSG_127_BASE_IDX                                                                  0
#घोषणा mmMP1_SMN_IH_CREDIT                                                                            0x02c1
#घोषणा mmMP1_SMN_IH_CREDIT_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_IH_SW_INT                                                                            0x02c2
#घोषणा mmMP1_SMN_IH_SW_INT_BASE_IDX                                                                   0
#घोषणा mmMP1_SMN_IH_SW_INT_CTRL                                                                       0x02c3
#घोषणा mmMP1_SMN_IH_SW_INT_CTRL_BASE_IDX                                                              0
#घोषणा mmMP1_SMN_FPS_CNT                                                                              0x02c4
#घोषणा mmMP1_SMN_FPS_CNT_BASE_IDX                                                                     0
#घोषणा mmMP1_SMN_EXT_SCRATCH0                                                                         0x03c0
#घोषणा mmMP1_SMN_EXT_SCRATCH0_BASE_IDX                                                                0
#घोषणा mmMP1_SMN_EXT_SCRATCH1                                                                         0x03c1
#घोषणा mmMP1_SMN_EXT_SCRATCH1_BASE_IDX                                                                0
#घोषणा mmMP1_SMN_EXT_SCRATCH2                                                                         0x03c2
#घोषणा mmMP1_SMN_EXT_SCRATCH2_BASE_IDX                                                                0
#घोषणा mmMP1_SMN_EXT_SCRATCH3                                                                         0x03c3
#घोषणा mmMP1_SMN_EXT_SCRATCH3_BASE_IDX                                                                0
#घोषणा mmMP1_SMN_EXT_SCRATCH4                                                                         0x03c4
#घोषणा mmMP1_SMN_EXT_SCRATCH4_BASE_IDX                                                                0
#घोषणा mmMP1_SMN_EXT_SCRATCH5                                                                         0x03c5
#घोषणा mmMP1_SMN_EXT_SCRATCH5_BASE_IDX                                                                0
#घोषणा mmMP1_SMN_EXT_SCRATCH6                                                                         0x03c6
#घोषणा mmMP1_SMN_EXT_SCRATCH6_BASE_IDX                                                                0
#घोषणा mmMP1_SMN_EXT_SCRATCH7                                                                         0x03c7
#घोषणा mmMP1_SMN_EXT_SCRATCH7_BASE_IDX                                                                0


#पूर्ण_अगर
