<शैली गुरु>
/*
 * Copyright 2012-15 Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, मुक्त of अक्षरge, to any person obtaining a
 * copy of this software and associated करोcumentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modअगरy, merge, publish, distribute, sublicense,
 *  and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to करो so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) OR AUTHOR(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * Authors: AMD
 *
 */

#अगर_अघोषित __DC_STREAM_ENCODER_DCE110_H__
#घोषणा __DC_STREAM_ENCODER_DCE110_H__

#समावेश "stream_encoder.h"

#घोषणा DCE110STRENC_FROM_STRENC(stream_encoder)\
	container_of(stream_encoder, काष्ठा dce110_stream_encoder, base)

#अगर_अघोषित TMDS_CNTL__TMDS_PIXEL_ENCODING_MASK
	#घोषणा TMDS_CNTL__TMDS_PIXEL_ENCODING_MASK       0x00000010L
	#घोषणा TMDS_CNTL__TMDS_COLOR_FORMAT_MASK         0x00000300L
	#घोषणा	TMDS_CNTL__TMDS_PIXEL_ENCODING__SHIFT     0x00000004
	#घोषणा	TMDS_CNTL__TMDS_COLOR_FORMAT__SHIFT       0x00000008
#पूर्ण_अगर


#घोषणा SE_COMMON_REG_LIST_DCE_BASE(id) \
	SE_COMMON_REG_LIST_BASE(id),\
	SRI(AFMT_AVI_INFO0, DIG, id), \
	SRI(AFMT_AVI_INFO1, DIG, id), \
	SRI(AFMT_AVI_INFO2, DIG, id), \
	SRI(AFMT_AVI_INFO3, DIG, id)

#घोषणा SE_COMMON_REG_LIST_BASE(id) \
	SRI(AFMT_GENERIC_0, DIG, id), \
	SRI(AFMT_GENERIC_1, DIG, id), \
	SRI(AFMT_GENERIC_2, DIG, id), \
	SRI(AFMT_GENERIC_3, DIG, id), \
	SRI(AFMT_GENERIC_4, DIG, id), \
	SRI(AFMT_GENERIC_5, DIG, id), \
	SRI(AFMT_GENERIC_6, DIG, id), \
	SRI(AFMT_GENERIC_7, DIG, id), \
	SRI(AFMT_GENERIC_HDR, DIG, id), \
	SRI(AFMT_INFOFRAME_CONTROL0, DIG, id), \
	SRI(AFMT_VBI_PACKET_CONTROL, DIG, id), \
	SRI(AFMT_AUDIO_PACKET_CONTROL, DIG, id), \
	SRI(AFMT_AUDIO_PACKET_CONTROL2, DIG, id), \
	SRI(AFMT_AUDIO_SRC_CONTROL, DIG, id), \
	SRI(AFMT_60958_0, DIG, id), \
	SRI(AFMT_60958_1, DIG, id), \
	SRI(AFMT_60958_2, DIG, id), \
	SRI(DIG_FE_CNTL, DIG, id), \
	SRI(HDMI_CONTROL, DIG, id), \
	SRI(HDMI_GC, DIG, id), \
	SRI(HDMI_GENERIC_PACKET_CONTROL0, DIG, id), \
	SRI(HDMI_GENERIC_PACKET_CONTROL1, DIG, id), \
	SRI(HDMI_INFOFRAME_CONTROL0, DIG, id), \
	SRI(HDMI_INFOFRAME_CONTROL1, DIG, id), \
	SRI(HDMI_VBI_PACKET_CONTROL, DIG, id), \
	SRI(HDMI_AUDIO_PACKET_CONTROL, DIG, id),\
	SRI(HDMI_ACR_PACKET_CONTROL, DIG, id),\
	SRI(HDMI_ACR_32_0, DIG, id),\
	SRI(HDMI_ACR_32_1, DIG, id),\
	SRI(HDMI_ACR_44_0, DIG, id),\
	SRI(HDMI_ACR_44_1, DIG, id),\
	SRI(HDMI_ACR_48_0, DIG, id),\
	SRI(HDMI_ACR_48_1, DIG, id),\
	SRI(TMDS_CNTL, DIG, id), \
	SRI(DP_MSE_RATE_CNTL, DP, id), \
	SRI(DP_MSE_RATE_UPDATE, DP, id), \
	SRI(DP_PIXEL_FORMAT, DP, id), \
	SRI(DP_SEC_CNTL, DP, id), \
	SRI(DP_STEER_FIFO, DP, id), \
	SRI(DP_VID_M, DP, id), \
	SRI(DP_VID_N, DP, id), \
	SRI(DP_VID_STREAM_CNTL, DP, id), \
	SRI(DP_VID_TIMING, DP, id), \
	SRI(DP_SEC_AUD_N, DP, id), \
	SRI(DP_SEC_TIMESTAMP, DP, id)

#घोषणा SE_COMMON_REG_LIST(id)\
	SE_COMMON_REG_LIST_DCE_BASE(id), \
	SRI(AFMT_CNTL, DIG, id)

#घोषणा SE_DCN_REG_LIST(id)\
	SE_COMMON_REG_LIST_BASE(id),\
	SRI(AFMT_CNTL, DIG, id),\
	SRI(AFMT_VBI_PACKET_CONTROL1, DIG, id),\
	SRI(HDMI_GENERIC_PACKET_CONTROL2, DIG, id), \
	SRI(HDMI_GENERIC_PACKET_CONTROL3, DIG, id), \
	SRI(DP_DB_CNTL, DP, id), \
	SRI(DP_MSA_MISC, DP, id), \
	SRI(DP_MSA_COLORIMETRY, DP, id), \
	SRI(DP_MSA_TIMING_PARAM1, DP, id), \
	SRI(DP_MSA_TIMING_PARAM2, DP, id), \
	SRI(DP_MSA_TIMING_PARAM3, DP, id), \
	SRI(DP_MSA_TIMING_PARAM4, DP, id), \
	SRI(HDMI_DB_CONTROL, DIG, id)

#घोषणा SE_SF(reg_name, field_name, post_fix)\
	.field_name = reg_name ## __ ## field_name ## post_fix

#घोषणा SE_COMMON_MASK_SH_LIST_DCE_COMMON_BASE(mask_sh)\
	SE_SF(AFMT_VBI_PACKET_CONTROL, AFMT_GENERIC_INDEX, mask_sh),\
	SE_SF(AFMT_VBI_PACKET_CONTROL, AFMT_GENERIC0_UPDATE, mask_sh),\
	SE_SF(AFMT_VBI_PACKET_CONTROL, AFMT_GENERIC2_UPDATE, mask_sh),\
	SE_SF(AFMT_GENERIC_HDR, AFMT_GENERIC_HB0, mask_sh),\
	SE_SF(AFMT_GENERIC_HDR, AFMT_GENERIC_HB1, mask_sh),\
	SE_SF(AFMT_GENERIC_HDR, AFMT_GENERIC_HB2, mask_sh),\
	SE_SF(AFMT_GENERIC_HDR, AFMT_GENERIC_HB3, mask_sh),\
	SE_SF(HDMI_GENERIC_PACKET_CONTROL0, HDMI_GENERIC0_CONT, mask_sh),\
	SE_SF(HDMI_GENERIC_PACKET_CONTROL0, HDMI_GENERIC0_SEND, mask_sh),\
	SE_SF(HDMI_GENERIC_PACKET_CONTROL0, HDMI_GENERIC0_LINE, mask_sh),\
	SE_SF(HDMI_GENERIC_PACKET_CONTROL0, HDMI_GENERIC1_CONT, mask_sh),\
	SE_SF(HDMI_GENERIC_PACKET_CONTROL0, HDMI_GENERIC1_SEND, mask_sh),\
	SE_SF(HDMI_GENERIC_PACKET_CONTROL0, HDMI_GENERIC1_LINE, mask_sh),\
	SE_SF(DP_PIXEL_FORMAT, DP_PIXEL_ENCODING, mask_sh),\
	SE_SF(DP_PIXEL_FORMAT, DP_COMPONENT_DEPTH, mask_sh),\
	SE_SF(DP_PIXEL_FORMAT, DP_DYN_RANGE, mask_sh),\
	SE_SF(DP_PIXEL_FORMAT, DP_YCBCR_RANGE, mask_sh),\
	SE_SF(HDMI_CONTROL, HDMI_PACKET_GEN_VERSION, mask_sh),\
	SE_SF(HDMI_CONTROL, HDMI_KEEPOUT_MODE, mask_sh),\
	SE_SF(HDMI_CONTROL, HDMI_DEEP_COLOR_ENABLE, mask_sh),\
	SE_SF(HDMI_CONTROL, HDMI_DEEP_COLOR_DEPTH, mask_sh),\
	SE_SF(HDMI_VBI_PACKET_CONTROL, HDMI_GC_CONT, mask_sh),\
	SE_SF(HDMI_VBI_PACKET_CONTROL, HDMI_GC_SEND, mask_sh),\
	SE_SF(HDMI_VBI_PACKET_CONTROL, HDMI_शून्य_SEND, mask_sh),\
	SE_SF(HDMI_INFOFRAME_CONTROL0, HDMI_AUDIO_INFO_SEND, mask_sh),\
	SE_SF(AFMT_INFOFRAME_CONTROL0, AFMT_AUDIO_INFO_UPDATE, mask_sh),\
	SE_SF(HDMI_INFOFRAME_CONTROL1, HDMI_AUDIO_INFO_LINE, mask_sh),\
	SE_SF(HDMI_GC, HDMI_GC_AVMUTE, mask_sh),\
	SE_SF(DP_MSE_RATE_CNTL, DP_MSE_RATE_X, mask_sh),\
	SE_SF(DP_MSE_RATE_CNTL, DP_MSE_RATE_Y, mask_sh),\
	SE_SF(DP_MSE_RATE_UPDATE, DP_MSE_RATE_UPDATE_PENDING, mask_sh),\
	SE_SF(AFMT_AVI_INFO3, AFMT_AVI_INFO_VERSION, mask_sh),\
	SE_SF(HDMI_INFOFRAME_CONTROL0, HDMI_AVI_INFO_SEND, mask_sh),\
	SE_SF(HDMI_INFOFRAME_CONTROL0, HDMI_AVI_INFO_CONT, mask_sh),\
	SE_SF(HDMI_INFOFRAME_CONTROL1, HDMI_AVI_INFO_LINE, mask_sh),\
	SE_SF(DP_SEC_CNTL, DP_SEC_GSP0_ENABLE, mask_sh),\
	SE_SF(DP_SEC_CNTL, DP_SEC_STREAM_ENABLE, mask_sh),\
	SE_SF(DP_SEC_CNTL, DP_SEC_GSP1_ENABLE, mask_sh),\
	SE_SF(DP_SEC_CNTL, DP_SEC_GSP2_ENABLE, mask_sh),\
	SE_SF(DP_SEC_CNTL, DP_SEC_GSP3_ENABLE, mask_sh),\
	SE_SF(DP_SEC_CNTL, DP_SEC_AVI_ENABLE, mask_sh),\
	SE_SF(DP_SEC_CNTL, DP_SEC_MPG_ENABLE, mask_sh),\
	SE_SF(DP_VID_STREAM_CNTL, DP_VID_STREAM_DIS_DEFER, mask_sh),\
	SE_SF(DP_VID_STREAM_CNTL, DP_VID_STREAM_ENABLE, mask_sh),\
	SE_SF(DP_VID_STREAM_CNTL, DP_VID_STREAM_STATUS, mask_sh),\
	SE_SF(DP_STEER_FIFO, DP_STEER_FIFO_RESET, mask_sh),\
	SE_SF(DP_VID_TIMING, DP_VID_M_N_GEN_EN, mask_sh),\
	SE_SF(DP_VID_N, DP_VID_N, mask_sh),\
	SE_SF(DP_VID_M, DP_VID_M, mask_sh),\
	SE_SF(DIG_FE_CNTL, DIG_START, mask_sh),\
	SE_SF(DIG_FE_CNTL, DIG_STEREOSYNC_SELECT, mask_sh),\
	SE_SF(DIG_FE_CNTL, DIG_STEREOSYNC_GATE_EN, mask_sh),\
	SE_SF(AFMT_AUDIO_SRC_CONTROL, AFMT_AUDIO_SRC_SELECT, mask_sh),\
	SE_SF(AFMT_AUDIO_PACKET_CONTROL2, AFMT_AUDIO_CHANNEL_ENABLE, mask_sh),\
	SE_SF(HDMI_AUDIO_PACKET_CONTROL, HDMI_AUDIO_PACKETS_PER_LINE, mask_sh),\
	SE_SF(HDMI_AUDIO_PACKET_CONTROL, HDMI_AUDIO_DELAY_EN, mask_sh),\
	SE_SF(AFMT_AUDIO_PACKET_CONTROL, AFMT_60958_CS_UPDATE, mask_sh),\
	SE_SF(AFMT_AUDIO_PACKET_CONTROL2, AFMT_AUDIO_LAYOUT_OVRD, mask_sh),\
	SE_SF(AFMT_AUDIO_PACKET_CONTROL2, AFMT_60958_OSF_OVRD, mask_sh),\
	SE_SF(HDMI_ACR_PACKET_CONTROL, HDMI_ACR_AUTO_SEND, mask_sh),\
	SE_SF(HDMI_ACR_PACKET_CONTROL, HDMI_ACR_SOURCE, mask_sh),\
	SE_SF(HDMI_ACR_PACKET_CONTROL, HDMI_ACR_AUDIO_PRIORITY, mask_sh),\
	SE_SF(HDMI_ACR_32_0, HDMI_ACR_CTS_32, mask_sh),\
	SE_SF(HDMI_ACR_32_1, HDMI_ACR_N_32, mask_sh),\
	SE_SF(HDMI_ACR_44_0, HDMI_ACR_CTS_44, mask_sh),\
	SE_SF(HDMI_ACR_44_1, HDMI_ACR_N_44, mask_sh),\
	SE_SF(HDMI_ACR_48_0, HDMI_ACR_CTS_48, mask_sh),\
	SE_SF(HDMI_ACR_48_1, HDMI_ACR_N_48, mask_sh),\
	SE_SF(AFMT_60958_0, AFMT_60958_CS_CHANNEL_NUMBER_L, mask_sh),\
	SE_SF(AFMT_60958_0, AFMT_60958_CS_CLOCK_ACCURACY, mask_sh),\
	SE_SF(AFMT_60958_1, AFMT_60958_CS_CHANNEL_NUMBER_R, mask_sh),\
	SE_SF(AFMT_60958_2, AFMT_60958_CS_CHANNEL_NUMBER_2, mask_sh),\
	SE_SF(AFMT_60958_2, AFMT_60958_CS_CHANNEL_NUMBER_3, mask_sh),\
	SE_SF(AFMT_60958_2, AFMT_60958_CS_CHANNEL_NUMBER_4, mask_sh),\
	SE_SF(AFMT_60958_2, AFMT_60958_CS_CHANNEL_NUMBER_5, mask_sh),\
	SE_SF(AFMT_60958_2, AFMT_60958_CS_CHANNEL_NUMBER_6, mask_sh),\
	SE_SF(AFMT_60958_2, AFMT_60958_CS_CHANNEL_NUMBER_7, mask_sh),\
	SE_SF(DP_SEC_AUD_N, DP_SEC_AUD_N, mask_sh),\
	SE_SF(DP_SEC_TIMESTAMP, DP_SEC_TIMESTAMP_MODE, mask_sh),\
	SE_SF(DP_SEC_CNTL, DP_SEC_ASP_ENABLE, mask_sh),\
	SE_SF(DP_SEC_CNTL, DP_SEC_ATP_ENABLE, mask_sh),\
	SE_SF(DP_SEC_CNTL, DP_SEC_AIP_ENABLE, mask_sh),\
	SE_SF(DP_SEC_CNTL, DP_SEC_ACM_ENABLE, mask_sh),\
	SE_SF(AFMT_AUDIO_PACKET_CONTROL, AFMT_AUDIO_SAMPLE_SEND, mask_sh),\
	SE_SF(DIG_FE_CNTL, DIG_SOURCE_SELECT, mask_sh)

#घोषणा SE_COMMON_MASK_SH_LIST_DCE_COMMON(mask_sh)\
	SE_COMMON_MASK_SH_LIST_DCE_COMMON_BASE(mask_sh)

#घोषणा SE_COMMON_MASK_SH_LIST_SOC_BASE(mask_sh)\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL, AFMT_GENERIC_INDEX, mask_sh),\
	SE_SF(DIG0_AFMT_GENERIC_HDR, AFMT_GENERIC_HB0, mask_sh),\
	SE_SF(DIG0_AFMT_GENERIC_HDR, AFMT_GENERIC_HB1, mask_sh),\
	SE_SF(DIG0_AFMT_GENERIC_HDR, AFMT_GENERIC_HB2, mask_sh),\
	SE_SF(DIG0_AFMT_GENERIC_HDR, AFMT_GENERIC_HB3, mask_sh),\
	SE_SF(DIG0_HDMI_GENERIC_PACKET_CONTROL0, HDMI_GENERIC0_CONT, mask_sh),\
	SE_SF(DIG0_HDMI_GENERIC_PACKET_CONTROL0, HDMI_GENERIC0_SEND, mask_sh),\
	SE_SF(DIG0_HDMI_GENERIC_PACKET_CONTROL0, HDMI_GENERIC0_LINE, mask_sh),\
	SE_SF(DIG0_HDMI_GENERIC_PACKET_CONTROL0, HDMI_GENERIC1_CONT, mask_sh),\
	SE_SF(DIG0_HDMI_GENERIC_PACKET_CONTROL0, HDMI_GENERIC1_SEND, mask_sh),\
	SE_SF(DIG0_HDMI_GENERIC_PACKET_CONTROL0, HDMI_GENERIC1_LINE, mask_sh),\
	SE_SF(DP0_DP_PIXEL_FORMAT, DP_PIXEL_ENCODING, mask_sh),\
	SE_SF(DP0_DP_PIXEL_FORMAT, DP_COMPONENT_DEPTH, mask_sh),\
	SE_SF(DIG0_HDMI_CONTROL, HDMI_PACKET_GEN_VERSION, mask_sh),\
	SE_SF(DIG0_HDMI_CONTROL, HDMI_KEEPOUT_MODE, mask_sh),\
	SE_SF(DIG0_HDMI_CONTROL, HDMI_DEEP_COLOR_ENABLE, mask_sh),\
	SE_SF(DIG0_HDMI_CONTROL, HDMI_DEEP_COLOR_DEPTH, mask_sh),\
	SE_SF(DIG0_HDMI_CONTROL, HDMI_DATA_SCRAMBLE_EN, mask_sh),\
	SE_SF(DIG0_HDMI_VBI_PACKET_CONTROL, HDMI_GC_CONT, mask_sh),\
	SE_SF(DIG0_HDMI_VBI_PACKET_CONTROL, HDMI_GC_SEND, mask_sh),\
	SE_SF(DIG0_HDMI_VBI_PACKET_CONTROL, HDMI_शून्य_SEND, mask_sh),\
	SE_SF(DIG0_HDMI_INFOFRAME_CONTROL0, HDMI_AUDIO_INFO_SEND, mask_sh),\
	SE_SF(DIG0_AFMT_INFOFRAME_CONTROL0, AFMT_AUDIO_INFO_UPDATE, mask_sh),\
	SE_SF(DIG0_HDMI_INFOFRAME_CONTROL1, HDMI_AUDIO_INFO_LINE, mask_sh),\
	SE_SF(DIG0_HDMI_GC, HDMI_GC_AVMUTE, mask_sh),\
	SE_SF(DP0_DP_MSE_RATE_CNTL, DP_MSE_RATE_X, mask_sh),\
	SE_SF(DP0_DP_MSE_RATE_CNTL, DP_MSE_RATE_Y, mask_sh),\
	SE_SF(DP0_DP_MSE_RATE_UPDATE, DP_MSE_RATE_UPDATE_PENDING, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_GSP0_ENABLE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_STREAM_ENABLE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_GSP1_ENABLE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_GSP2_ENABLE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_GSP3_ENABLE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_MPG_ENABLE, mask_sh),\
	SE_SF(DP0_DP_VID_STREAM_CNTL, DP_VID_STREAM_DIS_DEFER, mask_sh),\
	SE_SF(DP0_DP_VID_STREAM_CNTL, DP_VID_STREAM_ENABLE, mask_sh),\
	SE_SF(DP0_DP_VID_STREAM_CNTL, DP_VID_STREAM_STATUS, mask_sh),\
	SE_SF(DP0_DP_STEER_FIFO, DP_STEER_FIFO_RESET, mask_sh),\
	SE_SF(DP0_DP_VID_TIMING, DP_VID_M_N_GEN_EN, mask_sh),\
	SE_SF(DP0_DP_VID_N, DP_VID_N, mask_sh),\
	SE_SF(DP0_DP_VID_M, DP_VID_M, mask_sh),\
	SE_SF(DIG0_DIG_FE_CNTL, DIG_START, mask_sh),\
	SE_SF(DIG0_AFMT_AUDIO_SRC_CONTROL, AFMT_AUDIO_SRC_SELECT, mask_sh),\
	SE_SF(DIG0_AFMT_AUDIO_PACKET_CONTROL2, AFMT_AUDIO_CHANNEL_ENABLE, mask_sh),\
	SE_SF(DIG0_HDMI_AUDIO_PACKET_CONTROL, HDMI_AUDIO_PACKETS_PER_LINE, mask_sh),\
	SE_SF(DIG0_HDMI_AUDIO_PACKET_CONTROL, HDMI_AUDIO_DELAY_EN, mask_sh),\
	SE_SF(DIG0_AFMT_AUDIO_PACKET_CONTROL, AFMT_60958_CS_UPDATE, mask_sh),\
	SE_SF(DIG0_AFMT_AUDIO_PACKET_CONTROL2, AFMT_AUDIO_LAYOUT_OVRD, mask_sh),\
	SE_SF(DIG0_AFMT_AUDIO_PACKET_CONTROL2, AFMT_60958_OSF_OVRD, mask_sh),\
	SE_SF(DIG0_HDMI_ACR_PACKET_CONTROL, HDMI_ACR_AUTO_SEND, mask_sh),\
	SE_SF(DIG0_HDMI_ACR_PACKET_CONTROL, HDMI_ACR_SOURCE, mask_sh),\
	SE_SF(DIG0_HDMI_ACR_PACKET_CONTROL, HDMI_ACR_AUDIO_PRIORITY, mask_sh),\
	SE_SF(DIG0_HDMI_ACR_32_0, HDMI_ACR_CTS_32, mask_sh),\
	SE_SF(DIG0_HDMI_ACR_32_1, HDMI_ACR_N_32, mask_sh),\
	SE_SF(DIG0_HDMI_ACR_44_0, HDMI_ACR_CTS_44, mask_sh),\
	SE_SF(DIG0_HDMI_ACR_44_1, HDMI_ACR_N_44, mask_sh),\
	SE_SF(DIG0_HDMI_ACR_48_0, HDMI_ACR_CTS_48, mask_sh),\
	SE_SF(DIG0_HDMI_ACR_48_1, HDMI_ACR_N_48, mask_sh),\
	SE_SF(DIG0_AFMT_60958_0, AFMT_60958_CS_CHANNEL_NUMBER_L, mask_sh),\
	SE_SF(DIG0_AFMT_60958_0, AFMT_60958_CS_CLOCK_ACCURACY, mask_sh),\
	SE_SF(DIG0_AFMT_60958_1, AFMT_60958_CS_CHANNEL_NUMBER_R, mask_sh),\
	SE_SF(DIG0_AFMT_60958_2, AFMT_60958_CS_CHANNEL_NUMBER_2, mask_sh),\
	SE_SF(DIG0_AFMT_60958_2, AFMT_60958_CS_CHANNEL_NUMBER_3, mask_sh),\
	SE_SF(DIG0_AFMT_60958_2, AFMT_60958_CS_CHANNEL_NUMBER_4, mask_sh),\
	SE_SF(DIG0_AFMT_60958_2, AFMT_60958_CS_CHANNEL_NUMBER_5, mask_sh),\
	SE_SF(DIG0_AFMT_60958_2, AFMT_60958_CS_CHANNEL_NUMBER_6, mask_sh),\
	SE_SF(DIG0_AFMT_60958_2, AFMT_60958_CS_CHANNEL_NUMBER_7, mask_sh),\
	SE_SF(DP0_DP_SEC_AUD_N, DP_SEC_AUD_N, mask_sh),\
	SE_SF(DP0_DP_SEC_TIMESTAMP, DP_SEC_TIMESTAMP_MODE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_ASP_ENABLE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_ATP_ENABLE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_AIP_ENABLE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_ACM_ENABLE, mask_sh),\
	SE_SF(DIG0_AFMT_AUDIO_PACKET_CONTROL, AFMT_AUDIO_SAMPLE_SEND, mask_sh),\
	SE_SF(DIG0_AFMT_CNTL, AFMT_AUDIO_CLOCK_EN, mask_sh),\
	SE_SF(DIG0_HDMI_CONTROL, HDMI_CLOCK_CHANNEL_RATE, mask_sh),\
	SE_SF(DIG0_DIG_FE_CNTL, TMDS_PIXEL_ENCODING, mask_sh),\
	SE_SF(DIG0_DIG_FE_CNTL, TMDS_COLOR_FORMAT, mask_sh),\
	SE_SF(DIG0_DIG_FE_CNTL, DIG_STEREOSYNC_SELECT, mask_sh),\
	SE_SF(DIG0_DIG_FE_CNTL, DIG_STEREOSYNC_GATE_EN, mask_sh),\
	SE_SF(DIG0_DIG_FE_CNTL, DIG_SOURCE_SELECT, mask_sh)

#घोषणा SE_COMMON_MASK_SH_LIST_SOC(mask_sh)\
	SE_COMMON_MASK_SH_LIST_SOC_BASE(mask_sh)

#घोषणा SE_COMMON_MASK_SH_LIST_DCE80_100(mask_sh)\
	SE_COMMON_MASK_SH_LIST_DCE_COMMON(mask_sh),\
	SE_SF(TMDS_CNTL, TMDS_PIXEL_ENCODING, mask_sh),\
	SE_SF(TMDS_CNTL, TMDS_COLOR_FORMAT, mask_sh)

#घोषणा SE_COMMON_MASK_SH_LIST_DCE110(mask_sh)\
	SE_COMMON_MASK_SH_LIST_DCE_COMMON(mask_sh),\
	SE_SF(AFMT_CNTL, AFMT_AUDIO_CLOCK_EN, mask_sh),\
	SE_SF(HDMI_CONTROL, HDMI_CLOCK_CHANNEL_RATE, mask_sh),\
	SE_SF(HDMI_CONTROL, HDMI_DATA_SCRAMBLE_EN, mask_sh),\
	SE_SF(DIG_FE_CNTL, TMDS_PIXEL_ENCODING, mask_sh),\
	SE_SF(DIG_FE_CNTL, TMDS_COLOR_FORMAT, mask_sh),\
	SE_SF(DIG_FE_CNTL, DIG_STEREOSYNC_SELECT, mask_sh),\
	SE_SF(DIG_FE_CNTL, DIG_STEREOSYNC_GATE_EN, mask_sh)

#घोषणा SE_COMMON_MASK_SH_LIST_DCE112(mask_sh)\
	SE_COMMON_MASK_SH_LIST_DCE_COMMON(mask_sh),\
	SE_SF(AFMT_CNTL, AFMT_AUDIO_CLOCK_EN, mask_sh),\
	SE_SF(HDMI_CONTROL, HDMI_CLOCK_CHANNEL_RATE, mask_sh),\
	SE_SF(HDMI_CONTROL, HDMI_DATA_SCRAMBLE_EN, mask_sh),\
	SE_SF(DIG_FE_CNTL, TMDS_PIXEL_ENCODING, mask_sh),\
	SE_SF(DIG_FE_CNTL, TMDS_COLOR_FORMAT, mask_sh),\
	SE_SF(DP_VID_TIMING, DP_VID_M_DOUBLE_VALUE_EN, mask_sh)

#घोषणा SE_COMMON_MASK_SH_LIST_DCE120(mask_sh)\
	SE_COMMON_MASK_SH_LIST_SOC(mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL, AFMT_GENERIC0_UPDATE, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL, AFMT_GENERIC2_UPDATE, mask_sh),\
	SE_SF(DP0_DP_PIXEL_FORMAT, DP_DYN_RANGE, mask_sh),\
	SE_SF(DP0_DP_PIXEL_FORMAT, DP_YCBCR_RANGE, mask_sh),\
	SE_SF(DIG0_HDMI_INFOFRAME_CONTROL0, HDMI_AVI_INFO_SEND, mask_sh),\
	SE_SF(DIG0_HDMI_INFOFRAME_CONTROL0, HDMI_AVI_INFO_CONT, mask_sh),\
	SE_SF(DIG0_HDMI_INFOFRAME_CONTROL1, HDMI_AVI_INFO_LINE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_AVI_ENABLE, mask_sh),\
	SE_SF(DIG0_AFMT_AVI_INFO3, AFMT_AVI_INFO_VERSION, mask_sh),\
	SE_SF(DP0_DP_VID_TIMING, DP_VID_M_DOUBLE_VALUE_EN, mask_sh)

#घोषणा SE_COMMON_MASK_SH_LIST_DCN10(mask_sh)\
	SE_COMMON_MASK_SH_LIST_SOC(mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL, AFMT_GENERIC_LOCK_STATUS, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL, AFMT_GENERIC_CONFLICT, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL, AFMT_GENERIC_CONFLICT_CLR, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC0_FRAME_UPDATE_PENDING, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC1_FRAME_UPDATE_PENDING, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC2_FRAME_UPDATE_PENDING, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC3_FRAME_UPDATE_PENDING, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC4_FRAME_UPDATE_PENDING, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC5_FRAME_UPDATE_PENDING, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC6_FRAME_UPDATE_PENDING, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC7_FRAME_UPDATE_PENDING, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC0_FRAME_UPDATE, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC1_FRAME_UPDATE, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC2_FRAME_UPDATE, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC3_FRAME_UPDATE, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC4_FRAME_UPDATE, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC5_FRAME_UPDATE, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC6_FRAME_UPDATE, mask_sh),\
	SE_SF(DIG0_AFMT_VBI_PACKET_CONTROL1, AFMT_GENERIC7_FRAME_UPDATE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_GSP4_ENABLE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_GSP5_ENABLE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_GSP6_ENABLE, mask_sh),\
	SE_SF(DP0_DP_SEC_CNTL, DP_SEC_GSP7_ENABLE, mask_sh),\
	SE_SF(DP0_DP_DB_CNTL, DP_DB_DISABLE, mask_sh),\
	SE_SF(DP0_DP_MSA_COLORIMETRY, DP_MSA_MISC0, mask_sh),\
	SE_SF(DP0_DP_MSA_TIMING_PARAM1, DP_MSA_HTOTAL, mask_sh),\
	SE_SF(DP0_DP_MSA_TIMING_PARAM1, DP_MSA_VTOTAL, mask_sh),\
	SE_SF(DP0_DP_MSA_TIMING_PARAM2, DP_MSA_HSTART, mask_sh),\
	SE_SF(DP0_DP_MSA_TIMING_PARAM2, DP_MSA_VSTART, mask_sh),\
	SE_SF(DP0_DP_MSA_TIMING_PARAM3, DP_MSA_HSYNCWIDTH, mask_sh),\
	SE_SF(DP0_DP_MSA_TIMING_PARAM3, DP_MSA_HSYNCPOLARITY, mask_sh),\
	SE_SF(DP0_DP_MSA_TIMING_PARAM3, DP_MSA_VSYNCWIDTH, mask_sh),\
	SE_SF(DP0_DP_MSA_TIMING_PARAM3, DP_MSA_VSYNCPOLARITY, mask_sh),\
	SE_SF(DP0_DP_MSA_TIMING_PARAM4, DP_MSA_HWIDTH, mask_sh),\
	SE_SF(DP0_DP_MSA_TIMING_PARAM4, DP_MSA_VHEIGHT, mask_sh),\
	SE_SF(DIG0_HDMI_DB_CONTROL, HDMI_DB_DISABLE, mask_sh),\
	SE_SF(DP0_DP_VID_TIMING, DP_VID_N_MUL, mask_sh)

काष्ठा dce_stream_encoder_shअगरt अणु
	uपूर्णांक8_t AFMT_GENERIC_INDEX;
	uपूर्णांक8_t AFMT_GENERIC0_UPDATE;
	uपूर्णांक8_t AFMT_GENERIC2_UPDATE;
	uपूर्णांक8_t AFMT_GENERIC_HB0;
	uपूर्णांक8_t AFMT_GENERIC_HB1;
	uपूर्णांक8_t AFMT_GENERIC_HB2;
	uपूर्णांक8_t AFMT_GENERIC_HB3;
	uपूर्णांक8_t AFMT_GENERIC_LOCK_STATUS;
	uपूर्णांक8_t AFMT_GENERIC_CONFLICT;
	uपूर्णांक8_t AFMT_GENERIC_CONFLICT_CLR;
	uपूर्णांक8_t AFMT_GENERIC0_FRAME_UPDATE_PENDING;
	uपूर्णांक8_t AFMT_GENERIC1_FRAME_UPDATE_PENDING;
	uपूर्णांक8_t AFMT_GENERIC2_FRAME_UPDATE_PENDING;
	uपूर्णांक8_t AFMT_GENERIC3_FRAME_UPDATE_PENDING;
	uपूर्णांक8_t AFMT_GENERIC4_FRAME_UPDATE_PENDING;
	uपूर्णांक8_t AFMT_GENERIC5_FRAME_UPDATE_PENDING;
	uपूर्णांक8_t AFMT_GENERIC6_FRAME_UPDATE_PENDING;
	uपूर्णांक8_t AFMT_GENERIC7_FRAME_UPDATE_PENDING;
	uपूर्णांक8_t AFMT_GENERIC0_FRAME_UPDATE;
	uपूर्णांक8_t AFMT_GENERIC1_FRAME_UPDATE;
	uपूर्णांक8_t AFMT_GENERIC2_FRAME_UPDATE;
	uपूर्णांक8_t AFMT_GENERIC3_FRAME_UPDATE;
	uपूर्णांक8_t AFMT_GENERIC4_FRAME_UPDATE;
	uपूर्णांक8_t AFMT_GENERIC5_FRAME_UPDATE;
	uपूर्णांक8_t AFMT_GENERIC6_FRAME_UPDATE;
	uपूर्णांक8_t AFMT_GENERIC7_FRAME_UPDATE;
	uपूर्णांक8_t HDMI_GENERIC0_CONT;
	uपूर्णांक8_t HDMI_GENERIC0_SEND;
	uपूर्णांक8_t HDMI_GENERIC0_LINE;
	uपूर्णांक8_t HDMI_GENERIC1_CONT;
	uपूर्णांक8_t HDMI_GENERIC1_SEND;
	uपूर्णांक8_t HDMI_GENERIC1_LINE;
	uपूर्णांक8_t DP_PIXEL_ENCODING;
	uपूर्णांक8_t DP_COMPONENT_DEPTH;
	uपूर्णांक8_t DP_DYN_RANGE;
	uपूर्णांक8_t DP_YCBCR_RANGE;
	uपूर्णांक8_t HDMI_PACKET_GEN_VERSION;
	uपूर्णांक8_t HDMI_KEEPOUT_MODE;
	uपूर्णांक8_t HDMI_DEEP_COLOR_ENABLE;
	uपूर्णांक8_t HDMI_CLOCK_CHANNEL_RATE;
	uपूर्णांक8_t HDMI_DEEP_COLOR_DEPTH;
	uपूर्णांक8_t HDMI_GC_CONT;
	uपूर्णांक8_t HDMI_GC_SEND;
	uपूर्णांक8_t HDMI_शून्य_SEND;
	uपूर्णांक8_t HDMI_DATA_SCRAMBLE_EN;
	uपूर्णांक8_t HDMI_AUDIO_INFO_SEND;
	uपूर्णांक8_t AFMT_AUDIO_INFO_UPDATE;
	uपूर्णांक8_t HDMI_AUDIO_INFO_LINE;
	uपूर्णांक8_t HDMI_GC_AVMUTE;
	uपूर्णांक8_t DP_MSE_RATE_X;
	uपूर्णांक8_t DP_MSE_RATE_Y;
	uपूर्णांक8_t DP_MSE_RATE_UPDATE_PENDING;
	uपूर्णांक8_t AFMT_AVI_INFO_VERSION;
	uपूर्णांक8_t HDMI_AVI_INFO_SEND;
	uपूर्णांक8_t HDMI_AVI_INFO_CONT;
	uपूर्णांक8_t HDMI_AVI_INFO_LINE;
	uपूर्णांक8_t DP_SEC_GSP0_ENABLE;
	uपूर्णांक8_t DP_SEC_STREAM_ENABLE;
	uपूर्णांक8_t DP_SEC_GSP1_ENABLE;
	uपूर्णांक8_t DP_SEC_GSP2_ENABLE;
	uपूर्णांक8_t DP_SEC_GSP3_ENABLE;
	uपूर्णांक8_t DP_SEC_GSP4_ENABLE;
	uपूर्णांक8_t DP_SEC_GSP5_ENABLE;
	uपूर्णांक8_t DP_SEC_GSP6_ENABLE;
	uपूर्णांक8_t DP_SEC_GSP7_ENABLE;
	uपूर्णांक8_t DP_SEC_AVI_ENABLE;
	uपूर्णांक8_t DP_SEC_MPG_ENABLE;
	uपूर्णांक8_t DP_VID_STREAM_DIS_DEFER;
	uपूर्णांक8_t DP_VID_STREAM_ENABLE;
	uपूर्णांक8_t DP_VID_STREAM_STATUS;
	uपूर्णांक8_t DP_STEER_FIFO_RESET;
	uपूर्णांक8_t DP_VID_M_N_GEN_EN;
	uपूर्णांक8_t DP_VID_N;
	uपूर्णांक8_t DP_VID_M;
	uपूर्णांक8_t DIG_START;
	uपूर्णांक8_t AFMT_AUDIO_SRC_SELECT;
	uपूर्णांक8_t AFMT_AUDIO_CHANNEL_ENABLE;
	uपूर्णांक8_t HDMI_AUDIO_PACKETS_PER_LINE;
	uपूर्णांक8_t HDMI_AUDIO_DELAY_EN;
	uपूर्णांक8_t AFMT_60958_CS_UPDATE;
	uपूर्णांक8_t AFMT_AUDIO_LAYOUT_OVRD;
	uपूर्णांक8_t AFMT_60958_OSF_OVRD;
	uपूर्णांक8_t HDMI_ACR_AUTO_SEND;
	uपूर्णांक8_t HDMI_ACR_SOURCE;
	uपूर्णांक8_t HDMI_ACR_AUDIO_PRIORITY;
	uपूर्णांक8_t HDMI_ACR_CTS_32;
	uपूर्णांक8_t HDMI_ACR_N_32;
	uपूर्णांक8_t HDMI_ACR_CTS_44;
	uपूर्णांक8_t HDMI_ACR_N_44;
	uपूर्णांक8_t HDMI_ACR_CTS_48;
	uपूर्णांक8_t HDMI_ACR_N_48;
	uपूर्णांक8_t AFMT_60958_CS_CHANNEL_NUMBER_L;
	uपूर्णांक8_t AFMT_60958_CS_CLOCK_ACCURACY;
	uपूर्णांक8_t AFMT_60958_CS_CHANNEL_NUMBER_R;
	uपूर्णांक8_t AFMT_60958_CS_CHANNEL_NUMBER_2;
	uपूर्णांक8_t AFMT_60958_CS_CHANNEL_NUMBER_3;
	uपूर्णांक8_t AFMT_60958_CS_CHANNEL_NUMBER_4;
	uपूर्णांक8_t AFMT_60958_CS_CHANNEL_NUMBER_5;
	uपूर्णांक8_t AFMT_60958_CS_CHANNEL_NUMBER_6;
	uपूर्णांक8_t AFMT_60958_CS_CHANNEL_NUMBER_7;
	uपूर्णांक8_t DP_SEC_AUD_N;
	uपूर्णांक8_t DP_SEC_TIMESTAMP_MODE;
	uपूर्णांक8_t DP_SEC_ASP_ENABLE;
	uपूर्णांक8_t DP_SEC_ATP_ENABLE;
	uपूर्णांक8_t DP_SEC_AIP_ENABLE;
	uपूर्णांक8_t DP_SEC_ACM_ENABLE;
	uपूर्णांक8_t AFMT_AUDIO_SAMPLE_SEND;
	uपूर्णांक8_t AFMT_AUDIO_CLOCK_EN;
	uपूर्णांक8_t TMDS_PIXEL_ENCODING;
	uपूर्णांक8_t TMDS_COLOR_FORMAT;
	uपूर्णांक8_t DIG_STEREOSYNC_SELECT;
	uपूर्णांक8_t DIG_STEREOSYNC_GATE_EN;
	uपूर्णांक8_t DP_DB_DISABLE;
	uपूर्णांक8_t DP_MSA_MISC0;
	uपूर्णांक8_t DP_MSA_HTOTAL;
	uपूर्णांक8_t DP_MSA_VTOTAL;
	uपूर्णांक8_t DP_MSA_HSTART;
	uपूर्णांक8_t DP_MSA_VSTART;
	uपूर्णांक8_t DP_MSA_HSYNCWIDTH;
	uपूर्णांक8_t DP_MSA_HSYNCPOLARITY;
	uपूर्णांक8_t DP_MSA_VSYNCWIDTH;
	uपूर्णांक8_t DP_MSA_VSYNCPOLARITY;
	uपूर्णांक8_t DP_MSA_HWIDTH;
	uपूर्णांक8_t DP_MSA_VHEIGHT;
	uपूर्णांक8_t HDMI_DB_DISABLE;
	uपूर्णांक8_t DP_VID_N_MUL;
	uपूर्णांक8_t DP_VID_M_DOUBLE_VALUE_EN;
	uपूर्णांक8_t DIG_SOURCE_SELECT;
पूर्ण;

काष्ठा dce_stream_encoder_mask अणु
	uपूर्णांक32_t AFMT_GENERIC_INDEX;
	uपूर्णांक32_t AFMT_GENERIC0_UPDATE;
	uपूर्णांक32_t AFMT_GENERIC2_UPDATE;
	uपूर्णांक32_t AFMT_GENERIC_HB0;
	uपूर्णांक32_t AFMT_GENERIC_HB1;
	uपूर्णांक32_t AFMT_GENERIC_HB2;
	uपूर्णांक32_t AFMT_GENERIC_HB3;
	uपूर्णांक32_t AFMT_GENERIC_LOCK_STATUS;
	uपूर्णांक32_t AFMT_GENERIC_CONFLICT;
	uपूर्णांक32_t AFMT_GENERIC_CONFLICT_CLR;
	uपूर्णांक32_t AFMT_GENERIC0_FRAME_UPDATE_PENDING;
	uपूर्णांक32_t AFMT_GENERIC1_FRAME_UPDATE_PENDING;
	uपूर्णांक32_t AFMT_GENERIC2_FRAME_UPDATE_PENDING;
	uपूर्णांक32_t AFMT_GENERIC3_FRAME_UPDATE_PENDING;
	uपूर्णांक32_t AFMT_GENERIC4_FRAME_UPDATE_PENDING;
	uपूर्णांक32_t AFMT_GENERIC5_FRAME_UPDATE_PENDING;
	uपूर्णांक32_t AFMT_GENERIC6_FRAME_UPDATE_PENDING;
	uपूर्णांक32_t AFMT_GENERIC7_FRAME_UPDATE_PENDING;
	uपूर्णांक32_t AFMT_GENERIC0_FRAME_UPDATE;
	uपूर्णांक32_t AFMT_GENERIC1_FRAME_UPDATE;
	uपूर्णांक32_t AFMT_GENERIC2_FRAME_UPDATE;
	uपूर्णांक32_t AFMT_GENERIC3_FRAME_UPDATE;
	uपूर्णांक32_t AFMT_GENERIC4_FRAME_UPDATE;
	uपूर्णांक32_t AFMT_GENERIC5_FRAME_UPDATE;
	uपूर्णांक32_t AFMT_GENERIC6_FRAME_UPDATE;
	uपूर्णांक32_t AFMT_GENERIC7_FRAME_UPDATE;
	uपूर्णांक32_t HDMI_GENERIC0_CONT;
	uपूर्णांक32_t HDMI_GENERIC0_SEND;
	uपूर्णांक32_t HDMI_GENERIC0_LINE;
	uपूर्णांक32_t HDMI_GENERIC1_CONT;
	uपूर्णांक32_t HDMI_GENERIC1_SEND;
	uपूर्णांक32_t HDMI_GENERIC1_LINE;
	uपूर्णांक32_t DP_PIXEL_ENCODING;
	uपूर्णांक32_t DP_COMPONENT_DEPTH;
	uपूर्णांक32_t DP_DYN_RANGE;
	uपूर्णांक32_t DP_YCBCR_RANGE;
	uपूर्णांक32_t HDMI_PACKET_GEN_VERSION;
	uपूर्णांक32_t HDMI_KEEPOUT_MODE;
	uपूर्णांक32_t HDMI_DEEP_COLOR_ENABLE;
	uपूर्णांक32_t HDMI_CLOCK_CHANNEL_RATE;
	uपूर्णांक32_t HDMI_DEEP_COLOR_DEPTH;
	uपूर्णांक32_t HDMI_GC_CONT;
	uपूर्णांक32_t HDMI_GC_SEND;
	uपूर्णांक32_t HDMI_शून्य_SEND;
	uपूर्णांक32_t HDMI_DATA_SCRAMBLE_EN;
	uपूर्णांक32_t HDMI_AUDIO_INFO_SEND;
	uपूर्णांक32_t AFMT_AUDIO_INFO_UPDATE;
	uपूर्णांक32_t HDMI_AUDIO_INFO_LINE;
	uपूर्णांक32_t HDMI_GC_AVMUTE;
	uपूर्णांक32_t DP_MSE_RATE_X;
	uपूर्णांक32_t DP_MSE_RATE_Y;
	uपूर्णांक32_t DP_MSE_RATE_UPDATE_PENDING;
	uपूर्णांक32_t AFMT_AVI_INFO_VERSION;
	uपूर्णांक32_t HDMI_AVI_INFO_SEND;
	uपूर्णांक32_t HDMI_AVI_INFO_CONT;
	uपूर्णांक32_t HDMI_AVI_INFO_LINE;
	uपूर्णांक32_t DP_SEC_GSP0_ENABLE;
	uपूर्णांक32_t DP_SEC_STREAM_ENABLE;
	uपूर्णांक32_t DP_SEC_GSP1_ENABLE;
	uपूर्णांक32_t DP_SEC_GSP2_ENABLE;
	uपूर्णांक32_t DP_SEC_GSP3_ENABLE;
	uपूर्णांक32_t DP_SEC_GSP4_ENABLE;
	uपूर्णांक32_t DP_SEC_GSP5_ENABLE;
	uपूर्णांक32_t DP_SEC_GSP6_ENABLE;
	uपूर्णांक32_t DP_SEC_GSP7_ENABLE;
	uपूर्णांक32_t DP_SEC_AVI_ENABLE;
	uपूर्णांक32_t DP_SEC_MPG_ENABLE;
	uपूर्णांक32_t DP_VID_STREAM_DIS_DEFER;
	uपूर्णांक32_t DP_VID_STREAM_ENABLE;
	uपूर्णांक32_t DP_VID_STREAM_STATUS;
	uपूर्णांक32_t DP_STEER_FIFO_RESET;
	uपूर्णांक32_t DP_VID_M_N_GEN_EN;
	uपूर्णांक32_t DP_VID_N;
	uपूर्णांक32_t DP_VID_M;
	uपूर्णांक32_t DIG_START;
	uपूर्णांक32_t AFMT_AUDIO_SRC_SELECT;
	uपूर्णांक32_t AFMT_AUDIO_CHANNEL_ENABLE;
	uपूर्णांक32_t HDMI_AUDIO_PACKETS_PER_LINE;
	uपूर्णांक32_t HDMI_AUDIO_DELAY_EN;
	uपूर्णांक32_t AFMT_60958_CS_UPDATE;
	uपूर्णांक32_t AFMT_AUDIO_LAYOUT_OVRD;
	uपूर्णांक32_t AFMT_60958_OSF_OVRD;
	uपूर्णांक32_t HDMI_ACR_AUTO_SEND;
	uपूर्णांक32_t HDMI_ACR_SOURCE;
	uपूर्णांक32_t HDMI_ACR_AUDIO_PRIORITY;
	uपूर्णांक32_t HDMI_ACR_CTS_32;
	uपूर्णांक32_t HDMI_ACR_N_32;
	uपूर्णांक32_t HDMI_ACR_CTS_44;
	uपूर्णांक32_t HDMI_ACR_N_44;
	uपूर्णांक32_t HDMI_ACR_CTS_48;
	uपूर्णांक32_t HDMI_ACR_N_48;
	uपूर्णांक32_t AFMT_60958_CS_CHANNEL_NUMBER_L;
	uपूर्णांक32_t AFMT_60958_CS_CLOCK_ACCURACY;
	uपूर्णांक32_t AFMT_60958_CS_CHANNEL_NUMBER_R;
	uपूर्णांक32_t AFMT_60958_CS_CHANNEL_NUMBER_2;
	uपूर्णांक32_t AFMT_60958_CS_CHANNEL_NUMBER_3;
	uपूर्णांक32_t AFMT_60958_CS_CHANNEL_NUMBER_4;
	uपूर्णांक32_t AFMT_60958_CS_CHANNEL_NUMBER_5;
	uपूर्णांक32_t AFMT_60958_CS_CHANNEL_NUMBER_6;
	uपूर्णांक32_t AFMT_60958_CS_CHANNEL_NUMBER_7;
	uपूर्णांक32_t DP_SEC_AUD_N;
	uपूर्णांक32_t DP_SEC_TIMESTAMP_MODE;
	uपूर्णांक32_t DP_SEC_ASP_ENABLE;
	uपूर्णांक32_t DP_SEC_ATP_ENABLE;
	uपूर्णांक32_t DP_SEC_AIP_ENABLE;
	uपूर्णांक32_t DP_SEC_ACM_ENABLE;
	uपूर्णांक32_t AFMT_AUDIO_SAMPLE_SEND;
	uपूर्णांक32_t AFMT_AUDIO_CLOCK_EN;
	uपूर्णांक32_t TMDS_PIXEL_ENCODING;
	uपूर्णांक32_t DIG_STEREOSYNC_SELECT;
	uपूर्णांक32_t DIG_STEREOSYNC_GATE_EN;
	uपूर्णांक32_t TMDS_COLOR_FORMAT;
	uपूर्णांक32_t DP_DB_DISABLE;
	uपूर्णांक32_t DP_MSA_MISC0;
	uपूर्णांक32_t DP_MSA_HTOTAL;
	uपूर्णांक32_t DP_MSA_VTOTAL;
	uपूर्णांक32_t DP_MSA_HSTART;
	uपूर्णांक32_t DP_MSA_VSTART;
	uपूर्णांक32_t DP_MSA_HSYNCWIDTH;
	uपूर्णांक32_t DP_MSA_HSYNCPOLARITY;
	uपूर्णांक32_t DP_MSA_VSYNCWIDTH;
	uपूर्णांक32_t DP_MSA_VSYNCPOLARITY;
	uपूर्णांक32_t DP_MSA_HWIDTH;
	uपूर्णांक32_t DP_MSA_VHEIGHT;
	uपूर्णांक32_t HDMI_DB_DISABLE;
	uपूर्णांक32_t DP_VID_N_MUL;
	uपूर्णांक32_t DP_VID_M_DOUBLE_VALUE_EN;
	uपूर्णांक32_t DIG_SOURCE_SELECT;
पूर्ण;

काष्ठा dce110_stream_enc_रेजिस्टरs अणु
	uपूर्णांक32_t AFMT_CNTL;
	uपूर्णांक32_t AFMT_AVI_INFO0;
	uपूर्णांक32_t AFMT_AVI_INFO1;
	uपूर्णांक32_t AFMT_AVI_INFO2;
	uपूर्णांक32_t AFMT_AVI_INFO3;
	uपूर्णांक32_t AFMT_GENERIC_0;
	uपूर्णांक32_t AFMT_GENERIC_1;
	uपूर्णांक32_t AFMT_GENERIC_2;
	uपूर्णांक32_t AFMT_GENERIC_3;
	uपूर्णांक32_t AFMT_GENERIC_4;
	uपूर्णांक32_t AFMT_GENERIC_5;
	uपूर्णांक32_t AFMT_GENERIC_6;
	uपूर्णांक32_t AFMT_GENERIC_7;
	uपूर्णांक32_t AFMT_GENERIC_HDR;
	uपूर्णांक32_t AFMT_INFOFRAME_CONTROL0;
	uपूर्णांक32_t AFMT_VBI_PACKET_CONTROL;
	uपूर्णांक32_t AFMT_VBI_PACKET_CONTROL1;
	uपूर्णांक32_t AFMT_AUDIO_PACKET_CONTROL;
	uपूर्णांक32_t AFMT_AUDIO_PACKET_CONTROL2;
	uपूर्णांक32_t AFMT_AUDIO_SRC_CONTROL;
	uपूर्णांक32_t AFMT_60958_0;
	uपूर्णांक32_t AFMT_60958_1;
	uपूर्णांक32_t AFMT_60958_2;
	uपूर्णांक32_t DIG_FE_CNTL;
	uपूर्णांक32_t DP_MSE_RATE_CNTL;
	uपूर्णांक32_t DP_MSE_RATE_UPDATE;
	uपूर्णांक32_t DP_PIXEL_FORMAT;
	uपूर्णांक32_t DP_SEC_CNTL;
	uपूर्णांक32_t DP_STEER_FIFO;
	uपूर्णांक32_t DP_VID_M;
	uपूर्णांक32_t DP_VID_N;
	uपूर्णांक32_t DP_VID_STREAM_CNTL;
	uपूर्णांक32_t DP_VID_TIMING;
	uपूर्णांक32_t DP_SEC_AUD_N;
	uपूर्णांक32_t DP_SEC_TIMESTAMP;
	uपूर्णांक32_t HDMI_CONTROL;
	uपूर्णांक32_t HDMI_GC;
	uपूर्णांक32_t HDMI_GENERIC_PACKET_CONTROL0;
	uपूर्णांक32_t HDMI_GENERIC_PACKET_CONTROL1;
	uपूर्णांक32_t HDMI_GENERIC_PACKET_CONTROL2;
	uपूर्णांक32_t HDMI_GENERIC_PACKET_CONTROL3;
	uपूर्णांक32_t HDMI_INFOFRAME_CONTROL0;
	uपूर्णांक32_t HDMI_INFOFRAME_CONTROL1;
	uपूर्णांक32_t HDMI_VBI_PACKET_CONTROL;
	uपूर्णांक32_t HDMI_AUDIO_PACKET_CONTROL;
	uपूर्णांक32_t HDMI_ACR_PACKET_CONTROL;
	uपूर्णांक32_t HDMI_ACR_32_0;
	uपूर्णांक32_t HDMI_ACR_32_1;
	uपूर्णांक32_t HDMI_ACR_44_0;
	uपूर्णांक32_t HDMI_ACR_44_1;
	uपूर्णांक32_t HDMI_ACR_48_0;
	uपूर्णांक32_t HDMI_ACR_48_1;
	uपूर्णांक32_t TMDS_CNTL;
	uपूर्णांक32_t DP_DB_CNTL;
	uपूर्णांक32_t DP_MSA_MISC;
	uपूर्णांक32_t DP_MSA_COLORIMETRY;
	uपूर्णांक32_t DP_MSA_TIMING_PARAM1;
	uपूर्णांक32_t DP_MSA_TIMING_PARAM2;
	uपूर्णांक32_t DP_MSA_TIMING_PARAM3;
	uपूर्णांक32_t DP_MSA_TIMING_PARAM4;
	uपूर्णांक32_t HDMI_DB_CONTROL;
पूर्ण;

काष्ठा dce110_stream_encoder अणु
	काष्ठा stream_encoder base;
	स्थिर काष्ठा dce110_stream_enc_रेजिस्टरs *regs;
	स्थिर काष्ठा dce_stream_encoder_shअगरt *se_shअगरt;
	स्थिर काष्ठा dce_stream_encoder_mask *se_mask;
पूर्ण;

व्योम dce110_stream_encoder_स्थिरruct(
	काष्ठा dce110_stream_encoder *enc110,
	काष्ठा dc_context *ctx,
	काष्ठा dc_bios *bp,
	क्रमागत engine_id eng_id,
	स्थिर काष्ठा dce110_stream_enc_रेजिस्टरs *regs,
	स्थिर काष्ठा dce_stream_encoder_shअगरt *se_shअगरt,
	स्थिर काष्ठा dce_stream_encoder_mask *se_mask);


व्योम dce110_se_audio_mute_control(
	काष्ठा stream_encoder *enc, bool mute);

व्योम dce110_se_dp_audio_setup(
	काष्ठा stream_encoder *enc,
	अचिन्हित पूर्णांक az_inst,
	काष्ठा audio_info *info);

व्योम dce110_se_dp_audio_enable(
		काष्ठा stream_encoder *enc);

व्योम dce110_se_dp_audio_disable(
		काष्ठा stream_encoder *enc);

व्योम dce110_se_hdmi_audio_setup(
	काष्ठा stream_encoder *enc,
	अचिन्हित पूर्णांक az_inst,
	काष्ठा audio_info *info,
	काष्ठा audio_crtc_info *audio_crtc_info);

व्योम dce110_se_hdmi_audio_disable(
	काष्ठा stream_encoder *enc);

#पूर्ण_अगर /* __DC_STREAM_ENCODER_DCE110_H__ */
