<शैली गुरु>
/*
 * OSS_2_4 Register करोcumentation
 *
 * Copyright (C) 2014  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, मुक्त of अक्षरge, to any person obtaining a
 * copy of this software and associated करोcumentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modअगरy, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to करो so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#अगर_अघोषित OSS_2_4_D_H
#घोषणा OSS_2_4_D_H

#घोषणा mmIH_VMID_0_LUT                                                         0xe00
#घोषणा mmIH_VMID_1_LUT                                                         0xe01
#घोषणा mmIH_VMID_2_LUT                                                         0xe02
#घोषणा mmIH_VMID_3_LUT                                                         0xe03
#घोषणा mmIH_VMID_4_LUT                                                         0xe04
#घोषणा mmIH_VMID_5_LUT                                                         0xe05
#घोषणा mmIH_VMID_6_LUT                                                         0xe06
#घोषणा mmIH_VMID_7_LUT                                                         0xe07
#घोषणा mmIH_VMID_8_LUT                                                         0xe08
#घोषणा mmIH_VMID_9_LUT                                                         0xe09
#घोषणा mmIH_VMID_10_LUT                                                        0xe0a
#घोषणा mmIH_VMID_11_LUT                                                        0xe0b
#घोषणा mmIH_VMID_12_LUT                                                        0xe0c
#घोषणा mmIH_VMID_13_LUT                                                        0xe0d
#घोषणा mmIH_VMID_14_LUT                                                        0xe0e
#घोषणा mmIH_VMID_15_LUT                                                        0xe0f
#घोषणा mmIH_RB_CNTL                                                            0xe30
#घोषणा mmIH_RB_BASE                                                            0xe31
#घोषणा mmIH_RB_RPTR                                                            0xe32
#घोषणा mmIH_RB_WPTR                                                            0xe33
#घोषणा mmIH_RB_WPTR_ADDR_HI                                                    0xe34
#घोषणा mmIH_RB_WPTR_ADDR_LO                                                    0xe35
#घोषणा mmIH_CNTL                                                               0xe36
#घोषणा mmIH_LEVEL_STATUS                                                       0xe37
#घोषणा mmIH_STATUS                                                             0xe38
#घोषणा mmIH_PERFMON_CNTL                                                       0xe39
#घोषणा mmIH_PERFCOUNTER0_RESULT                                                0xe3a
#घोषणा mmIH_PERFCOUNTER1_RESULT                                                0xe3b
#घोषणा mmIH_DSM_MATCH_VALUE_BIT_31_0                                           0xe3d
#घोषणा mmIH_DSM_MATCH_VALUE_BIT_63_32                                          0xe3e
#घोषणा mmIH_DSM_MATCH_VALUE_BIT_95_64                                          0xe3f
#घोषणा mmIH_DSM_MATCH_FIELD_CONTROL                                            0xe40
#घोषणा mmIH_DSM_MATCH_DATA_CONTROL                                             0xe41
#घोषणा mmIH_VERSION                                                            0xe42
#घोषणा mmSEM_MCIF_CONFIG                                                       0xf90
#घोषणा mmSDMA_CONFIG                                                           0xf91
#घोषणा mmSDMA1_CONFIG                                                          0xf92
#घोषणा mmUVD_CONFIG                                                            0xf93
#घोषणा mmVCE_CONFIG                                                            0xf94
#घोषणा mmACP_CONFIG                                                            0xf95
#घोषणा mmCPG_CONFIG                                                            0xf96
#घोषणा mmCPC1_CONFIG                                                           0xf97
#घोषणा mmCPC2_CONFIG                                                           0xf98
#घोषणा mmSEM_STATUS                                                            0xf99
#घोषणा mmSEM_EDC_CONFIG                                                        0xf9a
#घोषणा mmSEM_MAILBOX_CLIENTCONFIG                                              0xf9b
#घोषणा mmSEM_MAILBOX                                                           0xf9c
#घोषणा mmSEM_MAILBOX_CONTROL                                                   0xf9d
#घोषणा mmSEM_CHICKEN_BITS                                                      0xf9e
#घोषणा mmSEM_MAILBOX_CLIENTCONFIG_EXTRA                                        0xf9f
#घोषणा mmSRBM_CNTL                                                             0x390
#घोषणा mmSRBM_GFX_CNTL                                                         0x391
#घोषणा mmSRBM_READ_CNTL                                                        0x392
#घोषणा mmSRBM_STATUS2                                                          0x393
#घोषणा mmSRBM_STATUS                                                           0x394
#घोषणा mmSRBM_STATUS3                                                          0x395
#घोषणा mmSRBM_SOFT_RESET                                                       0x398
#घोषणा mmSRBM_DEBUG_CNTL                                                       0x399
#घोषणा mmSRBM_DEBUG_DATA                                                       0x39a
#घोषणा mmSRBM_CHIP_REVISION                                                    0x39b
#घोषणा mmCC_SYS_RB_REDUNDANCY                                                  0x39f
#घोषणा mmCC_SYS_RB_BACKEND_DISABLE                                             0x3a0
#घोषणा mmGC_USER_SYS_RB_BACKEND_DISABLE                                        0x3a1
#घोषणा mmSRBM_MC_CLKEN_CNTL                                                    0x3b3
#घोषणा mmSRBM_SYS_CLKEN_CNTL                                                   0x3b4
#घोषणा mmSRBM_VCE_CLKEN_CNTL                                                   0x3b5
#घोषणा mmSRBM_UVD_CLKEN_CNTL                                                   0x3b6
#घोषणा mmSRBM_SDMA_CLKEN_CNTL                                                  0x3b7
#घोषणा mmSRBM_SAM_CLKEN_CNTL                                                   0x3b8
#घोषणा mmSRBM_ISP_CLKEN_CNTL                                                   0x3b9
#घोषणा mmSRBM_DEBUG                                                            0x3a4
#घोषणा mmSRBM_DEBUG_SNAPSHOT                                                   0x3a5
#घोषणा mmSRBM_DEBUG_SNAPSHOT2                                                  0x3ad
#घोषणा mmSRBM_READ_ERROR                                                       0x3a6
#घोषणा mmSRBM_READ_ERROR2                                                      0x3ae
#घोषणा mmSRBM_INT_CNTL                                                         0x3a8
#घोषणा mmSRBM_INT_STATUS                                                       0x3a9
#घोषणा mmSRBM_INT_ACK                                                          0x3aa
#घोषणा mmSRBM_FIREWALL_ERROR_SRC                                               0x3ab
#घोषणा mmSRBM_FIREWALL_ERROR_ADDR                                              0x3ac
#घोषणा mmSRBM_DSM_TRIG_CNTL0                                                   0x3af
#घोषणा mmSRBM_DSM_TRIG_CNTL1                                                   0x3b0
#घोषणा mmSRBM_DSM_TRIG_MASK0                                                   0x3b1
#घोषणा mmSRBM_DSM_TRIG_MASK1                                                   0x3b2
#घोषणा mmSRBM_PERFMON_CNTL                                                     0x7c00
#घोषणा mmSRBM_PERFCOUNTER0_SELECT                                              0x7c01
#घोषणा mmSRBM_PERFCOUNTER1_SELECT                                              0x7c02
#घोषणा mmSRBM_PERFCOUNTER0_LO                                                  0x7c03
#घोषणा mmSRBM_PERFCOUNTER0_HI                                                  0x7c04
#घोषणा mmSRBM_PERFCOUNTER1_LO                                                  0x7c05
#घोषणा mmSRBM_PERFCOUNTER1_HI                                                  0x7c06
#घोषणा mmSRBM_CAM_INDEX                                                        0xfe34
#घोषणा mmSRBM_CAM_DATA                                                         0xfe35
#घोषणा mmSRBM_MC_DOMAIN_ADDR0                                                  0xfa00
#घोषणा mmSRBM_MC_DOMAIN_ADDR1                                                  0xfa01
#घोषणा mmSRBM_MC_DOMAIN_ADDR2                                                  0xfa02
#घोषणा mmSRBM_MC_DOMAIN_ADDR3                                                  0xfa03
#घोषणा mmSRBM_MC_DOMAIN_ADDR4                                                  0xfa04
#घोषणा mmSRBM_MC_DOMAIN_ADDR5                                                  0xfa05
#घोषणा mmSRBM_MC_DOMAIN_ADDR6                                                  0xfa06
#घोषणा mmSRBM_SYS_DOMAIN_ADDR0                                                 0xfa08
#घोषणा mmSRBM_SYS_DOMAIN_ADDR1                                                 0xfa09
#घोषणा mmSRBM_SYS_DOMAIN_ADDR2                                                 0xfa0a
#घोषणा mmSRBM_SYS_DOMAIN_ADDR3                                                 0xfa0b
#घोषणा mmSRBM_SYS_DOMAIN_ADDR4                                                 0xfa0c
#घोषणा mmSRBM_SYS_DOMAIN_ADDR5                                                 0xfa0d
#घोषणा mmSRBM_SYS_DOMAIN_ADDR6                                                 0xfa0e
#घोषणा mmSRBM_SDMA_DOMAIN_ADDR0                                                0xfa10
#घोषणा mmSRBM_SDMA_DOMAIN_ADDR1                                                0xfa11
#घोषणा mmSRBM_SDMA_DOMAIN_ADDR2                                                0xfa12
#घोषणा mmSRBM_SDMA_DOMAIN_ADDR3                                                0xfa13
#घोषणा mmSRBM_UVD_DOMAIN_ADDR0                                                 0xfa14
#घोषणा mmSRBM_UVD_DOMAIN_ADDR1                                                 0xfa15
#घोषणा mmSRBM_UVD_DOMAIN_ADDR2                                                 0xfa16
#घोषणा mmSRBM_VCE_DOMAIN_ADDR0                                                 0xfa18
#घोषणा mmSRBM_VCE_DOMAIN_ADDR1                                                 0xfa19
#घोषणा mmSRBM_VCE_DOMAIN_ADDR2                                                 0xfa1a
#घोषणा mmSRBM_SAM_DOMAIN_ADDR0                                                 0xfa1c
#घोषणा mmSRBM_SAM_DOMAIN_ADDR1                                                 0xfa1d
#घोषणा mmSRBM_SAM_DOMAIN_ADDR2                                                 0xfa1e
#घोषणा mmSRBM_ISP_DOMAIN_ADDR0                                                 0xfa20
#घोषणा mmSRBM_ISP_DOMAIN_ADDR1                                                 0xfa21
#घोषणा mmSRBM_ISP_DOMAIN_ADDR2                                                 0xfa22
#घोषणा mmSYS_GRBM_GFX_INDEX_SELECT                                             0xfa2c
#घोषणा mmSYS_GRBM_GFX_INDEX_DATA                                               0xfa2d
#घोषणा mmSRBM_GFX_CNTL_SELECT                                                  0xfa2e
#घोषणा mmSRBM_GFX_CNTL_DATA                                                    0xfa2f
#घोषणा mmSRBM_VF_ENABLE                                                        0xfa30
#घोषणा mmSRBM_VIRT_CNTL                                                        0xfa31
#घोषणा mmSRBM_VIRT_RESET_REQ                                                   0xfa32
#घोषणा mmSDMA0_UCODE_ADDR                                                      0x3400
#घोषणा mmSDMA0_UCODE_DATA                                                      0x3401
#घोषणा mmSDMA0_POWER_CNTL                                                      0x3402
#घोषणा mmSDMA0_CLK_CTRL                                                        0x3403
#घोषणा mmSDMA0_CNTL                                                            0x3404
#घोषणा mmSDMA0_CHICKEN_BITS                                                    0x3405
#घोषणा mmSDMA0_TILING_CONFIG                                                   0x3406
#घोषणा mmSDMA0_HASH                                                            0x3407
#घोषणा mmSDMA0_SEM_WAIT_FAIL_TIMER_CNTL                                        0x3409
#घोषणा mmSDMA0_RB_RPTR_FETCH                                                   0x340a
#घोषणा mmSDMA0_IB_OFFSET_FETCH                                                 0x340b
#घोषणा mmSDMA0_PROGRAM                                                         0x340c
#घोषणा mmSDMA0_STATUS_REG                                                      0x340d
#घोषणा mmSDMA0_STATUS1_REG                                                     0x340e
#घोषणा mmSDMA0_PERFMON_CNTL                                                    0x9000
#घोषणा mmSDMA0_PERFCOUNTER0_RESULT                                             0x9001
#घोषणा mmSDMA0_PERFCOUNTER1_RESULT                                             0x9002
#घोषणा mmSDMA0_F32_CNTL                                                        0x3412
#घोषणा mmSDMA0_FREEZE                                                          0x3413
#घोषणा mmSDMA0_PHASE0_QUANTUM                                                  0x3414
#घोषणा mmSDMA0_PHASE1_QUANTUM                                                  0x3415
#घोषणा mmSDMA_POWER_GATING                                                     0x3416
#घोषणा mmSDMA_PGFSM_CONFIG                                                     0x3417
#घोषणा mmSDMA_PGFSM_WRITE                                                      0x3418
#घोषणा mmSDMA_PGFSM_READ                                                       0x3419
#घोषणा mmSDMA0_EDC_CONFIG                                                      0x341a
#घोषणा mmSDMA0_BA_THRESHOLD                                                    0x341b
#घोषणा mmSDMA0_ID                                                              0x341c
#घोषणा mmSDMA0_VERSION                                                         0x341d
#घोषणा mmSDMA0_STATUS2_REG                                                     0x341e
#घोषणा mmSDMA0_GFX_RB_CNTL                                                     0x3480
#घोषणा mmSDMA0_GFX_RB_BASE                                                     0x3481
#घोषणा mmSDMA0_GFX_RB_BASE_HI                                                  0x3482
#घोषणा mmSDMA0_GFX_RB_RPTR                                                     0x3483
#घोषणा mmSDMA0_GFX_RB_WPTR                                                     0x3484
#घोषणा mmSDMA0_GFX_RB_WPTR_POLL_CNTL                                           0x3485
#घोषणा mmSDMA0_GFX_RB_WPTR_POLL_ADDR_HI                                        0x3486
#घोषणा mmSDMA0_GFX_RB_WPTR_POLL_ADDR_LO                                        0x3487
#घोषणा mmSDMA0_GFX_RB_RPTR_ADDR_HI                                             0x3488
#घोषणा mmSDMA0_GFX_RB_RPTR_ADDR_LO                                             0x3489
#घोषणा mmSDMA0_GFX_IB_CNTL                                                     0x348a
#घोषणा mmSDMA0_GFX_IB_RPTR                                                     0x348b
#घोषणा mmSDMA0_GFX_IB_OFFSET                                                   0x348c
#घोषणा mmSDMA0_GFX_IB_BASE_LO                                                  0x348d
#घोषणा mmSDMA0_GFX_IB_BASE_HI                                                  0x348e
#घोषणा mmSDMA0_GFX_IB_SIZE                                                     0x348f
#घोषणा mmSDMA0_GFX_SKIP_CNTL                                                   0x3490
#घोषणा mmSDMA0_GFX_CONTEXT_STATUS                                              0x3491
#घोषणा mmSDMA0_GFX_CONTEXT_CNTL                                                0x3493
#घोषणा mmSDMA0_GFX_VIRTUAL_ADDR                                                0x34a7
#घोषणा mmSDMA0_GFX_APE1_CNTL                                                   0x34a8
#घोषणा mmSDMA0_GFX_WATERMARK                                                   0x34aa
#घोषणा mmSDMA0_GFX_CSA_ADDR_LO                                                 0x34ac
#घोषणा mmSDMA0_GFX_CSA_ADDR_HI                                                 0x34ad
#घोषणा mmSDMA0_GFX_DUMMY_REG                                                   0x34ae
#घोषणा mmSDMA0_GFX_IB_SUB_REMAIN                                               0x34af
#घोषणा mmSDMA0_GFX_PREEMPT                                                     0x34b0
#घोषणा mmSDMA0_RLC0_RB_CNTL                                                    0x3500
#घोषणा mmSDMA0_RLC0_RB_BASE                                                    0x3501
#घोषणा mmSDMA0_RLC0_RB_BASE_HI                                                 0x3502
#घोषणा mmSDMA0_RLC0_RB_RPTR                                                    0x3503
#घोषणा mmSDMA0_RLC0_RB_WPTR                                                    0x3504
#घोषणा mmSDMA0_RLC0_RB_WPTR_POLL_CNTL                                          0x3505
#घोषणा mmSDMA0_RLC0_RB_WPTR_POLL_ADDR_HI                                       0x3506
#घोषणा mmSDMA0_RLC0_RB_WPTR_POLL_ADDR_LO                                       0x3507
#घोषणा mmSDMA0_RLC0_RB_RPTR_ADDR_HI                                            0x3508
#घोषणा mmSDMA0_RLC0_RB_RPTR_ADDR_LO                                            0x3509
#घोषणा mmSDMA0_RLC0_IB_CNTL                                                    0x350a
#घोषणा mmSDMA0_RLC0_IB_RPTR                                                    0x350b
#घोषणा mmSDMA0_RLC0_IB_OFFSET                                                  0x350c
#घोषणा mmSDMA0_RLC0_IB_BASE_LO                                                 0x350d
#घोषणा mmSDMA0_RLC0_IB_BASE_HI                                                 0x350e
#घोषणा mmSDMA0_RLC0_IB_SIZE                                                    0x350f
#घोषणा mmSDMA0_RLC0_SKIP_CNTL                                                  0x3510
#घोषणा mmSDMA0_RLC0_CONTEXT_STATUS                                             0x3511
#घोषणा mmSDMA0_RLC0_DOORBELL                                                   0x3512
#घोषणा mmSDMA0_RLC0_VIRTUAL_ADDR                                               0x3527
#घोषणा mmSDMA0_RLC0_APE1_CNTL                                                  0x3528
#घोषणा mmSDMA0_RLC0_DOORBELL_LOG                                               0x3529
#घोषणा mmSDMA0_RLC0_WATERMARK                                                  0x352a
#घोषणा mmSDMA0_RLC0_CSA_ADDR_LO                                                0x352c
#घोषणा mmSDMA0_RLC0_CSA_ADDR_HI                                                0x352d
#घोषणा mmSDMA0_RLC0_DUMMY_REG                                                  0x352e
#घोषणा mmSDMA0_RLC0_IB_SUB_REMAIN                                              0x352f
#घोषणा mmSDMA0_RLC0_PREEMPT                                                    0x3530
#घोषणा mmSDMA0_RLC1_RB_CNTL                                                    0x3580
#घोषणा mmSDMA0_RLC1_RB_BASE                                                    0x3581
#घोषणा mmSDMA0_RLC1_RB_BASE_HI                                                 0x3582
#घोषणा mmSDMA0_RLC1_RB_RPTR                                                    0x3583
#घोषणा mmSDMA0_RLC1_RB_WPTR                                                    0x3584
#घोषणा mmSDMA0_RLC1_RB_WPTR_POLL_CNTL                                          0x3585
#घोषणा mmSDMA0_RLC1_RB_WPTR_POLL_ADDR_HI                                       0x3586
#घोषणा mmSDMA0_RLC1_RB_WPTR_POLL_ADDR_LO                                       0x3587
#घोषणा mmSDMA0_RLC1_RB_RPTR_ADDR_HI                                            0x3588
#घोषणा mmSDMA0_RLC1_RB_RPTR_ADDR_LO                                            0x3589
#घोषणा mmSDMA0_RLC1_IB_CNTL                                                    0x358a
#घोषणा mmSDMA0_RLC1_IB_RPTR                                                    0x358b
#घोषणा mmSDMA0_RLC1_IB_OFFSET                                                  0x358c
#घोषणा mmSDMA0_RLC1_IB_BASE_LO                                                 0x358d
#घोषणा mmSDMA0_RLC1_IB_BASE_HI                                                 0x358e
#घोषणा mmSDMA0_RLC1_IB_SIZE                                                    0x358f
#घोषणा mmSDMA0_RLC1_SKIP_CNTL                                                  0x3590
#घोषणा mmSDMA0_RLC1_CONTEXT_STATUS                                             0x3591
#घोषणा mmSDMA0_RLC1_DOORBELL                                                   0x3592
#घोषणा mmSDMA0_RLC1_VIRTUAL_ADDR                                               0x35a7
#घोषणा mmSDMA0_RLC1_APE1_CNTL                                                  0x35a8
#घोषणा mmSDMA0_RLC1_DOORBELL_LOG                                               0x35a9
#घोषणा mmSDMA0_RLC1_WATERMARK                                                  0x35aa
#घोषणा mmSDMA0_RLC1_CSA_ADDR_LO                                                0x35ac
#घोषणा mmSDMA0_RLC1_CSA_ADDR_HI                                                0x35ad
#घोषणा mmSDMA0_RLC1_DUMMY_REG                                                  0x35ae
#घोषणा mmSDMA0_RLC1_IB_SUB_REMAIN                                              0x35af
#घोषणा mmSDMA0_RLC1_PREEMPT                                                    0x35b0
#घोषणा mmSDMA1_UCODE_ADDR                                                      0x3600
#घोषणा mmSDMA1_UCODE_DATA                                                      0x3601
#घोषणा mmSDMA1_POWER_CNTL                                                      0x3602
#घोषणा mmSDMA1_CLK_CTRL                                                        0x3603
#घोषणा mmSDMA1_CNTL                                                            0x3604
#घोषणा mmSDMA1_CHICKEN_BITS                                                    0x3605
#घोषणा mmSDMA1_TILING_CONFIG                                                   0x3606
#घोषणा mmSDMA1_HASH                                                            0x3607
#घोषणा mmSDMA1_SEM_WAIT_FAIL_TIMER_CNTL                                        0x3609
#घोषणा mmSDMA1_RB_RPTR_FETCH                                                   0x360a
#घोषणा mmSDMA1_IB_OFFSET_FETCH                                                 0x360b
#घोषणा mmSDMA1_PROGRAM                                                         0x360c
#घोषणा mmSDMA1_STATUS_REG                                                      0x360d
#घोषणा mmSDMA1_STATUS1_REG                                                     0x360e
#घोषणा mmSDMA1_PERFMON_CNTL                                                    0x9010
#घोषणा mmSDMA1_PERFCOUNTER0_RESULT                                             0x9011
#घोषणा mmSDMA1_PERFCOUNTER1_RESULT                                             0x9012
#घोषणा mmSDMA1_F32_CNTL                                                        0x3612
#घोषणा mmSDMA1_FREEZE                                                          0x3613
#घोषणा mmSDMA1_PHASE0_QUANTUM                                                  0x3614
#घोषणा mmSDMA1_PHASE1_QUANTUM                                                  0x3615
#घोषणा mmSDMA1_EDC_CONFIG                                                      0x361a
#घोषणा mmSDMA1_BA_THRESHOLD                                                    0x361b
#घोषणा mmSDMA1_ID                                                              0x361c
#घोषणा mmSDMA1_VERSION                                                         0x361d
#घोषणा mmSDMA1_STATUS2_REG                                                     0x361e
#घोषणा mmSDMA1_GFX_RB_CNTL                                                     0x3680
#घोषणा mmSDMA1_GFX_RB_BASE                                                     0x3681
#घोषणा mmSDMA1_GFX_RB_BASE_HI                                                  0x3682
#घोषणा mmSDMA1_GFX_RB_RPTR                                                     0x3683
#घोषणा mmSDMA1_GFX_RB_WPTR                                                     0x3684
#घोषणा mmSDMA1_GFX_RB_WPTR_POLL_CNTL                                           0x3685
#घोषणा mmSDMA1_GFX_RB_WPTR_POLL_ADDR_HI                                        0x3686
#घोषणा mmSDMA1_GFX_RB_WPTR_POLL_ADDR_LO                                        0x3687
#घोषणा mmSDMA1_GFX_RB_RPTR_ADDR_HI                                             0x3688
#घोषणा mmSDMA1_GFX_RB_RPTR_ADDR_LO                                             0x3689
#घोषणा mmSDMA1_GFX_IB_CNTL                                                     0x368a
#घोषणा mmSDMA1_GFX_IB_RPTR                                                     0x368b
#घोषणा mmSDMA1_GFX_IB_OFFSET                                                   0x368c
#घोषणा mmSDMA1_GFX_IB_BASE_LO                                                  0x368d
#घोषणा mmSDMA1_GFX_IB_BASE_HI                                                  0x368e
#घोषणा mmSDMA1_GFX_IB_SIZE                                                     0x368f
#घोषणा mmSDMA1_GFX_SKIP_CNTL                                                   0x3690
#घोषणा mmSDMA1_GFX_CONTEXT_STATUS                                              0x3691
#घोषणा mmSDMA1_GFX_CONTEXT_CNTL                                                0x3693
#घोषणा mmSDMA1_GFX_VIRTUAL_ADDR                                                0x36a7
#घोषणा mmSDMA1_GFX_APE1_CNTL                                                   0x36a8
#घोषणा mmSDMA1_GFX_WATERMARK                                                   0x36aa
#घोषणा mmSDMA1_GFX_CSA_ADDR_LO                                                 0x36ac
#घोषणा mmSDMA1_GFX_CSA_ADDR_HI                                                 0x36ad
#घोषणा mmSDMA1_GFX_DUMMY_REG                                                   0x36ae
#घोषणा mmSDMA1_GFX_IB_SUB_REMAIN                                               0x36af
#घोषणा mmSDMA1_GFX_PREEMPT                                                     0x36b0
#घोषणा mmSDMA1_RLC0_RB_CNTL                                                    0x3700
#घोषणा mmSDMA1_RLC0_RB_BASE                                                    0x3701
#घोषणा mmSDMA1_RLC0_RB_BASE_HI                                                 0x3702
#घोषणा mmSDMA1_RLC0_RB_RPTR                                                    0x3703
#घोषणा mmSDMA1_RLC0_RB_WPTR                                                    0x3704
#घोषणा mmSDMA1_RLC0_RB_WPTR_POLL_CNTL                                          0x3705
#घोषणा mmSDMA1_RLC0_RB_WPTR_POLL_ADDR_HI                                       0x3706
#घोषणा mmSDMA1_RLC0_RB_WPTR_POLL_ADDR_LO                                       0x3707
#घोषणा mmSDMA1_RLC0_RB_RPTR_ADDR_HI                                            0x3708
#घोषणा mmSDMA1_RLC0_RB_RPTR_ADDR_LO                                            0x3709
#घोषणा mmSDMA1_RLC0_IB_CNTL                                                    0x370a
#घोषणा mmSDMA1_RLC0_IB_RPTR                                                    0x370b
#घोषणा mmSDMA1_RLC0_IB_OFFSET                                                  0x370c
#घोषणा mmSDMA1_RLC0_IB_BASE_LO                                                 0x370d
#घोषणा mmSDMA1_RLC0_IB_BASE_HI                                                 0x370e
#घोषणा mmSDMA1_RLC0_IB_SIZE                                                    0x370f
#घोषणा mmSDMA1_RLC0_SKIP_CNTL                                                  0x3710
#घोषणा mmSDMA1_RLC0_CONTEXT_STATUS                                             0x3711
#घोषणा mmSDMA1_RLC0_DOORBELL                                                   0x3712
#घोषणा mmSDMA1_RLC0_VIRTUAL_ADDR                                               0x3727
#घोषणा mmSDMA1_RLC0_APE1_CNTL                                                  0x3728
#घोषणा mmSDMA1_RLC0_DOORBELL_LOG                                               0x3729
#घोषणा mmSDMA1_RLC0_WATERMARK                                                  0x372a
#घोषणा mmSDMA1_RLC0_CSA_ADDR_LO                                                0x372c
#घोषणा mmSDMA1_RLC0_CSA_ADDR_HI                                                0x372d
#घोषणा mmSDMA1_RLC0_DUMMY_REG                                                  0x372e
#घोषणा mmSDMA1_RLC0_IB_SUB_REMAIN                                              0x372f
#घोषणा mmSDMA1_RLC0_PREEMPT                                                    0x3730
#घोषणा mmSDMA1_RLC1_RB_CNTL                                                    0x3780
#घोषणा mmSDMA1_RLC1_RB_BASE                                                    0x3781
#घोषणा mmSDMA1_RLC1_RB_BASE_HI                                                 0x3782
#घोषणा mmSDMA1_RLC1_RB_RPTR                                                    0x3783
#घोषणा mmSDMA1_RLC1_RB_WPTR                                                    0x3784
#घोषणा mmSDMA1_RLC1_RB_WPTR_POLL_CNTL                                          0x3785
#घोषणा mmSDMA1_RLC1_RB_WPTR_POLL_ADDR_HI                                       0x3786
#घोषणा mmSDMA1_RLC1_RB_WPTR_POLL_ADDR_LO                                       0x3787
#घोषणा mmSDMA1_RLC1_RB_RPTR_ADDR_HI                                            0x3788
#घोषणा mmSDMA1_RLC1_RB_RPTR_ADDR_LO                                            0x3789
#घोषणा mmSDMA1_RLC1_IB_CNTL                                                    0x378a
#घोषणा mmSDMA1_RLC1_IB_RPTR                                                    0x378b
#घोषणा mmSDMA1_RLC1_IB_OFFSET                                                  0x378c
#घोषणा mmSDMA1_RLC1_IB_BASE_LO                                                 0x378d
#घोषणा mmSDMA1_RLC1_IB_BASE_HI                                                 0x378e
#घोषणा mmSDMA1_RLC1_IB_SIZE                                                    0x378f
#घोषणा mmSDMA1_RLC1_SKIP_CNTL                                                  0x3790
#घोषणा mmSDMA1_RLC1_CONTEXT_STATUS                                             0x3791
#घोषणा mmSDMA1_RLC1_DOORBELL                                                   0x3792
#घोषणा mmSDMA1_RLC1_VIRTUAL_ADDR                                               0x37a7
#घोषणा mmSDMA1_RLC1_APE1_CNTL                                                  0x37a8
#घोषणा mmSDMA1_RLC1_DOORBELL_LOG                                               0x37a9
#घोषणा mmSDMA1_RLC1_WATERMARK                                                  0x37aa
#घोषणा mmSDMA1_RLC1_CSA_ADDR_LO                                                0x37ac
#घोषणा mmSDMA1_RLC1_CSA_ADDR_HI                                                0x37ad
#घोषणा mmSDMA1_RLC1_DUMMY_REG                                                  0x37ae
#घोषणा mmSDMA1_RLC1_IB_SUB_REMAIN                                              0x37af
#घोषणा mmSDMA1_RLC1_PREEMPT                                                    0x37b0
#घोषणा mmHDP_HOST_PATH_CNTL                                                    0xb00
#घोषणा mmHDP_NONSURFACE_BASE                                                   0xb01
#घोषणा mmHDP_NONSURFACE_INFO                                                   0xb02
#घोषणा mmHDP_NONSURFACE_SIZE                                                   0xb03
#घोषणा mmHDP_NONSURF_FLAGS                                                     0xbc9
#घोषणा mmHDP_NONSURF_FLAGS_CLR                                                 0xbca
#घोषणा mmHDP_SW_SEMAPHORE                                                      0xbcb
#घोषणा mmHDP_DEBUG0                                                            0xbcc
#घोषणा mmHDP_DEBUG1                                                            0xbcd
#घोषणा mmHDP_LAST_SURFACE_HIT                                                  0xbce
#घोषणा mmHDP_TILING_CONFIG                                                     0xbcf
#घोषणा mmHDP_SC_MULTI_CHIP_CNTL                                                0xbd0
#घोषणा mmHDP_OUTSTANDING_REQ                                                   0xbd1
#घोषणा mmHDP_ADDR_CONFIG                                                       0xbd2
#घोषणा mmHDP_MISC_CNTL                                                         0xbd3
#घोषणा mmHDP_MEM_POWER_LS                                                      0xbd4
#घोषणा mmHDP_NONSURFACE_PREFETCH                                               0xbd5
#घोषणा mmHDP_MEMIO_CNTL                                                        0xbf6
#घोषणा mmHDP_MEMIO_ADDR                                                        0xbf7
#घोषणा mmHDP_MEMIO_STATUS                                                      0xbf8
#घोषणा mmHDP_MEMIO_WR_DATA                                                     0xbf9
#घोषणा mmHDP_MEMIO_RD_DATA                                                     0xbfa
#घोषणा mmHDP_XDP_सूचीECT2HDP_FIRST                                              0xc00
#घोषणा mmHDP_XDP_D2H_FLUSH                                                     0xc01
#घोषणा mmHDP_XDP_D2H_BAR_UPDATE                                                0xc02
#घोषणा mmHDP_XDP_D2H_RSVD_3                                                    0xc03
#घोषणा mmHDP_XDP_D2H_RSVD_4                                                    0xc04
#घोषणा mmHDP_XDP_D2H_RSVD_5                                                    0xc05
#घोषणा mmHDP_XDP_D2H_RSVD_6                                                    0xc06
#घोषणा mmHDP_XDP_D2H_RSVD_7                                                    0xc07
#घोषणा mmHDP_XDP_D2H_RSVD_8                                                    0xc08
#घोषणा mmHDP_XDP_D2H_RSVD_9                                                    0xc09
#घोषणा mmHDP_XDP_D2H_RSVD_10                                                   0xc0a
#घोषणा mmHDP_XDP_D2H_RSVD_11                                                   0xc0b
#घोषणा mmHDP_XDP_D2H_RSVD_12                                                   0xc0c
#घोषणा mmHDP_XDP_D2H_RSVD_13                                                   0xc0d
#घोषणा mmHDP_XDP_D2H_RSVD_14                                                   0xc0e
#घोषणा mmHDP_XDP_D2H_RSVD_15                                                   0xc0f
#घोषणा mmHDP_XDP_D2H_RSVD_16                                                   0xc10
#घोषणा mmHDP_XDP_D2H_RSVD_17                                                   0xc11
#घोषणा mmHDP_XDP_D2H_RSVD_18                                                   0xc12
#घोषणा mmHDP_XDP_D2H_RSVD_19                                                   0xc13
#घोषणा mmHDP_XDP_D2H_RSVD_20                                                   0xc14
#घोषणा mmHDP_XDP_D2H_RSVD_21                                                   0xc15
#घोषणा mmHDP_XDP_D2H_RSVD_22                                                   0xc16
#घोषणा mmHDP_XDP_D2H_RSVD_23                                                   0xc17
#घोषणा mmHDP_XDP_D2H_RSVD_24                                                   0xc18
#घोषणा mmHDP_XDP_D2H_RSVD_25                                                   0xc19
#घोषणा mmHDP_XDP_D2H_RSVD_26                                                   0xc1a
#घोषणा mmHDP_XDP_D2H_RSVD_27                                                   0xc1b
#घोषणा mmHDP_XDP_D2H_RSVD_28                                                   0xc1c
#घोषणा mmHDP_XDP_D2H_RSVD_29                                                   0xc1d
#घोषणा mmHDP_XDP_D2H_RSVD_30                                                   0xc1e
#घोषणा mmHDP_XDP_D2H_RSVD_31                                                   0xc1f
#घोषणा mmHDP_XDP_D2H_RSVD_32                                                   0xc20
#घोषणा mmHDP_XDP_D2H_RSVD_33                                                   0xc21
#घोषणा mmHDP_XDP_D2H_RSVD_34                                                   0xc22
#घोषणा mmHDP_XDP_सूचीECT2HDP_LAST                                               0xc23
#घोषणा mmHDP_XDP_P2P_BAR_CFG                                                   0xc24
#घोषणा mmHDP_XDP_P2P_MBX_OFFSET                                                0xc25
#घोषणा mmHDP_XDP_P2P_MBX_ADDR0                                                 0xc26
#घोषणा mmHDP_XDP_P2P_MBX_ADDR1                                                 0xc27
#घोषणा mmHDP_XDP_P2P_MBX_ADDR2                                                 0xc28
#घोषणा mmHDP_XDP_P2P_MBX_ADDR3                                                 0xc29
#घोषणा mmHDP_XDP_P2P_MBX_ADDR4                                                 0xc2a
#घोषणा mmHDP_XDP_P2P_MBX_ADDR5                                                 0xc2b
#घोषणा mmHDP_XDP_P2P_MBX_ADDR6                                                 0xc2c
#घोषणा mmHDP_XDP_HDP_MBX_MC_CFG                                                0xc2d
#घोषणा mmHDP_XDP_HDP_MC_CFG                                                    0xc2e
#घोषणा mmHDP_XDP_HST_CFG                                                       0xc2f
#घोषणा mmHDP_XDP_SID_CFG                                                       0xc30
#घोषणा mmHDP_XDP_HDP_IPH_CFG                                                   0xc31
#घोषणा mmHDP_XDP_SRBM_CFG                                                      0xc32
#घोषणा mmHDP_XDP_CGTT_BLK_CTRL                                                 0xc33
#घोषणा mmHDP_XDP_P2P_BAR0                                                      0xc34
#घोषणा mmHDP_XDP_P2P_BAR1                                                      0xc35
#घोषणा mmHDP_XDP_P2P_BAR2                                                      0xc36
#घोषणा mmHDP_XDP_P2P_BAR3                                                      0xc37
#घोषणा mmHDP_XDP_P2P_BAR4                                                      0xc38
#घोषणा mmHDP_XDP_P2P_BAR5                                                      0xc39
#घोषणा mmHDP_XDP_P2P_BAR6                                                      0xc3a
#घोषणा mmHDP_XDP_P2P_BAR7                                                      0xc3b
#घोषणा mmHDP_XDP_FLUSH_ARMED_STS                                               0xc3c
#घोषणा mmHDP_XDP_FLUSH_CNTR0_STS                                               0xc3d
#घोषणा mmHDP_XDP_BUSY_STS                                                      0xc3e
#घोषणा mmHDP_XDP_STICKY                                                        0xc3f
#घोषणा mmHDP_XDP_CHKN                                                          0xc40
#घोषणा mmHDP_XDP_DBG_ADDR                                                      0xc41
#घोषणा mmHDP_XDP_DBG_DATA                                                      0xc42
#घोषणा mmHDP_XDP_DBG_MASK                                                      0xc43
#घोषणा mmHDP_XDP_BARS_ADDR_39_36                                               0xc44

#पूर्ण_अगर /* OSS_2_4_D_H */
