<शैली गुरु>
/*
 * Copyright (C) 2017  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, मुक्त of अक्षरge, to any person obtaining a
 * copy of this software and associated करोcumentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modअगरy, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to करो so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#अगर_अघोषित _osssys_4_0_1_OFFSET_HEADER
#घोषणा _osssys_4_0_1_OFFSET_HEADER



// addressBlock: osssys_osssysdec
// base address: 0x4280
#घोषणा mmIH_VMID_0_LUT                                                                                0x0000
#घोषणा mmIH_VMID_0_LUT_BASE_IDX                                                                       0
#घोषणा mmIH_VMID_1_LUT                                                                                0x0001
#घोषणा mmIH_VMID_1_LUT_BASE_IDX                                                                       0
#घोषणा mmIH_VMID_2_LUT                                                                                0x0002
#घोषणा mmIH_VMID_2_LUT_BASE_IDX                                                                       0
#घोषणा mmIH_VMID_3_LUT                                                                                0x0003
#घोषणा mmIH_VMID_3_LUT_BASE_IDX                                                                       0
#घोषणा mmIH_VMID_4_LUT                                                                                0x0004
#घोषणा mmIH_VMID_4_LUT_BASE_IDX                                                                       0
#घोषणा mmIH_VMID_5_LUT                                                                                0x0005
#घोषणा mmIH_VMID_5_LUT_BASE_IDX                                                                       0
#घोषणा mmIH_VMID_6_LUT                                                                                0x0006
#घोषणा mmIH_VMID_6_LUT_BASE_IDX                                                                       0
#घोषणा mmIH_VMID_7_LUT                                                                                0x0007
#घोषणा mmIH_VMID_7_LUT_BASE_IDX                                                                       0
#घोषणा mmIH_VMID_8_LUT                                                                                0x0008
#घोषणा mmIH_VMID_8_LUT_BASE_IDX                                                                       0
#घोषणा mmIH_VMID_9_LUT                                                                                0x0009
#घोषणा mmIH_VMID_9_LUT_BASE_IDX                                                                       0
#घोषणा mmIH_VMID_10_LUT                                                                               0x000a
#घोषणा mmIH_VMID_10_LUT_BASE_IDX                                                                      0
#घोषणा mmIH_VMID_11_LUT                                                                               0x000b
#घोषणा mmIH_VMID_11_LUT_BASE_IDX                                                                      0
#घोषणा mmIH_VMID_12_LUT                                                                               0x000c
#घोषणा mmIH_VMID_12_LUT_BASE_IDX                                                                      0
#घोषणा mmIH_VMID_13_LUT                                                                               0x000d
#घोषणा mmIH_VMID_13_LUT_BASE_IDX                                                                      0
#घोषणा mmIH_VMID_14_LUT                                                                               0x000e
#घोषणा mmIH_VMID_14_LUT_BASE_IDX                                                                      0
#घोषणा mmIH_VMID_15_LUT                                                                               0x000f
#घोषणा mmIH_VMID_15_LUT_BASE_IDX                                                                      0
#घोषणा mmIH_VMID_0_LUT_MM                                                                             0x0010
#घोषणा mmIH_VMID_0_LUT_MM_BASE_IDX                                                                    0
#घोषणा mmIH_VMID_1_LUT_MM                                                                             0x0011
#घोषणा mmIH_VMID_1_LUT_MM_BASE_IDX                                                                    0
#घोषणा mmIH_VMID_2_LUT_MM                                                                             0x0012
#घोषणा mmIH_VMID_2_LUT_MM_BASE_IDX                                                                    0
#घोषणा mmIH_VMID_3_LUT_MM                                                                             0x0013
#घोषणा mmIH_VMID_3_LUT_MM_BASE_IDX                                                                    0
#घोषणा mmIH_VMID_4_LUT_MM                                                                             0x0014
#घोषणा mmIH_VMID_4_LUT_MM_BASE_IDX                                                                    0
#घोषणा mmIH_VMID_5_LUT_MM                                                                             0x0015
#घोषणा mmIH_VMID_5_LUT_MM_BASE_IDX                                                                    0
#घोषणा mmIH_VMID_6_LUT_MM                                                                             0x0016
#घोषणा mmIH_VMID_6_LUT_MM_BASE_IDX                                                                    0
#घोषणा mmIH_VMID_7_LUT_MM                                                                             0x0017
#घोषणा mmIH_VMID_7_LUT_MM_BASE_IDX                                                                    0
#घोषणा mmIH_VMID_8_LUT_MM                                                                             0x0018
#घोषणा mmIH_VMID_8_LUT_MM_BASE_IDX                                                                    0
#घोषणा mmIH_VMID_9_LUT_MM                                                                             0x0019
#घोषणा mmIH_VMID_9_LUT_MM_BASE_IDX                                                                    0
#घोषणा mmIH_VMID_10_LUT_MM                                                                            0x001a
#घोषणा mmIH_VMID_10_LUT_MM_BASE_IDX                                                                   0
#घोषणा mmIH_VMID_11_LUT_MM                                                                            0x001b
#घोषणा mmIH_VMID_11_LUT_MM_BASE_IDX                                                                   0
#घोषणा mmIH_VMID_12_LUT_MM                                                                            0x001c
#घोषणा mmIH_VMID_12_LUT_MM_BASE_IDX                                                                   0
#घोषणा mmIH_VMID_13_LUT_MM                                                                            0x001d
#घोषणा mmIH_VMID_13_LUT_MM_BASE_IDX                                                                   0
#घोषणा mmIH_VMID_14_LUT_MM                                                                            0x001e
#घोषणा mmIH_VMID_14_LUT_MM_BASE_IDX                                                                   0
#घोषणा mmIH_VMID_15_LUT_MM                                                                            0x001f
#घोषणा mmIH_VMID_15_LUT_MM_BASE_IDX                                                                   0
#घोषणा mmIH_COOKIE_0                                                                                  0x0020
#घोषणा mmIH_COOKIE_0_BASE_IDX                                                                         0
#घोषणा mmIH_COOKIE_1                                                                                  0x0021
#घोषणा mmIH_COOKIE_1_BASE_IDX                                                                         0
#घोषणा mmIH_COOKIE_2                                                                                  0x0022
#घोषणा mmIH_COOKIE_2_BASE_IDX                                                                         0
#घोषणा mmIH_COOKIE_3                                                                                  0x0023
#घोषणा mmIH_COOKIE_3_BASE_IDX                                                                         0
#घोषणा mmIH_COOKIE_4                                                                                  0x0024
#घोषणा mmIH_COOKIE_4_BASE_IDX                                                                         0
#घोषणा mmIH_COOKIE_5                                                                                  0x0025
#घोषणा mmIH_COOKIE_5_BASE_IDX                                                                         0
#घोषणा mmIH_COOKIE_6                                                                                  0x0026
#घोषणा mmIH_COOKIE_6_BASE_IDX                                                                         0
#घोषणा mmIH_COOKIE_7                                                                                  0x0027
#घोषणा mmIH_COOKIE_7_BASE_IDX                                                                         0
#घोषणा mmIH_REGISTER_LAST_PART0                                                                       0x003f
#घोषणा mmIH_REGISTER_LAST_PART0_BASE_IDX                                                              0
#घोषणा mmSEM_REQ_INPUT_0                                                                              0x0040
#घोषणा mmSEM_REQ_INPUT_0_BASE_IDX                                                                     0
#घोषणा mmSEM_REQ_INPUT_1                                                                              0x0041
#घोषणा mmSEM_REQ_INPUT_1_BASE_IDX                                                                     0
#घोषणा mmSEM_REQ_INPUT_2                                                                              0x0042
#घोषणा mmSEM_REQ_INPUT_2_BASE_IDX                                                                     0
#घोषणा mmSEM_REQ_INPUT_3                                                                              0x0043
#घोषणा mmSEM_REQ_INPUT_3_BASE_IDX                                                                     0
#घोषणा mmSEM_REGISTER_LAST_PART0                                                                      0x007f
#घोषणा mmSEM_REGISTER_LAST_PART0_BASE_IDX                                                             0
#घोषणा mmIH_RB_CNTL                                                                                   0x0080
#घोषणा mmIH_RB_CNTL_BASE_IDX                                                                          0
#घोषणा mmIH_RB_BASE                                                                                   0x0081
#घोषणा mmIH_RB_BASE_BASE_IDX                                                                          0
#घोषणा mmIH_RB_BASE_HI                                                                                0x0082
#घोषणा mmIH_RB_BASE_HI_BASE_IDX                                                                       0
#घोषणा mmIH_RB_RPTR                                                                                   0x0083
#घोषणा mmIH_RB_RPTR_BASE_IDX                                                                          0
#घोषणा mmIH_RB_WPTR                                                                                   0x0084
#घोषणा mmIH_RB_WPTR_BASE_IDX                                                                          0
#घोषणा mmIH_RB_WPTR_ADDR_HI                                                                           0x0085
#घोषणा mmIH_RB_WPTR_ADDR_HI_BASE_IDX                                                                  0
#घोषणा mmIH_RB_WPTR_ADDR_LO                                                                           0x0086
#घोषणा mmIH_RB_WPTR_ADDR_LO_BASE_IDX                                                                  0
#घोषणा mmIH_DOORBELL_RPTR                                                                             0x0087
#घोषणा mmIH_DOORBELL_RPTR_BASE_IDX                                                                    0
#घोषणा mmIH_RB_CNTL_RING1                                                                             0x0088
#घोषणा mmIH_RB_CNTL_RING1_BASE_IDX                                                                    0
#घोषणा mmIH_RB_BASE_RING1                                                                             0x0089
#घोषणा mmIH_RB_BASE_RING1_BASE_IDX                                                                    0
#घोषणा mmIH_RB_BASE_HI_RING1                                                                          0x008a
#घोषणा mmIH_RB_BASE_HI_RING1_BASE_IDX                                                                 0
#घोषणा mmIH_RB_RPTR_RING1                                                                             0x008b
#घोषणा mmIH_RB_RPTR_RING1_BASE_IDX                                                                    0
#घोषणा mmIH_RB_WPTR_RING1                                                                             0x008c
#घोषणा mmIH_RB_WPTR_RING1_BASE_IDX                                                                    0
#घोषणा mmIH_DOORBELL_RPTR_RING1                                                                       0x008f
#घोषणा mmIH_DOORBELL_RPTR_RING1_BASE_IDX                                                              0
#घोषणा mmIH_RB_CNTL_RING2                                                                             0x0090
#घोषणा mmIH_RB_CNTL_RING2_BASE_IDX                                                                    0
#घोषणा mmIH_RB_BASE_RING2                                                                             0x0091
#घोषणा mmIH_RB_BASE_RING2_BASE_IDX                                                                    0
#घोषणा mmIH_RB_BASE_HI_RING2                                                                          0x0092
#घोषणा mmIH_RB_BASE_HI_RING2_BASE_IDX                                                                 0
#घोषणा mmIH_RB_RPTR_RING2                                                                             0x0093
#घोषणा mmIH_RB_RPTR_RING2_BASE_IDX                                                                    0
#घोषणा mmIH_RB_WPTR_RING2                                                                             0x0094
#घोषणा mmIH_RB_WPTR_RING2_BASE_IDX                                                                    0
#घोषणा mmIH_DOORBELL_RPTR_RING2                                                                       0x0097
#घोषणा mmIH_DOORBELL_RPTR_RING2_BASE_IDX                                                              0
#घोषणा mmIH_VERSION                                                                                   0x0098
#घोषणा mmIH_VERSION_BASE_IDX                                                                          0
#घोषणा mmIH_CNTL                                                                                      0x00c0
#घोषणा mmIH_CNTL_BASE_IDX                                                                             0
#घोषणा mmIH_CNTL2                                                                                     0x00c1
#घोषणा mmIH_CNTL2_BASE_IDX                                                                            0
#घोषणा mmIH_STATUS                                                                                    0x00c2
#घोषणा mmIH_STATUS_BASE_IDX                                                                           0
#घोषणा mmIH_PERFMON_CNTL                                                                              0x00c3
#घोषणा mmIH_PERFMON_CNTL_BASE_IDX                                                                     0
#घोषणा mmIH_PERFCOUNTER0_RESULT                                                                       0x00c4
#घोषणा mmIH_PERFCOUNTER0_RESULT_BASE_IDX                                                              0
#घोषणा mmIH_PERFCOUNTER1_RESULT                                                                       0x00c5
#घोषणा mmIH_PERFCOUNTER1_RESULT_BASE_IDX                                                              0
#घोषणा mmIH_DSM_MATCH_VALUE_BIT_31_0                                                                  0x00c7
#घोषणा mmIH_DSM_MATCH_VALUE_BIT_31_0_BASE_IDX                                                         0
#घोषणा mmIH_DSM_MATCH_VALUE_BIT_63_32                                                                 0x00c8
#घोषणा mmIH_DSM_MATCH_VALUE_BIT_63_32_BASE_IDX                                                        0
#घोषणा mmIH_DSM_MATCH_VALUE_BIT_95_64                                                                 0x00c9
#घोषणा mmIH_DSM_MATCH_VALUE_BIT_95_64_BASE_IDX                                                        0
#घोषणा mmIH_DSM_MATCH_FIELD_CONTROL                                                                   0x00ca
#घोषणा mmIH_DSM_MATCH_FIELD_CONTROL_BASE_IDX                                                          0
#घोषणा mmIH_DSM_MATCH_DATA_CONTROL                                                                    0x00cb
#घोषणा mmIH_DSM_MATCH_DATA_CONTROL_BASE_IDX                                                           0
#घोषणा mmIH_DSM_MATCH_FCN_ID                                                                          0x00cc
#घोषणा mmIH_DSM_MATCH_FCN_ID_BASE_IDX                                                                 0
#घोषणा mmIH_LIMIT_INT_RATE_CNTL                                                                       0x00cd
#घोषणा mmIH_LIMIT_INT_RATE_CNTL_BASE_IDX                                                              0
#घोषणा mmIH_VF_RB_STATUS                                                                              0x00ce
#घोषणा mmIH_VF_RB_STATUS_BASE_IDX                                                                     0
#घोषणा mmIH_VF_RB_STATUS2                                                                             0x00cf
#घोषणा mmIH_VF_RB_STATUS2_BASE_IDX                                                                    0
#घोषणा mmIH_VF_RB1_STATUS                                                                             0x00d0
#घोषणा mmIH_VF_RB1_STATUS_BASE_IDX                                                                    0
#घोषणा mmIH_VF_RB1_STATUS2                                                                            0x00d1
#घोषणा mmIH_VF_RB1_STATUS2_BASE_IDX                                                                   0
#घोषणा mmIH_VF_RB2_STATUS                                                                             0x00d2
#घोषणा mmIH_VF_RB2_STATUS_BASE_IDX                                                                    0
#घोषणा mmIH_VF_RB2_STATUS2                                                                            0x00d3
#घोषणा mmIH_VF_RB2_STATUS2_BASE_IDX                                                                   0
#घोषणा mmIH_INT_FLOOD_CNTL                                                                            0x00d5
#घोषणा mmIH_INT_FLOOD_CNTL_BASE_IDX                                                                   0
#घोषणा mmIH_RB0_INT_FLOOD_STATUS                                                                      0x00d6
#घोषणा mmIH_RB0_INT_FLOOD_STATUS_BASE_IDX                                                             0
#घोषणा mmIH_RB1_INT_FLOOD_STATUS                                                                      0x00d7
#घोषणा mmIH_RB1_INT_FLOOD_STATUS_BASE_IDX                                                             0
#घोषणा mmIH_RB2_INT_FLOOD_STATUS                                                                      0x00d8
#घोषणा mmIH_RB2_INT_FLOOD_STATUS_BASE_IDX                                                             0
#घोषणा mmIH_INT_FLOOD_STATUS                                                                          0x00d9
#घोषणा mmIH_INT_FLOOD_STATUS_BASE_IDX                                                                 0
#घोषणा mmIH_STORM_CLIENT_LIST_CNTL                                                                    0x00da
#घोषणा mmIH_STORM_CLIENT_LIST_CNTL_BASE_IDX                                                           0
#घोषणा mmIH_CLK_CTRL                                                                                  0x00db
#घोषणा mmIH_CLK_CTRL_BASE_IDX                                                                         0
#घोषणा mmIH_INT_FLAGS                                                                                 0x00dc
#घोषणा mmIH_INT_FLAGS_BASE_IDX                                                                        0
#घोषणा mmIH_LAST_INT_INFO0                                                                            0x00dd
#घोषणा mmIH_LAST_INT_INFO0_BASE_IDX                                                                   0
#घोषणा mmIH_LAST_INT_INFO1                                                                            0x00de
#घोषणा mmIH_LAST_INT_INFO1_BASE_IDX                                                                   0
#घोषणा mmIH_LAST_INT_INFO2                                                                            0x00df
#घोषणा mmIH_LAST_INT_INFO2_BASE_IDX                                                                   0
#घोषणा mmIH_SCRATCH                                                                                   0x00e0
#घोषणा mmIH_SCRATCH_BASE_IDX                                                                          0
#घोषणा mmIH_CLIENT_CREDIT_ERROR                                                                       0x00e1
#घोषणा mmIH_CLIENT_CREDIT_ERROR_BASE_IDX                                                              0
#घोषणा mmIH_GPU_IOV_VIOLATION_LOG                                                                     0x00e2
#घोषणा mmIH_GPU_IOV_VIOLATION_LOG_BASE_IDX                                                            0
#घोषणा mmIH_COOKIE_REC_VIOLATION_LOG                                                                  0x00e3
#घोषणा mmIH_COOKIE_REC_VIOLATION_LOG_BASE_IDX                                                         0
#घोषणा mmIH_CREDIT_STATUS                                                                             0x00e4
#घोषणा mmIH_CREDIT_STATUS_BASE_IDX                                                                    0
#घोषणा mmIH_MMHUB_ERROR                                                                               0x00e5
#घोषणा mmIH_MMHUB_ERROR_BASE_IDX                                                                      0
#घोषणा mmIH_REGISTER_LAST_PART2                                                                       0x00ff
#घोषणा mmIH_REGISTER_LAST_PART2_BASE_IDX                                                              0
#घोषणा mmSEM_CLK_CTRL                                                                                 0x0100
#घोषणा mmSEM_CLK_CTRL_BASE_IDX                                                                        0
#घोषणा mmSEM_UTC_CREDIT                                                                               0x0101
#घोषणा mmSEM_UTC_CREDIT_BASE_IDX                                                                      0
#घोषणा mmSEM_UTC_CONFIG                                                                               0x0102
#घोषणा mmSEM_UTC_CONFIG_BASE_IDX                                                                      0
#घोषणा mmSEM_UTCL2_TRAN_EN_LUT                                                                        0x0103
#घोषणा mmSEM_UTCL2_TRAN_EN_LUT_BASE_IDX                                                               0
#घोषणा mmSEM_MCIF_CONFIG                                                                              0x0104
#घोषणा mmSEM_MCIF_CONFIG_BASE_IDX                                                                     0
#घोषणा mmSEM_PERFMON_CNTL                                                                             0x0105
#घोषणा mmSEM_PERFMON_CNTL_BASE_IDX                                                                    0
#घोषणा mmSEM_PERFCOUNTER0_RESULT                                                                      0x0106
#घोषणा mmSEM_PERFCOUNTER0_RESULT_BASE_IDX                                                             0
#घोषणा mmSEM_PERFCOUNTER1_RESULT                                                                      0x0107
#घोषणा mmSEM_PERFCOUNTER1_RESULT_BASE_IDX                                                             0
#घोषणा mmSEM_STATUS                                                                                   0x0108
#घोषणा mmSEM_STATUS_BASE_IDX                                                                          0
#घोषणा mmSEM_MAILBOX_CLIENTCONFIG                                                                     0x0109
#घोषणा mmSEM_MAILBOX_CLIENTCONFIG_BASE_IDX                                                            0
#घोषणा mmSEM_MAILBOX                                                                                  0x010a
#घोषणा mmSEM_MAILBOX_BASE_IDX                                                                         0
#घोषणा mmSEM_MAILBOX_CONTROL                                                                          0x010b
#घोषणा mmSEM_MAILBOX_CONTROL_BASE_IDX                                                                 0
#घोषणा mmSEM_CHICKEN_BITS                                                                             0x010c
#घोषणा mmSEM_CHICKEN_BITS_BASE_IDX                                                                    0
#घोषणा mmSEM_MAILBOX_CLIENTCONFIG_EXTRA                                                               0x010d
#घोषणा mmSEM_MAILBOX_CLIENTCONFIG_EXTRA_BASE_IDX                                                      0
#घोषणा mmSEM_GPU_IOV_VIOLATION_LOG                                                                    0x010e
#घोषणा mmSEM_GPU_IOV_VIOLATION_LOG_BASE_IDX                                                           0
#घोषणा mmSEM_OUTSTANDING_THRESHOLD                                                                    0x010f
#घोषणा mmSEM_OUTSTANDING_THRESHOLD_BASE_IDX                                                           0
#घोषणा mmSEM_REGISTER_LAST_PART2                                                                      0x017f
#घोषणा mmSEM_REGISTER_LAST_PART2_BASE_IDX                                                             0
#घोषणा mmIH_ACTIVE_FCN_ID                                                                             0x0180
#घोषणा mmIH_ACTIVE_FCN_ID_BASE_IDX                                                                    0
#घोषणा mmIH_VIRT_RESET_REQ                                                                            0x0181
#घोषणा mmIH_VIRT_RESET_REQ_BASE_IDX                                                                   0
#घोषणा mmIH_CLIENT_CFG                                                                                0x0184
#घोषणा mmIH_CLIENT_CFG_BASE_IDX                                                                       0
#घोषणा mmIH_CLIENT_CFG_INDEX                                                                          0x0188
#घोषणा mmIH_CLIENT_CFG_INDEX_BASE_IDX                                                                 0
#घोषणा mmIH_CLIENT_CFG_DATA                                                                           0x0189
#घोषणा mmIH_CLIENT_CFG_DATA_BASE_IDX                                                                  0
#घोषणा mmIH_CID_REMAP_INDEX                                                                           0x018a
#घोषणा mmIH_CID_REMAP_INDEX_BASE_IDX                                                                  0
#घोषणा mmIH_CID_REMAP_DATA                                                                            0x018b
#घोषणा mmIH_CID_REMAP_DATA_BASE_IDX                                                                   0
#घोषणा mmIH_CHICKEN                                                                                   0x018c
#घोषणा mmIH_CHICKEN_BASE_IDX                                                                          0
#घोषणा mmIH_MMHUB_CNTL                                                                                0x018d
#घोषणा mmIH_MMHUB_CNTL_BASE_IDX                                                                       0
#घोषणा mmIH_INT_DROP_CNTL                                                                             0x018e
#घोषणा mmIH_INT_DROP_CNTL_BASE_IDX                                                                    0
#घोषणा mmIH_INT_DROP_MATCH_VALUE0                                                                     0x018f
#घोषणा mmIH_INT_DROP_MATCH_VALUE0_BASE_IDX                                                            0
#घोषणा mmIH_INT_DROP_MATCH_VALUE1                                                                     0x0190
#घोषणा mmIH_INT_DROP_MATCH_VALUE1_BASE_IDX                                                            0
#घोषणा mmIH_INT_DROP_MATCH_MASK0                                                                      0x0191
#घोषणा mmIH_INT_DROP_MATCH_MASK0_BASE_IDX                                                             0
#घोषणा mmIH_INT_DROP_MATCH_MASK1                                                                      0x0192
#घोषणा mmIH_INT_DROP_MATCH_MASK1_BASE_IDX                                                             0
#घोषणा mmIH_REGISTER_LAST_PART1                                                                       0x019f
#घोषणा mmIH_REGISTER_LAST_PART1_BASE_IDX                                                              0
#घोषणा mmSEM_ACTIVE_FCN_ID                                                                            0x01a0
#घोषणा mmSEM_ACTIVE_FCN_ID_BASE_IDX                                                                   0
#घोषणा mmSEM_VIRT_RESET_REQ                                                                           0x01a1
#घोषणा mmSEM_VIRT_RESET_REQ_BASE_IDX                                                                  0
#घोषणा mmSEM_RESP_SDMA0                                                                               0x01a4
#घोषणा mmSEM_RESP_SDMA0_BASE_IDX                                                                      0
#घोषणा mmSEM_RESP_SDMA1                                                                               0x01a5
#घोषणा mmSEM_RESP_SDMA1_BASE_IDX                                                                      0
#घोषणा mmSEM_RESP_UVD                                                                                 0x01a6
#घोषणा mmSEM_RESP_UVD_BASE_IDX                                                                        0
#घोषणा mmSEM_RESP_VCE_0                                                                               0x01a7
#घोषणा mmSEM_RESP_VCE_0_BASE_IDX                                                                      0
#घोषणा mmSEM_RESP_ACP                                                                                 0x01a8
#घोषणा mmSEM_RESP_ACP_BASE_IDX                                                                        0
#घोषणा mmSEM_RESP_ISP                                                                                 0x01a9
#घोषणा mmSEM_RESP_ISP_BASE_IDX                                                                        0
#घोषणा mmSEM_RESP_VCE_1                                                                               0x01aa
#घोषणा mmSEM_RESP_VCE_1_BASE_IDX                                                                      0
#घोषणा mmSEM_RESP_VP8                                                                                 0x01ab
#घोषणा mmSEM_RESP_VP8_BASE_IDX                                                                        0
#घोषणा mmSEM_RESP_GC                                                                                  0x01ac
#घोषणा mmSEM_RESP_GC_BASE_IDX                                                                         0
#घोषणा mmSEM_CID_REMAP_INDEX                                                                          0x01b0
#घोषणा mmSEM_CID_REMAP_INDEX_BASE_IDX                                                                 0
#घोषणा mmSEM_CID_REMAP_DATA                                                                           0x01b1
#घोषणा mmSEM_CID_REMAP_DATA_BASE_IDX                                                                  0
#घोषणा mmSEM_ATOMIC_OP_LUT                                                                            0x01b2
#घोषणा mmSEM_ATOMIC_OP_LUT_BASE_IDX                                                                   0
#घोषणा mmSEM_EDC_CONFIG                                                                               0x01b3
#घोषणा mmSEM_EDC_CONFIG_BASE_IDX                                                                      0
#घोषणा mmSEM_CHICKEN_BITS2                                                                            0x01b4
#घोषणा mmSEM_CHICKEN_BITS2_BASE_IDX                                                                   0
#घोषणा mmSEM_MMHUB_CNTL                                                                               0x01b5
#घोषणा mmSEM_MMHUB_CNTL_BASE_IDX                                                                      0
#घोषणा mmSEM_REGISTER_LAST_PART1                                                                      0x01bf
#घोषणा mmSEM_REGISTER_LAST_PART1_BASE_IDX                                                             0

#पूर्ण_अगर
