<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
/*
 * Copyright (c) 2015-2020, NVIDIA CORPORATION.  All rights reserved.
 */

#अगर_अघोषित TEGRA210_EMC_H
#घोषणा TEGRA210_EMC_H

#समावेश <linux/clk.h>
#समावेश <linux/clk/tegra.h>
#समावेश <linux/पन.स>
#समावेश <linux/platक्रमm_device.h>

#घोषणा DVFS_FGCG_HIGH_SPEED_THRESHOLD				1000
#घोषणा IOBRICK_DCC_THRESHOLD					2400
#घोषणा DVFS_FGCG_MID_SPEED_THRESHOLD				600

#घोषणा EMC_STATUS_UPDATE_TIMEOUT				1000

/* रेजिस्टर definitions */
#घोषणा EMC_INTSTATUS						0x0
#घोषणा EMC_INTSTATUS_CLKCHANGE_COMPLETE			BIT(4)
#घोषणा EMC_DBG							0x8
#घोषणा EMC_DBG_WRITE_MUX_ACTIVE				BIT(1)
#घोषणा EMC_DBG_WRITE_ACTIVE_ONLY				BIT(30)
#घोषणा EMC_CFG							0xc
#घोषणा EMC_CFG_DRAM_CLKSTOP_PD					BIT(31)
#घोषणा EMC_CFG_DRAM_CLKSTOP_SR					BIT(30)
#घोषणा EMC_CFG_DRAM_ACPD					BIT(29)
#घोषणा EMC_CFG_DYN_SELF_REF					BIT(28)
#घोषणा EMC_PIN							0x24
#घोषणा EMC_PIN_PIN_CKE						BIT(0)
#घोषणा EMC_PIN_PIN_CKEB					BIT(1)
#घोषणा EMC_PIN_PIN_CKE_PER_DEV					BIT(2)
#घोषणा EMC_TIMING_CONTROL					0x28
#घोषणा EMC_RC							0x2c
#घोषणा EMC_RFC							0x30
#घोषणा EMC_RAS							0x34
#घोषणा EMC_RP							0x38
#घोषणा EMC_R2W							0x3c
#घोषणा EMC_W2R							0x40
#घोषणा EMC_R2P							0x44
#घोषणा EMC_W2P							0x48
#घोषणा EMC_RD_RCD						0x4c
#घोषणा EMC_WR_RCD						0x50
#घोषणा EMC_RRD							0x54
#घोषणा EMC_REXT						0x58
#घोषणा EMC_WDV							0x5c
#घोषणा EMC_QUSE						0x60
#घोषणा EMC_QRST						0x64
#घोषणा EMC_QSAFE						0x68
#घोषणा EMC_RDV							0x6c
#घोषणा EMC_REFRESH						0x70
#घोषणा EMC_BURST_REFRESH_NUM					0x74
#घोषणा EMC_PDEX2WR						0x78
#घोषणा EMC_PDEX2RD						0x7c
#घोषणा EMC_PCHG2PDEN						0x80
#घोषणा EMC_ACT2PDEN						0x84
#घोषणा EMC_AR2PDEN						0x88
#घोषणा EMC_RW2PDEN						0x8c
#घोषणा EMC_TXSR						0x90
#घोषणा EMC_TCKE						0x94
#घोषणा EMC_TFAW						0x98
#घोषणा EMC_TRPAB						0x9c
#घोषणा EMC_TCLKSTABLE						0xa0
#घोषणा EMC_TCLKSTOP						0xa4
#घोषणा EMC_TREFBW						0xa8
#घोषणा EMC_TPPD						0xac
#घोषणा EMC_ODT_WRITE						0xb0
#घोषणा EMC_PDEX2MRR						0xb4
#घोषणा EMC_WEXT						0xb8
#घोषणा EMC_RFC_SLR						0xc0
#घोषणा EMC_MRS_WAIT_CNT2					0xc4
#घोषणा EMC_MRS_WAIT_CNT2_MRS_EXT2_WAIT_CNT_SHIFT		16
#घोषणा EMC_MRS_WAIT_CNT2_MRS_EXT1_WAIT_CNT_SHIFT		0
#घोषणा EMC_MRS_WAIT_CNT					0xc8
#घोषणा EMC_MRS_WAIT_CNT_SHORT_WAIT_SHIFT			0
#घोषणा EMC_MRS_WAIT_CNT_SHORT_WAIT_MASK			\
	(0x3FF << EMC_MRS_WAIT_CNT_SHORT_WAIT_SHIFT)

#घोषणा EMC_MRS							0xcc
#घोषणा EMC_EMRS						0xd0
#घोषणा EMC_EMRS_USE_EMRS_LONG_CNT				BIT(26)
#घोषणा EMC_REF							0xd4
#घोषणा  EMC_REF_REF_CMD					BIT(0)
#घोषणा EMC_SELF_REF						0xe0
#घोषणा EMC_MRW							0xe8
#घोषणा EMC_MRW_MRW_OP_SHIFT					0
#घोषणा EMC_MRW_MRW_OP_MASK					\
	(0xff << EMC_MRW_MRW_OP_SHIFT)
#घोषणा EMC_MRW_MRW_MA_SHIFT					16
#घोषणा EMC_MRW_USE_MRW_EXT_CNT					27
#घोषणा EMC_MRW_MRW_DEV_SELECTN_SHIFT				30

#घोषणा EMC_MRR							0xec
#घोषणा EMC_MRR_DEV_SEL_SHIFT					30
#घोषणा EMC_MRR_DEV_SEL_MASK					0x3
#घोषणा EMC_MRR_MA_SHIFT					16
#घोषणा EMC_MRR_MA_MASK						0xff
#घोषणा EMC_MRR_DATA_SHIFT					0
#घोषणा EMC_MRR_DATA_MASK					0xffff

#घोषणा EMC_FBIO_SPARE						0x100
#घोषणा EMC_FBIO_CFG5						0x104
#घोषणा EMC_FBIO_CFG5_DRAM_TYPE_SHIFT				0
#घोषणा EMC_FBIO_CFG5_DRAM_TYPE_MASK				\
	(0x3 << EMC_FBIO_CFG5_DRAM_TYPE_SHIFT)
#घोषणा EMC_FBIO_CFG5_CMD_TX_DIS				BIT(8)

#घोषणा EMC_PDEX2CKE						0x118
#घोषणा EMC_CKE2PDEN						0x11c
#घोषणा EMC_MPC							0x128
#घोषणा EMC_EMRS2						0x12c
#घोषणा EMC_EMRS2_USE_EMRS2_LONG_CNT				BIT(26)
#घोषणा EMC_MRW2						0x134
#घोषणा EMC_MRW3						0x138
#घोषणा EMC_MRW4						0x13c
#घोषणा EMC_R2R							0x144
#घोषणा EMC_EINPUT						0x14c
#घोषणा EMC_EINPUT_DURATION					0x150
#घोषणा EMC_PUTERM_EXTRA					0x154
#घोषणा EMC_TCKESR						0x158
#घोषणा EMC_TPD							0x15c
#घोषणा EMC_AUTO_CAL_CONFIG					0x2a4
#घोषणा EMC_AUTO_CAL_CONFIG_AUTO_CAL_COMPUTE_START		BIT(0)
#घोषणा EMC_AUTO_CAL_CONFIG_AUTO_CAL_MEASURE_STALL		BIT(9)
#घोषणा EMC_AUTO_CAL_CONFIG_AUTO_CAL_UPDATE_STALL		BIT(10)
#घोषणा EMC_AUTO_CAL_CONFIG_AUTO_CAL_ENABLE			BIT(29)
#घोषणा EMC_AUTO_CAL_CONFIG_AUTO_CAL_START			BIT(31)
#घोषणा EMC_EMC_STATUS						0x2b4
#घोषणा EMC_EMC_STATUS_MRR_DIVLD				BIT(20)
#घोषणा EMC_EMC_STATUS_TIMING_UPDATE_STALLED			BIT(23)
#घोषणा EMC_EMC_STATUS_DRAM_IN_POWERDOWN_SHIFT			4
#घोषणा EMC_EMC_STATUS_DRAM_IN_POWERDOWN_MASK			\
	(0x3 << EMC_EMC_STATUS_DRAM_IN_POWERDOWN_SHIFT)
#घोषणा EMC_EMC_STATUS_DRAM_IN_SELF_REFRESH_SHIFT		8
#घोषणा EMC_EMC_STATUS_DRAM_IN_SELF_REFRESH_MASK		\
	(0x3 << EMC_EMC_STATUS_DRAM_IN_SELF_REFRESH_SHIFT)

#घोषणा EMC_CFG_2						0x2b8
#घोषणा EMC_CFG_DIG_DLL						0x2bc
#घोषणा EMC_CFG_DIG_DLL_CFG_DLL_EN				BIT(0)
#घोषणा EMC_CFG_DIG_DLL_CFG_DLL_STALL_ALL_UNTIL_LOCK		BIT(1)
#घोषणा EMC_CFG_DIG_DLL_CFG_DLL_STALL_ALL_TRAFFIC		BIT(3)
#घोषणा EMC_CFG_DIG_DLL_CFG_DLL_STALL_RW_UNTIL_LOCK		BIT(4)
#घोषणा EMC_CFG_DIG_DLL_CFG_DLL_MODE_SHIFT			6
#घोषणा EMC_CFG_DIG_DLL_CFG_DLL_MODE_MASK			\
	(0x3 << EMC_CFG_DIG_DLL_CFG_DLL_MODE_SHIFT)
#घोषणा EMC_CFG_DIG_DLL_CFG_DLL_LOCK_LIMIT_SHIFT		8
#घोषणा EMC_CFG_DIG_DLL_CFG_DLL_LOCK_LIMIT_MASK			\
	(0x7 << EMC_CFG_DIG_DLL_CFG_DLL_LOCK_LIMIT_SHIFT)

#घोषणा EMC_CFG_DIG_DLL_PERIOD					0x2c0
#घोषणा EMC_DIG_DLL_STATUS					0x2c4
#घोषणा EMC_DIG_DLL_STATUS_DLL_LOCK				BIT(15)
#घोषणा EMC_DIG_DLL_STATUS_DLL_PRIV_UPDATED			BIT(17)
#घोषणा EMC_DIG_DLL_STATUS_DLL_OUT_SHIFT			0
#घोषणा EMC_DIG_DLL_STATUS_DLL_OUT_MASK				\
	(0x7ff << EMC_DIG_DLL_STATUS_DLL_OUT_SHIFT)

#घोषणा EMC_CFG_DIG_DLL_1					0x2c8
#घोषणा EMC_RDV_MASK						0x2cc
#घोषणा EMC_WDV_MASK						0x2d0
#घोषणा EMC_RDV_EARLY_MASK					0x2d4
#घोषणा EMC_RDV_EARLY						0x2d8
#घोषणा EMC_AUTO_CAL_CONFIG8					0x2dc
#घोषणा EMC_ZCAL_INTERVAL					0x2e0
#घोषणा EMC_ZCAL_WAIT_CNT					0x2e4
#घोषणा EMC_ZCAL_WAIT_CNT_ZCAL_WAIT_CNT_MASK			0x7ff
#घोषणा EMC_ZCAL_WAIT_CNT_ZCAL_WAIT_CNT_SHIFT			0

#घोषणा EMC_ZQ_CAL						0x2ec
#घोषणा EMC_ZQ_CAL_DEV_SEL_SHIFT				30
#घोषणा EMC_ZQ_CAL_LONG						BIT(4)
#घोषणा EMC_ZQ_CAL_ZQ_LATCH_CMD					BIT(1)
#घोषणा EMC_ZQ_CAL_ZQ_CAL_CMD					BIT(0)
#घोषणा EMC_FDPD_CTRL_DQ					0x310
#घोषणा EMC_FDPD_CTRL_CMD					0x314
#घोषणा EMC_PMACRO_CMD_BRICK_CTRL_FDPD				0x318
#घोषणा EMC_PMACRO_DATA_BRICK_CTRL_FDPD				0x31c
#घोषणा EMC_PMACRO_BRICK_CTRL_RFU1				0x330
#घोषणा EMC_PMACRO_BRICK_CTRL_RFU2				0x334
#घोषणा EMC_TR_TIMING_0						0x3b4
#घोषणा EMC_TR_CTRL_1						0x3bc
#घोषणा EMC_TR_RDV						0x3c4
#घोषणा EMC_STALL_THEN_EXE_AFTER_CLKCHANGE			0x3cc
#घोषणा EMC_SEL_DPD_CTRL					0x3d8
#घोषणा EMC_SEL_DPD_CTRL_DATA_SEL_DPD_EN			BIT(8)
#घोषणा EMC_SEL_DPD_CTRL_ODT_SEL_DPD_EN				BIT(5)
#घोषणा EMC_SEL_DPD_CTRL_RESET_SEL_DPD_EN			BIT(4)
#घोषणा EMC_SEL_DPD_CTRL_CA_SEL_DPD_EN				BIT(3)
#घोषणा EMC_SEL_DPD_CTRL_CLK_SEL_DPD_EN				BIT(2)
#घोषणा EMC_PRE_REFRESH_REQ_CNT					0x3dc
#घोषणा EMC_DYN_SELF_REF_CONTROL				0x3e0
#घोषणा EMC_TXSRDLL						0x3e4
#घोषणा EMC_CCFIFO_ADDR						0x3e8
#घोषणा  EMC_CCFIFO_ADDR_STALL_BY_1 (1 << 31)
#घोषणा  EMC_CCFIFO_ADDR_STALL(x) (((x) & 0x7fff) << 16)
#घोषणा  EMC_CCFIFO_ADDR_OFFSET(x) ((x) & 0xffff)
#घोषणा EMC_CCFIFO_DATA						0x3ec
#घोषणा EMC_TR_QPOP						0x3f4
#घोषणा EMC_TR_RDV_MASK						0x3f8
#घोषणा EMC_TR_QSAFE						0x3fc
#घोषणा EMC_TR_QRST						0x400
#घोषणा EMC_ISSUE_QRST						0x428
#घोषणा EMC_AUTO_CAL_CONFIG2					0x458
#घोषणा EMC_AUTO_CAL_CONFIG3					0x45c
#घोषणा EMC_TR_DVFS						0x460
#घोषणा EMC_AUTO_CAL_CHANNEL					0x464
#घोषणा EMC_IBDLY						0x468
#घोषणा EMC_OBDLY						0x46c
#घोषणा EMC_TXDSRVTTGEN						0x480
#घोषणा EMC_WE_DURATION						0x48c
#घोषणा EMC_WS_DURATION						0x490
#घोषणा EMC_WEV							0x494
#घोषणा EMC_WSV							0x498
#घोषणा EMC_CFG_3						0x49c
#घोषणा EMC_MRW6						0x4a4
#घोषणा EMC_MRW7						0x4a8
#घोषणा EMC_MRW8						0x4ac
#घोषणा EMC_MRW9						0x4b0
#घोषणा EMC_MRW10						0x4b4
#घोषणा EMC_MRW11						0x4b8
#घोषणा EMC_MRW12						0x4bc
#घोषणा EMC_MRW13						0x4c0
#घोषणा EMC_MRW14						0x4c4
#घोषणा EMC_MRW15						0x4d0
#घोषणा EMC_CFG_SYNC						0x4d4
#घोषणा EMC_FDPD_CTRL_CMD_NO_RAMP				0x4d8
#घोषणा EMC_FDPD_CTRL_CMD_NO_RAMP_CMD_DPD_NO_RAMP_ENABLE	BIT(0)
#घोषणा EMC_WDV_CHK						0x4e0
#घोषणा EMC_CFG_PIPE_2						0x554
#घोषणा EMC_CFG_PIPE_CLK					0x558
#घोषणा EMC_CFG_PIPE_CLK_CLK_ALWAYS_ON				BIT(0)
#घोषणा EMC_CFG_PIPE_1						0x55c
#घोषणा EMC_CFG_PIPE						0x560
#घोषणा EMC_QPOP						0x564
#घोषणा EMC_QUSE_WIDTH						0x568
#घोषणा EMC_PUTERM_WIDTH					0x56c
#घोषणा EMC_AUTO_CAL_CONFIG7					0x574
#घोषणा EMC_REFCTRL2						0x580
#घोषणा EMC_FBIO_CFG7						0x584
#घोषणा EMC_FBIO_CFG7_CH0_ENABLE				BIT(1)
#घोषणा EMC_FBIO_CFG7_CH1_ENABLE				BIT(2)
#घोषणा EMC_DATA_BRLSHFT_0					0x588
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE7_DATA_BRLSHFT_SHIFT	21
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE7_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_0_RANK0_BYTE7_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE6_DATA_BRLSHFT_SHIFT	18
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE6_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_0_RANK0_BYTE6_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE5_DATA_BRLSHFT_SHIFT	15
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE5_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_0_RANK0_BYTE5_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE4_DATA_BRLSHFT_SHIFT	12
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE4_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_0_RANK0_BYTE4_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE3_DATA_BRLSHFT_SHIFT	9
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE3_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_0_RANK0_BYTE3_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE2_DATA_BRLSHFT_SHIFT	6
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE2_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_0_RANK0_BYTE2_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE1_DATA_BRLSHFT_SHIFT	3
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE1_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_0_RANK0_BYTE1_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE0_DATA_BRLSHFT_SHIFT	0
#घोषणा EMC_DATA_BRLSHFT_0_RANK0_BYTE0_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_0_RANK0_BYTE0_DATA_BRLSHFT_SHIFT)

#घोषणा EMC_DATA_BRLSHFT_1					0x58c
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE7_DATA_BRLSHFT_SHIFT	21
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE7_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_1_RANK1_BYTE7_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE6_DATA_BRLSHFT_SHIFT	18
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE6_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_1_RANK1_BYTE6_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE5_DATA_BRLSHFT_SHIFT	15
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE5_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_1_RANK1_BYTE5_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE4_DATA_BRLSHFT_SHIFT	12
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE4_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_1_RANK1_BYTE4_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE3_DATA_BRLSHFT_SHIFT	9
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE3_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_1_RANK1_BYTE3_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE2_DATA_BRLSHFT_SHIFT	6
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE2_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_1_RANK1_BYTE2_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE1_DATA_BRLSHFT_SHIFT	3
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE1_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_1_RANK1_BYTE1_DATA_BRLSHFT_SHIFT)
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE0_DATA_BRLSHFT_SHIFT	0
#घोषणा EMC_DATA_BRLSHFT_1_RANK1_BYTE0_DATA_BRLSHFT_MASK	\
	(0x7 << EMC_DATA_BRLSHFT_1_RANK1_BYTE0_DATA_BRLSHFT_SHIFT)

#घोषणा EMC_RFCPB						0x590
#घोषणा EMC_DQS_BRLSHFT_0					0x594
#घोषणा EMC_DQS_BRLSHFT_1					0x598
#घोषणा EMC_CMD_BRLSHFT_0					0x59c
#घोषणा EMC_CMD_BRLSHFT_1					0x5a0
#घोषणा EMC_CMD_BRLSHFT_2					0x5a4
#घोषणा EMC_CMD_BRLSHFT_3					0x5a8
#घोषणा EMC_QUSE_BRLSHFT_0					0x5ac
#घोषणा EMC_AUTO_CAL_CONFIG4					0x5b0
#घोषणा EMC_AUTO_CAL_CONFIG5					0x5b4
#घोषणा EMC_QUSE_BRLSHFT_1					0x5b8
#घोषणा EMC_QUSE_BRLSHFT_2					0x5bc
#घोषणा EMC_CCDMW						0x5c0
#घोषणा EMC_QUSE_BRLSHFT_3					0x5c4
#घोषणा EMC_AUTO_CAL_CONFIG6					0x5cc
#घोषणा EMC_DLL_CFG_0						0x5e4
#घोषणा EMC_DLL_CFG_1						0x5e8
#घोषणा EMC_DLL_CFG_1_DDLLCAL_CTRL_START_TRIM_SHIFT		10
#घोषणा EMC_DLL_CFG_1_DDLLCAL_CTRL_START_TRIM_MASK		\
	(0x7ff << EMC_DLL_CFG_1_DDLLCAL_CTRL_START_TRIM_SHIFT)

#घोषणा EMC_CONFIG_SAMPLE_DELAY					0x5f0
#घोषणा EMC_CFG_UPDATE						0x5f4
#घोषणा EMC_CFG_UPDATE_UPDATE_DLL_IN_UPDATE_SHIFT		9
#घोषणा EMC_CFG_UPDATE_UPDATE_DLL_IN_UPDATE_MASK		\
	(0x3 << EMC_CFG_UPDATE_UPDATE_DLL_IN_UPDATE_SHIFT)

#घोषणा EMC_PMACRO_QUSE_DDLL_RANK0_0				0x600
#घोषणा EMC_PMACRO_QUSE_DDLL_RANK0_1				0x604
#घोषणा EMC_PMACRO_QUSE_DDLL_RANK0_2				0x608
#घोषणा EMC_PMACRO_QUSE_DDLL_RANK0_3				0x60c
#घोषणा EMC_PMACRO_QUSE_DDLL_RANK0_4				0x610
#घोषणा EMC_PMACRO_QUSE_DDLL_RANK0_5				0x614
#घोषणा EMC_PMACRO_QUSE_DDLL_RANK1_0				0x620
#घोषणा EMC_PMACRO_QUSE_DDLL_RANK1_1				0x624
#घोषणा EMC_PMACRO_QUSE_DDLL_RANK1_2				0x628
#घोषणा EMC_PMACRO_QUSE_DDLL_RANK1_3				0x62c
#घोषणा EMC_PMACRO_QUSE_DDLL_RANK1_4				0x630
#घोषणा EMC_PMACRO_QUSE_DDLL_RANK1_5				0x634
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_0			0x640
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_0_OB_DDLL_LONG_DQ_RANK0_BYTE1_SHIFT \
	16
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_0_OB_DDLL_LONG_DQ_RANK0_BYTE1_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_0_OB_DDLL_LONG_DQ_RANK0_BYTE1_SHIFT)
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_0_OB_DDLL_LONG_DQ_RANK0_BYTE0_SHIFT \
	0
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_0_OB_DDLL_LONG_DQ_RANK0_BYTE0_MASK \
	(0x3ff <<							    \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_0_OB_DDLL_LONG_DQ_RANK0_BYTE0_SHIFT)

#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_1			0x644
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_1_OB_DDLL_LONG_DQ_RANK0_BYTE3_SHIFT \
	16
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_1_OB_DDLL_LONG_DQ_RANK0_BYTE3_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_1_OB_DDLL_LONG_DQ_RANK0_BYTE3_SHIFT)
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_1_OB_DDLL_LONG_DQ_RANK0_BYTE2_SHIFT \
	0
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_1_OB_DDLL_LONG_DQ_RANK0_BYTE2_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_1_OB_DDLL_LONG_DQ_RANK0_BYTE2_SHIFT)

#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_2			0x648
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_2_OB_DDLL_LONG_DQ_RANK0_BYTE5_SHIFT  \
	16
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_2_OB_DDLL_LONG_DQ_RANK0_BYTE5_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_2_OB_DDLL_LONG_DQ_RANK0_BYTE5_SHIFT)
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_2_OB_DDLL_LONG_DQ_RANK0_BYTE4_SHIFT \
	0
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_2_OB_DDLL_LONG_DQ_RANK0_BYTE4_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_2_OB_DDLL_LONG_DQ_RANK0_BYTE4_SHIFT)

#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_3			0x64c
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_3_OB_DDLL_LONG_DQ_RANK0_BYTE7_SHIFT \
	16
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_3_OB_DDLL_LONG_DQ_RANK0_BYTE7_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_3_OB_DDLL_LONG_DQ_RANK0_BYTE7_SHIFT)
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_3_OB_DDLL_LONG_DQ_RANK0_BYTE6_SHIFT \
	0
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_3_OB_DDLL_LONG_DQ_RANK0_BYTE6_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_3_OB_DDLL_LONG_DQ_RANK0_BYTE6_SHIFT)

#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_4			0x650
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_5			0x654
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_0			0x660
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_0_OB_DDLL_LONG_DQ_RANK1_BYTE1_SHIFT \
	16
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_0_OB_DDLL_LONG_DQ_RANK1_BYTE1_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_0_OB_DDLL_LONG_DQ_RANK1_BYTE1_SHIFT)
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_0_OB_DDLL_LONG_DQ_RANK1_BYTE0_SHIFT \
	0
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_0_OB_DDLL_LONG_DQ_RANK1_BYTE0_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_0_OB_DDLL_LONG_DQ_RANK1_BYTE0_SHIFT)

#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_1			0x664
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_1_OB_DDLL_LONG_DQ_RANK1_BYTE3_SHIFT \
	16
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_1_OB_DDLL_LONG_DQ_RANK1_BYTE3_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_1_OB_DDLL_LONG_DQ_RANK1_BYTE3_SHIFT)
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_1_OB_DDLL_LONG_DQ_RANK1_BYTE2_SHIFT \
	0
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_1_OB_DDLL_LONG_DQ_RANK1_BYTE2_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_1_OB_DDLL_LONG_DQ_RANK1_BYTE2_SHIFT)

#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_2			0x668
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_2_OB_DDLL_LONG_DQ_RANK1_BYTE5_SHIFT \
	16
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_2_OB_DDLL_LONG_DQ_RANK1_BYTE5_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_2_OB_DDLL_LONG_DQ_RANK1_BYTE5_SHIFT)
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_2_OB_DDLL_LONG_DQ_RANK1_BYTE4_SHIFT \
	0
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_2_OB_DDLL_LONG_DQ_RANK1_BYTE4_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_2_OB_DDLL_LONG_DQ_RANK1_BYTE4_SHIFT)

#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_3			0x66c
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_3_OB_DDLL_LONG_DQ_RANK1_BYTE7_SHIFT \
	16
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_3_OB_DDLL_LONG_DQ_RANK1_BYTE7_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_3_OB_DDLL_LONG_DQ_RANK1_BYTE7_SHIFT)
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_3_OB_DDLL_LONG_DQ_RANK1_BYTE6_SHIFT \
	0
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_3_OB_DDLL_LONG_DQ_RANK1_BYTE6_MASK  \
	(0x3ff <<							     \
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_3_OB_DDLL_LONG_DQ_RANK1_BYTE6_SHIFT)

#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_4			0x670
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_5			0x674
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQS_RANK0_0			0x680
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQS_RANK0_1			0x684
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQS_RANK0_2			0x688
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQS_RANK0_3			0x68c
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQS_RANK0_4			0x690
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQS_RANK0_5			0x694
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQS_RANK1_0			0x6a0
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQS_RANK1_1			0x6a4
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQS_RANK1_2			0x6a8
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQS_RANK1_3			0x6ac
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQS_RANK1_4			0x6b0
#घोषणा EMC_PMACRO_OB_DDLL_LONG_DQS_RANK1_5			0x6b4
#घोषणा EMC_PMACRO_IB_DDLL_LONG_DQS_RANK0_0			0x6c0
#घोषणा EMC_PMACRO_IB_DDLL_LONG_DQS_RANK0_1			0x6c4
#घोषणा EMC_PMACRO_IB_DDLL_LONG_DQS_RANK0_2			0x6c8
#घोषणा EMC_PMACRO_IB_DDLL_LONG_DQS_RANK0_3			0x6cc
#घोषणा EMC_PMACRO_IB_DDLL_LONG_DQS_RANK1_0			0x6e0
#घोषणा EMC_PMACRO_IB_DDLL_LONG_DQS_RANK1_1			0x6e4
#घोषणा EMC_PMACRO_IB_DDLL_LONG_DQS_RANK1_2			0x6e8
#घोषणा EMC_PMACRO_IB_DDLL_LONG_DQS_RANK1_3			0x6ec
#घोषणा EMC_PMACRO_TX_PWRD_0					0x720
#घोषणा EMC_PMACRO_TX_PWRD_1					0x724
#घोषणा EMC_PMACRO_TX_PWRD_2					0x728
#घोषणा EMC_PMACRO_TX_PWRD_3					0x72c
#घोषणा EMC_PMACRO_TX_PWRD_4					0x730
#घोषणा EMC_PMACRO_TX_PWRD_5					0x734
#घोषणा EMC_PMACRO_TX_SEL_CLK_SRC_0				0x740
#घोषणा EMC_PMACRO_TX_SEL_CLK_SRC_1				0x744
#घोषणा EMC_PMACRO_TX_SEL_CLK_SRC_3				0x74c
#घोषणा EMC_PMACRO_TX_SEL_CLK_SRC_2				0x748
#घोषणा EMC_PMACRO_TX_SEL_CLK_SRC_4				0x750
#घोषणा EMC_PMACRO_TX_SEL_CLK_SRC_5				0x754
#घोषणा EMC_PMACRO_DDLL_BYPASS					0x760
#घोषणा EMC_PMACRO_DDLL_PWRD_0					0x770
#घोषणा EMC_PMACRO_DDLL_PWRD_1					0x774
#घोषणा EMC_PMACRO_DDLL_PWRD_2					0x778
#घोषणा EMC_PMACRO_CMD_CTRL_0					0x780
#घोषणा EMC_PMACRO_CMD_CTRL_1					0x784
#घोषणा EMC_PMACRO_CMD_CTRL_2					0x788
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE0_0		0x800
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE0_1		0x804
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE0_2		0x808
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE0_3		0x80c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE1_0		0x810
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE1_1		0x814
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE1_2		0x818
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE1_3		0x81c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE2_0		0x820
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE2_1		0x824
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE2_2		0x828
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE2_3		0x82c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE3_0		0x830
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE3_1		0x834
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE3_2		0x838
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE3_3		0x83c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE4_0		0x840
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE4_1		0x844
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE4_2		0x848
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE4_3		0x84c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE5_0		0x850
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE5_1		0x854
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE5_2		0x858
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE5_3		0x85c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE6_0		0x860
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE6_1		0x864
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE6_2		0x868
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE6_3		0x86c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE7_0		0x870
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE7_1		0x874
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE7_2		0x878
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_BYTE7_3		0x87c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD0_0		0x880
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD0_1		0x884
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD0_2		0x888
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD0_3		0x88c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD1_0		0x890
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD1_1		0x894
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD1_2		0x898
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD1_3		0x89c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD2_0		0x8a0
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD2_1		0x8a4
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD2_2		0x8a8
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD2_3		0x8ac
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD3_0		0x8b0
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD3_1		0x8b4
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD3_2		0x8b8
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK0_CMD3_3		0x8bc
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE0_0		0x900
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE0_1		0x904
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE0_2		0x908
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE0_3		0x90c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE1_0		0x910
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE1_1		0x914
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE1_2		0x918
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE1_3		0x91c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE2_0		0x920
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE2_1		0x924
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE2_2		0x928
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE2_3		0x92c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE3_0		0x930
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE3_1		0x934
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE3_2		0x938
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE3_3		0x93c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE4_0		0x940
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE4_1		0x944
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE4_2		0x948
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE4_3		0x94c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE5_0		0x950
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE5_1		0x954
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE5_2		0x958
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE5_3		0x95c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE6_0		0x960
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE6_1		0x964
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE6_2		0x968
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE6_3		0x96c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE7_0		0x970
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE7_1		0x974
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE7_2		0x978
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_BYTE7_3		0x97c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD0_0		0x980
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD0_1		0x984
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD0_2		0x988
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD0_3		0x98c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD1_0		0x990
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD1_1		0x994
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD1_2		0x998
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD1_3		0x99c
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD2_0		0x9a0
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD2_1		0x9a4
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD2_2		0x9a8
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD2_3		0x9ac
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD3_0		0x9b0
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD3_1		0x9b4
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD3_2		0x9b8
#घोषणा EMC_PMACRO_OB_DDLL_SHORT_DQ_RANK1_CMD3_3		0x9bc
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE0_0		0xa00
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE0_1		0xa04
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE0_2		0xa08
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE1_0		0xa10
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE1_1		0xa14
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE1_2		0xa18
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE2_0		0xa20
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE2_1		0xa24
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE2_2		0xa28
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE3_0		0xa30
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE3_1		0xa34
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE3_2		0xa38
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE4_0		0xa40
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE4_1		0xa44
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE4_2		0xa48
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE5_0		0xa50
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE5_1		0xa54
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE5_2		0xa58
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE6_0		0xa60
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE6_1		0xa64
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE6_2		0xa68
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE7_0		0xa70
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE7_1		0xa74
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK0_BYTE7_2		0xa78
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE0_0		0xb00
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE0_1		0xb04
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE0_2		0xb08
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE1_0		0xb10
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE1_1		0xb14
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE1_2		0xb18
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE2_0		0xb20
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE2_1		0xb24
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE2_2		0xb28
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE3_0		0xb30
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE3_1		0xb34
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE3_2		0xb38
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE4_0		0xb40
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE4_1		0xb44
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE4_2		0xb48
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE5_0		0xb50
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE5_1		0xb54
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE5_2		0xb58
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE6_0		0xb60
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE6_1		0xb64
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE6_2		0xb68
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE7_0		0xb70
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE7_1		0xb74
#घोषणा EMC_PMACRO_IB_DDLL_SHORT_DQ_RANK1_BYTE7_2		0xb78
#घोषणा EMC_PMACRO_IB_VREF_DQ_0					0xbe0
#घोषणा EMC_PMACRO_IB_VREF_DQ_1					0xbe4
#घोषणा EMC_PMACRO_IB_VREF_DQS_0				0xbf0
#घोषणा EMC_PMACRO_IB_VREF_DQS_1				0xbf4
#घोषणा EMC_PMACRO_DDLL_LONG_CMD_0				0xc00
#घोषणा EMC_PMACRO_DDLL_LONG_CMD_1				0xc04
#घोषणा EMC_PMACRO_DDLL_LONG_CMD_2				0xc08
#घोषणा EMC_PMACRO_DDLL_LONG_CMD_3				0xc0c
#घोषणा EMC_PMACRO_DDLL_LONG_CMD_4				0xc10
#घोषणा EMC_PMACRO_DDLL_LONG_CMD_5				0xc14
#घोषणा EMC_PMACRO_DDLL_SHORT_CMD_0				0xc20
#घोषणा EMC_PMACRO_DDLL_SHORT_CMD_1				0xc24
#घोषणा EMC_PMACRO_DDLL_SHORT_CMD_2				0xc28
#घोषणा EMC_PMACRO_CFG_PM_GLOBAL_0				0xc30
#घोषणा EMC_PMACRO_CFG_PM_GLOBAL_0_DISABLE_CFG_BYTE0		BIT(16)
#घोषणा EMC_PMACRO_CFG_PM_GLOBAL_0_DISABLE_CFG_BYTE1		BIT(17)
#घोषणा EMC_PMACRO_CFG_PM_GLOBAL_0_DISABLE_CFG_BYTE2		BIT(18)
#घोषणा EMC_PMACRO_CFG_PM_GLOBAL_0_DISABLE_CFG_BYTE3		BIT(19)
#घोषणा EMC_PMACRO_CFG_PM_GLOBAL_0_DISABLE_CFG_BYTE4		BIT(20)
#घोषणा EMC_PMACRO_CFG_PM_GLOBAL_0_DISABLE_CFG_BYTE5		BIT(21)
#घोषणा EMC_PMACRO_CFG_PM_GLOBAL_0_DISABLE_CFG_BYTE6		BIT(22)
#घोषणा EMC_PMACRO_CFG_PM_GLOBAL_0_DISABLE_CFG_BYTE7		BIT(23)
#घोषणा EMC_PMACRO_VTTGEN_CTRL_0				0xc34
#घोषणा EMC_PMACRO_VTTGEN_CTRL_1				0xc38
#घोषणा EMC_PMACRO_BG_BIAS_CTRL_0				0xc3c
#घोषणा EMC_PMACRO_BG_BIAS_CTRL_0_BG_E_PWRD			BIT(0)
#घोषणा EMC_PMACRO_BG_BIAS_CTRL_0_BGLP_E_PWRD			BIT(2)
#घोषणा EMC_PMACRO_PAD_CFG_CTRL					0xc40
#घोषणा EMC_PMACRO_ZCTRL					0xc44
#घोषणा EMC_PMACRO_CMD_PAD_RX_CTRL				0xc50
#घोषणा EMC_PMACRO_DATA_PAD_RX_CTRL				0xc54
#घोषणा EMC_PMACRO_CMD_RX_TERM_MODE				0xc58
#घोषणा EMC_PMACRO_DATA_RX_TERM_MODE				0xc5c
#घोषणा EMC_PMACRO_CMD_PAD_TX_CTRL				0xc60
#घोषणा EMC_PMACRO_CMD_PAD_TX_CTRL_CMD_DQ_TX_E_DCC		BIT(1)
#घोषणा EMC_PMACRO_CMD_PAD_TX_CTRL_CMD_DQSP_TX_E_DCC		BIT(9)
#घोषणा EMC_PMACRO_CMD_PAD_TX_CTRL_CMD_DQSN_TX_E_DCC		BIT(16)
#घोषणा EMC_PMACRO_CMD_PAD_TX_CTRL_CMD_CMD_TX_E_DCC		BIT(24)
#घोषणा EMC_PMACRO_CMD_PAD_TX_CTRL_CMD_DQ_TX_DRVFORCEON		BIT(26)

#घोषणा EMC_PMACRO_DATA_PAD_TX_CTRL				0xc64
#घोषणा EMC_PMACRO_DATA_PAD_TX_CTRL_DATA_DQ_E_IVREF		BIT(0)
#घोषणा EMC_PMACRO_DATA_PAD_TX_CTRL_DATA_DQ_TX_E_DCC		BIT(1)
#घोषणा EMC_PMACRO_DATA_PAD_TX_CTRL_DATA_DQS_E_IVREF		BIT(8)
#घोषणा EMC_PMACRO_DATA_PAD_TX_CTRL_DATA_DQSP_TX_E_DCC		BIT(9)
#घोषणा EMC_PMACRO_DATA_PAD_TX_CTRL_DATA_DQSN_TX_E_DCC		BIT(16)
#घोषणा EMC_PMACRO_DATA_PAD_TX_CTRL_DATA_CMD_TX_E_DCC		BIT(24)

#घोषणा EMC_PMACRO_COMMON_PAD_TX_CTRL				0xc68
#घोषणा EMC_PMACRO_AUTOCAL_CFG_COMMON				0xc78
#घोषणा EMC_PMACRO_AUTOCAL_CFG_COMMON_E_CAL_BYPASS_DVFS		BIT(16)
#घोषणा EMC_PMACRO_VTTGEN_CTRL_2				0xcf0
#घोषणा EMC_PMACRO_IB_RXRT					0xcf4
#घोषणा EMC_PMACRO_TRAINING_CTRL_0				0xcf8
#घोषणा EMC_PMACRO_TRAINING_CTRL_0_CH0_TRAINING_E_WRPTR		BIT(3)
#घोषणा EMC_PMACRO_TRAINING_CTRL_1				0xcfc
#घोषणा EMC_PMACRO_TRAINING_CTRL_1_CH1_TRAINING_E_WRPTR		BIT(3)
#घोषणा EMC_TRAINING_CTRL					0xe04
#घोषणा EMC_TRAINING_QUSE_CORS_CTRL				0xe0c
#घोषणा EMC_TRAINING_QUSE_FINE_CTRL				0xe10
#घोषणा EMC_TRAINING_QUSE_CTRL_MISC				0xe14
#घोषणा EMC_TRAINING_WRITE_FINE_CTRL				0xe18
#घोषणा EMC_TRAINING_WRITE_CTRL_MISC				0xe1c
#घोषणा EMC_TRAINING_WRITE_VREF_CTRL				0xe20
#घोषणा EMC_TRAINING_READ_FINE_CTRL				0xe24
#घोषणा EMC_TRAINING_READ_CTRL_MISC				0xe28
#घोषणा EMC_TRAINING_READ_VREF_CTRL				0xe2c
#घोषणा EMC_TRAINING_CA_FINE_CTRL				0xe30
#घोषणा EMC_TRAINING_CA_CTRL_MISC				0xe34
#घोषणा EMC_TRAINING_CA_CTRL_MISC1				0xe38
#घोषणा EMC_TRAINING_CA_VREF_CTRL				0xe3c
#घोषणा EMC_TRAINING_SETTLE					0xe44
#घोषणा EMC_TRAINING_MPC					0xe5c
#घोषणा EMC_TRAINING_VREF_SETTLE				0xe6c
#घोषणा EMC_TRAINING_QUSE_VREF_CTRL				0xed0
#घोषणा EMC_TRAINING_OPT_DQS_IB_VREF_RANK0			0xed4
#घोषणा EMC_TRAINING_OPT_DQS_IB_VREF_RANK1			0xed8

#घोषणा EMC_COPY_TABLE_PARAM_PERIODIC_FIELDS			BIT(0)
#घोषणा EMC_COPY_TABLE_PARAM_TRIM_REGS				BIT(1)

क्रमागत burst_regs_list अणु
	EMC_RP_INDEX = 6,
	EMC_R2P_INDEX = 9,
	EMC_W2P_INDEX,
	EMC_MRW6_INDEX = 31,
	EMC_REFRESH_INDEX = 41,
	EMC_PRE_REFRESH_REQ_CNT_INDEX = 43,
	EMC_TRPAB_INDEX = 59,
	EMC_MRW7_INDEX = 62,
	EMC_FBIO_CFG5_INDEX = 65,
	EMC_FBIO_CFG7_INDEX,
	EMC_CFG_DIG_DLL_INDEX,
	EMC_ZCAL_INTERVAL_INDEX = 139,
	EMC_ZCAL_WAIT_CNT_INDEX,
	EMC_MRS_WAIT_CNT_INDEX = 141,
	EMC_DLL_CFG_0_INDEX = 144,
	EMC_PMACRO_AUTOCAL_CFG_COMMON_INDEX = 146,
	EMC_CFG_INDEX = 148,
	EMC_DYN_SELF_REF_CONTROL_INDEX = 150,
	EMC_PMACRO_CMD_PAD_TX_CTRL_INDEX = 161,
	EMC_PMACRO_DATA_PAD_TX_CTRL_INDEX,
	EMC_PMACRO_COMMON_PAD_TX_CTRL_INDEX,
	EMC_PMACRO_BRICK_CTRL_RFU1_INDEX = 167,
	EMC_PMACRO_BG_BIAS_CTRL_0_INDEX = 171,
	EMC_MRW14_INDEX = 199,
	EMC_MRW15_INDEX = 220,
पूर्ण;

क्रमागत trim_regs_list अणु
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_0_INDEX = 60,
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_1_INDEX,
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_2_INDEX,
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_3_INDEX,
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_4_INDEX,
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK0_5_INDEX,
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_0_INDEX,
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_1_INDEX,
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_2_INDEX,
	EMC_PMACRO_OB_DDLL_LONG_DQ_RANK1_3_INDEX,
पूर्ण;

क्रमागत burst_mc_regs_list अणु
	MC_EMEM_ARB_MISC0_INDEX = 20,
पूर्ण;

क्रमागत अणु
	T_RP,
	T_FC_LPDDR4,
	T_RFC,
	T_PDEX,
	RL,
पूर्ण;

क्रमागत अणु
	AUTO_PD = 0,
	MAN_SR  = 2,
पूर्ण;

क्रमागत अणु
	ASSEMBLY = 0,
	ACTIVE,
पूर्ण;

क्रमागत अणु
	C0D0U0,
	C0D0U1,
	C0D1U0,
	C0D1U1,
	C1D0U0,
	C1D0U1,
	C1D1U0,
	C1D1U1,
	DRAM_CLKTREE_NUM,
पूर्ण;

#घोषणा VREF_REGS_PER_CHANNEL_SIZE 4
#घोषणा DRAM_TIMINGS_NUM 5
#घोषणा BURST_REGS_PER_CHANNEL_SIZE 8
#घोषणा TRIM_REGS_PER_CHANNEL_SIZE 10
#घोषणा PTFV_ARRAY_SIZE 12
#घोषणा SAVE_RESTORE_MOD_REGS_SIZE 12
#घोषणा TRAINING_MOD_REGS_SIZE 20
#घोषणा BURST_UP_DOWN_REGS_SIZE 24
#घोषणा BURST_MC_REGS_SIZE 33
#घोषणा TRIM_REGS_SIZE 138
#घोषणा BURST_REGS_SIZE 221

काष्ठा tegra210_emc_per_channel_regs अणु
	u16 bank;
	u16 offset;
पूर्ण;

काष्ठा tegra210_emc_table_रेजिस्टर_offsets अणु
	u16 burst[BURST_REGS_SIZE];
	u16 trim[TRIM_REGS_SIZE];
	u16 burst_mc[BURST_MC_REGS_SIZE];
	u16 la_scale[BURST_UP_DOWN_REGS_SIZE];
	काष्ठा tegra210_emc_per_channel_regs burst_per_channel[BURST_REGS_PER_CHANNEL_SIZE];
	काष्ठा tegra210_emc_per_channel_regs trim_per_channel[TRIM_REGS_PER_CHANNEL_SIZE];
	काष्ठा tegra210_emc_per_channel_regs vref_per_channel[VREF_REGS_PER_CHANNEL_SIZE];
पूर्ण;

काष्ठा tegra210_emc_timing अणु
	u32 revision;
	स्थिर अक्षर dvfs_ver[60];
	u32 rate;
	u32 min_volt;
	u32 gpu_min_volt;
	स्थिर अक्षर घड़ी_src[32];
	u32 clk_src_emc;
	u32 needs_training;
	u32 training_pattern;
	u32 trained;

	u32 periodic_training;
	u32 trained_dram_clktree[DRAM_CLKTREE_NUM];
	u32 current_dram_clktree[DRAM_CLKTREE_NUM];
	u32 run_घड़ीs;
	u32 tree_margin;

	u32 num_burst;
	u32 num_burst_per_ch;
	u32 num_trim;
	u32 num_trim_per_ch;
	u32 num_mc_regs;
	u32 num_up_करोwn;
	u32 vref_num;
	u32 training_mod_num;
	u32 dram_timing_num;

	u32 ptfv_list[PTFV_ARRAY_SIZE];

	u32 burst_regs[BURST_REGS_SIZE];
	u32 burst_reg_per_ch[BURST_REGS_PER_CHANNEL_SIZE];
	u32 shaकरोw_regs_ca_train[BURST_REGS_SIZE];
	u32 shaकरोw_regs_quse_train[BURST_REGS_SIZE];
	u32 shaकरोw_regs_rdwr_train[BURST_REGS_SIZE];

	u32 trim_regs[TRIM_REGS_SIZE];
	u32 trim_perch_regs[TRIM_REGS_PER_CHANNEL_SIZE];

	u32 vref_perch_regs[VREF_REGS_PER_CHANNEL_SIZE];

	u32 dram_timings[DRAM_TIMINGS_NUM];
	u32 training_mod_regs[TRAINING_MOD_REGS_SIZE];
	u32 save_restore_mod_regs[SAVE_RESTORE_MOD_REGS_SIZE];
	u32 burst_mc_regs[BURST_MC_REGS_SIZE];
	u32 la_scale_regs[BURST_UP_DOWN_REGS_SIZE];

	u32 min_mrs_रुको;
	u32 emc_mrw;
	u32 emc_mrw2;
	u32 emc_mrw3;
	u32 emc_mrw4;
	u32 emc_mrw9;
	u32 emc_mrs;
	u32 emc_emrs;
	u32 emc_emrs2;
	u32 emc_स्वतः_cal_config;
	u32 emc_स्वतः_cal_config2;
	u32 emc_स्वतः_cal_config3;
	u32 emc_स्वतः_cal_config4;
	u32 emc_स्वतः_cal_config5;
	u32 emc_स्वतः_cal_config6;
	u32 emc_स्वतः_cal_config7;
	u32 emc_स्वतः_cal_config8;
	u32 emc_cfg_2;
	u32 emc_sel_dpd_ctrl;
	u32 emc_fdpd_ctrl_cmd_no_ramp;
	u32 dll_clk_src;
	u32 clk_out_enb_x_0_clk_enb_emc_dll;
	u32 latency;
पूर्ण;

क्रमागत tegra210_emc_refresh अणु
	TEGRA210_EMC_REFRESH_NOMINAL = 0,
	TEGRA210_EMC_REFRESH_2X,
	TEGRA210_EMC_REFRESH_4X,
	TEGRA210_EMC_REFRESH_THROTTLE, /* 4x Refresh + derating. */
पूर्ण;

#घोषणा DRAM_TYPE_DDR3		0
#घोषणा DRAM_TYPE_LPDDR4	1
#घोषणा DRAM_TYPE_LPDDR2	2
#घोषणा DRAM_TYPE_DDR2		3

काष्ठा tegra210_emc अणु
	काष्ठा tegra_mc *mc;
	काष्ठा device *dev;
	काष्ठा clk *clk;

	/* nominal EMC frequency table */
	काष्ठा tegra210_emc_timing *nominal;
	/* derated EMC frequency table */
	काष्ठा tegra210_emc_timing *derated;

	/* currently selected table (nominal or derated) */
	काष्ठा tegra210_emc_timing *timings;
	अचिन्हित पूर्णांक num_timings;

	स्थिर काष्ठा tegra210_emc_table_रेजिस्टर_offsets *offsets;

	स्थिर काष्ठा tegra210_emc_sequence *sequence;
	spinlock_t lock;

	व्योम __iomem *regs, *channel[2];
	अचिन्हित पूर्णांक num_channels;
	अचिन्हित पूर्णांक num_devices;
	अचिन्हित पूर्णांक dram_type;

	काष्ठा tegra210_emc_timing *last;
	काष्ठा tegra210_emc_timing *next;

	अचिन्हित पूर्णांक training_पूर्णांकerval;
	काष्ठा समयr_list training;

	क्रमागत tegra210_emc_refresh refresh;
	अचिन्हित पूर्णांक refresh_poll_पूर्णांकerval;
	काष्ठा समयr_list refresh_समयr;
	अचिन्हित पूर्णांक temperature;
	atomic_t refresh_poll;

	kसमय_प्रकार clkchange_समय;
	पूर्णांक clkchange_delay;

	अचिन्हित दीर्घ resume_rate;

	काष्ठा अणु
		काष्ठा dentry *root;
		अचिन्हित दीर्घ min_rate;
		अचिन्हित दीर्घ max_rate;
		अचिन्हित पूर्णांक temperature;
	पूर्ण debugfs;

	काष्ठा tegra210_clk_emc_provider provider;
पूर्ण;

काष्ठा tegra210_emc_sequence अणु
	u8 revision;
	व्योम (*set_घड़ी)(काष्ठा tegra210_emc *emc, u32 clksrc);
	u32 (*periodic_compensation)(काष्ठा tegra210_emc *emc);
पूर्ण;

अटल अंतरभूत व्योम emc_ग_लिखोl(काष्ठा tegra210_emc *emc, u32 value,
			      अचिन्हित पूर्णांक offset)
अणु
	ग_लिखोl_relaxed(value, emc->regs + offset);
पूर्ण

अटल अंतरभूत u32 emc_पढ़ोl(काष्ठा tegra210_emc *emc, अचिन्हित पूर्णांक offset)
अणु
	वापस पढ़ोl_relaxed(emc->regs + offset);
पूर्ण

अटल अंतरभूत व्योम emc_channel_ग_लिखोl(काष्ठा tegra210_emc *emc,
				      अचिन्हित पूर्णांक channel,
				      u32 value, अचिन्हित पूर्णांक offset)
अणु
	ग_लिखोl_relaxed(value, emc->channel[channel] + offset);
पूर्ण

अटल अंतरभूत u32 emc_channel_पढ़ोl(काष्ठा tegra210_emc *emc,
				    अचिन्हित पूर्णांक channel, अचिन्हित पूर्णांक offset)
अणु
	वापस पढ़ोl_relaxed(emc->channel[channel] + offset);
पूर्ण

अटल अंतरभूत व्योम ccfअगरo_ग_लिखोl(काष्ठा tegra210_emc *emc, u32 value,
				 अचिन्हित पूर्णांक offset, u32 delay)
अणु
	ग_लिखोl_relaxed(value, emc->regs + EMC_CCFIFO_DATA);

	value = EMC_CCFIFO_ADDR_STALL_BY_1 | EMC_CCFIFO_ADDR_STALL(delay) |
		EMC_CCFIFO_ADDR_OFFSET(offset);
	ग_लिखोl_relaxed(value, emc->regs + EMC_CCFIFO_ADDR);
पूर्ण

अटल अंतरभूत u32 भाग_o3(u32 a, u32 b)
अणु
	u32 result = a / b;

	अगर ((b * result) < a)
		वापस result + 1;

	वापस result;
पूर्ण

/* from tegra210-emc-r21021.c */
बाह्य स्थिर काष्ठा tegra210_emc_sequence tegra210_emc_r21021;

पूर्णांक tegra210_emc_set_refresh(काष्ठा tegra210_emc *emc,
			     क्रमागत tegra210_emc_refresh refresh);
u32 tegra210_emc_mrr_पढ़ो(काष्ठा tegra210_emc *emc, अचिन्हित पूर्णांक chip,
			  अचिन्हित पूर्णांक address);
व्योम tegra210_emc_करो_घड़ी_change(काष्ठा tegra210_emc *emc, u32 clksrc);
व्योम tegra210_emc_set_shaकरोw_bypass(काष्ठा tegra210_emc *emc, पूर्णांक set);
व्योम tegra210_emc_timing_update(काष्ठा tegra210_emc *emc);
u32 tegra210_emc_get_dll_state(काष्ठा tegra210_emc_timing *next);
काष्ठा tegra210_emc_timing *tegra210_emc_find_timing(काष्ठा tegra210_emc *emc,
						     अचिन्हित दीर्घ rate);
व्योम tegra210_emc_adjust_timing(काष्ठा tegra210_emc *emc,
				काष्ठा tegra210_emc_timing *timing);
पूर्णांक tegra210_emc_रुको_क्रम_update(काष्ठा tegra210_emc *emc, अचिन्हित पूर्णांक channel,
				 अचिन्हित पूर्णांक offset, u32 bit_mask, bool state);
अचिन्हित दीर्घ tegra210_emc_actual_osc_घड़ीs(u32 in);
u32 tegra210_emc_compensate(काष्ठा tegra210_emc_timing *next, u32 offset);
व्योम tegra210_emc_dll_disable(काष्ठा tegra210_emc *emc);
व्योम tegra210_emc_dll_enable(काष्ठा tegra210_emc *emc);
u32 tegra210_emc_dll_prelock(काष्ठा tegra210_emc *emc, u32 clksrc);
u32 tegra210_emc_dvfs_घातer_ramp_करोwn(काष्ठा tegra210_emc *emc, u32 clk,
				      bool flip_backward);
u32 tegra210_emc_dvfs_घातer_ramp_up(काष्ठा tegra210_emc *emc, u32 clk,
				    bool flip_backward);
व्योम tegra210_emc_reset_dram_clktree_values(काष्ठा tegra210_emc_timing *timing);
व्योम tegra210_emc_start_periodic_compensation(काष्ठा tegra210_emc *emc);

#पूर्ण_अगर
