<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
/*
 * This header provides स्थिरants क्रम the reset controller
 * present in the Pistachio SoC
 */

#अगर_अघोषित _PISTACHIO_RESETS_H
#घोषणा _PISTACHIO_RESETS_H

#घोषणा PISTACHIO_RESET_I2C0		0
#घोषणा PISTACHIO_RESET_I2C1		1
#घोषणा PISTACHIO_RESET_I2C2		2
#घोषणा PISTACHIO_RESET_I2C3		3
#घोषणा PISTACHIO_RESET_I2S_IN		4
#घोषणा PISTACHIO_RESET_PRL_OUT		5
#घोषणा PISTACHIO_RESET_SPDIF_OUT	6
#घोषणा PISTACHIO_RESET_SPI		7
#घोषणा PISTACHIO_RESET_PWM_PDM		8
#घोषणा PISTACHIO_RESET_UART0		9
#घोषणा PISTACHIO_RESET_UART1		10
#घोषणा PISTACHIO_RESET_QSPI		11
#घोषणा PISTACHIO_RESET_MDC		12
#घोषणा PISTACHIO_RESET_SDHOST		13
#घोषणा PISTACHIO_RESET_ETHERNET	14
#घोषणा PISTACHIO_RESET_IR		15
#घोषणा PISTACHIO_RESET_HASH		16
#घोषणा PISTACHIO_RESET_TIMER		17
#घोषणा PISTACHIO_RESET_I2S_OUT		18
#घोषणा PISTACHIO_RESET_SPDIF_IN	19
#घोषणा PISTACHIO_RESET_EVT		20
#घोषणा PISTACHIO_RESET_USB_H		21
#घोषणा PISTACHIO_RESET_USB_PR		22
#घोषणा PISTACHIO_RESET_USB_PHY_PR	23
#घोषणा PISTACHIO_RESET_USB_PHY_PON	24
#घोषणा PISTACHIO_RESET_MAX		24

#पूर्ण_अगर
