<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
/*
 * This header provides स्थिरants क्रम the reset controller
 * based peripheral घातerकरोwn requests on the STMicroelectronics
 * STiH415 SoC.
 */
#अगर_अघोषित _DT_BINDINGS_RESET_CONTROLLER_STIH415
#घोषणा _DT_BINDINGS_RESET_CONTROLLER_STIH415

#घोषणा STIH415_EMISS_POWERDOWN		0
#घोषणा STIH415_न_अंकD_POWERDOWN		1
#घोषणा STIH415_KEYSCAN_POWERDOWN	2
#घोषणा STIH415_USB0_POWERDOWN		3
#घोषणा STIH415_USB1_POWERDOWN		4
#घोषणा STIH415_USB2_POWERDOWN		5
#घोषणा STIH415_SATA0_POWERDOWN		6
#घोषणा STIH415_SATA1_POWERDOWN		7
#घोषणा STIH415_PCIE_POWERDOWN		8

#घोषणा STIH415_ETH0_SOFTRESET		0
#घोषणा STIH415_ETH1_SOFTRESET		1
#घोषणा STIH415_IRB_SOFTRESET		2
#घोषणा STIH415_USB0_SOFTRESET		3
#घोषणा STIH415_USB1_SOFTRESET		4
#घोषणा STIH415_USB2_SOFTRESET		5
#घोषणा STIH415_KEYSCAN_SOFTRESET	6

#पूर्ण_अगर /* _DT_BINDINGS_RESET_CONTROLLER_STIH415 */
