<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
#अगर_अघोषित DT_BINDINGS_MEMORY_TEGRA210_MC_H
#घोषणा DT_BINDINGS_MEMORY_TEGRA210_MC_H

#घोषणा TEGRA_SWGROUP_PTC	0
#घोषणा TEGRA_SWGROUP_DC	1
#घोषणा TEGRA_SWGROUP_DCB	2
#घोषणा TEGRA_SWGROUP_AFI	3
#घोषणा TEGRA_SWGROUP_AVPC	4
#घोषणा TEGRA_SWGROUP_HDA	5
#घोषणा TEGRA_SWGROUP_HC	6
#घोषणा TEGRA_SWGROUP_NVENC	7
#घोषणा TEGRA_SWGROUP_PPCS	8
#घोषणा TEGRA_SWGROUP_SATA	9
#घोषणा TEGRA_SWGROUP_MPCORE	10
#घोषणा TEGRA_SWGROUP_ISP2	11
#घोषणा TEGRA_SWGROUP_XUSB_HOST	12
#घोषणा TEGRA_SWGROUP_XUSB_DEV	13
#घोषणा TEGRA_SWGROUP_ISP2B	14
#घोषणा TEGRA_SWGROUP_TSEC	15
#घोषणा TEGRA_SWGROUP_A9AVP	16
#घोषणा TEGRA_SWGROUP_GPU	17
#घोषणा TEGRA_SWGROUP_SDMMC1A	18
#घोषणा TEGRA_SWGROUP_SDMMC2A	19
#घोषणा TEGRA_SWGROUP_SDMMC3A	20
#घोषणा TEGRA_SWGROUP_SDMMC4A	21
#घोषणा TEGRA_SWGROUP_VIC	22
#घोषणा TEGRA_SWGROUP_VI	23
#घोषणा TEGRA_SWGROUP_NVDEC	24
#घोषणा TEGRA_SWGROUP_APE	25
#घोषणा TEGRA_SWGROUP_NVJPG	26
#घोषणा TEGRA_SWGROUP_SE	27
#घोषणा TEGRA_SWGROUP_AXIAP	28
#घोषणा TEGRA_SWGROUP_ETR	29
#घोषणा TEGRA_SWGROUP_TSECB	30
#घोषणा TEGRA_SWGROUP_NV	31
#घोषणा TEGRA_SWGROUP_NV2	32
#घोषणा TEGRA_SWGROUP_PPCS1	33
#घोषणा TEGRA_SWGROUP_DC1	34
#घोषणा TEGRA_SWGROUP_PPCS2	35
#घोषणा TEGRA_SWGROUP_HC1	36
#घोषणा TEGRA_SWGROUP_SE1	37
#घोषणा TEGRA_SWGROUP_TSEC1	38
#घोषणा TEGRA_SWGROUP_TSECB1	39
#घोषणा TEGRA_SWGROUP_NVDEC1	40

#घोषणा TEGRA210_MC_RESET_AFI		0
#घोषणा TEGRA210_MC_RESET_AVPC		1
#घोषणा TEGRA210_MC_RESET_DC		2
#घोषणा TEGRA210_MC_RESET_DCB		3
#घोषणा TEGRA210_MC_RESET_HC		4
#घोषणा TEGRA210_MC_RESET_HDA		5
#घोषणा TEGRA210_MC_RESET_ISP2		6
#घोषणा TEGRA210_MC_RESET_MPCORE	7
#घोषणा TEGRA210_MC_RESET_NVENC		8
#घोषणा TEGRA210_MC_RESET_PPCS		9
#घोषणा TEGRA210_MC_RESET_SATA		10
#घोषणा TEGRA210_MC_RESET_VI		11
#घोषणा TEGRA210_MC_RESET_VIC		12
#घोषणा TEGRA210_MC_RESET_XUSB_HOST	13
#घोषणा TEGRA210_MC_RESET_XUSB_DEV	14
#घोषणा TEGRA210_MC_RESET_A9AVP		15
#घोषणा TEGRA210_MC_RESET_TSEC		16
#घोषणा TEGRA210_MC_RESET_SDMMC1	17
#घोषणा TEGRA210_MC_RESET_SDMMC2	18
#घोषणा TEGRA210_MC_RESET_SDMMC3	19
#घोषणा TEGRA210_MC_RESET_SDMMC4	20
#घोषणा TEGRA210_MC_RESET_ISP2B		21
#घोषणा TEGRA210_MC_RESET_GPU		22
#घोषणा TEGRA210_MC_RESET_NVDEC		23
#घोषणा TEGRA210_MC_RESET_APE		24
#घोषणा TEGRA210_MC_RESET_SE		25
#घोषणा TEGRA210_MC_RESET_NVJPG		26
#घोषणा TEGRA210_MC_RESET_AXIAP		27
#घोषणा TEGRA210_MC_RESET_ETR		28
#घोषणा TEGRA210_MC_RESET_TSECB		29

#पूर्ण_अगर
