<शैली गुरु>
// SPDX-License-Identअगरier: GPL-2.0

// Generated by scripts/atomic/gen-atomic-दीर्घ.sh
// DO NOT MODIFY THIS खाता सूचीECTLY

#अगर_अघोषित _ASM_GENERIC_ATOMIC_LONG_H
#घोषणा _ASM_GENERIC_ATOMIC_LONG_H

#समावेश <linux/compiler.h>
#समावेश <यंत्र/types.h>

#अगर_घोषित CONFIG_64BIT
प्रकार atomic64_t atomic_दीर्घ_t;
#घोषणा ATOMIC_LONG_INIT(i)		ATOMIC64_INIT(i)
#घोषणा atomic_दीर्घ_cond_पढ़ो_acquire	atomic64_cond_पढ़ो_acquire
#घोषणा atomic_दीर्घ_cond_पढ़ो_relaxed	atomic64_cond_पढ़ो_relaxed
#अन्यथा
प्रकार atomic_t atomic_दीर्घ_t;
#घोषणा ATOMIC_LONG_INIT(i)		ATOMIC_INIT(i)
#घोषणा atomic_दीर्घ_cond_पढ़ो_acquire	atomic_cond_पढ़ो_acquire
#घोषणा atomic_दीर्घ_cond_पढ़ो_relaxed	atomic_cond_पढ़ो_relaxed
#पूर्ण_अगर

#अगर_घोषित CONFIG_64BIT

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_पढ़ो(स्थिर atomic_दीर्घ_t *v)
अणु
	वापस atomic64_पढ़ो(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_पढ़ो_acquire(स्थिर atomic_दीर्घ_t *v)
अणु
	वापस atomic64_पढ़ो_acquire(v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_set(atomic_दीर्घ_t *v, दीर्घ i)
अणु
	atomic64_set(v, i);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_set_release(atomic_दीर्घ_t *v, दीर्घ i)
अणु
	atomic64_set_release(v, i);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_add(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	atomic64_add(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_add_वापस(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_add_वापस(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_add_वापस_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_add_वापस_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_add_वापस_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_add_वापस_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_add_वापस_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_add_वापस_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_add(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_add(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_add_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_add_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_add_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_add_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_add_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_add_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_sub(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	atomic64_sub(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_sub_वापस(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_sub_वापस(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_sub_वापस_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_sub_वापस_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_sub_वापस_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_sub_वापस_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_sub_वापस_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_sub_वापस_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_sub(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_sub(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_sub_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_sub_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_sub_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_sub_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_sub_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_sub_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_inc(atomic_दीर्घ_t *v)
अणु
	atomic64_inc(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_inc_वापस(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_inc_वापस(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_inc_वापस_acquire(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_inc_वापस_acquire(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_inc_वापस_release(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_inc_वापस_release(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_inc_वापस_relaxed(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_inc_वापस_relaxed(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_inc(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_inc(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_inc_acquire(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_inc_acquire(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_inc_release(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_inc_release(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_inc_relaxed(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_inc_relaxed(v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_dec(atomic_दीर्घ_t *v)
अणु
	atomic64_dec(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_dec_वापस(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_dec_वापस(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_dec_वापस_acquire(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_dec_वापस_acquire(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_dec_वापस_release(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_dec_वापस_release(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_dec_वापस_relaxed(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_dec_वापस_relaxed(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_dec(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_dec(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_dec_acquire(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_dec_acquire(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_dec_release(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_dec_release(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_dec_relaxed(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_dec_relaxed(v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_and(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	atomic64_and(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_and(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_and(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_and_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_and_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_and_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_and_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_and_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_and_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_andnot(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	atomic64_andnot(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_andnot(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_andnot(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_andnot_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_andnot_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_andnot_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_andnot_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_andnot_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_andnot_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_or(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	atomic64_or(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_or(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_or(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_or_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_or_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_or_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_or_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_or_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_or_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_xor(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	atomic64_xor(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_xor(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_xor(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_xor_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_xor_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_xor_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_xor_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_xor_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_fetch_xor_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_xchg(atomic_दीर्घ_t *v, दीर्घ i)
अणु
	वापस atomic64_xchg(v, i);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_xchg_acquire(atomic_दीर्घ_t *v, दीर्घ i)
अणु
	वापस atomic64_xchg_acquire(v, i);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_xchg_release(atomic_दीर्घ_t *v, दीर्घ i)
अणु
	वापस atomic64_xchg_release(v, i);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_xchg_relaxed(atomic_दीर्घ_t *v, दीर्घ i)
अणु
	वापस atomic64_xchg_relaxed(v, i);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_cmpxchg(atomic_दीर्घ_t *v, दीर्घ old, दीर्घ new)
अणु
	वापस atomic64_cmpxchg(v, old, new);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_cmpxchg_acquire(atomic_दीर्घ_t *v, दीर्घ old, दीर्घ new)
अणु
	वापस atomic64_cmpxchg_acquire(v, old, new);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_cmpxchg_release(atomic_दीर्घ_t *v, दीर्घ old, दीर्घ new)
अणु
	वापस atomic64_cmpxchg_release(v, old, new);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_cmpxchg_relaxed(atomic_दीर्घ_t *v, दीर्घ old, दीर्घ new)
अणु
	वापस atomic64_cmpxchg_relaxed(v, old, new);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_try_cmpxchg(atomic_दीर्घ_t *v, दीर्घ *old, दीर्घ new)
अणु
	वापस atomic64_try_cmpxchg(v, (s64 *)old, new);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_try_cmpxchg_acquire(atomic_दीर्घ_t *v, दीर्घ *old, दीर्घ new)
अणु
	वापस atomic64_try_cmpxchg_acquire(v, (s64 *)old, new);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_try_cmpxchg_release(atomic_दीर्घ_t *v, दीर्घ *old, दीर्घ new)
अणु
	वापस atomic64_try_cmpxchg_release(v, (s64 *)old, new);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_try_cmpxchg_relaxed(atomic_दीर्घ_t *v, दीर्घ *old, दीर्घ new)
अणु
	वापस atomic64_try_cmpxchg_relaxed(v, (s64 *)old, new);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_sub_and_test(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_sub_and_test(i, v);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_dec_and_test(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_dec_and_test(v);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_inc_and_test(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_inc_and_test(v);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_add_negative(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic64_add_negative(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_add_unless(atomic_दीर्घ_t *v, दीर्घ a, दीर्घ u)
अणु
	वापस atomic64_fetch_add_unless(v, a, u);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_add_unless(atomic_दीर्घ_t *v, दीर्घ a, दीर्घ u)
अणु
	वापस atomic64_add_unless(v, a, u);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_inc_not_zero(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_inc_not_zero(v);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_inc_unless_negative(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_inc_unless_negative(v);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_dec_unless_positive(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_dec_unless_positive(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_dec_अगर_positive(atomic_दीर्घ_t *v)
अणु
	वापस atomic64_dec_अगर_positive(v);
पूर्ण

#अन्यथा /* CONFIG_64BIT */

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_पढ़ो(स्थिर atomic_दीर्घ_t *v)
अणु
	वापस atomic_पढ़ो(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_पढ़ो_acquire(स्थिर atomic_दीर्घ_t *v)
अणु
	वापस atomic_पढ़ो_acquire(v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_set(atomic_दीर्घ_t *v, दीर्घ i)
अणु
	atomic_set(v, i);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_set_release(atomic_दीर्घ_t *v, दीर्घ i)
अणु
	atomic_set_release(v, i);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_add(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	atomic_add(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_add_वापस(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_add_वापस(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_add_वापस_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_add_वापस_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_add_वापस_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_add_वापस_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_add_वापस_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_add_वापस_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_add(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_add(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_add_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_add_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_add_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_add_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_add_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_add_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_sub(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	atomic_sub(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_sub_वापस(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_sub_वापस(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_sub_वापस_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_sub_वापस_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_sub_वापस_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_sub_वापस_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_sub_वापस_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_sub_वापस_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_sub(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_sub(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_sub_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_sub_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_sub_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_sub_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_sub_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_sub_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_inc(atomic_दीर्घ_t *v)
अणु
	atomic_inc(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_inc_वापस(atomic_दीर्घ_t *v)
अणु
	वापस atomic_inc_वापस(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_inc_वापस_acquire(atomic_दीर्घ_t *v)
अणु
	वापस atomic_inc_वापस_acquire(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_inc_वापस_release(atomic_दीर्घ_t *v)
अणु
	वापस atomic_inc_वापस_release(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_inc_वापस_relaxed(atomic_दीर्घ_t *v)
अणु
	वापस atomic_inc_वापस_relaxed(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_inc(atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_inc(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_inc_acquire(atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_inc_acquire(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_inc_release(atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_inc_release(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_inc_relaxed(atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_inc_relaxed(v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_dec(atomic_दीर्घ_t *v)
अणु
	atomic_dec(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_dec_वापस(atomic_दीर्घ_t *v)
अणु
	वापस atomic_dec_वापस(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_dec_वापस_acquire(atomic_दीर्घ_t *v)
अणु
	वापस atomic_dec_वापस_acquire(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_dec_वापस_release(atomic_दीर्घ_t *v)
अणु
	वापस atomic_dec_वापस_release(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_dec_वापस_relaxed(atomic_दीर्घ_t *v)
अणु
	वापस atomic_dec_वापस_relaxed(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_dec(atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_dec(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_dec_acquire(atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_dec_acquire(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_dec_release(atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_dec_release(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_dec_relaxed(atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_dec_relaxed(v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_and(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	atomic_and(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_and(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_and(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_and_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_and_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_and_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_and_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_and_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_and_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_andnot(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	atomic_andnot(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_andnot(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_andnot(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_andnot_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_andnot_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_andnot_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_andnot_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_andnot_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_andnot_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_or(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	atomic_or(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_or(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_or(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_or_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_or_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_or_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_or_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_or_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_or_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत व्योम
atomic_दीर्घ_xor(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	atomic_xor(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_xor(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_xor(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_xor_acquire(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_xor_acquire(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_xor_release(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_xor_release(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_xor_relaxed(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_fetch_xor_relaxed(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_xchg(atomic_दीर्घ_t *v, दीर्घ i)
अणु
	वापस atomic_xchg(v, i);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_xchg_acquire(atomic_दीर्घ_t *v, दीर्घ i)
अणु
	वापस atomic_xchg_acquire(v, i);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_xchg_release(atomic_दीर्घ_t *v, दीर्घ i)
अणु
	वापस atomic_xchg_release(v, i);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_xchg_relaxed(atomic_दीर्घ_t *v, दीर्घ i)
अणु
	वापस atomic_xchg_relaxed(v, i);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_cmpxchg(atomic_दीर्घ_t *v, दीर्घ old, दीर्घ new)
अणु
	वापस atomic_cmpxchg(v, old, new);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_cmpxchg_acquire(atomic_दीर्घ_t *v, दीर्घ old, दीर्घ new)
अणु
	वापस atomic_cmpxchg_acquire(v, old, new);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_cmpxchg_release(atomic_दीर्घ_t *v, दीर्घ old, दीर्घ new)
अणु
	वापस atomic_cmpxchg_release(v, old, new);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_cmpxchg_relaxed(atomic_दीर्घ_t *v, दीर्घ old, दीर्घ new)
अणु
	वापस atomic_cmpxchg_relaxed(v, old, new);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_try_cmpxchg(atomic_दीर्घ_t *v, दीर्घ *old, दीर्घ new)
अणु
	वापस atomic_try_cmpxchg(v, (पूर्णांक *)old, new);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_try_cmpxchg_acquire(atomic_दीर्घ_t *v, दीर्घ *old, दीर्घ new)
अणु
	वापस atomic_try_cmpxchg_acquire(v, (पूर्णांक *)old, new);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_try_cmpxchg_release(atomic_दीर्घ_t *v, दीर्घ *old, दीर्घ new)
अणु
	वापस atomic_try_cmpxchg_release(v, (पूर्णांक *)old, new);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_try_cmpxchg_relaxed(atomic_दीर्घ_t *v, दीर्घ *old, दीर्घ new)
अणु
	वापस atomic_try_cmpxchg_relaxed(v, (पूर्णांक *)old, new);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_sub_and_test(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_sub_and_test(i, v);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_dec_and_test(atomic_दीर्घ_t *v)
अणु
	वापस atomic_dec_and_test(v);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_inc_and_test(atomic_दीर्घ_t *v)
अणु
	वापस atomic_inc_and_test(v);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_add_negative(दीर्घ i, atomic_दीर्घ_t *v)
अणु
	वापस atomic_add_negative(i, v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_fetch_add_unless(atomic_दीर्घ_t *v, दीर्घ a, दीर्घ u)
अणु
	वापस atomic_fetch_add_unless(v, a, u);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_add_unless(atomic_दीर्घ_t *v, दीर्घ a, दीर्घ u)
अणु
	वापस atomic_add_unless(v, a, u);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_inc_not_zero(atomic_दीर्घ_t *v)
अणु
	वापस atomic_inc_not_zero(v);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_inc_unless_negative(atomic_दीर्घ_t *v)
अणु
	वापस atomic_inc_unless_negative(v);
पूर्ण

अटल __always_अंतरभूत bool
atomic_दीर्घ_dec_unless_positive(atomic_दीर्घ_t *v)
अणु
	वापस atomic_dec_unless_positive(v);
पूर्ण

अटल __always_अंतरभूत दीर्घ
atomic_दीर्घ_dec_अगर_positive(atomic_दीर्घ_t *v)
अणु
	वापस atomic_dec_अगर_positive(v);
पूर्ण

#पूर्ण_अगर /* CONFIG_64BIT */
#पूर्ण_अगर /* _ASM_GENERIC_ATOMIC_LONG_H */
// a624200981f552b2c6be4f32fe44da8289f30d87
