<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0-only */
/*
 *
 * Copyright IBM Corp. 2008
 *
 * Authors: Hollis Blanअक्षरd <hollisb@us.ibm.com>
 */

#अगर_अघोषित __POWERPC_KVM_ASM_H__
#घोषणा __POWERPC_KVM_ASM_H__

#अगर_घोषित __ASSEMBLY__
#अगर_घोषित CONFIG_64BIT
#घोषणा PPC_STD(sreg, offset, areg)  std sreg, (offset)(areg)
#घोषणा PPC_LD(treg, offset, areg)   ld treg, (offset)(areg)
#अन्यथा
#घोषणा PPC_STD(sreg, offset, areg)  stw sreg, (offset+4)(areg)
#घोषणा PPC_LD(treg, offset, areg)   lwz treg, (offset+4)(areg)
#पूर्ण_अगर
#पूर्ण_अगर

/* IVPR must be 64KiB-aligned. */
#घोषणा VCPU_SIZE_ORDER 4
#घोषणा VCPU_SIZE_LOG   (VCPU_SIZE_ORDER + 12)
#घोषणा VCPU_SIZE_BYTES (1<<VCPU_SIZE_LOG)

#घोषणा BOOKE_INTERRUPT_CRITICAL 0
#घोषणा BOOKE_INTERRUPT_MACHINE_CHECK 1
#घोषणा BOOKE_INTERRUPT_DATA_STORAGE 2
#घोषणा BOOKE_INTERRUPT_INST_STORAGE 3
#घोषणा BOOKE_INTERRUPT_EXTERNAL 4
#घोषणा BOOKE_INTERRUPT_ALIGNMENT 5
#घोषणा BOOKE_INTERRUPT_PROGRAM 6
#घोषणा BOOKE_INTERRUPT_FP_UNAVAIL 7
#घोषणा BOOKE_INTERRUPT_SYSCALL 8
#घोषणा BOOKE_INTERRUPT_AP_UNAVAIL 9
#घोषणा BOOKE_INTERRUPT_DECREMENTER 10
#घोषणा BOOKE_INTERRUPT_FIT 11
#घोषणा BOOKE_INTERRUPT_WATCHDOG 12
#घोषणा BOOKE_INTERRUPT_DTLB_MISS 13
#घोषणा BOOKE_INTERRUPT_ITLB_MISS 14
#घोषणा BOOKE_INTERRUPT_DEBUG 15

/* E500 */
#अगर_घोषित CONFIG_SPE_POSSIBLE
#घोषणा BOOKE_INTERRUPT_SPE_UNAVAIL 32
#घोषणा BOOKE_INTERRUPT_SPE_FP_DATA 33
#घोषणा BOOKE_INTERRUPT_SPE_FP_ROUND 34
#पूर्ण_अगर

#अगर_घोषित CONFIG_PPC_E500MC
#घोषणा BOOKE_INTERRUPT_ALTIVEC_UNAVAIL 32
#घोषणा BOOKE_INTERRUPT_ALTIVEC_ASSIST 33
#पूर्ण_अगर

#घोषणा BOOKE_INTERRUPT_PERFORMANCE_MONITOR 35
#घोषणा BOOKE_INTERRUPT_DOORBELL 36
#घोषणा BOOKE_INTERRUPT_DOORBELL_CRITICAL 37

/* booke_hv */
#घोषणा BOOKE_INTERRUPT_GUEST_DBELL 38
#घोषणा BOOKE_INTERRUPT_GUEST_DBELL_CRIT 39
#घोषणा BOOKE_INTERRUPT_HV_SYSCALL 40
#घोषणा BOOKE_INTERRUPT_HV_PRIV 41
#घोषणा BOOKE_INTERRUPT_LRAT_ERROR 42

/* book3s */

#घोषणा BOOK3S_INTERRUPT_SYSTEM_RESET	0x100
#घोषणा BOOK3S_INTERRUPT_MACHINE_CHECK	0x200
#घोषणा BOOK3S_INTERRUPT_DATA_STORAGE	0x300
#घोषणा BOOK3S_INTERRUPT_DATA_SEGMENT	0x380
#घोषणा BOOK3S_INTERRUPT_INST_STORAGE	0x400
#घोषणा BOOK3S_INTERRUPT_INST_SEGMENT	0x480
#घोषणा BOOK3S_INTERRUPT_EXTERNAL	0x500
#घोषणा BOOK3S_INTERRUPT_EXTERNAL_HV	0x502
#घोषणा BOOK3S_INTERRUPT_ALIGNMENT	0x600
#घोषणा BOOK3S_INTERRUPT_PROGRAM	0x700
#घोषणा BOOK3S_INTERRUPT_FP_UNAVAIL	0x800
#घोषणा BOOK3S_INTERRUPT_DECREMENTER	0x900
#घोषणा BOOK3S_INTERRUPT_HV_DECREMENTER	0x980
#घोषणा BOOK3S_INTERRUPT_DOORBELL	0xa00
#घोषणा BOOK3S_INTERRUPT_SYSCALL	0xc00
#घोषणा BOOK3S_INTERRUPT_TRACE		0xd00
#घोषणा BOOK3S_INTERRUPT_H_DATA_STORAGE	0xe00
#घोषणा BOOK3S_INTERRUPT_H_INST_STORAGE	0xe20
#घोषणा BOOK3S_INTERRUPT_H_EMUL_ASSIST	0xe40
#घोषणा BOOK3S_INTERRUPT_HMI		0xe60
#घोषणा BOOK3S_INTERRUPT_H_DOORBELL	0xe80
#घोषणा BOOK3S_INTERRUPT_H_VIRT		0xea0
#घोषणा BOOK3S_INTERRUPT_PERFMON	0xf00
#घोषणा BOOK3S_INTERRUPT_ALTIVEC	0xf20
#घोषणा BOOK3S_INTERRUPT_VSX		0xf40
#घोषणा BOOK3S_INTERRUPT_FAC_UNAVAIL	0xf60
#घोषणा BOOK3S_INTERRUPT_H_FAC_UNAVAIL	0xf80

/* book3s_hv */

#घोषणा BOOK3S_INTERRUPT_HV_SOFTPATCH	0x1500

/*
 * Special trap used to indicate to host that this is a
 * passthrough पूर्णांकerrupt that could not be handled
 * completely in the guest.
 */
#घोषणा BOOK3S_INTERRUPT_HV_RM_HARD	0x5555

#घोषणा BOOK3S_IRQPRIO_SYSTEM_RESET		0
#घोषणा BOOK3S_IRQPRIO_DATA_SEGMENT		1
#घोषणा BOOK3S_IRQPRIO_INST_SEGMENT		2
#घोषणा BOOK3S_IRQPRIO_DATA_STORAGE		3
#घोषणा BOOK3S_IRQPRIO_INST_STORAGE		4
#घोषणा BOOK3S_IRQPRIO_ALIGNMENT		5
#घोषणा BOOK3S_IRQPRIO_PROGRAM			6
#घोषणा BOOK3S_IRQPRIO_FP_UNAVAIL		7
#घोषणा BOOK3S_IRQPRIO_ALTIVEC			8
#घोषणा BOOK3S_IRQPRIO_VSX			9
#घोषणा BOOK3S_IRQPRIO_FAC_UNAVAIL		10
#घोषणा BOOK3S_IRQPRIO_SYSCALL			11
#घोषणा BOOK3S_IRQPRIO_MACHINE_CHECK		12
#घोषणा BOOK3S_IRQPRIO_DEBUG			13
#घोषणा BOOK3S_IRQPRIO_EXTERNAL			14
#घोषणा BOOK3S_IRQPRIO_DECREMENTER		15
#घोषणा BOOK3S_IRQPRIO_PERFORMANCE_MONITOR	16
#घोषणा BOOK3S_IRQPRIO_MAX			17

#घोषणा BOOK3S_HFLAG_DCBZ32			0x1
#घोषणा BOOK3S_HFLAG_SLB			0x2
#घोषणा BOOK3S_HFLAG_PAIRED_SINGLE		0x4
#घोषणा BOOK3S_HFLAG_NATIVE_PS			0x8
#घोषणा BOOK3S_HFLAG_MULTI_PGSIZE		0x10
#घोषणा BOOK3S_HFLAG_NEW_TLBIE			0x20
#घोषणा BOOK3S_HFLAG_SPLIT_HACK			0x40

#घोषणा RESUME_FLAG_NV          (1<<0)  /* Reload guest nonअस्थिर state? */
#घोषणा RESUME_FLAG_HOST        (1<<1)  /* Resume host? */
#घोषणा RESUME_FLAG_ARCH1	(1<<2)
#घोषणा RESUME_FLAG_ARCH2	(1<<3)

#घोषणा RESUME_GUEST            0
#घोषणा RESUME_GUEST_NV         RESUME_FLAG_NV
#घोषणा RESUME_HOST             RESUME_FLAG_HOST
#घोषणा RESUME_HOST_NV          (RESUME_FLAG_HOST|RESUME_FLAG_NV)

#घोषणा KVM_GUEST_MODE_NONE	0
#घोषणा KVM_GUEST_MODE_GUEST	1
#घोषणा KVM_GUEST_MODE_SKIP	2
#घोषणा KVM_GUEST_MODE_GUEST_HV	3
#घोषणा KVM_GUEST_MODE_HOST_HV	4

#घोषणा KVM_INST_FETCH_FAILED	-1

/* Extract PO and XOP opcode fields */
#घोषणा PO_XOP_OPCODE_MASK 0xfc0007fe

#पूर्ण_अगर /* __POWERPC_KVM_ASM_H__ */
