<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
#अगर_अघोषित ARCH_PERF_BOOK3S_HV_HCALLS_H
#घोषणा ARCH_PERF_BOOK3S_HV_HCALLS_H

/*
 * PowerPC HCALL codes : hcall code to name mapping
 */
#घोषणा kvm_trace_symbol_hcall \
	अणु0x4, "H_REMOVE"पूर्ण,					\
	अणु0x8, "H_ENTER"पूर्ण,					\
	अणु0xc, "H_READ"पूर्ण,					\
	अणु0x10, "H_CLEAR_MOD"पूर्ण,					\
	अणु0x14, "H_CLEAR_REF"पूर्ण,					\
	अणु0x18, "H_PROTECT"पूर्ण,					\
	अणु0x1c, "H_GET_TCE"पूर्ण,					\
	अणु0x20, "H_PUT_TCE"पूर्ण,					\
	अणु0x24, "H_SET_SPRG0"पूर्ण,					\
	अणु0x28, "H_SET_DABR"पूर्ण,					\
	अणु0x2c, "H_PAGE_INIT"पूर्ण,					\
	अणु0x30, "H_SET_ASR"पूर्ण,					\
	अणु0x34, "H_ASR_ON"पूर्ण,					\
	अणु0x38, "H_ASR_OFF"पूर्ण,					\
	अणु0x3c, "H_LOGICAL_CI_LOAD"पूर्ण,				\
	अणु0x40, "H_LOGICAL_CI_STORE"पूर्ण,				\
	अणु0x44, "H_LOGICAL_CACHE_LOAD"पूर्ण,				\
	अणु0x48, "H_LOGICAL_CACHE_STORE"पूर्ण,			\
	अणु0x4c, "H_LOGICAL_ICBI"पूर्ण,				\
	अणु0x50, "H_LOGICAL_DCBF"पूर्ण,				\
	अणु0x54, "H_GET_TERM_CHAR"पूर्ण,				\
	अणु0x58, "H_PUT_TERM_CHAR"पूर्ण,				\
	अणु0x5c, "H_REAL_TO_LOGICAL"पूर्ण,				\
	अणु0x60, "H_HYPERVISOR_DATA"पूर्ण,				\
	अणु0x64, "H_EOI"पूर्ण,					\
	अणु0x68, "H_CPPR"पूर्ण,					\
	अणु0x6c, "H_IPI"पूर्ण,					\
	अणु0x70, "H_IPOLL"पूर्ण,					\
	अणु0x74, "H_XIRR"पूर्ण,					\
	अणु0x78, "H_MIGRATE_DMA"पूर्ण,				\
	अणु0x7c, "H_PERFMON"पूर्ण,					\
	अणु0xdc, "H_REGISTER_VPA"पूर्ण,				\
	अणु0xe0, "H_CEDE"पूर्ण,					\
	अणु0xe4, "H_CONFER"पूर्ण,					\
	अणु0xe8, "H_PROD"पूर्ण,					\
	अणु0xec, "H_GET_PPP"पूर्ण,					\
	अणु0xf0, "H_SET_PPP"पूर्ण,					\
	अणु0xf4, "H_PURR"पूर्ण,					\
	अणु0xf8, "H_PIC"पूर्ण,					\
	अणु0xfc, "H_REG_CRQ"पूर्ण,					\
	अणु0x100, "H_FREE_CRQ"पूर्ण,					\
	अणु0x104, "H_VIO_SIGNAL"पूर्ण,				\
	अणु0x108, "H_SEND_CRQ"पूर्ण,					\
	अणु0x110, "H_COPY_RDMA"पूर्ण,					\
	अणु0x114, "H_REGISTER_LOGICAL_LAN"पूर्ण,			\
	अणु0x118, "H_FREE_LOGICAL_LAN"पूर्ण,				\
	अणु0x11c, "H_ADD_LOGICAL_LAN_BUFFER"पूर्ण,			\
	अणु0x120, "H_SEND_LOGICAL_LAN"पूर्ण,				\
	अणु0x124, "H_BULK_REMOVE"पूर्ण,				\
	अणु0x130, "H_MULTICAST_CTRL"पूर्ण,				\
	अणु0x134, "H_SET_XDABR"पूर्ण,					\
	अणु0x138, "H_STUFF_TCE"पूर्ण,					\
	अणु0x13c, "H_PUT_TCE_INDIRECT"पूर्ण,				\
	अणु0x14c, "H_CHANGE_LOGICAL_LAN_MAC"पूर्ण,			\
	अणु0x150, "H_VTERM_PARTNER_INFO"पूर्ण,			\
	अणु0x154, "H_REGISTER_VTERM"पूर्ण,				\
	अणु0x158, "H_FREE_VTERM"पूर्ण,				\
	अणु0x15c, "H_RESET_EVENTS"पूर्ण,				\
	अणु0x160, "H_ALLOC_RESOURCE"पूर्ण,				\
	अणु0x164, "H_FREE_RESOURCE"पूर्ण,				\
	अणु0x168, "H_MODIFY_QP"पूर्ण,					\
	अणु0x16c, "H_QUERY_QP"पूर्ण,					\
	अणु0x170, "H_REREGISTER_PMR"पूर्ण,				\
	अणु0x174, "H_REGISTER_SMR"पूर्ण,				\
	अणु0x178, "H_QUERY_MR"पूर्ण,					\
	अणु0x17c, "H_QUERY_MW"पूर्ण,					\
	अणु0x180, "H_QUERY_HCA"पूर्ण,					\
	अणु0x184, "H_QUERY_PORT"पूर्ण,				\
	अणु0x188, "H_MODIFY_PORT"पूर्ण,				\
	अणु0x18c, "H_DEFINE_AQP1"पूर्ण,				\
	अणु0x190, "H_GET_TRACE_BUFFER"पूर्ण,				\
	अणु0x194, "H_DEFINE_AQP0"पूर्ण,				\
	अणु0x198, "H_RESIZE_MR"पूर्ण,					\
	अणु0x19c, "H_ATTACH_MCQP"पूर्ण,				\
	अणु0x1a0, "H_DETACH_MCQP"पूर्ण,				\
	अणु0x1a4, "H_CREATE_RPT"पूर्ण,				\
	अणु0x1a8, "H_REMOVE_RPT"पूर्ण,				\
	अणु0x1ac, "H_REGISTER_RPAGES"पूर्ण,				\
	अणु0x1b0, "H_DISABLE_AND_GET"पूर्ण,				\
	अणु0x1b4, "H_ERROR_DATA"पूर्ण,				\
	अणु0x1b8, "H_GET_HCA_INFO"पूर्ण,				\
	अणु0x1bc, "H_GET_PERF_COUNT"पूर्ण,				\
	अणु0x1c0, "H_MANAGE_TRACE"पूर्ण,				\
	अणु0x1d4, "H_FREE_LOGICAL_LAN_BUFFER"पूर्ण,			\
	अणु0x1d8, "H_POLL_PENDING"पूर्ण,				\
	अणु0x1e4, "H_QUERY_INT_STATE"पूर्ण,				\
	अणु0x244, "H_ILLAN_ATTRIBUTES"पूर्ण,				\
	अणु0x250, "H_MODIFY_HEA_QP"पूर्ण,				\
	अणु0x254, "H_QUERY_HEA_QP"पूर्ण,				\
	अणु0x258, "H_QUERY_HEA"पूर्ण,					\
	अणु0x25c, "H_QUERY_HEA_PORT"पूर्ण,				\
	अणु0x260, "H_MODIFY_HEA_PORT"पूर्ण,				\
	अणु0x264, "H_REG_BCMC"पूर्ण,					\
	अणु0x268, "H_DEREG_BCMC"पूर्ण,				\
	अणु0x26c, "H_REGISTER_HEA_RPAGES"पूर्ण,			\
	अणु0x270, "H_DISABLE_AND_GET_HEA"पूर्ण,			\
	अणु0x274, "H_GET_HEA_INFO"पूर्ण,				\
	अणु0x278, "H_ALLOC_HEA_RESOURCE"पूर्ण,			\
	अणु0x284, "H_ADD_CONN"पूर्ण,					\
	अणु0x288, "H_DEL_CONN"पूर्ण,					\
	अणु0x298, "H_JOIN"पूर्ण,					\
	अणु0x2a4, "H_VASI_STATE"पूर्ण,				\
	अणु0x2b0, "H_ENABLE_CRQ"पूर्ण,				\
	अणु0x2b8, "H_GET_EM_PARMS"पूर्ण,				\
	अणु0x2d0, "H_SET_MPP"पूर्ण,					\
	अणु0x2d4, "H_GET_MPP"पूर्ण,					\
	अणु0x2ec, "H_HOME_NODE_ASSOCIATIVITY"पूर्ण,			\
	अणु0x2f4, "H_BEST_ENERGY"पूर्ण,				\
	अणु0x2fc, "H_XIRR_X"पूर्ण,					\
	अणु0x300, "H_RANDOM"पूर्ण,					\
	अणु0x304, "H_COP"पूर्ण,					\
	अणु0x314, "H_GET_MPP_X"पूर्ण,					\
	अणु0x31c, "H_SET_MODE"पूर्ण,					\
	अणु0xf000, "H_RTAS"पूर्ण					\

#पूर्ण_अगर
