<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
/*
 * Device Tree defines क्रम Lochnagar pinctrl
 *
 * Copyright (c) 2018 Cirrus Logic, Inc. and
 *                    Cirrus Logic International Semiconductor Ltd.
 *
 * Author: Charles Keepax <ckeepax@खोलोsource.cirrus.com>
 */

#अगर_अघोषित DT_BINDINGS_PINCTRL_LOCHNAGAR_H
#घोषणा DT_BINDINGS_PINCTRL_LOCHNAGAR_H

#घोषणा LOCHNAGAR1_PIN_CDC_RESET		0
#घोषणा LOCHNAGAR1_PIN_DSP_RESET		1
#घोषणा LOCHNAGAR1_PIN_CDC_CIF1MODE		2
#घोषणा LOCHNAGAR1_PIN_NUM_GPIOS		3

#घोषणा LOCHNAGAR2_PIN_CDC_RESET		0
#घोषणा LOCHNAGAR2_PIN_DSP_RESET		1
#घोषणा LOCHNAGAR2_PIN_CDC_CIF1MODE		2
#घोषणा LOCHNAGAR2_PIN_CDC_LDOENA		3
#घोषणा LOCHNAGAR2_PIN_SPDIF_HWMODE		4
#घोषणा LOCHNAGAR2_PIN_SPDIF_RESET		5
#घोषणा LOCHNAGAR2_PIN_FPGA_GPIO1		6
#घोषणा LOCHNAGAR2_PIN_FPGA_GPIO2		7
#घोषणा LOCHNAGAR2_PIN_FPGA_GPIO3		8
#घोषणा LOCHNAGAR2_PIN_FPGA_GPIO4		9
#घोषणा LOCHNAGAR2_PIN_FPGA_GPIO5		10
#घोषणा LOCHNAGAR2_PIN_FPGA_GPIO6		11
#घोषणा LOCHNAGAR2_PIN_CDC_GPIO1		12
#घोषणा LOCHNAGAR2_PIN_CDC_GPIO2		13
#घोषणा LOCHNAGAR2_PIN_CDC_GPIO3		14
#घोषणा LOCHNAGAR2_PIN_CDC_GPIO4		15
#घोषणा LOCHNAGAR2_PIN_CDC_GPIO5		16
#घोषणा LOCHNAGAR2_PIN_CDC_GPIO6		17
#घोषणा LOCHNAGAR2_PIN_CDC_GPIO7		18
#घोषणा LOCHNAGAR2_PIN_CDC_GPIO8		19
#घोषणा LOCHNAGAR2_PIN_DSP_GPIO1		20
#घोषणा LOCHNAGAR2_PIN_DSP_GPIO2		21
#घोषणा LOCHNAGAR2_PIN_DSP_GPIO3		22
#घोषणा LOCHNAGAR2_PIN_DSP_GPIO4		23
#घोषणा LOCHNAGAR2_PIN_DSP_GPIO5		24
#घोषणा LOCHNAGAR2_PIN_DSP_GPIO6		25
#घोषणा LOCHNAGAR2_PIN_GF_GPIO2			26
#घोषणा LOCHNAGAR2_PIN_GF_GPIO3			27
#घोषणा LOCHNAGAR2_PIN_GF_GPIO7			28
#घोषणा LOCHNAGAR2_PIN_CDC_AIF1_BCLK		29
#घोषणा LOCHNAGAR2_PIN_CDC_AIF1_RXDAT		30
#घोषणा LOCHNAGAR2_PIN_CDC_AIF1_LRCLK		31
#घोषणा LOCHNAGAR2_PIN_CDC_AIF1_TXDAT		32
#घोषणा LOCHNAGAR2_PIN_CDC_AIF2_BCLK		33
#घोषणा LOCHNAGAR2_PIN_CDC_AIF2_RXDAT		34
#घोषणा LOCHNAGAR2_PIN_CDC_AIF2_LRCLK		35
#घोषणा LOCHNAGAR2_PIN_CDC_AIF2_TXDAT		36
#घोषणा LOCHNAGAR2_PIN_CDC_AIF3_BCLK		37
#घोषणा LOCHNAGAR2_PIN_CDC_AIF3_RXDAT		38
#घोषणा LOCHNAGAR2_PIN_CDC_AIF3_LRCLK		39
#घोषणा LOCHNAGAR2_PIN_CDC_AIF3_TXDAT		40
#घोषणा LOCHNAGAR2_PIN_DSP_AIF1_BCLK		41
#घोषणा LOCHNAGAR2_PIN_DSP_AIF1_RXDAT		42
#घोषणा LOCHNAGAR2_PIN_DSP_AIF1_LRCLK		43
#घोषणा LOCHNAGAR2_PIN_DSP_AIF1_TXDAT		44
#घोषणा LOCHNAGAR2_PIN_DSP_AIF2_BCLK		45
#घोषणा LOCHNAGAR2_PIN_DSP_AIF2_RXDAT		46
#घोषणा LOCHNAGAR2_PIN_DSP_AIF2_LRCLK		47
#घोषणा LOCHNAGAR2_PIN_DSP_AIF2_TXDAT		48
#घोषणा LOCHNAGAR2_PIN_PSIA1_BCLK		49
#घोषणा LOCHNAGAR2_PIN_PSIA1_RXDAT		50
#घोषणा LOCHNAGAR2_PIN_PSIA1_LRCLK		51
#घोषणा LOCHNAGAR2_PIN_PSIA1_TXDAT		52
#घोषणा LOCHNAGAR2_PIN_PSIA2_BCLK		53
#घोषणा LOCHNAGAR2_PIN_PSIA2_RXDAT		54
#घोषणा LOCHNAGAR2_PIN_PSIA2_LRCLK		55
#घोषणा LOCHNAGAR2_PIN_PSIA2_TXDAT		56
#घोषणा LOCHNAGAR2_PIN_GF_AIF3_BCLK		57
#घोषणा LOCHNAGAR2_PIN_GF_AIF3_RXDAT		58
#घोषणा LOCHNAGAR2_PIN_GF_AIF3_LRCLK		59
#घोषणा LOCHNAGAR2_PIN_GF_AIF3_TXDAT		60
#घोषणा LOCHNAGAR2_PIN_GF_AIF4_BCLK		61
#घोषणा LOCHNAGAR2_PIN_GF_AIF4_RXDAT		62
#घोषणा LOCHNAGAR2_PIN_GF_AIF4_LRCLK		63
#घोषणा LOCHNAGAR2_PIN_GF_AIF4_TXDAT		64
#घोषणा LOCHNAGAR2_PIN_GF_AIF1_BCLK		65
#घोषणा LOCHNAGAR2_PIN_GF_AIF1_RXDAT		66
#घोषणा LOCHNAGAR2_PIN_GF_AIF1_LRCLK		67
#घोषणा LOCHNAGAR2_PIN_GF_AIF1_TXDAT		68
#घोषणा LOCHNAGAR2_PIN_GF_AIF2_BCLK		69
#घोषणा LOCHNAGAR2_PIN_GF_AIF2_RXDAT		70
#घोषणा LOCHNAGAR2_PIN_GF_AIF2_LRCLK		71
#घोषणा LOCHNAGAR2_PIN_GF_AIF2_TXDAT		72
#घोषणा LOCHNAGAR2_PIN_DSP_UART1_RX		73
#घोषणा LOCHNAGAR2_PIN_DSP_UART1_TX		74
#घोषणा LOCHNAGAR2_PIN_DSP_UART2_RX		75
#घोषणा LOCHNAGAR2_PIN_DSP_UART2_TX		76
#घोषणा LOCHNAGAR2_PIN_GF_UART2_RX		77
#घोषणा LOCHNAGAR2_PIN_GF_UART2_TX		78
#घोषणा LOCHNAGAR2_PIN_USB_UART_RX		79
#घोषणा LOCHNAGAR2_PIN_CDC_PDMCLK1		80
#घोषणा LOCHNAGAR2_PIN_CDC_PDMDAT1		81
#घोषणा LOCHNAGAR2_PIN_CDC_PDMCLK2		82
#घोषणा LOCHNAGAR2_PIN_CDC_PDMDAT2		83
#घोषणा LOCHNAGAR2_PIN_CDC_DMICCLK1		84
#घोषणा LOCHNAGAR2_PIN_CDC_DMICDAT1		85
#घोषणा LOCHNAGAR2_PIN_CDC_DMICCLK2		86
#घोषणा LOCHNAGAR2_PIN_CDC_DMICDAT2		87
#घोषणा LOCHNAGAR2_PIN_CDC_DMICCLK3		88
#घोषणा LOCHNAGAR2_PIN_CDC_DMICDAT3		89
#घोषणा LOCHNAGAR2_PIN_CDC_DMICCLK4		90
#घोषणा LOCHNAGAR2_PIN_CDC_DMICDAT4		91
#घोषणा LOCHNAGAR2_PIN_DSP_DMICCLK1		92
#घोषणा LOCHNAGAR2_PIN_DSP_DMICDAT1		93
#घोषणा LOCHNAGAR2_PIN_DSP_DMICCLK2		94
#घोषणा LOCHNAGAR2_PIN_DSP_DMICDAT2		95
#घोषणा LOCHNAGAR2_PIN_I2C2_SCL			96
#घोषणा LOCHNAGAR2_PIN_I2C2_SDA			97
#घोषणा LOCHNAGAR2_PIN_I2C3_SCL			98
#घोषणा LOCHNAGAR2_PIN_I2C3_SDA			99
#घोषणा LOCHNAGAR2_PIN_I2C4_SCL			100
#घोषणा LOCHNAGAR2_PIN_I2C4_SDA			101
#घोषणा LOCHNAGAR2_PIN_DSP_STANDBY		102
#घोषणा LOCHNAGAR2_PIN_CDC_MCLK1		103
#घोषणा LOCHNAGAR2_PIN_CDC_MCLK2		104
#घोषणा LOCHNAGAR2_PIN_DSP_CLKIN		105
#घोषणा LOCHNAGAR2_PIN_PSIA1_MCLK		106
#घोषणा LOCHNAGAR2_PIN_PSIA2_MCLK		107
#घोषणा LOCHNAGAR2_PIN_GF_GPIO1			108
#घोषणा LOCHNAGAR2_PIN_GF_GPIO5			109
#घोषणा LOCHNAGAR2_PIN_DSP_GPIO20		110
#घोषणा LOCHNAGAR2_PIN_NUM_GPIOS		111

#पूर्ण_अगर
