<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
#अगर_अघोषित __ASM_MACH_LOONGSON64_WORKAROUNDS_H_
#घोषणा __ASM_MACH_LOONGSON64_WORKAROUNDS_H_

#घोषणा WORKAROUND_CPUFREQ	0x00000001
#घोषणा WORKAROUND_CPUHOTPLUG	0x00000002

#पूर्ण_अगर
