<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0-only WITH Linux-syscall-note */
/* Copyright (C) 2020 Intel Corporation */

#अगर_अघोषित __UAPI_CCS_H__
#घोषणा __UAPI_CCS_H__

#समावेश <linux/v4l2-controls.h>

#घोषणा V4L2_CID_CCS_ANALOGUE_GAIN_M0		(V4L2_CID_USER_CCS_BASE + 1)
#घोषणा V4L2_CID_CCS_ANALOGUE_GAIN_C0		(V4L2_CID_USER_CCS_BASE + 2)
#घोषणा V4L2_CID_CCS_ANALOGUE_GAIN_M1		(V4L2_CID_USER_CCS_BASE + 3)
#घोषणा V4L2_CID_CCS_ANALOGUE_GAIN_C1		(V4L2_CID_USER_CCS_BASE + 4)
#घोषणा V4L2_CID_CCS_ANALOGUE_LINEAR_GAIN	(V4L2_CID_USER_CCS_BASE + 5)
#घोषणा V4L2_CID_CCS_ANALOGUE_EXPONENTIAL_GAIN	(V4L2_CID_USER_CCS_BASE + 6)
#घोषणा V4L2_CID_CCS_SHADING_CORRECTION		(V4L2_CID_USER_CCS_BASE + 8)
#घोषणा V4L2_CID_CCS_LUMIन_अंकCE_CORRECTION_LEVEL	(V4L2_CID_USER_CCS_BASE + 9)

#पूर्ण_अगर
