<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
/*
 * mtu3_hw_regs.h - MediaTek USB3 DRD रेजिस्टर and field definitions
 *
 * Copyright (C) 2016 MediaTek Inc.
 *
 * Author: Chunfeng Yun <chunfeng.yun@mediatek.com>
 */

#अगर_अघोषित _SSUSB_HW_REGS_H_
#घोषणा _SSUSB_HW_REGS_H_

/* segment offset of MAC रेजिस्टर */
#घोषणा SSUSB_DEV_BASE		0x0000
#घोषणा SSUSB_EPCTL_CSR_BASE	0x0800
#घोषणा SSUSB_USB3_MAC_CSR_BASE	0x1400
#घोषणा SSUSB_USB3_SYS_CSR_BASE	0x1400
#घोषणा SSUSB_USB2_CSR_BASE	0x2400

/* IPPC रेजिस्टर in Infra */
#घोषणा SSUSB_SIFSLV_IPPC_BASE	0x0000

/* --------------- SSUSB_DEV REGISTER DEFINITION --------------- */

#घोषणा U3D_LV1ISR		(SSUSB_DEV_BASE + 0x0000)
#घोषणा U3D_LV1IER		(SSUSB_DEV_BASE + 0x0004)
#घोषणा U3D_LV1IESR		(SSUSB_DEV_BASE + 0x0008)
#घोषणा U3D_LV1IECR		(SSUSB_DEV_BASE + 0x000C)

#घोषणा U3D_EPISR		(SSUSB_DEV_BASE + 0x0080)
#घोषणा U3D_EPIER		(SSUSB_DEV_BASE + 0x0084)
#घोषणा U3D_EPIESR		(SSUSB_DEV_BASE + 0x0088)
#घोषणा U3D_EPIECR		(SSUSB_DEV_BASE + 0x008C)

#घोषणा U3D_EP0CSR		(SSUSB_DEV_BASE + 0x0100)
#घोषणा U3D_RXCOUNT0		(SSUSB_DEV_BASE + 0x0108)
#घोषणा U3D_RESERVED		(SSUSB_DEV_BASE + 0x010C)
#घोषणा U3D_TX1CSR0		(SSUSB_DEV_BASE + 0x0110)
#घोषणा U3D_TX1CSR1		(SSUSB_DEV_BASE + 0x0114)
#घोषणा U3D_TX1CSR2		(SSUSB_DEV_BASE + 0x0118)

#घोषणा U3D_RX1CSR0		(SSUSB_DEV_BASE + 0x0210)
#घोषणा U3D_RX1CSR1		(SSUSB_DEV_BASE + 0x0214)
#घोषणा U3D_RX1CSR2		(SSUSB_DEV_BASE + 0x0218)

#घोषणा U3D_FIFO0		(SSUSB_DEV_BASE + 0x0300)

#घोषणा U3D_QCR0		(SSUSB_DEV_BASE + 0x0400)
#घोषणा U3D_QCR1		(SSUSB_DEV_BASE + 0x0404)
#घोषणा U3D_QCR2		(SSUSB_DEV_BASE + 0x0408)
#घोषणा U3D_QCR3		(SSUSB_DEV_BASE + 0x040C)
#घोषणा U3D_QFCR		(SSUSB_DEV_BASE + 0x0428)
#घोषणा U3D_TXQHIAR1		(SSUSB_DEV_BASE + 0x0484)
#घोषणा U3D_RXQHIAR1		(SSUSB_DEV_BASE + 0x04C4)

#घोषणा U3D_TXQCSR1		(SSUSB_DEV_BASE + 0x0510)
#घोषणा U3D_TXQSAR1		(SSUSB_DEV_BASE + 0x0514)
#घोषणा U3D_TXQCPR1		(SSUSB_DEV_BASE + 0x0518)

#घोषणा U3D_RXQCSR1		(SSUSB_DEV_BASE + 0x0610)
#घोषणा U3D_RXQSAR1		(SSUSB_DEV_BASE + 0x0614)
#घोषणा U3D_RXQCPR1		(SSUSB_DEV_BASE + 0x0618)
#घोषणा U3D_RXQLDPR1		(SSUSB_DEV_BASE + 0x061C)

#घोषणा U3D_QISAR0		(SSUSB_DEV_BASE + 0x0700)
#घोषणा U3D_QIER0		(SSUSB_DEV_BASE + 0x0704)
#घोषणा U3D_QIESR0		(SSUSB_DEV_BASE + 0x0708)
#घोषणा U3D_QIECR0		(SSUSB_DEV_BASE + 0x070C)
#घोषणा U3D_QISAR1		(SSUSB_DEV_BASE + 0x0710)
#घोषणा U3D_QIER1		(SSUSB_DEV_BASE + 0x0714)
#घोषणा U3D_QIESR1		(SSUSB_DEV_BASE + 0x0718)
#घोषणा U3D_QIECR1		(SSUSB_DEV_BASE + 0x071C)

#घोषणा U3D_TQERRIR0		(SSUSB_DEV_BASE + 0x0780)
#घोषणा U3D_TQERRIER0		(SSUSB_DEV_BASE + 0x0784)
#घोषणा U3D_TQERRIESR0		(SSUSB_DEV_BASE + 0x0788)
#घोषणा U3D_TQERRIECR0		(SSUSB_DEV_BASE + 0x078C)
#घोषणा U3D_RQERRIR0		(SSUSB_DEV_BASE + 0x07C0)
#घोषणा U3D_RQERRIER0		(SSUSB_DEV_BASE + 0x07C4)
#घोषणा U3D_RQERRIESR0		(SSUSB_DEV_BASE + 0x07C8)
#घोषणा U3D_RQERRIECR0		(SSUSB_DEV_BASE + 0x07CC)
#घोषणा U3D_RQERRIR1		(SSUSB_DEV_BASE + 0x07D0)
#घोषणा U3D_RQERRIER1		(SSUSB_DEV_BASE + 0x07D4)
#घोषणा U3D_RQERRIESR1		(SSUSB_DEV_BASE + 0x07D8)
#घोषणा U3D_RQERRIECR1		(SSUSB_DEV_BASE + 0x07DC)

#घोषणा U3D_CAP_EP0FFSZ		(SSUSB_DEV_BASE + 0x0C04)
#घोषणा U3D_CAP_EPNTXFFSZ	(SSUSB_DEV_BASE + 0x0C08)
#घोषणा U3D_CAP_EPNRXFFSZ	(SSUSB_DEV_BASE + 0x0C0C)
#घोषणा U3D_CAP_EPINFO		(SSUSB_DEV_BASE + 0x0C10)
#घोषणा U3D_MISC_CTRL		(SSUSB_DEV_BASE + 0x0C84)

/*---------------- SSUSB_DEV FIELD DEFINITION ---------------*/

/* U3D_LV1ISR */
#घोषणा EP_CTRL_INTR		BIT(5)
#घोषणा MAC2_INTR		BIT(4)
#घोषणा DMA_INTR		BIT(3)
#घोषणा MAC3_INTR		BIT(2)
#घोषणा QMU_INTR		BIT(1)
#घोषणा BMU_INTR		BIT(0)

/* U3D_LV1IECR */
#घोषणा LV1IECR_MSK		GENMASK(31, 0)

/* U3D_EPISR */
#घोषणा EPRISR(x)		(BIT(16) << (x))
#घोषणा SETUPENDISR		BIT(16)
#घोषणा EPTISR(x)		(BIT(0) << (x))
#घोषणा EP0ISR			BIT(0)

/* U3D_EP0CSR */
#घोषणा EP0_SENDSTALL		BIT(25)
#घोषणा EP0_FIFOFULL		BIT(23)
#घोषणा EP0_SENTSTALL		BIT(22)
#घोषणा EP0_DPHTX		BIT(20)
#घोषणा EP0_DATAEND		BIT(19)
#घोषणा EP0_TXPKTRDY		BIT(18)
#घोषणा EP0_SETUPPKTRDY		BIT(17)
#घोषणा EP0_RXPKTRDY		BIT(16)
#घोषणा EP0_MAXPKTSZ_MSK	GENMASK(9, 0)
#घोषणा EP0_MAXPKTSZ(x)		((x) & EP0_MAXPKTSZ_MSK)
#घोषणा EP0_W1C_BITS	(~(EP0_RXPKTRDY | EP0_SETUPPKTRDY | EP0_SENTSTALL))

/* U3D_TX1CSR0 */
#घोषणा TX_DMAREQEN		BIT(29)
#घोषणा TX_FIFOFULL		BIT(25)
#घोषणा TX_FIFOEMPTY		BIT(24)
#घोषणा TX_SENTSTALL		BIT(22)
#घोषणा TX_SENDSTALL		BIT(21)
#घोषणा TX_TXPKTRDY		BIT(16)
#घोषणा TX_TXMAXPKTSZ_MSK	GENMASK(10, 0)
#घोषणा TX_TXMAXPKTSZ(x)	((x) & TX_TXMAXPKTSZ_MSK)
#घोषणा TX_W1C_BITS		(~(TX_SENTSTALL))

/* U3D_TX1CSR1 */
#घोषणा TX_MAX_PKT_G2(x)	(((x) & 0xff) << 24)
#घोषणा TX_MULT_G2(x)		(((x) & 0x7) << 21)
#घोषणा TX_MULT_OG(x)		(((x) & 0x3) << 22)
#घोषणा TX_MAX_PKT_OG(x)	(((x) & 0x3f) << 16)
#घोषणा TX_SLOT(x)		(((x) & 0x3f) << 8)
#घोषणा TX_TYPE(x)		(((x) & 0x3) << 4)
#घोषणा TX_SS_BURST(x)		(((x) & 0xf) << 0)
#घोषणा TX_MULT(g2c, x)		\
(अणु				\
	typeof(x) x_ = (x);	\
	(g2c) ? TX_MULT_G2(x_) : TX_MULT_OG(x_);	\
पूर्ण)
#घोषणा TX_MAX_PKT(g2c, x)	\
(अणु				\
	typeof(x) x_ = (x);	\
	(g2c) ? TX_MAX_PKT_G2(x_) : TX_MAX_PKT_OG(x_);	\
पूर्ण)

/* क्रम TX_TYPE & RX_TYPE */
#घोषणा TYPE_BULK		(0x0)
#घोषणा TYPE_INT		(0x1)
#घोषणा TYPE_ISO		(0x2)
#घोषणा TYPE_MASK		(0x3)

/* U3D_TX1CSR2 */
#घोषणा TX_BINTERVAL(x)		(((x) & 0xff) << 24)
#घोषणा TX_FIFOSEGSIZE(x)	(((x) & 0xf) << 16)
#घोषणा TX_FIFOADDR(x)		(((x) & 0x1fff) << 0)

/* U3D_RX1CSR0 */
#घोषणा RX_DMAREQEN		BIT(29)
#घोषणा RX_SENTSTALL		BIT(22)
#घोषणा RX_SENDSTALL		BIT(21)
#घोषणा RX_RXPKTRDY		BIT(16)
#घोषणा RX_RXMAXPKTSZ_MSK	GENMASK(10, 0)
#घोषणा RX_RXMAXPKTSZ(x)	((x) & RX_RXMAXPKTSZ_MSK)
#घोषणा RX_W1C_BITS		(~(RX_SENTSTALL | RX_RXPKTRDY))

/* U3D_RX1CSR1 */
#घोषणा RX_MAX_PKT_G2(x)	(((x) & 0xff) << 24)
#घोषणा RX_MULT_G2(x)		(((x) & 0x7) << 21)
#घोषणा RX_MULT_OG(x)		(((x) & 0x3) << 22)
#घोषणा RX_MAX_PKT_OG(x)	(((x) & 0x3f) << 16)
#घोषणा RX_SLOT(x)		(((x) & 0x3f) << 8)
#घोषणा RX_TYPE(x)		(((x) & 0x3) << 4)
#घोषणा RX_SS_BURST(x)		(((x) & 0xf) << 0)
#घोषणा RX_MULT(g2c, x)		\
(अणु				\
	typeof(x) x_ = (x);	\
	(g2c) ? RX_MULT_G2(x_) : RX_MULT_OG(x_);	\
पूर्ण)
#घोषणा RX_MAX_PKT(g2c, x)	\
(अणु				\
	typeof(x) x_ = (x);	\
	(g2c) ? RX_MAX_PKT_G2(x_) : RX_MAX_PKT_OG(x_);	\
पूर्ण)

/* U3D_RX1CSR2 */
#घोषणा RX_BINTERVAL(x)		(((x) & 0xff) << 24)
#घोषणा RX_FIFOSEGSIZE(x)	(((x) & 0xf) << 16)
#घोषणा RX_FIFOADDR(x)		(((x) & 0x1fff) << 0)

/* U3D_QCR0 */
#घोषणा QMU_RX_CS_EN(x)		(BIT(16) << (x))
#घोषणा QMU_TX_CS_EN(x)		(BIT(0) << (x))
#घोषणा QMU_CS16B_EN		BIT(0)

/* U3D_QCR1 */
#घोषणा QMU_TX_ZLP(x)		(BIT(0) << (x))

/* U3D_QCR3 */
#घोषणा QMU_RX_COZ(x)		(BIT(16) << (x))
#घोषणा QMU_RX_ZLP(x)		(BIT(0) << (x))

/* U3D_TXQHIAR1 */
/* U3D_RXQHIAR1 */
#घोषणा QMU_LAST_DONE_PTR_HI(x)	(((x) >> 16) & 0xf)
#घोषणा QMU_CUR_GPD_ADDR_HI(x)	(((x) >> 8) & 0xf)
#घोषणा QMU_START_ADDR_HI_MSK	GENMASK(3, 0)
#घोषणा QMU_START_ADDR_HI(x)	(((x) & 0xf) << 0)

/* U3D_TXQCSR1 */
/* U3D_RXQCSR1 */
#घोषणा QMU_Q_ACTIVE		BIT(15)
#घोषणा QMU_Q_STOP		BIT(2)
#घोषणा QMU_Q_RESUME		BIT(1)
#घोषणा QMU_Q_START		BIT(0)

/* U3D_QISAR0, U3D_QIER0, U3D_QIESR0, U3D_QIECR0 */
#घोषणा QMU_RX_DONE_INT(x)	(BIT(16) << (x))
#घोषणा QMU_TX_DONE_INT(x)	(BIT(0) << (x))

/* U3D_QISAR1, U3D_QIER1, U3D_QIESR1, U3D_QIECR1 */
#घोषणा RXQ_ZLPERR_INT		BIT(20)
#घोषणा RXQ_LENERR_INT		BIT(18)
#घोषणा RXQ_CSERR_INT		BIT(17)
#घोषणा RXQ_EMPTY_INT		BIT(16)
#घोषणा TXQ_LENERR_INT		BIT(2)
#घोषणा TXQ_CSERR_INT		BIT(1)
#घोषणा TXQ_EMPTY_INT		BIT(0)

/* U3D_TQERRIR0, U3D_TQERRIER0, U3D_TQERRIESR0, U3D_TQERRIECR0 */
#घोषणा QMU_TX_LEN_ERR(x)	(BIT(16) << (x))
#घोषणा QMU_TX_CS_ERR(x)	(BIT(0) << (x))

/* U3D_RQERRIR0, U3D_RQERRIER0, U3D_RQERRIESR0, U3D_RQERRIECR0 */
#घोषणा QMU_RX_LEN_ERR(x)	(BIT(16) << (x))
#घोषणा QMU_RX_CS_ERR(x)	(BIT(0) << (x))

/* U3D_RQERRIR1, U3D_RQERRIER1, U3D_RQERRIESR1, U3D_RQERRIECR1 */
#घोषणा QMU_RX_ZLP_ERR(n)	(BIT(16) << (n))

/* U3D_CAP_EPINFO */
#घोषणा CAP_RX_EP_NUM(x)	(((x) >> 8) & 0x1f)
#घोषणा CAP_TX_EP_NUM(x)	((x) & 0x1f)

/* U3D_MISC_CTRL */
#घोषणा DMA_ADDR_36BIT		BIT(31)
#घोषणा VBUS_ON			BIT(1)
#घोषणा VBUS_FRC_EN		BIT(0)


/*---------------- SSUSB_EPCTL_CSR REGISTER DEFINITION ----------------*/

#घोषणा U3D_DEVICE_CONF			(SSUSB_EPCTL_CSR_BASE + 0x0000)
#घोषणा U3D_EP_RST			(SSUSB_EPCTL_CSR_BASE + 0x0004)

#घोषणा U3D_DEV_LINK_INTR_ENABLE	(SSUSB_EPCTL_CSR_BASE + 0x0050)
#घोषणा U3D_DEV_LINK_INTR		(SSUSB_EPCTL_CSR_BASE + 0x0054)

/*---------------- SSUSB_EPCTL_CSR FIELD DEFINITION ----------------*/

/* U3D_DEVICE_CONF */
#घोषणा DEV_ADDR_MSK		GENMASK(30, 24)
#घोषणा DEV_ADDR(x)		((0x7f & (x)) << 24)
#घोषणा HW_USB2_3_SEL		BIT(18)
#घोषणा SW_USB2_3_SEL_EN	BIT(17)
#घोषणा SW_USB2_3_SEL		BIT(16)
#घोषणा SSUSB_DEV_SPEED(x)	((x) & 0x7)

/* U3D_EP_RST */
#घोषणा EP1_IN_RST		BIT(17)
#घोषणा EP1_OUT_RST		BIT(1)
#घोषणा EP_RST(is_in, epnum)	(((is_in) ? BIT(16) : BIT(0)) << (epnum))
#घोषणा EP0_RST			BIT(0)

/* U3D_DEV_LINK_INTR_ENABLE */
/* U3D_DEV_LINK_INTR */
#घोषणा SSUSB_DEV_SPEED_CHG_INTR	BIT(0)


/*---------------- SSUSB_USB3_MAC_CSR REGISTER DEFINITION ----------------*/

#घोषणा U3D_LTSSM_CTRL		(SSUSB_USB3_MAC_CSR_BASE + 0x0010)
#घोषणा U3D_USB3_CONFIG		(SSUSB_USB3_MAC_CSR_BASE + 0x001C)

#घोषणा U3D_LINK_STATE_MACHINE	(SSUSB_USB3_MAC_CSR_BASE + 0x0134)
#घोषणा U3D_LTSSM_INTR_ENABLE	(SSUSB_USB3_MAC_CSR_BASE + 0x013C)
#घोषणा U3D_LTSSM_INTR		(SSUSB_USB3_MAC_CSR_BASE + 0x0140)

#घोषणा U3D_U3U2_SWITCH_CTRL	(SSUSB_USB3_MAC_CSR_BASE + 0x0170)

/*---------------- SSUSB_USB3_MAC_CSR FIELD DEFINITION ----------------*/

/* U3D_LTSSM_CTRL */
#घोषणा FORCE_POLLING_FAIL	BIT(4)
#घोषणा FORCE_RXDETECT_FAIL	BIT(3)
#घोषणा SOFT_U3_EXIT_EN		BIT(2)
#घोषणा COMPLIANCE_EN		BIT(1)
#घोषणा U1_GO_U2_EN		BIT(0)

/* U3D_USB3_CONFIG */
#घोषणा USB3_EN			BIT(0)

/* U3D_LINK_STATE_MACHINE */
#घोषणा LTSSM_STATE(x)	((x) & 0x1f)

/* U3D_LTSSM_INTR_ENABLE */
/* U3D_LTSSM_INTR */
#घोषणा U3_RESUME_INTR		BIT(18)
#घोषणा U3_LFPS_TMOUT_INTR	BIT(17)
#घोषणा VBUS_FALL_INTR		BIT(16)
#घोषणा VBUS_RISE_INTR		BIT(15)
#घोषणा RXDET_SUCCESS_INTR	BIT(14)
#घोषणा EXIT_U3_INTR		BIT(13)
#घोषणा EXIT_U2_INTR		BIT(12)
#घोषणा EXIT_U1_INTR		BIT(11)
#घोषणा ENTER_U3_INTR		BIT(10)
#घोषणा ENTER_U2_INTR		BIT(9)
#घोषणा ENTER_U1_INTR		BIT(8)
#घोषणा ENTER_U0_INTR		BIT(7)
#घोषणा RECOVERY_INTR		BIT(6)
#घोषणा WARM_RST_INTR		BIT(5)
#घोषणा HOT_RST_INTR		BIT(4)
#घोषणा LOOPBACK_INTR		BIT(3)
#घोषणा COMPLIANCE_INTR		BIT(2)
#घोषणा SS_DISABLE_INTR		BIT(1)
#घोषणा SS_INACTIVE_INTR	BIT(0)

/* U3D_U3U2_SWITCH_CTRL */
#घोषणा SOFTCON_CLR_AUTO_EN	BIT(0)

/*---------------- SSUSB_USB3_SYS_CSR REGISTER DEFINITION ----------------*/

#घोषणा U3D_LINK_UX_INACT_TIMER	(SSUSB_USB3_SYS_CSR_BASE + 0x020C)
#घोषणा U3D_LINK_POWER_CONTROL	(SSUSB_USB3_SYS_CSR_BASE + 0x0210)
#घोषणा U3D_LINK_ERR_COUNT	(SSUSB_USB3_SYS_CSR_BASE + 0x0214)

/*---------------- SSUSB_USB3_SYS_CSR FIELD DEFINITION ----------------*/

/* U3D_LINK_UX_INACT_TIMER */
#घोषणा DEV_U2_INACT_TIMEOUT_MSK	GENMASK(23, 16)
#घोषणा DEV_U2_INACT_TIMEOUT_VALUE(x)	(((x) & 0xff) << 16)
#घोषणा U2_INACT_TIMEOUT_MSK		GENMASK(15, 8)
#घोषणा U1_INACT_TIMEOUT_MSK		GENMASK(7, 0)
#घोषणा U1_INACT_TIMEOUT_VALUE(x)	((x) & 0xff)

/* U3D_LINK_POWER_CONTROL */
#घोषणा SW_U2_ACCEPT_ENABLE	BIT(9)
#घोषणा SW_U1_ACCEPT_ENABLE	BIT(8)
#घोषणा UX_EXIT			BIT(5)
#घोषणा LGO_U3			BIT(4)
#घोषणा LGO_U2			BIT(3)
#घोषणा LGO_U1			BIT(2)
#घोषणा SW_U2_REQUEST_ENABLE	BIT(1)
#घोषणा SW_U1_REQUEST_ENABLE	BIT(0)

/* U3D_LINK_ERR_COUNT */
#घोषणा CLR_LINK_ERR_CNT	BIT(16)
#घोषणा LINK_ERROR_COUNT	GENMASK(15, 0)

/*---------------- SSUSB_USB2_CSR REGISTER DEFINITION ----------------*/

#घोषणा U3D_POWER_MANAGEMENT		(SSUSB_USB2_CSR_BASE + 0x0004)
#घोषणा U3D_DEVICE_CONTROL		(SSUSB_USB2_CSR_BASE + 0x000C)
#घोषणा U3D_USB2_TEST_MODE		(SSUSB_USB2_CSR_BASE + 0x0014)
#घोषणा U3D_COMMON_USB_INTR_ENABLE	(SSUSB_USB2_CSR_BASE + 0x0018)
#घोषणा U3D_COMMON_USB_INTR		(SSUSB_USB2_CSR_BASE + 0x001C)
#घोषणा U3D_LINK_RESET_INFO		(SSUSB_USB2_CSR_BASE + 0x0024)
#घोषणा U3D_USB20_FRAME_NUM		(SSUSB_USB2_CSR_BASE + 0x003C)
#घोषणा U3D_USB20_LPM_PARAMETER		(SSUSB_USB2_CSR_BASE + 0x0044)
#घोषणा U3D_USB20_MISC_CONTROL		(SSUSB_USB2_CSR_BASE + 0x004C)
#घोषणा U3D_USB20_OPSTATE		(SSUSB_USB2_CSR_BASE + 0x0060)

/*---------------- SSUSB_USB2_CSR FIELD DEFINITION ----------------*/

/* U3D_POWER_MANAGEMENT */
#घोषणा LPM_BESL_STALL		BIT(14)
#घोषणा LPM_BESLD_STALL		BIT(13)
#घोषणा LPM_RWP			BIT(11)
#घोषणा LPM_HRWE		BIT(10)
#घोषणा LPM_MODE(x)		(((x) & 0x3) << 8)
#घोषणा ISO_UPDATE		BIT(7)
#घोषणा SOFT_CONN		BIT(6)
#घोषणा HS_ENABLE		BIT(5)
#घोषणा RESUME			BIT(2)
#घोषणा SUSPENDM_ENABLE		BIT(0)

/* U3D_DEVICE_CONTROL */
#घोषणा DC_HOSTREQ		BIT(1)
#घोषणा DC_SESSION		BIT(0)

/* U3D_USB2_TEST_MODE */
#घोषणा U2U3_AUTO_SWITCH	BIT(10)
#घोषणा LPM_FORCE_STALL		BIT(8)
#घोषणा FIFO_ACCESS		BIT(6)
#घोषणा FORCE_FS		BIT(5)
#घोषणा FORCE_HS		BIT(4)
#घोषणा TEST_PACKET_MODE	BIT(3)
#घोषणा TEST_K_MODE		BIT(2)
#घोषणा TEST_J_MODE		BIT(1)
#घोषणा TEST_SE0_NAK_MODE	BIT(0)

/* U3D_COMMON_USB_INTR_ENABLE */
/* U3D_COMMON_USB_INTR */
#घोषणा LPM_RESUME_INTR		BIT(9)
#घोषणा LPM_INTR		BIT(8)
#घोषणा DISCONN_INTR		BIT(5)
#घोषणा CONN_INTR		BIT(4)
#घोषणा SOF_INTR		BIT(3)
#घोषणा RESET_INTR		BIT(2)
#घोषणा RESUME_INTR		BIT(1)
#घोषणा SUSPEND_INTR		BIT(0)

/* U3D_LINK_RESET_INFO */
#घोषणा WTCHRP_MSK		GENMASK(19, 16)

/* U3D_USB20_LPM_PARAMETER */
#घोषणा LPM_BESLCK_U3(x)	(((x) & 0xf) << 12)
#घोषणा LPM_BESLCK(x)		(((x) & 0xf) << 8)
#घोषणा LPM_BESLDCK(x)		(((x) & 0xf) << 4)
#घोषणा LPM_BESL		GENMASK(3, 0)

/* U3D_USB20_MISC_CONTROL */
#घोषणा LPM_U3_ACK_EN		BIT(0)

/*---------------- SSUSB_SIFSLV_IPPC REGISTER DEFINITION ----------------*/

#घोषणा U3D_SSUSB_IP_PW_CTRL0	(SSUSB_SIFSLV_IPPC_BASE + 0x0000)
#घोषणा U3D_SSUSB_IP_PW_CTRL1	(SSUSB_SIFSLV_IPPC_BASE + 0x0004)
#घोषणा U3D_SSUSB_IP_PW_CTRL2	(SSUSB_SIFSLV_IPPC_BASE + 0x0008)
#घोषणा U3D_SSUSB_IP_PW_CTRL3	(SSUSB_SIFSLV_IPPC_BASE + 0x000C)
#घोषणा U3D_SSUSB_IP_PW_STS1	(SSUSB_SIFSLV_IPPC_BASE + 0x0010)
#घोषणा U3D_SSUSB_IP_PW_STS2	(SSUSB_SIFSLV_IPPC_BASE + 0x0014)
#घोषणा U3D_SSUSB_OTG_STS	(SSUSB_SIFSLV_IPPC_BASE + 0x0018)
#घोषणा U3D_SSUSB_OTG_STS_CLR	(SSUSB_SIFSLV_IPPC_BASE + 0x001C)
#घोषणा U3D_SSUSB_IP_XHCI_CAP	(SSUSB_SIFSLV_IPPC_BASE + 0x0024)
#घोषणा U3D_SSUSB_IP_DEV_CAP	(SSUSB_SIFSLV_IPPC_BASE + 0x0028)
#घोषणा U3D_SSUSB_OTG_INT_EN	(SSUSB_SIFSLV_IPPC_BASE + 0x002C)
#घोषणा U3D_SSUSB_U3_CTRL_0P	(SSUSB_SIFSLV_IPPC_BASE + 0x0030)
#घोषणा U3D_SSUSB_U2_CTRL_0P	(SSUSB_SIFSLV_IPPC_BASE + 0x0050)
#घोषणा U3D_SSUSB_REF_CK_CTRL	(SSUSB_SIFSLV_IPPC_BASE + 0x008C)
#घोषणा U3D_SSUSB_DEV_RST_CTRL	(SSUSB_SIFSLV_IPPC_BASE + 0x0098)
#घोषणा U3D_SSUSB_HW_ID		(SSUSB_SIFSLV_IPPC_BASE + 0x00A0)
#घोषणा U3D_SSUSB_HW_SUB_ID	(SSUSB_SIFSLV_IPPC_BASE + 0x00A4)
#घोषणा U3D_SSUSB_IP_TRUNK_VERS	(U3D_SSUSB_HW_SUB_ID)
#घोषणा U3D_SSUSB_PRB_CTRL0	(SSUSB_SIFSLV_IPPC_BASE + 0x00B0)
#घोषणा U3D_SSUSB_PRB_CTRL1	(SSUSB_SIFSLV_IPPC_BASE + 0x00B4)
#घोषणा U3D_SSUSB_PRB_CTRL2	(SSUSB_SIFSLV_IPPC_BASE + 0x00B8)
#घोषणा U3D_SSUSB_PRB_CTRL3	(SSUSB_SIFSLV_IPPC_BASE + 0x00BC)
#घोषणा U3D_SSUSB_PRB_CTRL4	(SSUSB_SIFSLV_IPPC_BASE + 0x00C0)
#घोषणा U3D_SSUSB_PRB_CTRL5	(SSUSB_SIFSLV_IPPC_BASE + 0x00C4)
#घोषणा U3D_SSUSB_IP_SPARE0	(SSUSB_SIFSLV_IPPC_BASE + 0x00C8)

/*---------------- SSUSB_SIFSLV_IPPC FIELD DEFINITION ----------------*/

/* U3D_SSUSB_IP_PW_CTRL0 */
#घोषणा SSUSB_IP_SW_RST			BIT(0)

/* U3D_SSUSB_IP_PW_CTRL1 */
#घोषणा SSUSB_IP_HOST_PDN		BIT(0)

/* U3D_SSUSB_IP_PW_CTRL2 */
#घोषणा SSUSB_IP_DEV_PDN		BIT(0)

/* U3D_SSUSB_IP_PW_CTRL3 */
#घोषणा SSUSB_IP_PCIE_PDN		BIT(0)

/* U3D_SSUSB_IP_PW_STS1 */
#घोषणा SSUSB_IP_SLEEP_STS		BIT(30)
#घोषणा SSUSB_U3_MAC_RST_B_STS		BIT(16)
#घोषणा SSUSB_XHCI_RST_B_STS		BIT(11)
#घोषणा SSUSB_SYS125_RST_B_STS		BIT(10)
#घोषणा SSUSB_REF_RST_B_STS		BIT(8)
#घोषणा SSUSB_SYSPLL_STABLE		BIT(0)

/* U3D_SSUSB_IP_PW_STS2 */
#घोषणा SSUSB_U2_MAC_SYS_RST_B_STS	BIT(0)

/* U3D_SSUSB_OTG_STS */
#घोषणा SSUSB_VBUS_VALID		BIT(9)

/* U3D_SSUSB_OTG_STS_CLR */
#घोषणा SSUSB_VBUS_INTR_CLR		BIT(6)

/* U3D_SSUSB_IP_XHCI_CAP */
#घोषणा SSUSB_IP_XHCI_U2_PORT_NUM(x)	(((x) >> 8) & 0xff)
#घोषणा SSUSB_IP_XHCI_U3_PORT_NUM(x)	((x) & 0xff)

/* U3D_SSUSB_IP_DEV_CAP */
#घोषणा SSUSB_IP_DEV_U3_PORT_NUM(x)	((x) & 0xff)

/* U3D_SSUSB_OTG_INT_EN */
#घोषणा SSUSB_VBUS_CHG_INT_A_EN		BIT(7)
#घोषणा SSUSB_VBUS_CHG_INT_B_EN		BIT(6)

/* U3D_SSUSB_U3_CTRL_0P */
#घोषणा SSUSB_U3_PORT_SSP_SPEED	BIT(9)
#घोषणा SSUSB_U3_PORT_DUAL_MODE	BIT(7)
#घोषणा SSUSB_U3_PORT_HOST_SEL		BIT(2)
#घोषणा SSUSB_U3_PORT_PDN		BIT(1)
#घोषणा SSUSB_U3_PORT_DIS		BIT(0)

/* U3D_SSUSB_U2_CTRL_0P */
#घोषणा SSUSB_U2_PORT_RG_IDDIG		BIT(12)
#घोषणा SSUSB_U2_PORT_FORCE_IDDIG	BIT(11)
#घोषणा SSUSB_U2_PORT_VBUSVALID	BIT(9)
#घोषणा SSUSB_U2_PORT_OTG_SEL		BIT(7)
#घोषणा SSUSB_U2_PORT_HOST		BIT(2)
#घोषणा SSUSB_U2_PORT_PDN		BIT(1)
#घोषणा SSUSB_U2_PORT_DIS		BIT(0)
#घोषणा SSUSB_U2_PORT_HOST_SEL	(SSUSB_U2_PORT_VBUSVALID | SSUSB_U2_PORT_HOST)

/* U3D_SSUSB_DEV_RST_CTRL */
#घोषणा SSUSB_DEV_SW_RST		BIT(0)

/* U3D_SSUSB_IP_TRUNK_VERS */
#घोषणा IP_TRUNK_VERS(x)		(((x) >> 16) & 0xffff)

#पूर्ण_अगर	/* _SSUSB_HW_REGS_H_ */
