<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0-or-later OR MIT */
#अगर_अघोषित DT_BINDINGS_AST2600_CLOCK_H
#घोषणा DT_BINDINGS_AST2600_CLOCK_H

#घोषणा ASPEED_CLK_GATE_ECLK		0
#घोषणा ASPEED_CLK_GATE_GCLK		1

#घोषणा ASPEED_CLK_GATE_MCLK		2

#घोषणा ASPEED_CLK_GATE_VCLK		3
#घोषणा ASPEED_CLK_GATE_BCLK		4
#घोषणा ASPEED_CLK_GATE_DCLK		5

#घोषणा ASPEED_CLK_GATE_LCLK		6
#घोषणा ASPEED_CLK_GATE_LHCCLK		7

#घोषणा ASPEED_CLK_GATE_D1CLK		8
#घोषणा ASPEED_CLK_GATE_YCLK		9

#घोषणा ASPEED_CLK_GATE_REF0CLK		10
#घोषणा ASPEED_CLK_GATE_REF1CLK		11

#घोषणा ASPEED_CLK_GATE_ESPICLK		12

#घोषणा ASPEED_CLK_GATE_USBUHCICLK	13
#घोषणा ASPEED_CLK_GATE_USBPORT1CLK	14
#घोषणा ASPEED_CLK_GATE_USBPORT2CLK	15

#घोषणा ASPEED_CLK_GATE_RSACLK		16
#घोषणा ASPEED_CLK_GATE_RVASCLK		17

#घोषणा ASPEED_CLK_GATE_MAC1CLK		18
#घोषणा ASPEED_CLK_GATE_MAC2CLK		19
#घोषणा ASPEED_CLK_GATE_MAC3CLK		20
#घोषणा ASPEED_CLK_GATE_MAC4CLK		21

#घोषणा ASPEED_CLK_GATE_UART1CLK	22
#घोषणा ASPEED_CLK_GATE_UART2CLK	23
#घोषणा ASPEED_CLK_GATE_UART3CLK	24
#घोषणा ASPEED_CLK_GATE_UART4CLK	25
#घोषणा ASPEED_CLK_GATE_UART5CLK	26
#घोषणा ASPEED_CLK_GATE_UART6CLK	27
#घोषणा ASPEED_CLK_GATE_UART7CLK	28
#घोषणा ASPEED_CLK_GATE_UART8CLK	29
#घोषणा ASPEED_CLK_GATE_UART9CLK	30
#घोषणा ASPEED_CLK_GATE_UART10CLK	31
#घोषणा ASPEED_CLK_GATE_UART11CLK	32
#घोषणा ASPEED_CLK_GATE_UART12CLK	33
#घोषणा ASPEED_CLK_GATE_UART13CLK	34

#घोषणा ASPEED_CLK_GATE_SDCLK		35
#घोषणा ASPEED_CLK_GATE_EMMCCLK		36

#घोषणा ASPEED_CLK_GATE_I3C0CLK		37
#घोषणा ASPEED_CLK_GATE_I3C1CLK		38
#घोषणा ASPEED_CLK_GATE_I3C2CLK		39
#घोषणा ASPEED_CLK_GATE_I3C3CLK		40
#घोषणा ASPEED_CLK_GATE_I3C4CLK		41
#घोषणा ASPEED_CLK_GATE_I3C5CLK		42
#घोषणा ASPEED_CLK_GATE_I3C6CLK		43
#घोषणा ASPEED_CLK_GATE_I3C7CLK		44

#घोषणा ASPEED_CLK_GATE_FSICLK		45

#घोषणा ASPEED_CLK_HPLL			46
#घोषणा ASPEED_CLK_MPLL			47
#घोषणा ASPEED_CLK_DPLL			48
#घोषणा ASPEED_CLK_EPLL			49
#घोषणा ASPEED_CLK_APLL			50
#घोषणा ASPEED_CLK_AHB			51
#घोषणा ASPEED_CLK_APB1			52
#घोषणा ASPEED_CLK_APB2			53
#घोषणा ASPEED_CLK_BCLK			54
#घोषणा ASPEED_CLK_D1CLK		55
#घोषणा ASPEED_CLK_VCLK			56
#घोषणा ASPEED_CLK_LHCLK		57
#घोषणा ASPEED_CLK_UART			58
#घोषणा ASPEED_CLK_UARTX		59
#घोषणा ASPEED_CLK_SDIO			60
#घोषणा ASPEED_CLK_EMMC			61
#घोषणा ASPEED_CLK_ECLK			62
#घोषणा ASPEED_CLK_ECLK_MUX		63
#घोषणा ASPEED_CLK_MAC12		64
#घोषणा ASPEED_CLK_MAC34		65
#घोषणा ASPEED_CLK_USBPHY_40M		66
#घोषणा ASPEED_CLK_MAC1RCLK		67
#घोषणा ASPEED_CLK_MAC2RCLK		68
#घोषणा ASPEED_CLK_MAC3RCLK		69
#घोषणा ASPEED_CLK_MAC4RCLK		70

/* Only list resets here that are not part of a gate */
#घोषणा ASPEED_RESET_ADC		55
#घोषणा ASPEED_RESET_JTAG_MASTER2	54
#घोषणा ASPEED_RESET_I3C_DMA		39
#घोषणा ASPEED_RESET_PWM		37
#घोषणा ASPEED_RESET_PECI		36
#घोषणा ASPEED_RESET_MII		35
#घोषणा ASPEED_RESET_I2C		34
#घोषणा ASPEED_RESET_H2X		31
#घोषणा ASPEED_RESET_GP_MCU		30
#घोषणा ASPEED_RESET_DP_MCU		29
#घोषणा ASPEED_RESET_DP			28
#घोषणा ASPEED_RESET_RC_XDMA		27
#घोषणा ASPEED_RESET_GRAPHICS		26
#घोषणा ASPEED_RESET_DEV_XDMA		25
#घोषणा ASPEED_RESET_DEV_MCTP		24
#घोषणा ASPEED_RESET_RC_MCTP		23
#घोषणा ASPEED_RESET_JTAG_MASTER	22
#घोषणा ASPEED_RESET_PCIE_DEV_O		21
#घोषणा ASPEED_RESET_PCIE_DEV_OEN	20
#घोषणा ASPEED_RESET_PCIE_RC_O		19
#घोषणा ASPEED_RESET_PCIE_RC_OEN	18
#घोषणा ASPEED_RESET_PCI_DP		5
#घोषणा ASPEED_RESET_AHB		1
#घोषणा ASPEED_RESET_SDRAM		0

#पूर्ण_अगर
