<शैली गुरु>
/* Copyright (c) 2015 The Linux Foundation. All rights reserved.
 *
 * Permission to use, copy, modअगरy, and/or distribute this software क्रम any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, सूचीECT, INसूचीECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 */
#अगर_अघोषित __QCOM_CLK_IPQ4019_H__
#घोषणा __QCOM_CLK_IPQ4019_H__

#घोषणा GCC_DUMMY_CLK					0
#घोषणा AUDIO_CLK_SRC					1
#घोषणा BLSP1_QUP1_I2C_APPS_CLK_SRC			2
#घोषणा BLSP1_QUP1_SPI_APPS_CLK_SRC			3
#घोषणा BLSP1_QUP2_I2C_APPS_CLK_SRC			4
#घोषणा BLSP1_QUP2_SPI_APPS_CLK_SRC			5
#घोषणा BLSP1_UART1_APPS_CLK_SRC			6
#घोषणा BLSP1_UART2_APPS_CLK_SRC			7
#घोषणा GCC_USB3_MOCK_UTMI_CLK_SRC			8
#घोषणा GCC_APPS_CLK_SRC				9
#घोषणा GCC_APPS_AHB_CLK_SRC				10
#घोषणा GP1_CLK_SRC					11
#घोषणा GP2_CLK_SRC					12
#घोषणा GP3_CLK_SRC					13
#घोषणा SDCC1_APPS_CLK_SRC				14
#घोषणा FEPHY_125M_DLY_CLK_SRC				15
#घोषणा WCSS2G_CLK_SRC					16
#घोषणा WCSS5G_CLK_SRC					17
#घोषणा GCC_APSS_AHB_CLK				18
#घोषणा GCC_AUDIO_AHB_CLK				19
#घोषणा GCC_AUDIO_PWM_CLK				20
#घोषणा GCC_BLSP1_AHB_CLK				21
#घोषणा GCC_BLSP1_QUP1_I2C_APPS_CLK			22
#घोषणा GCC_BLSP1_QUP1_SPI_APPS_CLK			23
#घोषणा GCC_BLSP1_QUP2_I2C_APPS_CLK			24
#घोषणा GCC_BLSP1_QUP2_SPI_APPS_CLK			25
#घोषणा GCC_BLSP1_UART1_APPS_CLK			26
#घोषणा GCC_BLSP1_UART2_APPS_CLK			27
#घोषणा GCC_DCD_XO_CLK					28
#घोषणा GCC_GP1_CLK					29
#घोषणा GCC_GP2_CLK					30
#घोषणा GCC_GP3_CLK					31
#घोषणा GCC_BOOT_ROM_AHB_CLK				32
#घोषणा GCC_CRYPTO_AHB_CLK				33
#घोषणा GCC_CRYPTO_AXI_CLK				34
#घोषणा GCC_CRYPTO_CLK					35
#घोषणा GCC_ESS_CLK					36
#घोषणा GCC_IMEM_AXI_CLK				37
#घोषणा GCC_IMEM_CFG_AHB_CLK				38
#घोषणा GCC_PCIE_AHB_CLK				39
#घोषणा GCC_PCIE_AXI_M_CLK				40
#घोषणा GCC_PCIE_AXI_S_CLK				41
#घोषणा GCC_PCNOC_AHB_CLK				42
#घोषणा GCC_PRNG_AHB_CLK				43
#घोषणा GCC_QPIC_AHB_CLK				44
#घोषणा GCC_QPIC_CLK					45
#घोषणा GCC_SDCC1_AHB_CLK				46
#घोषणा GCC_SDCC1_APPS_CLK				47
#घोषणा GCC_SNOC_PCNOC_AHB_CLK				48
#घोषणा GCC_SYS_NOC_125M_CLK				49
#घोषणा GCC_SYS_NOC_AXI_CLK				50
#घोषणा GCC_TCSR_AHB_CLK				51
#घोषणा GCC_TLMM_AHB_CLK				52
#घोषणा GCC_USB2_MASTER_CLK				53
#घोषणा GCC_USB2_SLEEP_CLK				54
#घोषणा GCC_USB2_MOCK_UTMI_CLK				55
#घोषणा GCC_USB3_MASTER_CLK				56
#घोषणा GCC_USB3_SLEEP_CLK				57
#घोषणा GCC_USB3_MOCK_UTMI_CLK				58
#घोषणा GCC_WCSS2G_CLK					59
#घोषणा GCC_WCSS2G_REF_CLK				60
#घोषणा GCC_WCSS2G_RTC_CLK				61
#घोषणा GCC_WCSS5G_CLK					62
#घोषणा GCC_WCSS5G_REF_CLK				63
#घोषणा GCC_WCSS5G_RTC_CLK				64
#घोषणा GCC_APSS_DDRPLL_VCO				65
#घोषणा GCC_SDCC_PLLDIV_CLK				66
#घोषणा GCC_FEPLL_VCO					67
#घोषणा GCC_FEPLL125_CLK				68
#घोषणा GCC_FEPLL125DLY_CLK				69
#घोषणा GCC_FEPLL200_CLK				70
#घोषणा GCC_FEPLL500_CLK				71
#घोषणा GCC_FEPLL_WCSS2G_CLK				72
#घोषणा GCC_FEPLL_WCSS5G_CLK				73
#घोषणा GCC_APSS_CPU_PLLDIV_CLK				74
#घोषणा GCC_PCNOC_AHB_CLK_SRC				75

#घोषणा WIFI0_CPU_INIT_RESET				0
#घोषणा WIFI0_RADIO_SRIF_RESET				1
#घोषणा WIFI0_RADIO_WARM_RESET				2
#घोषणा WIFI0_RADIO_COLD_RESET				3
#घोषणा WIFI0_CORE_WARM_RESET				4
#घोषणा WIFI0_CORE_COLD_RESET				5
#घोषणा WIFI1_CPU_INIT_RESET				6
#घोषणा WIFI1_RADIO_SRIF_RESET				7
#घोषणा WIFI1_RADIO_WARM_RESET				8
#घोषणा WIFI1_RADIO_COLD_RESET				9
#घोषणा WIFI1_CORE_WARM_RESET				10
#घोषणा WIFI1_CORE_COLD_RESET				11
#घोषणा USB3_UNIPHY_PHY_ARES				12
#घोषणा USB3_HSPHY_POR_ARES				13
#घोषणा USB3_HSPHY_S_ARES				14
#घोषणा USB2_HSPHY_POR_ARES				15
#घोषणा USB2_HSPHY_S_ARES				16
#घोषणा PCIE_PHY_AHB_ARES				17
#घोषणा PCIE_AHB_ARES					18
#घोषणा PCIE_PWR_ARES					19
#घोषणा PCIE_PIPE_STICKY_ARES				20
#घोषणा PCIE_AXI_M_STICKY_ARES				21
#घोषणा PCIE_PHY_ARES					22
#घोषणा PCIE_PARF_XPU_ARES				23
#घोषणा PCIE_AXI_S_XPU_ARES				24
#घोषणा PCIE_AXI_M_VMIDMT_ARES				25
#घोषणा PCIE_PIPE_ARES					26
#घोषणा PCIE_AXI_S_ARES					27
#घोषणा PCIE_AXI_M_ARES					28
#घोषणा ESS_RESET					29
#घोषणा GCC_BLSP1_BCR					30
#घोषणा GCC_BLSP1_QUP1_BCR				31
#घोषणा GCC_BLSP1_UART1_BCR				32
#घोषणा GCC_BLSP1_QUP2_BCR				33
#घोषणा GCC_BLSP1_UART2_BCR				34
#घोषणा GCC_BIMC_BCR					35
#घोषणा GCC_TLMM_BCR					36
#घोषणा GCC_IMEM_BCR					37
#घोषणा GCC_ESS_BCR					38
#घोषणा GCC_PRNG_BCR					39
#घोषणा GCC_BOOT_ROM_BCR				40
#घोषणा GCC_CRYPTO_BCR					41
#घोषणा GCC_SDCC1_BCR					42
#घोषणा GCC_SEC_CTRL_BCR				43
#घोषणा GCC_AUDIO_BCR					44
#घोषणा GCC_QPIC_BCR					45
#घोषणा GCC_PCIE_BCR					46
#घोषणा GCC_USB2_BCR					47
#घोषणा GCC_USB2_PHY_BCR				48
#घोषणा GCC_USB3_BCR					49
#घोषणा GCC_USB3_PHY_BCR				50
#घोषणा GCC_SYSTEM_NOC_BCR				51
#घोषणा GCC_PCNOC_BCR					52
#घोषणा GCC_DCD_BCR					53
#घोषणा GCC_SNOC_BUS_TIMEOUT0_BCR			54
#घोषणा GCC_SNOC_BUS_TIMEOUT1_BCR			55
#घोषणा GCC_SNOC_BUS_TIMEOUT2_BCR			56
#घोषणा GCC_SNOC_BUS_TIMEOUT3_BCR			57
#घोषणा GCC_PCNOC_BUS_TIMEOUT0_BCR			58
#घोषणा GCC_PCNOC_BUS_TIMEOUT1_BCR			59
#घोषणा GCC_PCNOC_BUS_TIMEOUT2_BCR			60
#घोषणा GCC_PCNOC_BUS_TIMEOUT3_BCR			61
#घोषणा GCC_PCNOC_BUS_TIMEOUT4_BCR			62
#घोषणा GCC_PCNOC_BUS_TIMEOUT5_BCR			63
#घोषणा GCC_PCNOC_BUS_TIMEOUT6_BCR			64
#घोषणा GCC_PCNOC_BUS_TIMEOUT7_BCR			65
#घोषणा GCC_PCNOC_BUS_TIMEOUT8_BCR			66
#घोषणा GCC_PCNOC_BUS_TIMEOUT9_BCR			67
#घोषणा GCC_TCSR_BCR					68
#घोषणा GCC_QDSS_BCR					69
#घोषणा GCC_MPM_BCR					70
#घोषणा GCC_SPDM_BCR					71

#पूर्ण_अगर
