<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
/*
 * Copyright (c) 2020, The Linux Foundation. All rights reserved.
 */

#अगर_अघोषित _DT_BINDINGS_CLK_MSM_MMCC_660_H
#घोषणा _DT_BINDINGS_CLK_MSM_MMCC_660_H

#घोषणा AHB_CLK_SRC							0
#घोषणा BYTE0_CLK_SRC						1
#घोषणा BYTE1_CLK_SRC						2
#घोषणा CAMSS_GP0_CLK_SRC					3
#घोषणा CAMSS_GP1_CLK_SRC					4
#घोषणा CCI_CLK_SRC							5
#घोषणा CPP_CLK_SRC							6
#घोषणा CSI0_CLK_SRC						7
#घोषणा CSI0PHYTIMER_CLK_SRC				8
#घोषणा CSI1_CLK_SRC						9
#घोषणा CSI1PHYTIMER_CLK_SRC				10
#घोषणा CSI2_CLK_SRC						11
#घोषणा CSI2PHYTIMER_CLK_SRC				12
#घोषणा CSI3_CLK_SRC						13
#घोषणा CSIPHY_CLK_SRC						14
#घोषणा DP_AUX_CLK_SRC						15
#घोषणा DP_CRYPTO_CLK_SRC					16
#घोषणा DP_GTC_CLK_SRC						17
#घोषणा DP_LINK_CLK_SRC						18
#घोषणा DP_PIXEL_CLK_SRC					19
#घोषणा ESC0_CLK_SRC						20
#घोषणा ESC1_CLK_SRC						21
#घोषणा JPEG0_CLK_SRC						22
#घोषणा MCLK0_CLK_SRC						23
#घोषणा MCLK1_CLK_SRC						24
#घोषणा MCLK2_CLK_SRC						25
#घोषणा MCLK3_CLK_SRC						26
#घोषणा MDP_CLK_SRC							27
#घोषणा MMPLL0_PLL							28
#घोषणा MMPLL10_PLL							29
#घोषणा MMPLL1_PLL							30
#घोषणा MMPLL3_PLL							31
#घोषणा MMPLL4_PLL							32
#घोषणा MMPLL5_PLL							33
#घोषणा MMPLL6_PLL							34
#घोषणा MMPLL7_PLL							35
#घोषणा MMPLL8_PLL							36
#घोषणा BIMC_SMMU_AHB_CLK					37
#घोषणा BIMC_SMMU_AXI_CLK					38
#घोषणा CAMSS_AHB_CLK						39
#घोषणा CAMSS_CCI_AHB_CLK					40
#घोषणा CAMSS_CCI_CLK						41
#घोषणा CAMSS_CPHY_CSID0_CLK				42
#घोषणा CAMSS_CPHY_CSID1_CLK				43
#घोषणा CAMSS_CPHY_CSID2_CLK				44
#घोषणा CAMSS_CPHY_CSID3_CLK				45
#घोषणा CAMSS_CPP_AHB_CLK					46
#घोषणा CAMSS_CPP_AXI_CLK					47
#घोषणा CAMSS_CPP_CLK						48
#घोषणा CAMSS_CPP_VBIF_AHB_CLK				49
#घोषणा CAMSS_CSI0_AHB_CLK					50
#घोषणा CAMSS_CSI0_CLK						51
#घोषणा CAMSS_CSI0PHYTIMER_CLK				52
#घोषणा CAMSS_CSI0PIX_CLK					53
#घोषणा CAMSS_CSI0RDI_CLK					54
#घोषणा CAMSS_CSI1_AHB_CLK					55
#घोषणा CAMSS_CSI1_CLK						56
#घोषणा CAMSS_CSI1PHYTIMER_CLK				57
#घोषणा CAMSS_CSI1PIX_CLK					58
#घोषणा CAMSS_CSI1RDI_CLK					59
#घोषणा CAMSS_CSI2_AHB_CLK					60
#घोषणा CAMSS_CSI2_CLK						61
#घोषणा CAMSS_CSI2PHYTIMER_CLK				62
#घोषणा CAMSS_CSI2PIX_CLK					63
#घोषणा CAMSS_CSI2RDI_CLK					64
#घोषणा CAMSS_CSI3_AHB_CLK					65
#घोषणा CAMSS_CSI3_CLK						66
#घोषणा CAMSS_CSI3PIX_CLK					67
#घोषणा CAMSS_CSI3RDI_CLK					68
#घोषणा CAMSS_CSI_VFE0_CLK					69
#घोषणा CAMSS_CSI_VFE1_CLK					70
#घोषणा CAMSS_CSIPHY0_CLK					71
#घोषणा CAMSS_CSIPHY1_CLK					72
#घोषणा CAMSS_CSIPHY2_CLK					73
#घोषणा CAMSS_GP0_CLK						74
#घोषणा CAMSS_GP1_CLK						75
#घोषणा CAMSS_ISPIF_AHB_CLK					76
#घोषणा CAMSS_JPEG0_CLK						77
#घोषणा CAMSS_JPEG_AHB_CLK					78
#घोषणा CAMSS_JPEG_AXI_CLK					79
#घोषणा CAMSS_MCLK0_CLK						80
#घोषणा CAMSS_MCLK1_CLK						81
#घोषणा CAMSS_MCLK2_CLK						82
#घोषणा CAMSS_MCLK3_CLK						83
#घोषणा CAMSS_MICRO_AHB_CLK					84
#घोषणा CAMSS_TOP_AHB_CLK					85
#घोषणा CAMSS_VFE0_AHB_CLK					86
#घोषणा CAMSS_VFE0_CLK						87
#घोषणा CAMSS_VFE0_STREAM_CLK				88
#घोषणा CAMSS_VFE1_AHB_CLK					89
#घोषणा CAMSS_VFE1_CLK						90
#घोषणा CAMSS_VFE1_STREAM_CLK				91
#घोषणा CAMSS_VFE_VBIF_AHB_CLK				92
#घोषणा CAMSS_VFE_VBIF_AXI_CLK				93
#घोषणा CSIPHY_AHB2CRIF_CLK					94
#घोषणा CXO_CLK								95
#घोषणा MDSS_AHB_CLK						96
#घोषणा MDSS_AXI_CLK						97
#घोषणा MDSS_BYTE0_CLK						98
#घोषणा MDSS_BYTE0_INTF_CLK					99
#घोषणा MDSS_BYTE0_INTF_DIV_CLK				100
#घोषणा MDSS_BYTE1_CLK						101
#घोषणा MDSS_BYTE1_INTF_CLK					102
#घोषणा MDSS_DP_AUX_CLK						103
#घोषणा MDSS_DP_CRYPTO_CLK					104
#घोषणा MDSS_DP_GTC_CLK						105
#घोषणा MDSS_DP_LINK_CLK					106
#घोषणा MDSS_DP_LINK_INTF_CLK				107
#घोषणा MDSS_DP_PIXEL_CLK					108
#घोषणा MDSS_ESC0_CLK						109
#घोषणा MDSS_ESC1_CLK						110
#घोषणा MDSS_HDMI_DP_AHB_CLK				111
#घोषणा MDSS_MDP_CLK						112
#घोषणा MDSS_PCLK0_CLK						113
#घोषणा MDSS_PCLK1_CLK						114
#घोषणा MDSS_ROT_CLK						115
#घोषणा MDSS_VSYNC_CLK						116
#घोषणा MISC_AHB_CLK						117
#घोषणा MISC_CXO_CLK						118
#घोषणा MNOC_AHB_CLK						119
#घोषणा SNOC_DVM_AXI_CLK					120
#घोषणा THROTTLE_CAMSS_AHB_CLK				121
#घोषणा THROTTLE_CAMSS_AXI_CLK				122
#घोषणा THROTTLE_MDSS_AHB_CLK				123
#घोषणा THROTTLE_MDSS_AXI_CLK				124
#घोषणा THROTTLE_VIDEO_AHB_CLK				125
#घोषणा THROTTLE_VIDEO_AXI_CLK				126
#घोषणा VIDEO_AHB_CLK						127
#घोषणा VIDEO_AXI_CLK						128
#घोषणा VIDEO_CORE_CLK						129
#घोषणा VIDEO_SUBCORE0_CLK					130
#घोषणा PCLK0_CLK_SRC						131
#घोषणा PCLK1_CLK_SRC						132
#घोषणा ROT_CLK_SRC							133
#घोषणा VFE0_CLK_SRC						134
#घोषणा VFE1_CLK_SRC						135
#घोषणा VIDEO_CORE_CLK_SRC					136
#घोषणा VSYNC_CLK_SRC						137
#घोषणा MDSS_BYTE1_INTF_DIV_CLK				138
#घोषणा AXI_CLK_SRC							139

#घोषणा VENUS_GDSC								0
#घोषणा VENUS_CORE0_GDSC						1
#घोषणा MDSS_GDSC								2
#घोषणा CAMSS_TOP_GDSC							3
#घोषणा CAMSS_VFE0_GDSC							4
#घोषणा CAMSS_VFE1_GDSC							5
#घोषणा CAMSS_CPP_GDSC							6
#घोषणा BIMC_SMMU_GDSC							7

#घोषणा CAMSS_MICRO_BCR				 0

#पूर्ण_अगर

