<शैली गुरु>
/*
 * GMC_8_2 Register करोcumentation
 *
 * Copyright (C) 2014  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, मुक्त of अक्षरge, to any person obtaining a
 * copy of this software and associated करोcumentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modअगरy, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to करो so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#अगर_अघोषित GMC_8_2_D_H
#घोषणा GMC_8_2_D_H

#घोषणा mmMC_CONFIG                                                             0x800
#घोषणा mmMC_ARB_ATOMIC                                                         0x9be
#घोषणा mmMC_ARB_AGE_CNTL                                                       0x9bf
#घोषणा mmMC_ARB_RET_CREDITS2                                                   0x9c0
#घोषणा mmMC_ARB_FED_CNTL                                                       0x9c1
#घोषणा mmMC_ARB_GECC2_STATUS                                                   0x9c2
#घोषणा mmMC_ARB_GECC2_MISC                                                     0x9c3
#घोषणा mmMC_ARB_GECC2_DEBUG                                                    0x9c4
#घोषणा mmMC_ARB_GECC2_DEBUG2                                                   0x9c5
#घोषणा mmMC_ARB_PERF_CID                                                       0x9c6
#घोषणा mmMC_ARB_SNOOP                                                          0x9c7
#घोषणा mmMC_ARB_GRUB                                                           0x9c8
#घोषणा mmMC_ARB_GECC2                                                          0x9c9
#घोषणा mmMC_ARB_GECC2_CLI                                                      0x9ca
#घोषणा mmMC_ARB_ADDR_SWIZ0                                                     0x9cb
#घोषणा mmMC_ARB_ADDR_SWIZ1                                                     0x9cc
#घोषणा mmMC_ARB_MISC3                                                          0x9cd
#घोषणा mmMC_ARB_GRUB_PROMOTE                                                   0x9ce
#घोषणा mmMC_ARB_RTT_DATA                                                       0x9cf
#घोषणा mmMC_ARB_RTT_CNTL0                                                      0x9d0
#घोषणा mmMC_ARB_RTT_CNTL1                                                      0x9d1
#घोषणा mmMC_ARB_RTT_CNTL2                                                      0x9d2
#घोषणा mmMC_ARB_RTT_DEBUG                                                      0x9d3
#घोषणा mmMC_ARB_CAC_CNTL                                                       0x9d4
#घोषणा mmMC_ARB_MISC2                                                          0x9d5
#घोषणा mmMC_ARB_MISC                                                           0x9d6
#घोषणा mmMC_ARB_BANKMAP                                                        0x9d7
#घोषणा mmMC_ARB_RAMCFG                                                         0x9d8
#घोषणा mmMC_ARB_POP                                                            0x9d9
#घोषणा mmMC_ARB_MINCLKS                                                        0x9da
#घोषणा mmMC_ARB_SQM_CNTL                                                       0x9db
#घोषणा mmMC_ARB_ADDR_HASH                                                      0x9dc
#घोषणा mmMC_ARB_DRAM_TIMING                                                    0x9dd
#घोषणा mmMC_ARB_DRAM_TIMING2                                                   0x9de
#घोषणा mmMC_ARB_WTM_CNTL_RD                                                    0x9df
#घोषणा mmMC_ARB_WTM_CNTL_WR                                                    0x9e0
#घोषणा mmMC_ARB_WTM_GRPWT_RD                                                   0x9e1
#घोषणा mmMC_ARB_WTM_GRPWT_WR                                                   0x9e2
#घोषणा mmMC_ARB_TM_CNTL_RD                                                     0x9e3
#घोषणा mmMC_ARB_TM_CNTL_WR                                                     0x9e4
#घोषणा mmMC_ARB_LAZY0_RD                                                       0x9e5
#घोषणा mmMC_ARB_LAZY0_WR                                                       0x9e6
#घोषणा mmMC_ARB_LAZY1_RD                                                       0x9e7
#घोषणा mmMC_ARB_LAZY1_WR                                                       0x9e8
#घोषणा mmMC_ARB_AGE_RD                                                         0x9e9
#घोषणा mmMC_ARB_AGE_WR                                                         0x9ea
#घोषणा mmMC_ARB_RFSH_CNTL                                                      0x9eb
#घोषणा mmMC_ARB_RFSH_RATE                                                      0x9ec
#घोषणा mmMC_ARB_PM_CNTL                                                        0x9ed
#घोषणा mmMC_ARB_GDEC_RD_CNTL                                                   0x9ee
#घोषणा mmMC_ARB_GDEC_WR_CNTL                                                   0x9ef
#घोषणा mmMC_ARB_LM_RD                                                          0x9f0
#घोषणा mmMC_ARB_LM_WR                                                          0x9f1
#घोषणा mmMC_ARB_REMREQ                                                         0x9f2
#घोषणा mmMC_ARB_REPLAY                                                         0x9f3
#घोषणा mmMC_ARB_RET_CREDITS_RD                                                 0x9f4
#घोषणा mmMC_ARB_RET_CREDITS_WR                                                 0x9f5
#घोषणा mmMC_ARB_MAX_LAT_CID                                                    0x9f6
#घोषणा mmMC_ARB_MAX_LAT_RSLT0                                                  0x9f7
#घोषणा mmMC_ARB_MAX_LAT_RSLT1                                                  0x9f8
#घोषणा mmMC_ARB_GRUB_REALTIME_RD                                               0x9f9
#घोषणा mmMC_ARB_CG                                                             0x9fa
#घोषणा mmMC_ARB_GRUB_REALTIME_WR                                               0x9fb
#घोषणा mmMC_ARB_DRAM_TIMING_1                                                  0x9fc
#घोषणा mmMC_ARB_BUSY_STATUS                                                    0x9fd
#घोषणा mmMC_ARB_DRAM_TIMING2_1                                                 0x9ff
#घोषणा mmMC_ARB_GRUB2                                                          0xa01
#घोषणा mmMC_ARB_BURST_TIME                                                     0xa02
#घोषणा mmMC_CITF_XTRA_ENABLE                                                   0x96d
#घोषणा mmCC_MC_MAX_CHANNEL                                                     0x96e
#घोषणा mmMC_CG_CONFIG                                                          0x96f
#घोषणा mmMC_CITF_CNTL                                                          0x970
#घोषणा mmMC_CITF_CREDITS_VM                                                    0x971
#घोषणा mmMC_CITF_CREDITS_ARB_RD                                                0x972
#घोषणा mmMC_CITF_CREDITS_ARB_WR                                                0x973
#घोषणा mmMC_CITF_DAGB_CNTL                                                     0x974
#घोषणा mmMC_CITF_INT_CREDITS                                                   0x975
#घोषणा mmMC_CITF_RET_MODE                                                      0x976
#घोषणा mmMC_CITF_DAGB_DLY                                                      0x977
#घोषणा mmMC_RD_GRP_EXT                                                         0x978
#घोषणा mmMC_WR_GRP_EXT                                                         0x979
#घोषणा mmMC_CITF_REMREQ                                                        0x97a
#घोषणा mmMC_WR_TC0                                                             0x97b
#घोषणा mmMC_WR_TC1                                                             0x97c
#घोषणा mmMC_CITF_INT_CREDITS_WR                                                0x97d
#घोषणा mmMC_CITF_CREDITS_ARB_RD2                                               0x97e
#घोषणा mmMC_CITF_WTM_RD_CNTL                                                   0x97f
#घोषणा mmMC_CITF_WTM_WR_CNTL                                                   0x980
#घोषणा mmMC_RD_CB                                                              0x981
#घोषणा mmMC_RD_DB                                                              0x982
#घोषणा mmMC_RD_TC0                                                             0x983
#घोषणा mmMC_RD_TC1                                                             0x984
#घोषणा mmMC_RD_HUB                                                             0x985
#घोषणा mmMC_WR_CB                                                              0x986
#घोषणा mmMC_WR_DB                                                              0x987
#घोषणा mmMC_WR_HUB                                                             0x988
#घोषणा mmMC_CITF_CREDITS_XBAR                                                  0x989
#घोषणा mmMC_RD_GRP_LCL                                                         0x98a
#घोषणा mmMC_WR_GRP_LCL                                                         0x98b
#घोषणा mmMC_CITF_PERF_MON_CNTL2                                                0x98e
#घोषणा mmMC_CITF_PERF_MON_RSLT2                                                0x991
#घोषणा mmMC_CITF_MISC_RD_CG                                                    0x992
#घोषणा mmMC_CITF_MISC_WR_CG                                                    0x993
#घोषणा mmMC_CITF_MISC_VM_CG                                                    0x994
#घोषणा mmMC_HUB_MISC_POWER                                                     0x82d
#घोषणा mmMC_HUB_MISC_HUB_CG                                                    0x82e
#घोषणा mmMC_HUB_MISC_VM_CG                                                     0x82f
#घोषणा mmMC_HUB_MISC_SIP_CG                                                    0x830
#घोषणा mmMC_HUB_MISC_STATUS                                                    0x832
#घोषणा mmMC_HUB_MISC_OVERRIDE                                                  0x833
#घोषणा mmMC_HUB_MISC_FRAMING                                                   0x834
#घोषणा mmMC_HUB_WDP_CNTL                                                       0x835
#घोषणा mmMC_HUB_WDP_ERR                                                        0x836
#घोषणा mmMC_HUB_WDP_BP                                                         0x837
#घोषणा mmMC_HUB_WDP_STATUS                                                     0x838
#घोषणा mmMC_HUB_RDREQ_STATUS                                                   0x839
#घोषणा mmMC_HUB_WRRET_STATUS                                                   0x83a
#घोषणा mmMC_HUB_RDREQ_CNTL                                                     0x83b
#घोषणा mmMC_HUB_WRRET_CNTL                                                     0x83c
#घोषणा mmMC_HUB_RDREQ_WTM_CNTL                                                 0x83d
#घोषणा mmMC_HUB_WDP_WTM_CNTL                                                   0x83e
#घोषणा mmMC_HUB_WDP_CREDITS                                                    0x83f
#घोषणा mmMC_HUB_WDP_CREDITS2                                                   0x840
#घोषणा mmMC_HUB_WDP_GBL0                                                       0x841
#घोषणा mmMC_HUB_WDP_GBL1                                                       0x842
#घोषणा mmMC_HUB_RDREQ_CREDITS                                                  0x844
#घोषणा mmMC_HUB_RDREQ_CREDITS2                                                 0x845
#घोषणा mmMC_HUB_SHARED_DAGB_DLY                                                0x846
#घोषणा mmMC_HUB_MISC_IDLE_STATUS                                               0x847
#घोषणा mmMC_HUB_RDREQ_DMIF_LIMIT                                               0x848
#घोषणा mmMC_HUB_RDREQ_ACPG_LIMIT                                               0x849
#घोषणा mmMC_HUB_WDP_BYPASS_GBL0                                                0x84a
#घोषणा mmMC_HUB_WDP_BYPASS_GBL1                                                0x84b
#घोषणा mmMC_HUB_RDREQ_BYPASS_GBL0                                              0x84c
#घोषणा mmMC_HUB_WDP_SH2                                                        0x84d
#घोषणा mmMC_HUB_WDP_SH3                                                        0x84e
#घोषणा mmMC_HUB_MISC_ATOMIC_IDLE_STATUS                                        0x84f
#घोषणा mmMC_HUB_RDREQ_MCDW                                                     0x851
#घोषणा mmMC_HUB_RDREQ_MCDX                                                     0x852
#घोषणा mmMC_HUB_RDREQ_MCDY                                                     0x853
#घोषणा mmMC_HUB_RDREQ_MCDZ                                                     0x854
#घोषणा mmMC_HUB_RDREQ_SIP                                                      0x855
#घोषणा mmMC_HUB_RDREQ_GBL0                                                     0x856
#घोषणा mmMC_HUB_RDREQ_GBL1                                                     0x857
#घोषणा mmMC_HUB_RDREQ_SMU                                                      0x858
#घोषणा mmMC_HUB_RDREQ_SDMA0                                                    0x859
#घोषणा mmMC_HUB_RDREQ_HDP                                                      0x85a
#घोषणा mmMC_HUB_RDREQ_SDMA1                                                    0x85b
#घोषणा mmMC_HUB_RDREQ_RLC                                                      0x85c
#घोषणा mmMC_HUB_RDREQ_SEM                                                      0x85d
#घोषणा mmMC_HUB_RDREQ_VCE0                                                     0x85e
#घोषणा mmMC_HUB_RDREQ_UMC                                                      0x85f
#घोषणा mmMC_HUB_RDREQ_UVD                                                      0x860
#घोषणा mmMC_HUB_RDREQ_DMIF                                                     0x862
#घोषणा mmMC_HUB_RDREQ_MCIF                                                     0x863
#घोषणा mmMC_HUB_RDREQ_VMC                                                      0x864
#घोषणा mmMC_HUB_RDREQ_VCEU0                                                    0x865
#घोषणा mmMC_HUB_WDP_MCDW                                                       0x866
#घोषणा mmMC_HUB_WDP_MCDX                                                       0x867
#घोषणा mmMC_HUB_WDP_MCDY                                                       0x868
#घोषणा mmMC_HUB_WDP_MCDZ                                                       0x869
#घोषणा mmMC_HUB_WDP_SIP                                                        0x86a
#घोषणा mmMC_HUB_WDP_SDMA1                                                      0x86b
#घोषणा mmMC_HUB_WDP_SH0                                                        0x86c
#घोषणा mmMC_HUB_WDP_MCIF                                                       0x86d
#घोषणा mmMC_HUB_WDP_VCE0                                                       0x86e
#घोषणा mmMC_HUB_WDP_XDP                                                        0x86f
#घोषणा mmMC_HUB_WDP_IH                                                         0x870
#घोषणा mmMC_HUB_WDP_RLC                                                        0x871
#घोषणा mmMC_HUB_WDP_SEM                                                        0x872
#घोषणा mmMC_HUB_WDP_SMU                                                        0x873
#घोषणा mmMC_HUB_WDP_SH1                                                        0x874
#घोषणा mmMC_HUB_WDP_UMC                                                        0x875
#घोषणा mmMC_HUB_WDP_UVD                                                        0x876
#घोषणा mmMC_HUB_WDP_HDP                                                        0x877
#घोषणा mmMC_HUB_WDP_SDMA0                                                      0x878
#घोषणा mmMC_HUB_WRRET_MCDW                                                     0x879
#घोषणा mmMC_HUB_WRRET_MCDX                                                     0x87a
#घोषणा mmMC_HUB_WRRET_MCDY                                                     0x87b
#घोषणा mmMC_HUB_WRRET_MCDZ                                                     0x87c
#घोषणा mmMC_HUB_WDP_VCEU0                                                      0x87d
#घोषणा mmMC_HUB_WDP_XDMAM                                                      0x87e
#घोषणा mmMC_HUB_WDP_XDMA                                                       0x87f
#घोषणा mmMC_HUB_RDREQ_XDMAM                                                    0x880
#घोषणा mmMC_HUB_RDREQ_ACPG                                                     0x881
#घोषणा mmMC_HUB_RDREQ_ACPO                                                     0x882
#घोषणा mmMC_HUB_RDREQ_SAMMSP                                                   0x883
#घोषणा mmMC_HUB_RDREQ_VP8                                                      0x884
#घोषणा mmMC_HUB_RDREQ_VP8U                                                     0x885
#घोषणा mmMC_HUB_WDP_ACPG                                                       0x886
#घोषणा mmMC_HUB_WDP_ACPO                                                       0x887
#घोषणा mmMC_HUB_WDP_SAMMSP                                                     0x888
#घोषणा mmMC_HUB_WDP_VP8                                                        0x889
#घोषणा mmMC_HUB_WDP_VP8U                                                       0x88a
#घोषणा mmMC_HUB_RDREQ_ISP_SPM                                                  0xde0
#घोषणा mmMC_HUB_RDREQ_ISP_MPM                                                  0xde1
#घोषणा mmMC_HUB_RDREQ_ISP_CCPU                                                 0xde2
#घोषणा mmMC_HUB_WDP_ISP_SPM                                                    0xde3
#घोषणा mmMC_HUB_WDP_ISP_MPS                                                    0xde4
#घोषणा mmMC_HUB_WDP_ISP_MPM                                                    0xde5
#घोषणा mmMC_HUB_WDP_ISP_CCPU                                                   0xde6
#घोषणा mmMC_HUB_RDREQ_MCDS                                                     0xde7
#घोषणा mmMC_HUB_RDREQ_MCDT                                                     0xde8
#घोषणा mmMC_HUB_RDREQ_MCDU                                                     0xde9
#घोषणा mmMC_HUB_RDREQ_MCDV                                                     0xdea
#घोषणा mmMC_HUB_WDP_MCDS                                                       0xdeb
#घोषणा mmMC_HUB_WDP_MCDT                                                       0xdec
#घोषणा mmMC_HUB_WDP_MCDU                                                       0xded
#घोषणा mmMC_HUB_WDP_MCDV                                                       0xdee
#घोषणा mmMC_HUB_WRRET_MCDS                                                     0xdef
#घोषणा mmMC_HUB_WRRET_MCDT                                                     0xdf0
#घोषणा mmMC_HUB_WRRET_MCDU                                                     0xdf1
#घोषणा mmMC_HUB_WRRET_MCDV                                                     0xdf2
#घोषणा mmMC_HUB_WDP_CREDITS_MCDW                                               0xdf3
#घोषणा mmMC_HUB_WDP_CREDITS_MCDX                                               0xdf4
#घोषणा mmMC_HUB_WDP_CREDITS_MCDY                                               0xdf5
#घोषणा mmMC_HUB_WDP_CREDITS_MCDZ                                               0xdf6
#घोषणा mmMC_HUB_WDP_CREDITS_MCDS                                               0xdf7
#घोषणा mmMC_HUB_WDP_CREDITS_MCDT                                               0xdf8
#घोषणा mmMC_HUB_WDP_CREDITS_MCDU                                               0xdf9
#घोषणा mmMC_HUB_WDP_CREDITS_MCDV                                               0xdfa
#घोषणा mmMC_HUB_WDP_BP2                                                        0xdfb
#घोषणा mmMC_HUB_RDREQ_VCE1                                                     0xdfc
#घोषणा mmMC_HUB_RDREQ_VCEU1                                                    0xdfd
#घोषणा mmMC_HUB_WDP_VCE1                                                       0xdfe
#घोषणा mmMC_HUB_WDP_VCEU1                                                      0xdff
#घोषणा mmMC_RPB_CONF                                                           0x94d
#घोषणा mmMC_RPB_IF_CONF                                                        0x94e
#घोषणा mmMC_RPB_DBG1                                                           0x94f
#घोषणा mmMC_RPB_EFF_CNTL                                                       0x950
#घोषणा mmMC_RPB_ARB_CNTL                                                       0x951
#घोषणा mmMC_RPB_BIF_CNTL                                                       0x952
#घोषणा mmMC_RPB_WR_SWITCH_CNTL                                                 0x953
#घोषणा mmMC_RPB_WR_COMBINE_CNTL                                                0x954
#घोषणा mmMC_RPB_RD_SWITCH_CNTL                                                 0x955
#घोषणा mmMC_RPB_CID_QUEUE_WR                                                   0x956
#घोषणा mmMC_RPB_CID_QUEUE_RD                                                   0x957
#घोषणा mmMC_RPB_PERF_COUNTER_CNTL                                              0x958
#घोषणा mmMC_RPB_PERF_COUNTER_STATUS                                            0x959
#घोषणा mmMC_RPB_CID_QUEUE_EX                                                   0x95a
#घोषणा mmMC_RPB_CID_QUEUE_EX_DATA                                              0x95b
#घोषणा mmMC_RPB_TCI_CNTL                                                       0x95c
#घोषणा mmMC_RPB_TCI_CNTL2                                                      0x95d
#घोषणा mmMC_SHARED_CHMAP                                                       0x801
#घोषणा mmMC_SHARED_CHREMAP                                                     0x802
#घोषणा mmMC_RD_GRP_GFX                                                         0x803
#घोषणा mmMC_WR_GRP_GFX                                                         0x804
#घोषणा mmMC_RD_GRP_SYS                                                         0x805
#घोषणा mmMC_WR_GRP_SYS                                                         0x806
#घोषणा mmMC_RD_GRP_OTH                                                         0x807
#घोषणा mmMC_WR_GRP_OTH                                                         0x808
#घोषणा mmMC_VM_FB_LOCATION                                                     0x809
#घोषणा mmMC_VM_AGP_TOP                                                         0x80a
#घोषणा mmMC_VM_AGP_BOT                                                         0x80b
#घोषणा mmMC_VM_AGP_BASE                                                        0x80c
#घोषणा mmMC_VM_SYSTEM_APERTURE_LOW_ADDR                                        0x80d
#घोषणा mmMC_VM_SYSTEM_APERTURE_HIGH_ADDR                                       0x80e
#घोषणा mmMC_VM_SYSTEM_APERTURE_DEFAULT_ADDR                                    0x80f
#घोषणा mmMC_VM_DC_WRITE_CNTL                                                   0x810
#घोषणा mmMC_VM_DC_WRITE_HIT_REGION_0_LOW_ADDR                                  0x811
#घोषणा mmMC_VM_DC_WRITE_HIT_REGION_1_LOW_ADDR                                  0x812
#घोषणा mmMC_VM_DC_WRITE_HIT_REGION_2_LOW_ADDR                                  0x813
#घोषणा mmMC_VM_DC_WRITE_HIT_REGION_3_LOW_ADDR                                  0x814
#घोषणा mmMC_VM_DC_WRITE_HIT_REGION_0_HIGH_ADDR                                 0x815
#घोषणा mmMC_VM_DC_WRITE_HIT_REGION_1_HIGH_ADDR                                 0x816
#घोषणा mmMC_VM_DC_WRITE_HIT_REGION_2_HIGH_ADDR                                 0x817
#घोषणा mmMC_VM_DC_WRITE_HIT_REGION_3_HIGH_ADDR                                 0x818
#घोषणा mmMC_VM_MX_L1_TLB_CNTL                                                  0x819
#घोषणा mmMC_VM_FB_OFFSET                                                       0x81a
#घोषणा mmMC_VM_STEERING                                                        0x81b
#घोषणा mmMC_SHARED_CHREMAP2                                                    0x81c
#घोषणा mmMC_SHARED_VF_ENABLE                                                   0x81d
#घोषणा mmMC_SHARED_VIRT_RESET_REQ                                              0x81e
#घोषणा mmMC_SHARED_ACTIVE_FCN_ID                                               0x81f
#घोषणा mmMC_CONFIG_MCD                                                         0x828
#घोषणा mmMC_CG_CONFIG_MCD                                                      0x829
#घोषणा mmMC_MEM_POWER_LS                                                       0x82a
#घोषणा mmMC_SHARED_BLACKOUT_CNTL                                               0x82b
#घोषणा mmMC_VM_MB_L1_TLB0_DEBUG                                                0x891
#घोषणा mmMC_VM_MB_L1_TLB1_DEBUG                                                0x892
#घोषणा mmMC_VM_MB_L1_TLB2_DEBUG                                                0x893
#घोषणा mmMC_VM_MB_L1_TLB0_STATUS                                               0x895
#घोषणा mmMC_VM_MB_L1_TLB1_STATUS                                               0x896
#घोषणा mmMC_VM_MB_L1_TLB2_STATUS                                               0x897
#घोषणा mmMC_VM_MB_L2ARBITER_L2_CREDITS                                         0x8a1
#घोषणा mmMC_VM_MB_L1_TLB3_DEBUG                                                0x8a5
#घोषणा mmMC_VM_MB_L1_TLB3_STATUS                                               0x8a6
#घोषणा mmMC_VM_MD_L1_TLB0_DEBUG                                                0x998
#घोषणा mmMC_VM_MD_L1_TLB1_DEBUG                                                0x999
#घोषणा mmMC_VM_MD_L1_TLB2_DEBUG                                                0x99a
#घोषणा mmMC_VM_MD_L1_TLB0_STATUS                                               0x99b
#घोषणा mmMC_VM_MD_L1_TLB1_STATUS                                               0x99c
#घोषणा mmMC_VM_MD_L1_TLB2_STATUS                                               0x99d
#घोषणा mmMC_VM_MD_L2ARBITER_L2_CREDITS                                         0x9a4
#घोषणा mmMC_VM_MD_L1_TLB3_DEBUG                                                0x9a7
#घोषणा mmMC_VM_MD_L1_TLB3_STATUS                                               0x9a8
#घोषणा mmMC_XPB_RTR_SRC_APRTR0                                                 0x8cd
#घोषणा mmMC_XPB_RTR_SRC_APRTR1                                                 0x8ce
#घोषणा mmMC_XPB_RTR_SRC_APRTR2                                                 0x8cf
#घोषणा mmMC_XPB_RTR_SRC_APRTR3                                                 0x8d0
#घोषणा mmMC_XPB_RTR_SRC_APRTR4                                                 0x8d1
#घोषणा mmMC_XPB_RTR_SRC_APRTR5                                                 0x8d2
#घोषणा mmMC_XPB_RTR_SRC_APRTR6                                                 0x8d3
#घोषणा mmMC_XPB_RTR_SRC_APRTR7                                                 0x8d4
#घोषणा mmMC_XPB_RTR_SRC_APRTR8                                                 0x8d5
#घोषणा mmMC_XPB_RTR_SRC_APRTR9                                                 0x8d6
#घोषणा mmMC_XPB_XDMA_RTR_SRC_APRTR0                                            0x8d7
#घोषणा mmMC_XPB_XDMA_RTR_SRC_APRTR1                                            0x8d8
#घोषणा mmMC_XPB_XDMA_RTR_SRC_APRTR2                                            0x8d9
#घोषणा mmMC_XPB_XDMA_RTR_SRC_APRTR3                                            0x8da
#घोषणा mmMC_XPB_RTR_DEST_MAP0                                                  0x8db
#घोषणा mmMC_XPB_RTR_DEST_MAP1                                                  0x8dc
#घोषणा mmMC_XPB_RTR_DEST_MAP2                                                  0x8dd
#घोषणा mmMC_XPB_RTR_DEST_MAP3                                                  0x8de
#घोषणा mmMC_XPB_RTR_DEST_MAP4                                                  0x8df
#घोषणा mmMC_XPB_RTR_DEST_MAP5                                                  0x8e0
#घोषणा mmMC_XPB_RTR_DEST_MAP6                                                  0x8e1
#घोषणा mmMC_XPB_RTR_DEST_MAP7                                                  0x8e2
#घोषणा mmMC_XPB_RTR_DEST_MAP8                                                  0x8e3
#घोषणा mmMC_XPB_RTR_DEST_MAP9                                                  0x8e4
#घोषणा mmMC_XPB_XDMA_RTR_DEST_MAP0                                             0x8e5
#घोषणा mmMC_XPB_XDMA_RTR_DEST_MAP1                                             0x8e6
#घोषणा mmMC_XPB_XDMA_RTR_DEST_MAP2                                             0x8e7
#घोषणा mmMC_XPB_XDMA_RTR_DEST_MAP3                                             0x8e8
#घोषणा mmMC_XPB_CLG_CFG0                                                       0x8e9
#घोषणा mmMC_XPB_CLG_CFG1                                                       0x8ea
#घोषणा mmMC_XPB_CLG_CFG2                                                       0x8eb
#घोषणा mmMC_XPB_CLG_CFG3                                                       0x8ec
#घोषणा mmMC_XPB_CLG_CFG4                                                       0x8ed
#घोषणा mmMC_XPB_CLG_CFG5                                                       0x8ee
#घोषणा mmMC_XPB_CLG_CFG6                                                       0x8ef
#घोषणा mmMC_XPB_CLG_CFG7                                                       0x8f0
#घोषणा mmMC_XPB_CLG_CFG8                                                       0x8f1
#घोषणा mmMC_XPB_CLG_CFG9                                                       0x8f2
#घोषणा mmMC_XPB_CLG_CFG10                                                      0x8f3
#घोषणा mmMC_XPB_CLG_CFG11                                                      0x8f4
#घोषणा mmMC_XPB_CLG_CFG12                                                      0x8f5
#घोषणा mmMC_XPB_CLG_CFG13                                                      0x8f6
#घोषणा mmMC_XPB_CLG_CFG14                                                      0x8f7
#घोषणा mmMC_XPB_CLG_CFG15                                                      0x8f8
#घोषणा mmMC_XPB_CLG_CFG16                                                      0x8f9
#घोषणा mmMC_XPB_CLG_CFG17                                                      0x8fa
#घोषणा mmMC_XPB_CLG_CFG18                                                      0x8fb
#घोषणा mmMC_XPB_CLG_CFG19                                                      0x8fc
#घोषणा mmMC_XPB_CLG_EXTRA                                                      0x8fd
#घोषणा mmMC_XPB_LB_ADDR                                                        0x8fe
#घोषणा mmMC_XPB_UNC_THRESH_HST                                                 0x8ff
#घोषणा mmMC_XPB_UNC_THRESH_SID                                                 0x900
#घोषणा mmMC_XPB_WCB_STS                                                        0x901
#घोषणा mmMC_XPB_WCB_CFG                                                        0x902
#घोषणा mmMC_XPB_P2P_BAR_CFG                                                    0x903
#घोषणा mmMC_XPB_P2P_BAR0                                                       0x904
#घोषणा mmMC_XPB_P2P_BAR1                                                       0x905
#घोषणा mmMC_XPB_P2P_BAR2                                                       0x906
#घोषणा mmMC_XPB_P2P_BAR3                                                       0x907
#घोषणा mmMC_XPB_P2P_BAR4                                                       0x908
#घोषणा mmMC_XPB_P2P_BAR5                                                       0x909
#घोषणा mmMC_XPB_P2P_BAR6                                                       0x90a
#घोषणा mmMC_XPB_P2P_BAR7                                                       0x90b
#घोषणा mmMC_XPB_P2P_BAR_SETUP                                                  0x90c
#घोषणा mmMC_XPB_P2P_BAR_DEBUG                                                  0x90d
#घोषणा mmMC_XPB_P2P_BAR_DELTA_ABOVE                                            0x90e
#घोषणा mmMC_XPB_P2P_BAR_DELTA_BELOW                                            0x90f
#घोषणा mmMC_XPB_PEER_SYS_BAR0                                                  0x910
#घोषणा mmMC_XPB_PEER_SYS_BAR1                                                  0x911
#घोषणा mmMC_XPB_PEER_SYS_BAR2                                                  0x912
#घोषणा mmMC_XPB_PEER_SYS_BAR3                                                  0x913
#घोषणा mmMC_XPB_PEER_SYS_BAR4                                                  0x914
#घोषणा mmMC_XPB_PEER_SYS_BAR5                                                  0x915
#घोषणा mmMC_XPB_PEER_SYS_BAR6                                                  0x916
#घोषणा mmMC_XPB_PEER_SYS_BAR7                                                  0x917
#घोषणा mmMC_XPB_PEER_SYS_BAR8                                                  0x918
#घोषणा mmMC_XPB_PEER_SYS_BAR9                                                  0x919
#घोषणा mmMC_XPB_XDMA_PEER_SYS_BAR0                                             0x91a
#घोषणा mmMC_XPB_XDMA_PEER_SYS_BAR1                                             0x91b
#घोषणा mmMC_XPB_XDMA_PEER_SYS_BAR2                                             0x91c
#घोषणा mmMC_XPB_XDMA_PEER_SYS_BAR3                                             0x91d
#घोषणा mmMC_XPB_CLK_GAT                                                        0x91e
#घोषणा mmMC_XPB_INTF_CFG                                                       0x91f
#घोषणा mmMC_XPB_INTF_STS                                                       0x920
#घोषणा mmMC_XPB_PIPE_STS                                                       0x921
#घोषणा mmMC_XPB_SUB_CTRL                                                       0x922
#घोषणा mmMC_XPB_MAP_INVERT_FLUSH_NUM_LSB                                       0x923
#घोषणा mmMC_XPB_PERF_KNOBS                                                     0x924
#घोषणा mmMC_XPB_STICKY                                                         0x925
#घोषणा mmMC_XPB_STICKY_W1C                                                     0x926
#घोषणा mmMC_XPB_MISC_CFG                                                       0x927
#घोषणा mmMC_XPB_CLG_CFG20                                                      0x928
#घोषणा mmMC_XPB_CLG_CFG21                                                      0x929
#घोषणा mmMC_XPB_CLG_CFG22                                                      0x92a
#घोषणा mmMC_XPB_CLG_CFG23                                                      0x92b
#घोषणा mmMC_XPB_CLG_CFG24                                                      0x92c
#घोषणा mmMC_XPB_CLG_CFG25                                                      0x92d
#घोषणा mmMC_XPB_CLG_CFG26                                                      0x92e
#घोषणा mmMC_XPB_CLG_CFG27                                                      0x92f
#घोषणा mmMC_XPB_CLG_CFG28                                                      0x930
#घोषणा mmMC_XPB_CLG_CFG29                                                      0x931
#घोषणा mmMC_XPB_CLG_CFG30                                                      0x932
#घोषणा mmMC_XPB_CLG_CFG31                                                      0x933
#घोषणा mmMC_XPB_INTF_CFG2                                                      0x934
#घोषणा mmMC_XPB_CLG_EXTRA_RD                                                   0x935
#घोषणा mmMC_XPB_CLG_CFG32                                                      0x936
#घोषणा mmMC_XPB_CLG_CFG33                                                      0x937
#घोषणा mmMC_XPB_CLG_CFG34                                                      0x938
#घोषणा mmMC_XPB_CLG_CFG35                                                      0x939
#घोषणा mmMC_XPB_CLG_CFG36                                                      0x93a
#घोषणा mmMC_XBAR_ADDR_DEC                                                      0xc80
#घोषणा mmMC_XBAR_REMOTE                                                        0xc81
#घोषणा mmMC_XBAR_WRREQ_CREDIT                                                  0xc82
#घोषणा mmMC_XBAR_RDREQ_CREDIT                                                  0xc83
#घोषणा mmMC_XBAR_RDREQ_PRI_CREDIT                                              0xc84
#घोषणा mmMC_XBAR_WRRET_CREDIT1                                                 0xc85
#घोषणा mmMC_XBAR_WRRET_CREDIT2                                                 0xc86
#घोषणा mmMC_XBAR_RDRET_CREDIT1                                                 0xc87
#घोषणा mmMC_XBAR_RDRET_CREDIT2                                                 0xc88
#घोषणा mmMC_XBAR_RDRET_PRI_CREDIT1                                             0xc89
#घोषणा mmMC_XBAR_RDRET_PRI_CREDIT2                                             0xc8a
#घोषणा mmMC_XBAR_CHTRIREMAP                                                    0xc8b
#घोषणा mmMC_XBAR_TWOCHAN                                                       0xc8c
#घोषणा mmMC_XBAR_ARB                                                           0xc8d
#घोषणा mmMC_XBAR_ARB_MAX_BURST                                                 0xc8e
#घोषणा mmMC_XBAR_FIFO_MON_CNTL0                                                0xc8f
#घोषणा mmMC_XBAR_FIFO_MON_CNTL1                                                0xc90
#घोषणा mmMC_XBAR_FIFO_MON_CNTL2                                                0xc91
#घोषणा mmMC_XBAR_FIFO_MON_RSLT0                                                0xc92
#घोषणा mmMC_XBAR_FIFO_MON_RSLT1                                                0xc93
#घोषणा mmMC_XBAR_FIFO_MON_RSLT2                                                0xc94
#घोषणा mmMC_XBAR_FIFO_MON_RSLT3                                                0xc95
#घोषणा mmMC_XBAR_FIFO_MON_MAX_THSH                                             0xc96
#घोषणा mmMC_XBAR_SPARE0                                                        0xc97
#घोषणा mmMC_XBAR_SPARE1                                                        0xc98
#घोषणा mmMC_CITF_PERFCOUNTER_LO                                                0x7a0
#घोषणा mmMC_HUB_PERFCOUNTER_LO                                                 0x7a1
#घोषणा mmMC_RPB_PERFCOUNTER_LO                                                 0x7a2
#घोषणा mmMC_MCBVM_PERFCOUNTER_LO                                               0x7a3
#घोषणा mmMC_MCDVM_PERFCOUNTER_LO                                               0x7a4
#घोषणा mmMC_VM_L2_PERFCOUNTER_LO                                               0x7a5
#घोषणा mmMC_ARB_PERFCOUNTER_LO                                                 0x7a6
#घोषणा mmATC_PERFCOUNTER_LO                                                    0x7a7
#घोषणा mmMC_CITF_PERFCOUNTER_HI                                                0x7a8
#घोषणा mmMC_HUB_PERFCOUNTER_HI                                                 0x7a9
#घोषणा mmMC_MCBVM_PERFCOUNTER_HI                                               0x7aa
#घोषणा mmMC_MCDVM_PERFCOUNTER_HI                                               0x7ab
#घोषणा mmMC_RPB_PERFCOUNTER_HI                                                 0x7ac
#घोषणा mmMC_VM_L2_PERFCOUNTER_HI                                               0x7ad
#घोषणा mmMC_ARB_PERFCOUNTER_HI                                                 0x7ae
#घोषणा mmATC_PERFCOUNTER_HI                                                    0x7af
#घोषणा mmMC_CITF_PERFCOUNTER0_CFG                                              0x7b0
#घोषणा mmMC_CITF_PERFCOUNTER1_CFG                                              0x7b1
#घोषणा mmMC_CITF_PERFCOUNTER2_CFG                                              0x7b2
#घोषणा mmMC_CITF_PERFCOUNTER3_CFG                                              0x7b3
#घोषणा mmMC_HUB_PERFCOUNTER0_CFG                                               0x7b4
#घोषणा mmMC_HUB_PERFCOUNTER1_CFG                                               0x7b5
#घोषणा mmMC_HUB_PERFCOUNTER2_CFG                                               0x7b6
#घोषणा mmMC_HUB_PERFCOUNTER3_CFG                                               0x7b7
#घोषणा mmMC_RPB_PERFCOUNTER0_CFG                                               0x7b8
#घोषणा mmMC_RPB_PERFCOUNTER1_CFG                                               0x7b9
#घोषणा mmMC_RPB_PERFCOUNTER2_CFG                                               0x7ba
#घोषणा mmMC_RPB_PERFCOUNTER3_CFG                                               0x7bb
#घोषणा mmMC_ARB_PERFCOUNTER0_CFG                                               0x7bc
#घोषणा mmMC_ARB_PERFCOUNTER1_CFG                                               0x7bd
#घोषणा mmMC_ARB_PERFCOUNTER2_CFG                                               0x7be
#घोषणा mmMC_ARB_PERFCOUNTER3_CFG                                               0x7bf
#घोषणा mmMC_MCBVM_PERFCOUNTER0_CFG                                             0x7c0
#घोषणा mmMC_MCBVM_PERFCOUNTER1_CFG                                             0x7c1
#घोषणा mmMC_MCBVM_PERFCOUNTER2_CFG                                             0x7c2
#घोषणा mmMC_MCBVM_PERFCOUNTER3_CFG                                             0x7c3
#घोषणा mmMC_MCDVM_PERFCOUNTER0_CFG                                             0x7c4
#घोषणा mmMC_MCDVM_PERFCOUNTER1_CFG                                             0x7c5
#घोषणा mmMC_MCDVM_PERFCOUNTER2_CFG                                             0x7c6
#घोषणा mmMC_MCDVM_PERFCOUNTER3_CFG                                             0x7c7
#घोषणा mmATC_PERFCOUNTER0_CFG                                                  0x7c8
#घोषणा mmATC_PERFCOUNTER1_CFG                                                  0x7c9
#घोषणा mmATC_PERFCOUNTER2_CFG                                                  0x7ca
#घोषणा mmATC_PERFCOUNTER3_CFG                                                  0x7cb
#घोषणा mmMC_VM_L2_PERFCOUNTER0_CFG                                             0x7cc
#घोषणा mmMC_VM_L2_PERFCOUNTER1_CFG                                             0x7cd
#घोषणा mmMC_CITF_PERFCOUNTER_RSLT_CNTL                                         0x7ce
#घोषणा mmMC_HUB_PERFCOUNTER_RSLT_CNTL                                          0x7cf
#घोषणा mmMC_RPB_PERFCOUNTER_RSLT_CNTL                                          0x7d0
#घोषणा mmMC_MCBVM_PERFCOUNTER_RSLT_CNTL                                        0x7d1
#घोषणा mmMC_MCDVM_PERFCOUNTER_RSLT_CNTL                                        0x7d2
#घोषणा mmMC_VM_L2_PERFCOUNTER_RSLT_CNTL                                        0x7d3
#घोषणा mmMC_ARB_PERFCOUNTER_RSLT_CNTL                                          0x7d4
#घोषणा mmATC_PERFCOUNTER_RSLT_CNTL                                             0x7d5
#घोषणा mmCHUB_ATC_PERFCOUNTER_LO                                               0x7d6
#घोषणा mmCHUB_ATC_PERFCOUNTER_HI                                               0x7d7
#घोषणा mmCHUB_ATC_PERFCOUNTER0_CFG                                             0x7d8
#घोषणा mmCHUB_ATC_PERFCOUNTER1_CFG                                             0x7d9
#घोषणा mmCHUB_ATC_PERFCOUNTER_RSLT_CNTL                                        0x7da
#घोषणा mmMC_GRUB_PERFCOUNTER_LO                                                0x7e4
#घोषणा mmMC_GRUB_PERFCOUNTER_HI                                                0x7e5
#घोषणा mmMC_GRUB_PERFCOUNTER0_CFG                                              0x7e6
#घोषणा mmMC_GRUB_PERFCOUNTER1_CFG                                              0x7e7
#घोषणा mmMC_GRUB_PERFCOUNTER_RSLT_CNTL                                         0x7e8
#घोषणा mmATC_VM_APERTURE0_LOW_ADDR                                             0xcc0
#घोषणा mmATC_VM_APERTURE1_LOW_ADDR                                             0xcc1
#घोषणा mmATC_VM_APERTURE0_HIGH_ADDR                                            0xcc2
#घोषणा mmATC_VM_APERTURE1_HIGH_ADDR                                            0xcc3
#घोषणा mmATC_VM_APERTURE0_CNTL                                                 0xcc4
#घोषणा mmATC_VM_APERTURE1_CNTL                                                 0xcc5
#घोषणा mmATC_VM_APERTURE0_CNTL2                                                0xcc6
#घोषणा mmATC_VM_APERTURE1_CNTL2                                                0xcc7
#घोषणा mmATC_ATS_CNTL                                                          0xcc9
#घोषणा mmATC_ATS_DEBUG                                                         0xcca
#घोषणा mmATC_ATS_FAULT_DEBUG                                                   0xccb
#घोषणा mmATC_ATS_STATUS                                                        0xccc
#घोषणा mmATC_ATS_FAULT_CNTL                                                    0xccd
#घोषणा mmATC_ATS_FAULT_STATUS_INFO                                             0xcce
#घोषणा mmATC_ATS_FAULT_STATUS_ADDR                                             0xccf
#घोषणा mmATC_ATS_DEFAULT_PAGE_LOW                                              0xcd0
#घोषणा mmATC_ATS_DEFAULT_PAGE_CNTL                                             0xcd1
#घोषणा mmATC_ATS_FAULT_STATUS_INFO2                                            0xcd2
#घोषणा mmATC_MISC_CG                                                           0xcd4
#घोषणा mmATC_L2_CNTL                                                           0xcd5
#घोषणा mmATC_L2_CNTL2                                                          0xcd6
#घोषणा mmATC_L2_DEBUG                                                          0xcd7
#घोषणा mmATC_L2_DEBUG2                                                         0xcd8
#घोषणा mmATC_L2_CACHE_DATA0                                                    0xcd9
#घोषणा mmATC_L2_CACHE_DATA1                                                    0xcda
#घोषणा mmATC_L2_CACHE_DATA2                                                    0xcdb
#घोषणा mmATC_L1_CNTL                                                           0xcdc
#घोषणा mmATC_L1_ADDRESS_OFFSET                                                 0xcdd
#घोषणा mmATC_L1RD_DEBUG_TLB                                                    0xcde
#घोषणा mmATC_L1WR_DEBUG_TLB                                                    0xcdf
#घोषणा mmATC_L1RD_STATUS                                                       0xce0
#घोषणा mmATC_L1WR_STATUS                                                       0xce1
#घोषणा mmATC_L1RD_DEBUG2_TLB                                                   0xce2
#घोषणा mmATC_L1WR_DEBUG2_TLB                                                   0xce3
#घोषणा mmATC_VMID_PASID_MAPPING_UPDATE_STATUS                                  0xce6
#घोषणा mmATC_VMID0_PASID_MAPPING                                               0xce7
#घोषणा mmATC_VMID1_PASID_MAPPING                                               0xce8
#घोषणा mmATC_VMID2_PASID_MAPPING                                               0xce9
#घोषणा mmATC_VMID3_PASID_MAPPING                                               0xcea
#घोषणा mmATC_VMID4_PASID_MAPPING                                               0xceb
#घोषणा mmATC_VMID5_PASID_MAPPING                                               0xcec
#घोषणा mmATC_VMID6_PASID_MAPPING                                               0xced
#घोषणा mmATC_VMID7_PASID_MAPPING                                               0xcee
#घोषणा mmATC_VMID8_PASID_MAPPING                                               0xcef
#घोषणा mmATC_VMID9_PASID_MAPPING                                               0xcf0
#घोषणा mmATC_VMID10_PASID_MAPPING                                              0xcf1
#घोषणा mmATC_VMID11_PASID_MAPPING                                              0xcf2
#घोषणा mmATC_VMID12_PASID_MAPPING                                              0xcf3
#घोषणा mmATC_VMID13_PASID_MAPPING                                              0xcf4
#घोषणा mmATC_VMID14_PASID_MAPPING                                              0xcf5
#घोषणा mmATC_VMID15_PASID_MAPPING                                              0xcf6
#घोषणा mmATC_ATS_VMID_STATUS                                                   0xd07
#घोषणा mmATC_ATS_SMU_STATUS                                                    0xd08
#घोषणा mmATC_L2_CNTL3                                                          0xd09
#घोषणा mmATC_L2_STATUS                                                         0xd0a
#घोषणा mmATC_L2_STATUS2                                                        0xd0b
#घोषणा mmGMCON_RENG_RAM_INDEX                                                  0xd40
#घोषणा mmGMCON_RENG_RAM_DATA                                                   0xd41
#घोषणा mmGMCON_RENG_EXECUTE                                                    0xd42
#घोषणा mmGMCON_MISC                                                            0xd43
#घोषणा mmGMCON_MISC2                                                           0xd44
#घोषणा mmGMCON_STCTRL_REGISTER_SAVE_RANGE0                                     0xd45
#घोषणा mmGMCON_STCTRL_REGISTER_SAVE_RANGE1                                     0xd46
#घोषणा mmGMCON_STCTRL_REGISTER_SAVE_RANGE2                                     0xd47
#घोषणा mmGMCON_STCTRL_REGISTER_SAVE_EXCL_SET0                                  0xd48
#घोषणा mmGMCON_STCTRL_REGISTER_SAVE_EXCL_SET1                                  0xd49
#घोषणा mmGMCON_PERF_MON_CNTL0                                                  0xd4a
#घोषणा mmGMCON_PERF_MON_CNTL1                                                  0xd4b
#घोषणा mmGMCON_PERF_MON_RSLT0                                                  0xd4c
#घोषणा mmGMCON_PERF_MON_RSLT1                                                  0xd4d
#घोषणा mmGMCON_PGFSM_CONFIG                                                    0xd4e
#घोषणा mmGMCON_PGFSM_WRITE                                                     0xd4f
#घोषणा mmGMCON_PGFSM_READ                                                      0xd50
#घोषणा mmGMCON_MISC3                                                           0xd51
#घोषणा mmGMCON_MASK                                                            0xd52
#घोषणा mmGMCON_LPT_TARGET                                                      0xd53
#घोषणा mmGMCON_DEBUG                                                           0xd5f
#घोषणा mmVM_L2_CNTL                                                            0x500
#घोषणा mmVM_L2_CNTL2                                                           0x501
#घोषणा mmVM_L2_CNTL3                                                           0x502
#घोषणा mmVM_L2_STATUS                                                          0x503
#घोषणा mmVM_CONTEXT0_CNTL                                                      0x504
#घोषणा mmVM_CONTEXT1_CNTL                                                      0x505
#घोषणा mmVM_DUMMY_PAGE_FAULT_CNTL                                              0x506
#घोषणा mmVM_DUMMY_PAGE_FAULT_ADDR                                              0x507
#घोषणा mmVM_CONTEXT0_CNTL2                                                     0x50c
#घोषणा mmVM_CONTEXT1_CNTL2                                                     0x50d
#घोषणा mmVM_CONTEXT8_PAGE_TABLE_BASE_ADDR                                      0x50e
#घोषणा mmVM_CONTEXT9_PAGE_TABLE_BASE_ADDR                                      0x50f
#घोषणा mmVM_CONTEXT10_PAGE_TABLE_BASE_ADDR                                     0x510
#घोषणा mmVM_CONTEXT11_PAGE_TABLE_BASE_ADDR                                     0x511
#घोषणा mmVM_CONTEXT12_PAGE_TABLE_BASE_ADDR                                     0x512
#घोषणा mmVM_CONTEXT13_PAGE_TABLE_BASE_ADDR                                     0x513
#घोषणा mmVM_CONTEXT14_PAGE_TABLE_BASE_ADDR                                     0x514
#घोषणा mmVM_CONTEXT15_PAGE_TABLE_BASE_ADDR                                     0x515
#घोषणा mmVM_INVALIDATE_REQUEST                                                 0x51e
#घोषणा mmVM_INVALIDATE_RESPONSE                                                0x51f
#घोषणा mmVM_PRT_APERTURE0_LOW_ADDR                                             0x52c
#घोषणा mmVM_PRT_APERTURE1_LOW_ADDR                                             0x52d
#घोषणा mmVM_PRT_APERTURE2_LOW_ADDR                                             0x52e
#घोषणा mmVM_PRT_APERTURE3_LOW_ADDR                                             0x52f
#घोषणा mmVM_PRT_APERTURE0_HIGH_ADDR                                            0x530
#घोषणा mmVM_PRT_APERTURE1_HIGH_ADDR                                            0x531
#घोषणा mmVM_PRT_APERTURE2_HIGH_ADDR                                            0x532
#घोषणा mmVM_PRT_APERTURE3_HIGH_ADDR                                            0x533
#घोषणा mmVM_PRT_CNTL                                                           0x534
#घोषणा mmVM_CONTEXTS_DISABLE                                                   0x535
#घोषणा mmVM_CONTEXT0_PROTECTION_FAULT_STATUS                                   0x536
#घोषणा mmVM_CONTEXT1_PROTECTION_FAULT_STATUS                                   0x537
#घोषणा mmVM_CONTEXT0_PROTECTION_FAULT_MCCLIENT                                 0x538
#घोषणा mmVM_CONTEXT1_PROTECTION_FAULT_MCCLIENT                                 0x539
#घोषणा mmVM_CONTEXT0_PROTECTION_FAULT_ADDR                                     0x53e
#घोषणा mmVM_CONTEXT1_PROTECTION_FAULT_ADDR                                     0x53f
#घोषणा mmVM_CONTEXT0_PROTECTION_FAULT_DEFAULT_ADDR                             0x546
#घोषणा mmVM_CONTEXT1_PROTECTION_FAULT_DEFAULT_ADDR                             0x547
#घोषणा mmVM_FAULT_CLIENT_ID                                                    0x54e
#घोषणा mmVM_CONTEXT0_PAGE_TABLE_BASE_ADDR                                      0x54f
#घोषणा mmVM_CONTEXT1_PAGE_TABLE_BASE_ADDR                                      0x550
#घोषणा mmVM_CONTEXT2_PAGE_TABLE_BASE_ADDR                                      0x551
#घोषणा mmVM_CONTEXT3_PAGE_TABLE_BASE_ADDR                                      0x552
#घोषणा mmVM_CONTEXT4_PAGE_TABLE_BASE_ADDR                                      0x553
#घोषणा mmVM_CONTEXT5_PAGE_TABLE_BASE_ADDR                                      0x554
#घोषणा mmVM_CONTEXT6_PAGE_TABLE_BASE_ADDR                                      0x555
#घोषणा mmVM_CONTEXT7_PAGE_TABLE_BASE_ADDR                                      0x556
#घोषणा mmVM_CONTEXT0_PAGE_TABLE_START_ADDR                                     0x557
#घोषणा mmVM_CONTEXT1_PAGE_TABLE_START_ADDR                                     0x558
#घोषणा mmVM_CONTEXT0_PAGE_TABLE_END_ADDR                                       0x55f
#घोषणा mmVM_CONTEXT1_PAGE_TABLE_END_ADDR                                       0x560
#घोषणा mmVM_DEBUG                                                              0x56f
#घोषणा mmVM_L2_CG                                                              0x570
#घोषणा mmVM_L2_BANK_SELECT_MASKA                                               0x572
#घोषणा mmVM_L2_BANK_SELECT_MASKB                                               0x573
#घोषणा mmVM_L2_CONTEXT1_IDENTITY_APERTURE_LOW_ADDR                             0x575
#घोषणा mmVM_L2_CONTEXT1_IDENTITY_APERTURE_HIGH_ADDR                            0x576
#घोषणा mmVM_L2_CONTEXT_IDENTITY_PHYSICAL_OFFSET                                0x577
#घोषणा mmVM_L2_CNTL4                                                           0x578
#घोषणा mmVM_L2_BANK_SELECT_RESERVED_CID                                        0x579
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF0                                              0xf980
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF1                                              0xf981
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF2                                              0xf982
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF3                                              0xf983
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF4                                              0xf984
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF5                                              0xf985
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF6                                              0xf986
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF7                                              0xf987
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF8                                              0xf988
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF9                                              0xf989
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF10                                             0xf98a
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF11                                             0xf98b
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF12                                             0xf98c
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF13                                             0xf98d
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF14                                             0xf98e
#घोषणा mmMC_VM_FB_SIZE_OFFSET_VF15                                             0xf98f
#घोषणा mmMC_VM_NB_MMIOBASE                                                     0xf990
#घोषणा mmMC_VM_NB_MMIOLIMIT                                                    0xf991
#घोषणा mmMC_VM_NB_PCI_CTRL                                                     0xf992
#घोषणा mmMC_VM_NB_PCI_ARB                                                      0xf993
#घोषणा mmMC_VM_NB_TOP_OF_DRAM_SLOT1                                            0xf994
#घोषणा mmMC_VM_NB_LOWER_TOP_OF_DRAM2                                           0xf995
#घोषणा mmMC_VM_NB_UPPER_TOP_OF_DRAM2                                           0xf996
#घोषणा mmMC_VM_NB_TOP_OF_DRAM3                                                 0xf997
#घोषणा mmMC_VM_MARC_BASE_LO_0                                                  0xf998
#घोषणा mmMC_VM_MARC_BASE_LO_1                                                  0xf99e
#घोषणा mmMC_VM_MARC_BASE_LO_2                                                  0xf9a4
#घोषणा mmMC_VM_MARC_BASE_LO_3                                                  0xf9aa
#घोषणा mmMC_VM_MARC_BASE_HI_0                                                  0xf999
#घोषणा mmMC_VM_MARC_BASE_HI_1                                                  0xf99f
#घोषणा mmMC_VM_MARC_BASE_HI_2                                                  0xf9a5
#घोषणा mmMC_VM_MARC_BASE_HI_3                                                  0xf9ab
#घोषणा mmMC_VM_MARC_RELOC_LO_0                                                 0xf99a
#घोषणा mmMC_VM_MARC_RELOC_LO_1                                                 0xf9a0
#घोषणा mmMC_VM_MARC_RELOC_LO_2                                                 0xf9a6
#घोषणा mmMC_VM_MARC_RELOC_LO_3                                                 0xf9ac
#घोषणा mmMC_VM_MARC_RELOC_HI_0                                                 0xf99b
#घोषणा mmMC_VM_MARC_RELOC_HI_1                                                 0xf9a1
#घोषणा mmMC_VM_MARC_RELOC_HI_2                                                 0xf9a7
#घोषणा mmMC_VM_MARC_RELOC_HI_3                                                 0xf9ad
#घोषणा mmMC_VM_MARC_LEN_LO_0                                                   0xf99c
#घोषणा mmMC_VM_MARC_LEN_LO_1                                                   0xf9a2
#घोषणा mmMC_VM_MARC_LEN_LO_2                                                   0xf9a8
#घोषणा mmMC_VM_MARC_LEN_LO_3                                                   0xf9ae
#घोषणा mmMC_VM_MARC_LEN_HI_0                                                   0xf99d
#घोषणा mmMC_VM_MARC_LEN_HI_1                                                   0xf9a3
#घोषणा mmMC_VM_MARC_LEN_HI_2                                                   0xf9a9
#घोषणा mmMC_VM_MARC_LEN_HI_3                                                   0xf9af
#घोषणा mmMC_VM_MARC_CNTL                                                       0xf9b0
#घोषणा mmMC_ARB_HARSH_EN_RD                                                    0xdc0
#घोषणा mmMC_ARB_HARSH_EN_WR                                                    0xdc1
#घोषणा mmMC_ARB_HARSH_TX_HI0_RD                                                0xdc2
#घोषणा mmMC_ARB_HARSH_TX_HI0_WR                                                0xdc3
#घोषणा mmMC_ARB_HARSH_TX_HI1_RD                                                0xdc4
#घोषणा mmMC_ARB_HARSH_TX_HI1_WR                                                0xdc5
#घोषणा mmMC_ARB_HARSH_TX_LO0_RD                                                0xdc6
#घोषणा mmMC_ARB_HARSH_TX_LO0_WR                                                0xdc7
#घोषणा mmMC_ARB_HARSH_TX_LO1_RD                                                0xdc8
#घोषणा mmMC_ARB_HARSH_TX_LO1_WR                                                0xdc9
#घोषणा mmMC_ARB_HARSH_BWPERIOD0_RD                                             0xdca
#घोषणा mmMC_ARB_HARSH_BWPERIOD0_WR                                             0xdcb
#घोषणा mmMC_ARB_HARSH_BWPERIOD1_RD                                             0xdcc
#घोषणा mmMC_ARB_HARSH_BWPERIOD1_WR                                             0xdcd
#घोषणा mmMC_ARB_HARSH_BWCNT0_RD                                                0xdce
#घोषणा mmMC_ARB_HARSH_BWCNT0_WR                                                0xdcf
#घोषणा mmMC_ARB_HARSH_BWCNT1_RD                                                0xdd0
#घोषणा mmMC_ARB_HARSH_BWCNT1_WR                                                0xdd1
#घोषणा mmMC_ARB_HARSH_SAT0_RD                                                  0xdd2
#घोषणा mmMC_ARB_HARSH_SAT0_WR                                                  0xdd3
#घोषणा mmMC_ARB_HARSH_SAT1_RD                                                  0xdd4
#घोषणा mmMC_ARB_HARSH_SAT1_WR                                                  0xdd5
#घोषणा mmMC_ARB_HARSH_CTL_RD                                                   0xdd6
#घोषणा mmMC_ARB_HARSH_CTL_WR                                                   0xdd7
#घोषणा mmMC_ARB_GRUB_PRIORITY1_RD                                              0xdd8
#घोषणा mmMC_ARB_GRUB_PRIORITY1_WR                                              0xdd9
#घोषणा mmMC_ARB_GRUB_PRIORITY2_RD                                              0xdda
#घोषणा mmMC_ARB_GRUB_PRIORITY2_WR                                              0xddb
#घोषणा mmMC_FUS_DRAM0_CS0_BASE                                                 0xa05
#घोषणा mmMC_FUS_DRAM1_CS0_BASE                                                 0xa06
#घोषणा mmMC_FUS_DRAM0_CS1_BASE                                                 0xa07
#घोषणा mmMC_FUS_DRAM1_CS1_BASE                                                 0xa08
#घोषणा mmMC_FUS_DRAM0_CS2_BASE                                                 0xa09
#घोषणा mmMC_FUS_DRAM1_CS2_BASE                                                 0xa0a
#घोषणा mmMC_FUS_DRAM0_CS3_BASE                                                 0xa0b
#घोषणा mmMC_FUS_DRAM1_CS3_BASE                                                 0xa0c
#घोषणा mmMC_FUS_DRAM0_CS01_MASK                                                0xa0d
#घोषणा mmMC_FUS_DRAM1_CS01_MASK                                                0xa0e
#घोषणा mmMC_FUS_DRAM0_CS23_MASK                                                0xa0f
#घोषणा mmMC_FUS_DRAM1_CS23_MASK                                                0xa10
#घोषणा mmMC_FUS_DRAM0_BANK_ADDR_MAPPING                                        0xa11
#घोषणा mmMC_FUS_DRAM1_BANK_ADDR_MAPPING                                        0xa12
#घोषणा mmMC_FUS_DRAM0_CTL_BASE                                                 0xa13
#घोषणा mmMC_FUS_DRAM1_CTL_BASE                                                 0xa14
#घोषणा mmMC_FUS_DRAM0_CTL_LIMIT                                                0xa15
#घोषणा mmMC_FUS_DRAM1_CTL_LIMIT                                                0xa16
#घोषणा mmMC_FUS_DRAM_CTL_HIGH_01                                               0xa17
#घोषणा mmMC_FUS_DRAM_CTL_HIGH_23                                               0xa18
#घोषणा mmMC_FUS_DRAM_MODE                                                      0xa19
#घोषणा mmMC_FUS_DRAM_APER_BASE                                                 0xa1a
#घोषणा mmMC_FUS_DRAM_APER_TOP                                                  0xa1b
#घोषणा mmMC_FUS_DRAM_APER_DEF                                                  0xa1e
#घोषणा mmMC_FUS_ARB_GARLIC_ISOC_PRI                                            0xa1f
#घोषणा mmMC_FUS_ARB_GARLIC_CNTL                                                0xa20
#घोषणा mmMC_FUS_ARB_GARLIC_WR_PRI                                              0xa21
#घोषणा mmMC_FUS_ARB_GARLIC_WR_PRI2                                             0xa22
#घोषणा mmMC_CG_DATAPORT                                                        0xa32
#घोषणा mmMC_GRUB_PROBE_MAP                                                     0xa33
#घोषणा mmMC_GRUB_POST_PROBE_DELAY                                              0xa34
#घोषणा mmMC_GRUB_PROBE_CREDITS                                                 0xa35
#घोषणा mmMC_GRUB_FEATURES                                                      0xa36
#घोषणा mmMC_GRUB_TX_CREDITS                                                    0xa37
#घोषणा mmMC_GRUB_TCB_INDEX                                                     0xa38
#घोषणा mmMC_GRUB_TCB_DATA_LO                                                   0xa39
#घोषणा mmMC_GRUB_TCB_DATA_HI                                                   0xa3a
#घोषणा mmMCIF_WB_BUFMGR_SW_CONTROL                                             0x5e78
#घोषणा mmMCIF_WB0_MCIF_WB_BUFMGR_SW_CONTROL                                    0x5e78
#घोषणा mmMCIF_WB1_MCIF_WB_BUFMGR_SW_CONTROL                                    0x5eb8
#घोषणा mmMCIF_WB2_MCIF_WB_BUFMGR_SW_CONTROL                                    0x5ef8
#घोषणा mmMCIF_WB_BUFMGR_CUR_LINE_R                                             0x5e79
#घोषणा mmMCIF_WB0_MCIF_WB_BUFMGR_CUR_LINE_R                                    0x5e79
#घोषणा mmMCIF_WB1_MCIF_WB_BUFMGR_CUR_LINE_R                                    0x5eb9
#घोषणा mmMCIF_WB2_MCIF_WB_BUFMGR_CUR_LINE_R                                    0x5ef9
#घोषणा mmMCIF_WB_BUFMGR_STATUS                                                 0x5e7a
#घोषणा mmMCIF_WB0_MCIF_WB_BUFMGR_STATUS                                        0x5e7a
#घोषणा mmMCIF_WB1_MCIF_WB_BUFMGR_STATUS                                        0x5eba
#घोषणा mmMCIF_WB2_MCIF_WB_BUFMGR_STATUS                                        0x5efa
#घोषणा mmMCIF_WB_BUF_PITCH                                                     0x5e7b
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_PITCH                                            0x5e7b
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_PITCH                                            0x5ebb
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_PITCH                                            0x5efb
#घोषणा mmMCIF_WB_BUF_1_STATUS                                                  0x5e7c
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_1_STATUS                                         0x5e7c
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_1_STATUS                                         0x5ebc
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_1_STATUS                                         0x5efc
#घोषणा mmMCIF_WB_BUF_1_STATUS2                                                 0x5e7d
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_1_STATUS2                                        0x5e7d
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_1_STATUS2                                        0x5ebd
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_1_STATUS2                                        0x5efd
#घोषणा mmMCIF_WB_BUF_2_STATUS                                                  0x5e7e
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_2_STATUS                                         0x5e7e
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_2_STATUS                                         0x5ebe
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_2_STATUS                                         0x5efe
#घोषणा mmMCIF_WB_BUF_2_STATUS2                                                 0x5e7f
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_2_STATUS2                                        0x5e7f
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_2_STATUS2                                        0x5ebf
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_2_STATUS2                                        0x5eff
#घोषणा mmMCIF_WB_BUF_3_STATUS                                                  0x5e80
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_3_STATUS                                         0x5e80
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_3_STATUS                                         0x5ec0
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_3_STATUS                                         0x5f00
#घोषणा mmMCIF_WB_BUF_3_STATUS2                                                 0x5e81
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_3_STATUS2                                        0x5e81
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_3_STATUS2                                        0x5ec1
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_3_STATUS2                                        0x5f01
#घोषणा mmMCIF_WB_BUF_4_STATUS                                                  0x5e82
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_4_STATUS                                         0x5e82
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_4_STATUS                                         0x5ec2
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_4_STATUS                                         0x5f02
#घोषणा mmMCIF_WB_BUF_4_STATUS2                                                 0x5e83
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_4_STATUS2                                        0x5e83
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_4_STATUS2                                        0x5ec3
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_4_STATUS2                                        0x5f03
#घोषणा mmMCIF_WB_ARBITRATION_CONTROL                                           0x5e84
#घोषणा mmMCIF_WB0_MCIF_WB_ARBITRATION_CONTROL                                  0x5e84
#घोषणा mmMCIF_WB1_MCIF_WB_ARBITRATION_CONTROL                                  0x5ec4
#घोषणा mmMCIF_WB2_MCIF_WB_ARBITRATION_CONTROL                                  0x5f04
#घोषणा mmMCIF_WB_URGENCY_WATERMARK                                             0x5e85
#घोषणा mmMCIF_WB0_MCIF_WB_URGENCY_WATERMARK                                    0x5e85
#घोषणा mmMCIF_WB1_MCIF_WB_URGENCY_WATERMARK                                    0x5ec5
#घोषणा mmMCIF_WB2_MCIF_WB_URGENCY_WATERMARK                                    0x5f05
#घोषणा mmMCIF_WB_TEST_DEBUG_INDEX                                              0x5e86
#घोषणा mmMCIF_WB0_MCIF_WB_TEST_DEBUG_INDEX                                     0x5e86
#घोषणा mmMCIF_WB1_MCIF_WB_TEST_DEBUG_INDEX                                     0x5ec6
#घोषणा mmMCIF_WB2_MCIF_WB_TEST_DEBUG_INDEX                                     0x5f06
#घोषणा mmMCIF_WB_TEST_DEBUG_DATA                                               0x5e87
#घोषणा mmMCIF_WB0_MCIF_WB_TEST_DEBUG_DATA                                      0x5e87
#घोषणा mmMCIF_WB1_MCIF_WB_TEST_DEBUG_DATA                                      0x5ec7
#घोषणा mmMCIF_WB2_MCIF_WB_TEST_DEBUG_DATA                                      0x5f07
#घोषणा mmMCIF_WB_BUF_1_ADDR_Y                                                  0x5e88
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_1_ADDR_Y                                         0x5e88
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_1_ADDR_Y                                         0x5ec8
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_1_ADDR_Y                                         0x5f08
#घोषणा mmMCIF_WB_BUF_1_ADDR_Y_OFFSET                                           0x5e89
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_1_ADDR_Y_OFFSET                                  0x5e89
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_1_ADDR_Y_OFFSET                                  0x5ec9
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_1_ADDR_Y_OFFSET                                  0x5f09
#घोषणा mmMCIF_WB_BUF_1_ADDR_C                                                  0x5e8a
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_1_ADDR_C                                         0x5e8a
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_1_ADDR_C                                         0x5eca
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_1_ADDR_C                                         0x5f0a
#घोषणा mmMCIF_WB_BUF_1_ADDR_C_OFFSET                                           0x5e8b
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_1_ADDR_C_OFFSET                                  0x5e8b
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_1_ADDR_C_OFFSET                                  0x5ecb
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_1_ADDR_C_OFFSET                                  0x5f0b
#घोषणा mmMCIF_WB_BUF_2_ADDR_Y                                                  0x5e8c
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_2_ADDR_Y                                         0x5e8c
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_2_ADDR_Y                                         0x5ecc
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_2_ADDR_Y                                         0x5f0c
#घोषणा mmMCIF_WB_BUF_2_ADDR_Y_OFFSET                                           0x5e8d
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_2_ADDR_Y_OFFSET                                  0x5e8d
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_2_ADDR_Y_OFFSET                                  0x5ecd
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_2_ADDR_Y_OFFSET                                  0x5f0d
#घोषणा mmMCIF_WB_BUF_2_ADDR_C                                                  0x5e8e
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_2_ADDR_C                                         0x5e8e
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_2_ADDR_C                                         0x5ece
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_2_ADDR_C                                         0x5f0e
#घोषणा mmMCIF_WB_BUF_2_ADDR_C_OFFSET                                           0x5e8f
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_2_ADDR_C_OFFSET                                  0x5e8f
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_2_ADDR_C_OFFSET                                  0x5ecf
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_2_ADDR_C_OFFSET                                  0x5f0f
#घोषणा mmMCIF_WB_BUF_3_ADDR_Y                                                  0x5e90
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_3_ADDR_Y                                         0x5e90
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_3_ADDR_Y                                         0x5ed0
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_3_ADDR_Y                                         0x5f10
#घोषणा mmMCIF_WB_BUF_3_ADDR_Y_OFFSET                                           0x5e91
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_3_ADDR_Y_OFFSET                                  0x5e91
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_3_ADDR_Y_OFFSET                                  0x5ed1
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_3_ADDR_Y_OFFSET                                  0x5f11
#घोषणा mmMCIF_WB_BUF_3_ADDR_C                                                  0x5e92
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_3_ADDR_C                                         0x5e92
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_3_ADDR_C                                         0x5ed2
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_3_ADDR_C                                         0x5f12
#घोषणा mmMCIF_WB_BUF_3_ADDR_C_OFFSET                                           0x5e93
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_3_ADDR_C_OFFSET                                  0x5e93
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_3_ADDR_C_OFFSET                                  0x5ed3
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_3_ADDR_C_OFFSET                                  0x5f13
#घोषणा mmMCIF_WB_BUF_4_ADDR_Y                                                  0x5e94
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_4_ADDR_Y                                         0x5e94
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_4_ADDR_Y                                         0x5ed4
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_4_ADDR_Y                                         0x5f14
#घोषणा mmMCIF_WB_BUF_4_ADDR_Y_OFFSET                                           0x5e95
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_4_ADDR_Y_OFFSET                                  0x5e95
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_4_ADDR_Y_OFFSET                                  0x5ed5
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_4_ADDR_Y_OFFSET                                  0x5f15
#घोषणा mmMCIF_WB_BUF_4_ADDR_C                                                  0x5e96
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_4_ADDR_C                                         0x5e96
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_4_ADDR_C                                         0x5ed6
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_4_ADDR_C                                         0x5f16
#घोषणा mmMCIF_WB_BUF_4_ADDR_C_OFFSET                                           0x5e97
#घोषणा mmMCIF_WB0_MCIF_WB_BUF_4_ADDR_C_OFFSET                                  0x5e97
#घोषणा mmMCIF_WB1_MCIF_WB_BUF_4_ADDR_C_OFFSET                                  0x5ed7
#घोषणा mmMCIF_WB2_MCIF_WB_BUF_4_ADDR_C_OFFSET                                  0x5f17
#घोषणा mmMCIF_WB_BUFMGR_VCE_CONTROL                                            0x5e98
#घोषणा mmMCIF_WB0_MCIF_WB_BUFMGR_VCE_CONTROL                                   0x5e98
#घोषणा mmMCIF_WB1_MCIF_WB_BUFMGR_VCE_CONTROL                                   0x5ed8
#घोषणा mmMCIF_WB2_MCIF_WB_BUFMGR_VCE_CONTROL                                   0x5f18
#घोषणा mmMCIF_WB_HVVMID_CONTROL                                                0x5e99
#घोषणा mmMCIF_WB0_MCIF_WB_HVVMID_CONTROL                                       0x5e99
#घोषणा mmMCIF_WB1_MCIF_WB_HVVMID_CONTROL                                       0x5ed9
#घोषणा mmMCIF_WB2_MCIF_WB_HVVMID_CONTROL                                       0x5f19

#पूर्ण_अगर /* GMC_8_2_D_H */
