<शैली गुरु>
अणु
	"runtime/jit: tail_call within bounds, prog once",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_3, 0),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 1 पूर्ण,
	.result = ACCEPT,
	.retval = 42,
पूर्ण,
अणु
	"runtime/jit: tail_call within bounds, prog loop",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_3, 1),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 1 पूर्ण,
	.result = ACCEPT,
	.retval = 41,
पूर्ण,
अणु
	"runtime/jit: tail_call within bounds, no prog",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_3, 3),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 1 पूर्ण,
	.result = ACCEPT,
	.retval = 1,
पूर्ण,
अणु
	"runtime/jit: tail_call within bounds, key 2",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_3, 2),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 1 पूर्ण,
	.result = ACCEPT,
	.retval = 24,
पूर्ण,
अणु
	"runtime/jit: tail_call within bounds, key 2 / key 2, first branch",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_0, 13),
	BPF_STX_MEM(BPF_B, BPF_REG_1, BPF_REG_0,
		    दुरत्व(काष्ठा __sk_buff, cb[0])),
	BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
		    दुरत्व(काष्ठा __sk_buff, cb[0])),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_0, 13, 4),
	BPF_MOV64_IMM(BPF_REG_3, 2),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_JMP_IMM(BPF_JA, 0, 0, 3),
	BPF_MOV64_IMM(BPF_REG_3, 2),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 5, 9 पूर्ण,
	.result = ACCEPT,
	.retval = 24,
पूर्ण,
अणु
	"runtime/jit: tail_call within bounds, key 2 / key 2, second branch",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_0, 14),
	BPF_STX_MEM(BPF_B, BPF_REG_1, BPF_REG_0,
		    दुरत्व(काष्ठा __sk_buff, cb[0])),
	BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
		    दुरत्व(काष्ठा __sk_buff, cb[0])),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_0, 13, 4),
	BPF_MOV64_IMM(BPF_REG_3, 2),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_JMP_IMM(BPF_JA, 0, 0, 3),
	BPF_MOV64_IMM(BPF_REG_3, 2),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 5, 9 पूर्ण,
	.result = ACCEPT,
	.retval = 24,
पूर्ण,
अणु
	"runtime/jit: tail_call within bounds, key 0 / key 2, first branch",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_0, 13),
	BPF_STX_MEM(BPF_B, BPF_REG_1, BPF_REG_0,
		    दुरत्व(काष्ठा __sk_buff, cb[0])),
	BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
		    दुरत्व(काष्ठा __sk_buff, cb[0])),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_0, 13, 4),
	BPF_MOV64_IMM(BPF_REG_3, 0),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_JMP_IMM(BPF_JA, 0, 0, 3),
	BPF_MOV64_IMM(BPF_REG_3, 2),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 5, 9 पूर्ण,
	.result = ACCEPT,
	.retval = 24,
पूर्ण,
अणु
	"runtime/jit: tail_call within bounds, key 0 / key 2, second branch",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_0, 14),
	BPF_STX_MEM(BPF_B, BPF_REG_1, BPF_REG_0,
		    दुरत्व(काष्ठा __sk_buff, cb[0])),
	BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
		    दुरत्व(काष्ठा __sk_buff, cb[0])),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_0, 13, 4),
	BPF_MOV64_IMM(BPF_REG_3, 0),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_JMP_IMM(BPF_JA, 0, 0, 3),
	BPF_MOV64_IMM(BPF_REG_3, 2),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 5, 9 पूर्ण,
	.result = ACCEPT,
	.retval = 42,
पूर्ण,
अणु
	"runtime/jit: tail_call within bounds, different maps, first branch",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_0, 13),
	BPF_STX_MEM(BPF_B, BPF_REG_1, BPF_REG_0,
		    दुरत्व(काष्ठा __sk_buff, cb[0])),
	BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
		    दुरत्व(काष्ठा __sk_buff, cb[0])),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_0, 13, 4),
	BPF_MOV64_IMM(BPF_REG_3, 0),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_JMP_IMM(BPF_JA, 0, 0, 3),
	BPF_MOV64_IMM(BPF_REG_3, 0),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 5 पूर्ण,
	.fixup_prog2 = अणु 9 पूर्ण,
	.result_unpriv = REJECT,
	.errstr_unpriv = "tail_call abusing map_ptr",
	.result = ACCEPT,
	.retval = 1,
पूर्ण,
अणु
	"runtime/jit: tail_call within bounds, different maps, second branch",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_0, 14),
	BPF_STX_MEM(BPF_B, BPF_REG_1, BPF_REG_0,
		    दुरत्व(काष्ठा __sk_buff, cb[0])),
	BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
		    दुरत्व(काष्ठा __sk_buff, cb[0])),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_0, 13, 4),
	BPF_MOV64_IMM(BPF_REG_3, 0),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_JMP_IMM(BPF_JA, 0, 0, 3),
	BPF_MOV64_IMM(BPF_REG_3, 0),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 5 पूर्ण,
	.fixup_prog2 = अणु 9 पूर्ण,
	.result_unpriv = REJECT,
	.errstr_unpriv = "tail_call abusing map_ptr",
	.result = ACCEPT,
	.retval = 42,
पूर्ण,
अणु
	"runtime/jit: tail_call out of bounds",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_3, 256),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 2),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 1 पूर्ण,
	.result = ACCEPT,
	.retval = 2,
पूर्ण,
अणु
	"runtime/jit: pass negative index to tail_call",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_3, -1),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 2),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 1 पूर्ण,
	.result = ACCEPT,
	.retval = 2,
पूर्ण,
अणु
	"runtime/jit: pass > 32bit index to tail_call",
	.insns = अणु
	BPF_LD_IMM64(BPF_REG_3, 0x100000000ULL),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_tail_call),
	BPF_MOV64_IMM(BPF_REG_0, 2),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_prog1 = अणु 2 पूर्ण,
	.result = ACCEPT,
	.retval = 42,
	/* Verअगरier reग_लिखो क्रम unpriv skips tail call here. */
	.retval_unpriv = 2,
पूर्ण,
