<शैली गुरु>
अणु
	"skb->sk: no NULL check",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_1, 0),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = REJECT,
	.errstr = "invalid mem access 'sock_common_or_null'",
पूर्ण,
अणु
	"skb->sk: sk->family [non fullsock field]",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_1, दुरत्व(काष्ठा bpf_sock, family)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"skb->sk: sk->type [fullsock field]",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_1, दुरत्व(काष्ठा bpf_sock, type)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = REJECT,
	.errstr = "invalid sock_common access",
पूर्ण,
अणु
	"bpf_sk_fullsock(skb->sk): no !skb->sk check",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = REJECT,
	.errstr = "type=sock_common_or_null expected=sock_common",
पूर्ण,
अणु
	"sk_fullsock(skb->sk): no NULL check on ret",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_sock, type)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = REJECT,
	.errstr = "invalid mem access 'sock_or_null'",
पूर्ण,
अणु
	"sk_fullsock(skb->sk): sk->type [fullsock field]",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_sock, type)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"sk_fullsock(skb->sk): sk->family [non fullsock field]",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_sock, family)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"sk_fullsock(skb->sk): sk->state [narrow load]",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_sock, state)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"sk_fullsock(skb->sk): sk->dst_port [narrow load]",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_H, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_sock, dst_port)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"sk_fullsock(skb->sk): sk->dst_port [load 2nd byte]",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_sock, dst_port) + 1),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = REJECT,
	.errstr = "invalid sock access",
पूर्ण,
अणु
	"sk_fullsock(skb->sk): sk->dst_ip6 [load 2nd byte]",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_sock, dst_ip6[0]) + 1),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"sk_fullsock(skb->sk): sk->type [narrow load]",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_sock, type)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"sk_fullsock(skb->sk): sk->protocol [narrow load]",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_sock, protocol)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"sk_fullsock(skb->sk): beyond last field",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_0, दुरत्वend(काष्ठा bpf_sock, rx_queue_mapping)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = REJECT,
	.errstr = "invalid sock access",
पूर्ण,
अणु
	"bpf_tcp_sock(skb->sk): no !skb->sk check",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_EMIT_CALL(BPF_FUNC_tcp_sock),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = REJECT,
	.errstr = "type=sock_common_or_null expected=sock_common",
पूर्ण,
अणु
	"bpf_tcp_sock(skb->sk): no NULL check on ret",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_tcp_sock),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_tcp_sock, snd_cwnd)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = REJECT,
	.errstr = "invalid mem access 'tcp_sock_or_null'",
पूर्ण,
अणु
	"bpf_tcp_sock(skb->sk): tp->snd_cwnd",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_tcp_sock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_tcp_sock, snd_cwnd)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"bpf_tcp_sock(skb->sk): tp->bytes_acked",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_tcp_sock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_tcp_sock, bytes_acked)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"bpf_tcp_sock(skb->sk): beyond last field",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_tcp_sock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_0, दुरत्वend(काष्ठा bpf_tcp_sock, bytes_acked)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = REJECT,
	.errstr = "invalid tcp_sock access",
पूर्ण,
अणु
	"bpf_tcp_sock(bpf_sk_fullsock(skb->sk)): tp->snd_cwnd",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_0),
	BPF_EMIT_CALL(BPF_FUNC_tcp_sock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_tcp_sock, snd_cwnd)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_CGROUP_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"bpf_sk_release(skb->sk)",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JEQ, BPF_REG_1, 0, 1),
	BPF_EMIT_CALL(BPF_FUNC_sk_release),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.result = REJECT,
	.errstr = "reference has not been acquired before",
पूर्ण,
अणु
	"bpf_sk_release(bpf_sk_fullsock(skb->sk))",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_0),
	BPF_EMIT_CALL(BPF_FUNC_sk_release),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.result = REJECT,
	.errstr = "reference has not been acquired before",
पूर्ण,
अणु
	"bpf_sk_release(bpf_tcp_sock(skb->sk))",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_tcp_sock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_0),
	BPF_EMIT_CALL(BPF_FUNC_sk_release),
	BPF_MOV64_IMM(BPF_REG_0, 1),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.result = REJECT,
	.errstr = "reference has not been acquired before",
पूर्ण,
अणु
	"sk_storage_get(map, skb->sk, NULL, 0): value == NULL",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_MOV64_IMM(BPF_REG_4, 0),
	BPF_MOV64_IMM(BPF_REG_3, 0),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_0),
	BPF_LD_MAP_FD(BPF_REG_1, 0),
	BPF_EMIT_CALL(BPF_FUNC_sk_storage_get),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_sk_storage_map = अणु 11 पूर्ण,
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.result = ACCEPT,
पूर्ण,
अणु
	"sk_storage_get(map, skb->sk, 1, 1): value == 1",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_MOV64_IMM(BPF_REG_4, 1),
	BPF_MOV64_IMM(BPF_REG_3, 1),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_0),
	BPF_LD_MAP_FD(BPF_REG_1, 0),
	BPF_EMIT_CALL(BPF_FUNC_sk_storage_get),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_sk_storage_map = अणु 11 पूर्ण,
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.result = REJECT,
	.errstr = "R3 type=inv expected=fp",
पूर्ण,
अणु
	"sk_storage_get(map, skb->sk, &stack_value, 1): stack_value",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_2, 0),
	BPF_STX_MEM(BPF_DW, BPF_REG_10, BPF_REG_2, -8),
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_MOV64_IMM(BPF_REG_4, 1),
	BPF_MOV64_REG(BPF_REG_3, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_3, -8),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_0),
	BPF_LD_MAP_FD(BPF_REG_1, 0),
	BPF_EMIT_CALL(BPF_FUNC_sk_storage_get),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_sk_storage_map = अणु 14 पूर्ण,
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.result = ACCEPT,
पूर्ण,
अणु
	"sk_storage_get(map, skb->sk, &stack_value, 1): partially init stack_value",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_2, 0),
	BPF_STX_MEM(BPF_W, BPF_REG_10, BPF_REG_2, -8),
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_EMIT_CALL(BPF_FUNC_sk_fullsock),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_MOV64_IMM(BPF_REG_4, 1),
	BPF_MOV64_REG(BPF_REG_3, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_3, -8),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_0),
	BPF_LD_MAP_FD(BPF_REG_1, 0),
	BPF_EMIT_CALL(BPF_FUNC_sk_storage_get),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_sk_storage_map = अणु 14 पूर्ण,
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.result = REJECT,
	.errstr = "invalid indirect read from stack",
पूर्ण,
अणु
	"bpf_map_lookup_elem(smap, &key)",
	.insns = अणु
	BPF_ST_MEM(BPF_W, BPF_REG_10, -4, 0),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_2, -4),
	BPF_LD_MAP_FD(BPF_REG_1, 0),
	BPF_EMIT_CALL(BPF_FUNC_map_lookup_elem),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_sk_storage_map = अणु 3 पूर्ण,
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.result = REJECT,
	.errstr = "cannot pass map_type 24 into func bpf_map_lookup_elem",
पूर्ण,
अणु
	"bpf_map_lookup_elem(xskmap, &key); xs->queue_id",
	.insns = अणु
	BPF_ST_MEM(BPF_W, BPF_REG_10, -8, 0),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_2, -8),
	BPF_LD_MAP_FD(BPF_REG_1, 0),
	BPF_EMIT_CALL(BPF_FUNC_map_lookup_elem),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_xdp_sock, queue_id)),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_map_xskmap = अणु 3 पूर्ण,
	.prog_type = BPF_PROG_TYPE_XDP,
	.result = ACCEPT,
पूर्ण,
अणु
	"bpf_map_lookup_elem(sockmap, &key)",
	.insns = अणु
	BPF_ST_MEM(BPF_W, BPF_REG_10, -4, 0),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_2, -4),
	BPF_LD_MAP_FD(BPF_REG_1, 0),
	BPF_EMIT_CALL(BPF_FUNC_map_lookup_elem),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_map_sockmap = अणु 3 पूर्ण,
	.prog_type = BPF_PROG_TYPE_SK_SKB,
	.result = REJECT,
	.errstr = "Unreleased reference id=2 alloc_insn=5",
पूर्ण,
अणु
	"bpf_map_lookup_elem(sockhash, &key)",
	.insns = अणु
	BPF_ST_MEM(BPF_W, BPF_REG_10, -4, 0),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_2, -4),
	BPF_LD_MAP_FD(BPF_REG_1, 0),
	BPF_EMIT_CALL(BPF_FUNC_map_lookup_elem),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_map_sockhash = अणु 3 पूर्ण,
	.prog_type = BPF_PROG_TYPE_SK_SKB,
	.result = REJECT,
	.errstr = "Unreleased reference id=2 alloc_insn=5",
पूर्ण,
अणु
	"bpf_map_lookup_elem(sockmap, &key); sk->type [fullsock field]; bpf_sk_release(sk)",
	.insns = अणु
	BPF_ST_MEM(BPF_W, BPF_REG_10, -4, 0),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_2, -4),
	BPF_LD_MAP_FD(BPF_REG_1, 0),
	BPF_EMIT_CALL(BPF_FUNC_map_lookup_elem),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_0),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_sock, type)),
	BPF_EMIT_CALL(BPF_FUNC_sk_release),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_map_sockmap = अणु 3 पूर्ण,
	.prog_type = BPF_PROG_TYPE_SK_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"bpf_map_lookup_elem(sockhash, &key); sk->type [fullsock field]; bpf_sk_release(sk)",
	.insns = अणु
	BPF_ST_MEM(BPF_W, BPF_REG_10, -4, 0),
	BPF_MOV64_REG(BPF_REG_2, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_2, -4),
	BPF_LD_MAP_FD(BPF_REG_1, 0),
	BPF_EMIT_CALL(BPF_FUNC_map_lookup_elem),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
	BPF_EXIT_INSN(),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_0),
	BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_0, दुरत्व(काष्ठा bpf_sock, type)),
	BPF_EMIT_CALL(BPF_FUNC_sk_release),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_map_sockhash = अणु 3 पूर्ण,
	.prog_type = BPF_PROG_TYPE_SK_SKB,
	.result = ACCEPT,
पूर्ण,
अणु
	"bpf_sk_select_reuseport(ctx, reuseport_array, &key, flags)",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_4, 0),
	BPF_ST_MEM(BPF_W, BPF_REG_10, -4, 0),
	BPF_MOV64_REG(BPF_REG_3, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_3, -4),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_EMIT_CALL(BPF_FUNC_sk_select_reuseport),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_map_reuseport_array = अणु 4 पूर्ण,
	.prog_type = BPF_PROG_TYPE_SK_REUSEPORT,
	.result = ACCEPT,
पूर्ण,
अणु
	"bpf_sk_select_reuseport(ctx, sockmap, &key, flags)",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_4, 0),
	BPF_ST_MEM(BPF_W, BPF_REG_10, -4, 0),
	BPF_MOV64_REG(BPF_REG_3, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_3, -4),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_EMIT_CALL(BPF_FUNC_sk_select_reuseport),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_map_sockmap = अणु 4 पूर्ण,
	.prog_type = BPF_PROG_TYPE_SK_REUSEPORT,
	.result = ACCEPT,
पूर्ण,
अणु
	"bpf_sk_select_reuseport(ctx, sockhash, &key, flags)",
	.insns = अणु
	BPF_MOV64_IMM(BPF_REG_4, 0),
	BPF_ST_MEM(BPF_W, BPF_REG_10, -4, 0),
	BPF_MOV64_REG(BPF_REG_3, BPF_REG_10),
	BPF_ALU64_IMM(BPF_ADD, BPF_REG_3, -4),
	BPF_LD_MAP_FD(BPF_REG_2, 0),
	BPF_EMIT_CALL(BPF_FUNC_sk_select_reuseport),
	BPF_EXIT_INSN(),
	पूर्ण,
	.fixup_map_sockmap = अणु 4 पूर्ण,
	.prog_type = BPF_PROG_TYPE_SK_REUSEPORT,
	.result = ACCEPT,
पूर्ण,
अणु
	"mark null check on return value of bpf_skc_to helpers",
	.insns = अणु
	BPF_LDX_MEM(BPF_DW, BPF_REG_1, BPF_REG_1, दुरत्व(काष्ठा __sk_buff, sk)),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_1, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_MOV64_REG(BPF_REG_6, BPF_REG_1),
	BPF_EMIT_CALL(BPF_FUNC_skc_to_tcp_sock),
	BPF_MOV64_REG(BPF_REG_7, BPF_REG_0),
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_6),
	BPF_EMIT_CALL(BPF_FUNC_skc_to_tcp_request_sock),
	BPF_MOV64_REG(BPF_REG_8, BPF_REG_0),
	BPF_JMP_IMM(BPF_JNE, BPF_REG_8, 0, 2),
	BPF_MOV64_IMM(BPF_REG_0, 0),
	BPF_EXIT_INSN(),
	BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_7, 0),
	BPF_EXIT_INSN(),
	पूर्ण,
	.prog_type = BPF_PROG_TYPE_SCHED_CLS,
	.result = REJECT,
	.errstr = "invalid mem access",
	.result_unpriv = REJECT,
	.errstr_unpriv = "unknown func",
पूर्ण,
