<शैली गुरु>
/*
 * Mbus-L to Mbus Bridge Registers
 *
 * This file is licensed under the terms of the GNU General Public
 * License version 2.  This program is licensed "as is" without any
 * warranty of any kind, whether express or implied.
 */

#अगर_अघोषित __ASM_ARCH_BRIDGE_REGS_H
#घोषणा __ASM_ARCH_BRIDGE_REGS_H

#समावेश "dove.h"

#घोषणा CPU_CONFIG		(BRIDGE_VIRT_BASE + 0x0000)

#घोषणा CPU_CONTROL		(BRIDGE_VIRT_BASE + 0x0104)
#घोषणा  CPU_CTRL_PCIE0_LINK	0x00000001
#घोषणा  CPU_RESET		0x00000002
#घोषणा  CPU_CTRL_PCIE1_LINK	0x00000008

#घोषणा RSTOUTn_MASK		(BRIDGE_VIRT_BASE + 0x0108)
#घोषणा RSTOUTn_MASK_PHYS	(BRIDGE_PHYS_BASE + 0x0108)
#घोषणा  SOFT_RESET_OUT_EN	0x00000004

#घोषणा SYSTEM_SOFT_RESET	(BRIDGE_VIRT_BASE + 0x010c)
#घोषणा  SOFT_RESET		0x00000001

#घोषणा BRIDGE_CAUSE		(BRIDGE_VIRT_BASE + 0x0110)
#घोषणा  BRIDGE_INT_TIMER1_CLR	(~0x0004)

#घोषणा IRQ_VIRT_BASE		(BRIDGE_VIRT_BASE + 0x0200)
#घोषणा IRQ_CAUSE_LOW_OFF	0x0000
#घोषणा IRQ_MASK_LOW_OFF	0x0004
#घोषणा FIQ_MASK_LOW_OFF	0x0008
#घोषणा ENDPOINT_MASK_LOW_OFF	0x000c
#घोषणा IRQ_CAUSE_HIGH_OFF	0x0010
#घोषणा IRQ_MASK_HIGH_OFF	0x0014
#घोषणा FIQ_MASK_HIGH_OFF	0x0018
#घोषणा ENDPOINT_MASK_HIGH_OFF	0x001c
#घोषणा PCIE_INTERRUPT_MASK_OFF	0x0020

#घोषणा IRQ_MASK_LOW		(IRQ_VIRT_BASE + IRQ_MASK_LOW_OFF)
#घोषणा FIQ_MASK_LOW		(IRQ_VIRT_BASE + FIQ_MASK_LOW_OFF)
#घोषणा ENDPOINT_MASK_LOW	(IRQ_VIRT_BASE + ENDPOINT_MASK_LOW_OFF)
#घोषणा IRQ_MASK_HIGH		(IRQ_VIRT_BASE + IRQ_MASK_HIGH_OFF)
#घोषणा FIQ_MASK_HIGH		(IRQ_VIRT_BASE + FIQ_MASK_HIGH_OFF)
#घोषणा ENDPOINT_MASK_HIGH	(IRQ_VIRT_BASE + ENDPOINT_MASK_HIGH_OFF)
#घोषणा PCIE_INTERRUPT_MASK	(IRQ_VIRT_BASE + PCIE_INTERRUPT_MASK_OFF)

#घोषणा POWER_MANAGEMENT	(BRIDGE_VIRT_BASE + 0x011c)

#घोषणा TIMER_VIRT_BASE		(BRIDGE_VIRT_BASE + 0x0300)
#घोषणा TIMER_PHYS_BASE         (BRIDGE_PHYS_BASE + 0x0300)

#पूर्ण_अगर
