<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0+ */

#अगर_अघोषित _DT_BINDINGS_INTERRUPT_CONTROLLER_ASPEED_SCU_IC_H_
#घोषणा _DT_BINDINGS_INTERRUPT_CONTROLLER_ASPEED_SCU_IC_H_

#घोषणा ASPEED_SCU_IC_VGA_CURSOR_CHANGE			0
#घोषणा ASPEED_SCU_IC_VGA_SCRATCH_REG_CHANGE		1

#घोषणा ASPEED_AST2500_SCU_IC_PCIE_RESET_LO_TO_HI	2
#घोषणा ASPEED_AST2500_SCU_IC_PCIE_RESET_HI_TO_LO	3
#घोषणा ASPEED_AST2500_SCU_IC_LPC_RESET_LO_TO_HI	4
#घोषणा ASPEED_AST2500_SCU_IC_LPC_RESET_HI_TO_LO	5
#घोषणा ASPEED_AST2500_SCU_IC_ISSUE_MSI			6

#घोषणा ASPEED_AST2600_SCU_IC0_PCIE_PERST_LO_TO_HI	2
#घोषणा ASPEED_AST2600_SCU_IC0_PCIE_PERST_HI_TO_LO	3
#घोषणा ASPEED_AST2600_SCU_IC0_PCIE_RCRST_LO_TO_HI	4
#घोषणा ASPEED_AST2600_SCU_IC0_PCIE_RCRST_HI_TO_LO	5

#घोषणा ASPEED_AST2600_SCU_IC1_LPC_RESET_LO_TO_HI	0
#घोषणा ASPEED_AST2600_SCU_IC1_LPC_RESET_HI_TO_LO	1

#पूर्ण_अगर /* _DT_BINDINGS_INTERRUPT_CONTROLLER_ASPEED_SCU_IC_H_ */
