<शैली गुरु>
/* SPDX-License-Identअगरier: (GPL-2.0 OR MIT) */
/*
 * Driver क्रम Microsemi VSC85xx PHYs
 *
 * Copyright (c) 2020 Microsemi Corporation
 */

#अगर_अघोषित _MSCC_PHY_LINE_MAC_H_
#घोषणा _MSCC_PHY_LINE_MAC_H_

#घोषणा MSCC_MAC_CFG_ENA_CFG					0x00
#घोषणा MSCC_MAC_CFG_MODE_CFG					0x01
#घोषणा MSCC_MAC_CFG_MAXLEN_CFG					0x02
#घोषणा MSCC_MAC_CFG_NUM_TAGS_CFG				0x03
#घोषणा MSCC_MAC_CFG_TAGS_CFG					0x04
#घोषणा MSCC_MAC_CFG_ADV_CHK_CFG				0x07
#घोषणा MSCC_MAC_CFG_LFS_CFG					0x08
#घोषणा MSCC_MAC_CFG_LB_CFG					0x09
#घोषणा MSCC_MAC_CFG_PKTINF_CFG					0x0a
#घोषणा MSCC_MAC_PAUSE_CFG_TX_FRAME_CTRL			0x0b
#घोषणा MSCC_MAC_PAUSE_CFG_TX_FRAME_CTRL_2			0x0c
#घोषणा MSCC_MAC_PAUSE_CFG_RX_FRAME_CTRL			0x0d
#घोषणा MSCC_MAC_PAUSE_CFG_STATE				0x0e
#घोषणा MSCC_MAC_PAUSE_CFG_MAC_ADDRESS_LSB			0x0f
#घोषणा MSCC_MAC_PAUSE_CFG_MAC_ADDRESS_MSB			0x10
#घोषणा MSCC_MAC_STATUS_RX_LANE_STICKY_0			0x11
#घोषणा MSCC_MAC_STATUS_RX_LANE_STICKY_1			0x12
#घोषणा MSCC_MAC_STATUS_TX_MONITOR_STICKY			0x13
#घोषणा MSCC_MAC_STATUS_TX_MONITOR_STICKY_MASK			0x14
#घोषणा MSCC_MAC_STATUS_STICKY					0x15
#घोषणा MSCC_MAC_STATUS_STICKY_MASK				0x16
#घोषणा MSCC_MAC_STATS_32BIT_RX_HIH_CKSM_ERR_CNT		0x17
#घोषणा MSCC_MAC_STATS_32BIT_RX_XGMII_PROT_ERR_CNT		0x18
#घोषणा MSCC_MAC_STATS_32BIT_RX_SYMBOL_ERR_CNT			0x19
#घोषणा MSCC_MAC_STATS_32BIT_RX_PAUSE_CNT			0x1a
#घोषणा MSCC_MAC_STATS_32BIT_RX_UNSUP_OPCODE_CNT		0x1b
#घोषणा MSCC_MAC_STATS_32BIT_RX_UC_CNT				0x1c
#घोषणा MSCC_MAC_STATS_32BIT_RX_MC_CNT				0x1d
#घोषणा MSCC_MAC_STATS_32BIT_RX_BC_CNT				0x1e
#घोषणा MSCC_MAC_STATS_32BIT_RX_CRC_ERR_CNT			0x1f
#घोषणा MSCC_MAC_STATS_32BIT_RX_UNDERSIZE_CNT			0x20
#घोषणा MSCC_MAC_STATS_32BIT_RX_FRAGMENTS_CNT			0x21
#घोषणा MSCC_MAC_STATS_32BIT_RX_IN_RANGE_LEN_ERR_CNT		0x22
#घोषणा MSCC_MAC_STATS_32BIT_RX_OUT_OF_RANGE_LEN_ERR_CNT	0x23
#घोषणा MSCC_MAC_STATS_32BIT_RX_OVERSIZE_CNT			0x24
#घोषणा MSCC_MAC_STATS_32BIT_RX_JABBERS_CNT			0x25
#घोषणा MSCC_MAC_STATS_32BIT_RX_SIZE64_CNT			0x26
#घोषणा MSCC_MAC_STATS_32BIT_RX_SIZE65TO127_CNT			0x27
#घोषणा MSCC_MAC_STATS_32BIT_RX_SIZE128TO255_CNT		0x28
#घोषणा MSCC_MAC_STATS_32BIT_RX_SIZE256TO511_CNT		0x29
#घोषणा MSCC_MAC_STATS_32BIT_RX_SIZE512TO1023_CNT		0x2a
#घोषणा MSCC_MAC_STATS_32BIT_RX_SIZE1024TO1518_CNT		0x2b
#घोषणा MSCC_MAC_STATS_32BIT_RX_SIZE1519TOMAX_CNT		0x2c
#घोषणा MSCC_MAC_STATS_32BIT_RX_IPG_SHRINK_CNT			0x2d
#घोषणा MSCC_MAC_STATS_32BIT_TX_PAUSE_CNT			0x2e
#घोषणा MSCC_MAC_STATS_32BIT_TX_UC_CNT				0x2f
#घोषणा MSCC_MAC_STATS_32BIT_TX_MC_CNT				0x30
#घोषणा MSCC_MAC_STATS_32BIT_TX_BC_CNT				0x31
#घोषणा MSCC_MAC_STATS_32BIT_TX_SIZE64_CNT			0x32
#घोषणा MSCC_MAC_STATS_32BIT_TX_SIZE65TO127_CNT			0x33
#घोषणा MSCC_MAC_STATS_32BIT_TX_SIZE128TO255_CNT		0x34
#घोषणा MSCC_MAC_STATS_32BIT_TX_SIZE256TO511_CNT		0x35
#घोषणा MSCC_MAC_STATS_32BIT_TX_SIZE512TO1023_CNT		0x36
#घोषणा MSCC_MAC_STATS_32BIT_TX_SIZE1024TO1518_CNT		0x37
#घोषणा MSCC_MAC_STATS_32BIT_TX_SIZE1519TOMAX_CNT		0x38
#घोषणा MSCC_MAC_STATS_40BIT_RX_BAD_BYTES_CNT			0x39
#घोषणा MSCC_MAC_STATS_40BIT_RX_BAD_BYTES_MSB_CNT		0x3a
#घोषणा MSCC_MAC_STATS_40BIT_RX_OK_BYTES_CNT			0x3b
#घोषणा MSCC_MAC_STATS_40BIT_RX_OK_BYTES_MSB_CNT		0x3c
#घोषणा MSCC_MAC_STATS_40BIT_RX_IN_BYTES_CNT			0x3d
#घोषणा MSCC_MAC_STATS_40BIT_RX_IN_BYTES_MSB_CNT		0x3e
#घोषणा MSCC_MAC_STATS_40BIT_TX_OK_BYTES_CNT			0x3f
#घोषणा MSCC_MAC_STATS_40BIT_TX_OK_BYTES_MSB_CNT		0x40
#घोषणा MSCC_MAC_STATS_40BIT_TX_OUT_BYTES_CNT			0x41
#घोषणा MSCC_MAC_STATS_40BIT_TX_OUT_BYTES_MSB_CNT		0x42

#घोषणा MSCC_MAC_CFG_ENA_CFG_RX_CLK_ENA				BIT(0)
#घोषणा MSCC_MAC_CFG_ENA_CFG_TX_CLK_ENA				BIT(4)
#घोषणा MSCC_MAC_CFG_ENA_CFG_RX_SW_RST				BIT(8)
#घोषणा MSCC_MAC_CFG_ENA_CFG_TX_SW_RST				BIT(12)
#घोषणा MSCC_MAC_CFG_ENA_CFG_RX_ENA				BIT(16)
#घोषणा MSCC_MAC_CFG_ENA_CFG_TX_ENA				BIT(20)

#घोषणा MSCC_MAC_CFG_MODE_CFG_FORCE_CW_UPDATE_INTERVAL(x)	((x) << 20)
#घोषणा MSCC_MAC_CFG_MODE_CFG_FORCE_CW_UPDATE_INTERVAL_M	GENMASK(29, 20)
#घोषणा MSCC_MAC_CFG_MODE_CFG_FORCE_CW_UPDATE			BIT(16)
#घोषणा MSCC_MAC_CFG_MODE_CFG_TUNNEL_PAUSE_FRAMES		BIT(14)
#घोषणा MSCC_MAC_CFG_MODE_CFG_MAC_PREAMBLE_CFG(x)		((x) << 10)
#घोषणा MSCC_MAC_CFG_MODE_CFG_MAC_PREAMBLE_CFG_M		GENMASK(12, 10)
#घोषणा MSCC_MAC_CFG_MODE_CFG_MAC_IPG_CFG			BIT(6)
#घोषणा MSCC_MAC_CFG_MODE_CFG_XGMII_GEN_MODE_ENA		BIT(4)
#घोषणा MSCC_MAC_CFG_MODE_CFG_HIH_CRC_CHECK			BIT(2)
#घोषणा MSCC_MAC_CFG_MODE_CFG_UNDERSIZED_FRAME_DROP_DIS		BIT(1)
#घोषणा MSCC_MAC_CFG_MODE_CFG_DISABLE_DIC			BIT(0)

#घोषणा MSCC_MAC_CFG_MAXLEN_CFG_MAX_LEN_TAG_CHK			BIT(16)
#घोषणा MSCC_MAC_CFG_MAXLEN_CFG_MAX_LEN(x)			(x)
#घोषणा MSCC_MAC_CFG_MAXLEN_CFG_MAX_LEN_M			GENMASK(15, 0)

#घोषणा MSCC_MAC_CFG_TAGS_CFG_RSZ				0x4
#घोषणा MSCC_MAC_CFG_TAGS_CFG_TAG_ID(x)				((x) << 16)
#घोषणा MSCC_MAC_CFG_TAGS_CFG_TAG_ID_M				GENMASK(31, 16)
#घोषणा MSCC_MAC_CFG_TAGS_CFG_TAG_ENA				BIT(4)

#घोषणा MSCC_MAC_CFG_ADV_CHK_CFG_EXT_EOP_CHK_ENA		BIT(24)
#घोषणा MSCC_MAC_CFG_ADV_CHK_CFG_EXT_SOP_CHK_ENA		BIT(20)
#घोषणा MSCC_MAC_CFG_ADV_CHK_CFG_SFD_CHK_ENA			BIT(16)
#घोषणा MSCC_MAC_CFG_ADV_CHK_CFG_PRM_SHK_CHK_DIS		BIT(12)
#घोषणा MSCC_MAC_CFG_ADV_CHK_CFG_PRM_CHK_ENA			BIT(8)
#घोषणा MSCC_MAC_CFG_ADV_CHK_CFG_OOR_ERR_ENA			BIT(4)
#घोषणा MSCC_MAC_CFG_ADV_CHK_CFG_INR_ERR_ENA			BIT(0)

#घोषणा MSCC_MAC_CFG_LFS_CFG_LFS_INH_TX				BIT(8)
#घोषणा MSCC_MAC_CFG_LFS_CFG_LFS_DIS_TX				BIT(4)
#घोषणा MSCC_MAC_CFG_LFS_CFG_LFS_UNIसूची_ENA			BIT(3)
#घोषणा MSCC_MAC_CFG_LFS_CFG_USE_LEADING_EDGE_DETECT		BIT(2)
#घोषणा MSCC_MAC_CFG_LFS_CFG_SPURIOUS_Q_DIS			BIT(1)
#घोषणा MSCC_MAC_CFG_LFS_CFG_LFS_MODE_ENA			BIT(0)

#घोषणा MSCC_MAC_CFG_LB_CFG_XGMII_HOST_LB_ENA			BIT(4)
#घोषणा MSCC_MAC_CFG_LB_CFG_XGMII_PHY_LB_ENA			BIT(0)

#घोषणा MSCC_MAC_CFG_PKTINF_CFG_STRIP_FCS_ENA			BIT(0)
#घोषणा MSCC_MAC_CFG_PKTINF_CFG_INSERT_FCS_ENA			BIT(4)
#घोषणा MSCC_MAC_CFG_PKTINF_CFG_STRIP_PREAMBLE_ENA		BIT(8)
#घोषणा MSCC_MAC_CFG_PKTINF_CFG_INSERT_PREAMBLE_ENA		BIT(12)
#घोषणा MSCC_MAC_CFG_PKTINF_CFG_LPI_RELAY_ENA			BIT(16)
#घोषणा MSCC_MAC_CFG_PKTINF_CFG_LF_RELAY_ENA			BIT(20)
#घोषणा MSCC_MAC_CFG_PKTINF_CFG_RF_RELAY_ENA			BIT(24)
#घोषणा MSCC_MAC_CFG_PKTINF_CFG_ENABLE_TX_PADDING		BIT(25)
#घोषणा MSCC_MAC_CFG_PKTINF_CFG_ENABLE_RX_PADDING		BIT(26)
#घोषणा MSCC_MAC_CFG_PKTINF_CFG_ENABLE_4BYTE_PREAMBLE		BIT(27)
#घोषणा MSCC_MAC_CFG_PKTINF_CFG_MACSEC_BYPASS_NUM_PTP_STALL_CLKS(x)	((x) << 28)
#घोषणा MSCC_MAC_CFG_PKTINF_CFG_MACSEC_BYPASS_NUM_PTP_STALL_CLKS_M	GENMASK(30, 28)

#घोषणा MSCC_MAC_PAUSE_CFG_TX_FRAME_CTRL_PAUSE_VALUE(x)		((x) << 16)
#घोषणा MSCC_MAC_PAUSE_CFG_TX_FRAME_CTRL_PAUSE_VALUE_M		GENMASK(31, 16)
#घोषणा MSCC_MAC_PAUSE_CFG_TX_FRAME_CTRL_WAIT_FOR_LPI_LOW	BIT(12)
#घोषणा MSCC_MAC_PAUSE_CFG_TX_FRAME_CTRL_USE_PAUSE_STALL_ENA	BIT(8)
#घोषणा MSCC_MAC_PAUSE_CFG_TX_FRAME_CTRL_PAUSE_REPL_MODE	BIT(4)
#घोषणा MSCC_MAC_PAUSE_CFG_TX_FRAME_CTRL_PAUSE_FRC_FRAME	BIT(2)
#घोषणा MSCC_MAC_PAUSE_CFG_TX_FRAME_CTRL_PAUSE_MODE(x)		(x)
#घोषणा MSCC_MAC_PAUSE_CFG_TX_FRAME_CTRL_PAUSE_MODE_M		GENMASK(1, 0)

#घोषणा MSCC_MAC_PAUSE_CFG_RX_FRAME_CTRL_EARLY_PAUSE_DETECT_ENA	BIT(16)
#घोषणा MSCC_MAC_PAUSE_CFG_RX_FRAME_CTRL_PRE_CRC_MODE		BIT(20)
#घोषणा MSCC_MAC_PAUSE_CFG_RX_FRAME_CTRL_PAUSE_TIMER_ENA	BIT(12)
#घोषणा MSCC_MAC_PAUSE_CFG_RX_FRAME_CTRL_PAUSE_REACT_ENA	BIT(8)
#घोषणा MSCC_MAC_PAUSE_CFG_RX_FRAME_CTRL_PAUSE_FRAME_DROP_ENA	BIT(4)
#घोषणा MSCC_MAC_PAUSE_CFG_RX_FRAME_CTRL_PAUSE_MODE		BIT(0)

#घोषणा MSCC_MAC_PAUSE_CFG_STATE_PAUSE_STATE			BIT(0)
#घोषणा MSCC_MAC_PAUSE_CFG_STATE_MAC_TX_PAUSE_GEN		BIT(4)

#घोषणा MSCC_PROC_IP_1588_TOP_CFG_STAT_MODE_CTL			0x2
#घोषणा MSCC_PROC_IP_1588_TOP_CFG_STAT_MODE_CTL_PROTOCOL_MODE(x)	(x)
#घोषणा MSCC_PROC_IP_1588_TOP_CFG_STAT_MODE_CTL_PROTOCOL_MODE_M	GENMASK(2, 0)

#पूर्ण_अगर /* _MSCC_PHY_LINE_MAC_H_ */
