<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
#अगर_अघोषित __DT_BINDINGS_Q6_ASM_H__
#घोषणा __DT_BINDINGS_Q6_ASM_H__

#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA1	0
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA2	1
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA3	2
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA4	3
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA5	4
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA6	5
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA7	6
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA8	7
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA9	8
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA10	9
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA11	10
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA12	11
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA13	12
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA14	13
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA15	14
#घोषणा	MSM_FRONTEND_DAI_MULTIMEDIA16	15

#घोषणा Q6ASM_DAI_TX_RX	0
#घोषणा Q6ASM_DAI_TX	1
#घोषणा Q6ASM_DAI_RX	2

#पूर्ण_अगर /* __DT_BINDINGS_Q6_ASM_H__ */
