<शैली गुरु>
/* SPDX-License-Identअगरier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Qualcomm SM8350 पूर्णांकerconnect IDs
 *
 * Copyright (c) 2019-2020, The Linux Foundation. All rights reserved.
 * Copyright (c) 2021, Linaro Limited
 */

#अगर_अघोषित __DT_BINDINGS_INTERCONNECT_QCOM_SM8350_H
#घोषणा __DT_BINDINGS_INTERCONNECT_QCOM_SM8350_H

#घोषणा MASTER_QSPI_0			0
#घोषणा MASTER_QUP_1			1
#घोषणा MASTER_A1NOC_CFG		2
#घोषणा MASTER_SDCC_4			3
#घोषणा MASTER_UFS_MEM			4
#घोषणा MASTER_USB3_0			5
#घोषणा MASTER_USB3_1			6
#घोषणा SLAVE_A1NOC_SNOC		7
#घोषणा SLAVE_SERVICE_A1NOC		8

#घोषणा MASTER_QDSS_BAM			0
#घोषणा MASTER_QUP_0			1
#घोषणा MASTER_QUP_2			2
#घोषणा MASTER_A2NOC_CFG		3
#घोषणा MASTER_CRYPTO			4
#घोषणा MASTER_IPA			5
#घोषणा MASTER_PCIE_0			6
#घोषणा MASTER_PCIE_1			7
#घोषणा MASTER_QDSS_ETR			8
#घोषणा MASTER_SDCC_2			9
#घोषणा MASTER_UFS_CARD			10
#घोषणा SLAVE_A2NOC_SNOC		11
#घोषणा SLAVE_ANOC_PCIE_GEM_NOC		12
#घोषणा SLAVE_SERVICE_A2NOC		13

#घोषणा MASTER_GEM_NOC_CNOC		0
#घोषणा MASTER_GEM_NOC_PCIE_SNOC	1
#घोषणा MASTER_QDSS_DAP			2
#घोषणा SLAVE_AHB2PHY_SOUTH		3
#घोषणा SLAVE_AHB2PHY_NORTH		4
#घोषणा SLAVE_AOSS			5
#घोषणा SLAVE_APPSS			6
#घोषणा SLAVE_CAMERA_CFG		7
#घोषणा SLAVE_CLK_CTL			8
#घोषणा SLAVE_CDSP_CFG			9
#घोषणा SLAVE_RBCPR_CX_CFG		10
#घोषणा SLAVE_RBCPR_MMCX_CFG		11
#घोषणा SLAVE_RBCPR_MX_CFG		12
#घोषणा SLAVE_CRYPTO_0_CFG		13
#घोषणा SLAVE_CX_RDPM			14
#घोषणा SLAVE_DCC_CFG			15
#घोषणा SLAVE_DISPLAY_CFG		16
#घोषणा SLAVE_GFX3D_CFG			17
#घोषणा SLAVE_HWKM			18
#घोषणा SLAVE_IMEM_CFG			19
#घोषणा SLAVE_IPA_CFG			20
#घोषणा SLAVE_IPC_ROUTER_CFG		21
#घोषणा SLAVE_LPASS			22
#घोषणा SLAVE_CNOC_MSS			23
#घोषणा SLAVE_MX_RDPM			24
#घोषणा SLAVE_PCIE_0_CFG		25
#घोषणा SLAVE_PCIE_1_CFG		26
#घोषणा SLAVE_PDM			27
#घोषणा SLAVE_PIMEM_CFG			28
#घोषणा SLAVE_PKA_WRAPPER_CFG		29
#घोषणा SLAVE_PMU_WRAPPER_CFG		30
#घोषणा SLAVE_QDSS_CFG			31
#घोषणा SLAVE_QSPI_0			32
#घोषणा SLAVE_QUP_0			33
#घोषणा SLAVE_QUP_1			34
#घोषणा SLAVE_QUP_2			35
#घोषणा SLAVE_SDCC_2			36
#घोषणा SLAVE_SDCC_4			37
#घोषणा SLAVE_SECURITY			38
#घोषणा SLAVE_SPSS_CFG			39
#घोषणा SLAVE_TCSR			40
#घोषणा SLAVE_TLMM			41
#घोषणा SLAVE_UFS_CARD_CFG		42
#घोषणा SLAVE_UFS_MEM_CFG		43
#घोषणा SLAVE_USB3_0			44
#घोषणा SLAVE_USB3_1			45
#घोषणा SLAVE_VENUS_CFG			46
#घोषणा SLAVE_VSENSE_CTRL_CFG		47
#घोषणा SLAVE_A1NOC_CFG			48
#घोषणा SLAVE_A2NOC_CFG			49
#घोषणा SLAVE_DDRSS_CFG			50
#घोषणा SLAVE_CNOC_MNOC_CFG		51
#घोषणा SLAVE_SNOC_CFG			52
#घोषणा SLAVE_BOOT_IMEM			53
#घोषणा SLAVE_IMEM			54
#घोषणा SLAVE_PIMEM			55
#घोषणा SLAVE_SERVICE_CNOC		56
#घोषणा SLAVE_PCIE_0			57
#घोषणा SLAVE_PCIE_1			58
#घोषणा SLAVE_QDSS_STM			59
#घोषणा SLAVE_TCU			60

#घोषणा MASTER_CNOC_DC_NOC		0
#घोषणा SLAVE_LLCC_CFG			1
#घोषणा SLAVE_GEM_NOC_CFG		2

#घोषणा MASTER_GPU_TCU			0
#घोषणा MASTER_SYS_TCU			1
#घोषणा MASTER_APPSS_PROC		2
#घोषणा MASTER_COMPUTE_NOC		3
#घोषणा MASTER_GEM_NOC_CFG		4
#घोषणा MASTER_GFX3D			5
#घोषणा MASTER_MNOC_HF_MEM_NOC		6
#घोषणा MASTER_MNOC_SF_MEM_NOC		7
#घोषणा MASTER_ANOC_PCIE_GEM_NOC	8
#घोषणा MASTER_SNOC_GC_MEM_NOC		9
#घोषणा MASTER_SNOC_SF_MEM_NOC		10
#घोषणा SLAVE_MSS_PROC_MS_MPU_CFG	11
#घोषणा SLAVE_MCDMA_MS_MPU_CFG		12
#घोषणा SLAVE_GEM_NOC_CNOC		13
#घोषणा SLAVE_LLCC			14
#घोषणा SLAVE_MEM_NOC_PCIE_SNOC		15
#घोषणा SLAVE_SERVICE_GEM_NOC_1		16
#घोषणा SLAVE_SERVICE_GEM_NOC_2		17
#घोषणा SLAVE_SERVICE_GEM_NOC		18
#घोषणा MASTER_MNOC_HF_MEM_NOC_DISP	19
#घोषणा MASTER_MNOC_SF_MEM_NOC_DISP	20
#घोषणा SLAVE_LLCC_DISP			21

#घोषणा MASTER_CNOC_LPASS_AG_NOC	0
#घोषणा SLAVE_LPASS_CORE_CFG		1
#घोषणा SLAVE_LPASS_LPI_CFG		2
#घोषणा SLAVE_LPASS_MPU_CFG		3
#घोषणा SLAVE_LPASS_TOP_CFG		4
#घोषणा SLAVE_SERVICES_LPASS_AML_NOC	5
#घोषणा SLAVE_SERVICE_LPASS_AG_NOC	6

#घोषणा MASTER_LLCC			0
#घोषणा SLAVE_EBI1			1
#घोषणा MASTER_LLCC_DISP		2
#घोषणा SLAVE_EBI1_DISP			3

#घोषणा MASTER_CAMNOC_HF		0
#घोषणा MASTER_CAMNOC_ICP		1
#घोषणा MASTER_CAMNOC_SF		2
#घोषणा MASTER_CNOC_MNOC_CFG		3
#घोषणा MASTER_VIDEO_P0			4
#घोषणा MASTER_VIDEO_P1			5
#घोषणा MASTER_VIDEO_PROC		6
#घोषणा MASTER_MDP0			7
#घोषणा MASTER_MDP1			8
#घोषणा MASTER_ROTATOR			9
#घोषणा SLAVE_MNOC_HF_MEM_NOC		10
#घोषणा SLAVE_MNOC_SF_MEM_NOC		11
#घोषणा SLAVE_SERVICE_MNOC		12
#घोषणा MASTER_MDP0_DISP		13
#घोषणा MASTER_MDP1_DISP		14
#घोषणा MASTER_ROTATOR_DISP		15
#घोषणा SLAVE_MNOC_HF_MEM_NOC_DISP	16
#घोषणा SLAVE_MNOC_SF_MEM_NOC_DISP	17

#घोषणा MASTER_CDSP_NOC_CFG		0
#घोषणा MASTER_CDSP_PROC		1
#घोषणा SLAVE_CDSP_MEM_NOC		2
#घोषणा SLAVE_SERVICE_NSP_NOC		3

#घोषणा MASTER_A1NOC_SNOC		0
#घोषणा MASTER_A2NOC_SNOC		1
#घोषणा MASTER_SNOC_CFG			2
#घोषणा MASTER_PIMEM			3
#घोषणा MASTER_GIC			4
#घोषणा SLAVE_SNOC_GEM_NOC_GC		5
#घोषणा SLAVE_SNOC_GEM_NOC_SF		6
#घोषणा SLAVE_SERVICE_SNOC		7

#पूर्ण_अगर
