<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0 */
/*
 * Qualcomm SM8250 पूर्णांकerconnect IDs
 *
 * Copyright (c) 2020, The Linux Foundation. All rights reserved.
 */

#अगर_अघोषित __DT_BINDINGS_INTERCONNECT_QCOM_SM8250_H
#घोषणा __DT_BINDINGS_INTERCONNECT_QCOM_SM8250_H

#घोषणा MASTER_A1NOC_CFG		0
#घोषणा MASTER_QSPI_0			1
#घोषणा MASTER_QUP_1			2
#घोषणा MASTER_QUP_2			3
#घोषणा MASTER_TSIF			4
#घोषणा MASTER_PCIE_2			5
#घोषणा MASTER_SDCC_4			6
#घोषणा MASTER_UFS_MEM			7
#घोषणा MASTER_USB3			8
#घोषणा MASTER_USB3_1			9
#घोषणा A1NOC_SNOC_SLV			10
#घोषणा SLAVE_ANOC_PCIE_GEM_NOC_1	11
#घोषणा SLAVE_SERVICE_A1NOC		12

#घोषणा MASTER_A2NOC_CFG		0
#घोषणा MASTER_QDSS_BAM			1
#घोषणा MASTER_QUP_0			2
#घोषणा MASTER_CNOC_A2NOC		3
#घोषणा MASTER_CRYPTO_CORE_0		4
#घोषणा MASTER_IPA			5
#घोषणा MASTER_PCIE			6
#घोषणा MASTER_PCIE_1			7
#घोषणा MASTER_QDSS_ETR			8
#घोषणा MASTER_SDCC_2			9
#घोषणा MASTER_UFS_CARD			10
#घोषणा A2NOC_SNOC_SLV			11
#घोषणा SLAVE_ANOC_PCIE_GEM_NOC		12
#घोषणा SLAVE_SERVICE_A2NOC		13

#घोषणा MASTER_NPU			0
#घोषणा SLAVE_CDSP_MEM_NOC		1

#घोषणा SNOC_CNOC_MAS			0
#घोषणा MASTER_QDSS_DAP			1
#घोषणा SLAVE_A1NOC_CFG			2
#घोषणा SLAVE_A2NOC_CFG			3
#घोषणा SLAVE_AHB2PHY_SOUTH		4
#घोषणा SLAVE_AHB2PHY_NORTH		5
#घोषणा SLAVE_AOSS			6
#घोषणा SLAVE_CAMERA_CFG		7
#घोषणा SLAVE_CLK_CTL			8
#घोषणा SLAVE_CDSP_CFG			9
#घोषणा SLAVE_RBCPR_CX_CFG		10
#घोषणा SLAVE_RBCPR_MMCX_CFG		11
#घोषणा SLAVE_RBCPR_MX_CFG		12
#घोषणा SLAVE_CRYPTO_0_CFG		13
#घोषणा SLAVE_CX_RDPM			14
#घोषणा SLAVE_DCC_CFG			15
#घोषणा SLAVE_CNOC_DDRSS		16
#घोषणा SLAVE_DISPLAY_CFG		17
#घोषणा SLAVE_GRAPHICS_3D_CFG		18
#घोषणा SLAVE_IMEM_CFG			19
#घोषणा SLAVE_IPA_CFG			20
#घोषणा SLAVE_IPC_ROUTER_CFG		21
#घोषणा SLAVE_LPASS			22
#घोषणा SLAVE_CNOC_MNOC_CFG		23
#घोषणा SLAVE_NPU_CFG			24
#घोषणा SLAVE_PCIE_0_CFG		25
#घोषणा SLAVE_PCIE_1_CFG		26
#घोषणा SLAVE_PCIE_2_CFG		27
#घोषणा SLAVE_PDM			28
#घोषणा SLAVE_PIMEM_CFG			29
#घोषणा SLAVE_PRNG			30
#घोषणा SLAVE_QDSS_CFG			31
#घोषणा SLAVE_QSPI_0			32
#घोषणा SLAVE_QUP_0			33
#घोषणा SLAVE_QUP_1			34
#घोषणा SLAVE_QUP_2			35
#घोषणा SLAVE_SDCC_2			36
#घोषणा SLAVE_SDCC_4			37
#घोषणा SLAVE_SNOC_CFG			38
#घोषणा SLAVE_TCSR			39
#घोषणा SLAVE_TLMM_NORTH		40
#घोषणा SLAVE_TLMM_SOUTH		41
#घोषणा SLAVE_TLMM_WEST			42
#घोषणा SLAVE_TSIF			43
#घोषणा SLAVE_UFS_CARD_CFG		44
#घोषणा SLAVE_UFS_MEM_CFG		45
#घोषणा SLAVE_USB3			46
#घोषणा SLAVE_USB3_1			47
#घोषणा SLAVE_VENUS_CFG			48
#घोषणा SLAVE_VSENSE_CTRL_CFG		49
#घोषणा SLAVE_CNOC_A2NOC		50
#घोषणा SLAVE_SERVICE_CNOC		51

#घोषणा MASTER_CNOC_DC_NOC		0
#घोषणा SLAVE_LLCC_CFG			1
#घोषणा SLAVE_GEM_NOC_CFG		2

#घोषणा MASTER_GPU_TCU			0
#घोषणा MASTER_SYS_TCU			1
#घोषणा MASTER_AMPSS_M0			2
#घोषणा MASTER_GEM_NOC_CFG		3
#घोषणा MASTER_COMPUTE_NOC		4
#घोषणा MASTER_GRAPHICS_3D		5
#घोषणा MASTER_MNOC_HF_MEM_NOC		6
#घोषणा MASTER_MNOC_SF_MEM_NOC		7
#घोषणा MASTER_ANOC_PCIE_GEM_NOC	8
#घोषणा MASTER_SNOC_GC_MEM_NOC		9
#घोषणा MASTER_SNOC_SF_MEM_NOC		10
#घोषणा SLAVE_GEM_NOC_SNOC		11
#घोषणा SLAVE_LLCC			12
#घोषणा SLAVE_MEM_NOC_PCIE_SNOC		13
#घोषणा SLAVE_SERVICE_GEM_NOC_1		14
#घोषणा SLAVE_SERVICE_GEM_NOC_2		15
#घोषणा SLAVE_SERVICE_GEM_NOC		16

#घोषणा MASTER_IPA_CORE			0
#घोषणा SLAVE_IPA_CORE			1

#घोषणा MASTER_LLCC			0
#घोषणा SLAVE_EBI_CH0			1

#घोषणा MASTER_CNOC_MNOC_CFG		0
#घोषणा MASTER_CAMNOC_HF		1
#घोषणा MASTER_CAMNOC_ICP		2
#घोषणा MASTER_CAMNOC_SF		3
#घोषणा MASTER_VIDEO_P0			4
#घोषणा MASTER_VIDEO_P1			5
#घोषणा MASTER_VIDEO_PROC		6
#घोषणा MASTER_MDP_PORT0		7
#घोषणा MASTER_MDP_PORT1		8
#घोषणा MASTER_ROTATOR			9
#घोषणा SLAVE_MNOC_HF_MEM_NOC		10
#घोषणा SLAVE_MNOC_SF_MEM_NOC		11
#घोषणा SLAVE_SERVICE_MNOC		12

#घोषणा MASTER_NPU_SYS			0
#घोषणा MASTER_NPU_CDP			1
#घोषणा MASTER_NPU_NOC_CFG		2
#घोषणा SLAVE_NPU_CAL_DP0		3
#घोषणा SLAVE_NPU_CAL_DP1		4
#घोषणा SLAVE_NPU_CP			5
#घोषणा SLAVE_NPU_INT_DMA_BWMON_CFG	6
#घोषणा SLAVE_NPU_DPM			7
#घोषणा SLAVE_ISENSE_CFG		8
#घोषणा SLAVE_NPU_LLM_CFG		9
#घोषणा SLAVE_NPU_TCM			10
#घोषणा SLAVE_NPU_COMPUTE_NOC		11
#घोषणा SLAVE_SERVICE_NPU_NOC		12

#घोषणा MASTER_SNOC_CFG			0
#घोषणा A1NOC_SNOC_MAS			1
#घोषणा A2NOC_SNOC_MAS			2
#घोषणा MASTER_GEM_NOC_SNOC		3
#घोषणा MASTER_GEM_NOC_PCIE_SNOC	4
#घोषणा MASTER_PIMEM			5
#घोषणा MASTER_GIC			6
#घोषणा SLAVE_APPSS			7
#घोषणा SNOC_CNOC_SLV			8
#घोषणा SLAVE_SNOC_GEM_NOC_GC		9
#घोषणा SLAVE_SNOC_GEM_NOC_SF		10
#घोषणा SLAVE_OCIMEM			11
#घोषणा SLAVE_PIMEM			12
#घोषणा SLAVE_SERVICE_SNOC		13
#घोषणा SLAVE_PCIE_0			14
#घोषणा SLAVE_PCIE_1			15
#घोषणा SLAVE_PCIE_2			16
#घोषणा SLAVE_QDSS_STM			17
#घोषणा SLAVE_TCU			18

#पूर्ण_अगर
