<शैली गुरु>
/* SPDX-License-Identअगरier: (GPL-2.0 OR BSD-2-Clause) */
/*
 * Qualcomm msm8974 पूर्णांकerconnect IDs
 *
 * Copyright (c) 2019 Brian Masney <masneyb@onstation.org>
 */

#अगर_अघोषित __DT_BINDINGS_INTERCONNECT_QCOM_MSM8974_H
#घोषणा __DT_BINDINGS_INTERCONNECT_QCOM_MSM8974_H

#घोषणा BIMC_MAS_AMPSS_M0		0
#घोषणा BIMC_MAS_AMPSS_M1		1
#घोषणा BIMC_MAS_MSS_PROC		2
#घोषणा BIMC_TO_MNOC			3
#घोषणा BIMC_TO_SNOC			4
#घोषणा BIMC_SLV_EBI_CH0		5
#घोषणा BIMC_SLV_AMPSS_L2		6

#घोषणा CNOC_MAS_RPM_INST		0
#घोषणा CNOC_MAS_RPM_DATA		1
#घोषणा CNOC_MAS_RPM_SYS		2
#घोषणा CNOC_MAS_DEHR			3
#घोषणा CNOC_MAS_QDSS_DAP		4
#घोषणा CNOC_MAS_SPDM			5
#घोषणा CNOC_MAS_TIC			6
#घोषणा CNOC_SLV_CLK_CTL		7
#घोषणा CNOC_SLV_CNOC_MSS		8
#घोषणा CNOC_SLV_SECURITY		9
#घोषणा CNOC_SLV_TCSR			10
#घोषणा CNOC_SLV_TLMM			11
#घोषणा CNOC_SLV_CRYPTO_0_CFG		12
#घोषणा CNOC_SLV_CRYPTO_1_CFG		13
#घोषणा CNOC_SLV_IMEM_CFG		14
#घोषणा CNOC_SLV_MESSAGE_RAM		15
#घोषणा CNOC_SLV_BIMC_CFG		16
#घोषणा CNOC_SLV_BOOT_ROM		17
#घोषणा CNOC_SLV_PMIC_ARB		18
#घोषणा CNOC_SLV_SPDM_WRAPPER		19
#घोषणा CNOC_SLV_DEHR_CFG		20
#घोषणा CNOC_SLV_MPM			21
#घोषणा CNOC_SLV_QDSS_CFG		22
#घोषणा CNOC_SLV_RBCPR_CFG		23
#घोषणा CNOC_SLV_RBCPR_QDSS_APU_CFG	24
#घोषणा CNOC_TO_SNOC			25
#घोषणा CNOC_SLV_CNOC_ONOC_CFG		26
#घोषणा CNOC_SLV_CNOC_MNOC_MMSS_CFG	27
#घोषणा CNOC_SLV_CNOC_MNOC_CFG		28
#घोषणा CNOC_SLV_PNOC_CFG		29
#घोषणा CNOC_SLV_SNOC_MPU_CFG		30
#घोषणा CNOC_SLV_SNOC_CFG		31
#घोषणा CNOC_SLV_EBI1_DLL_CFG		32
#घोषणा CNOC_SLV_PHY_APU_CFG		33
#घोषणा CNOC_SLV_EBI1_PHY_CFG		34
#घोषणा CNOC_SLV_RPM			35
#घोषणा CNOC_SLV_SERVICE_CNOC		36

#घोषणा MNOC_MAS_GRAPHICS_3D		0
#घोषणा MNOC_MAS_JPEG			1
#घोषणा MNOC_MAS_MDP_PORT0		2
#घोषणा MNOC_MAS_VIDEO_P0		3
#घोषणा MNOC_MAS_VIDEO_P1		4
#घोषणा MNOC_MAS_VFE			5
#घोषणा MNOC_TO_CNOC			6
#घोषणा MNOC_TO_BIMC			7
#घोषणा MNOC_SLV_CAMERA_CFG		8
#घोषणा MNOC_SLV_DISPLAY_CFG		9
#घोषणा MNOC_SLV_OCMEM_CFG		10
#घोषणा MNOC_SLV_CPR_CFG		11
#घोषणा MNOC_SLV_CPR_XPU_CFG		12
#घोषणा MNOC_SLV_MISC_CFG		13
#घोषणा MNOC_SLV_MISC_XPU_CFG		14
#घोषणा MNOC_SLV_VENUS_CFG		15
#घोषणा MNOC_SLV_GRAPHICS_3D_CFG	16
#घोषणा MNOC_SLV_MMSS_CLK_CFG		17
#घोषणा MNOC_SLV_MMSS_CLK_XPU_CFG	18
#घोषणा MNOC_SLV_MNOC_MPU_CFG		19
#घोषणा MNOC_SLV_ONOC_MPU_CFG		20
#घोषणा MNOC_SLV_SERVICE_MNOC		21

#घोषणा OCMEM_NOC_TO_OCMEM_VNOC		0
#घोषणा OCMEM_MAS_JPEG_OCMEM		1
#घोषणा OCMEM_MAS_MDP_OCMEM		2
#घोषणा OCMEM_MAS_VIDEO_P0_OCMEM	3
#घोषणा OCMEM_MAS_VIDEO_P1_OCMEM	4
#घोषणा OCMEM_MAS_VFE_OCMEM		5
#घोषणा OCMEM_MAS_CNOC_ONOC_CFG		6
#घोषणा OCMEM_SLV_SERVICE_ONOC		7
#घोषणा OCMEM_VNOC_TO_SNOC		8
#घोषणा OCMEM_VNOC_TO_OCMEM_NOC		9
#घोषणा OCMEM_VNOC_MAS_GFX3D		10
#घोषणा OCMEM_SLV_OCMEM			11

#घोषणा PNOC_MAS_PNOC_CFG		0
#घोषणा PNOC_MAS_SDCC_1			1
#घोषणा PNOC_MAS_SDCC_3			2
#घोषणा PNOC_MAS_SDCC_4			3
#घोषणा PNOC_MAS_SDCC_2			4
#घोषणा PNOC_MAS_TSIF			5
#घोषणा PNOC_MAS_BAM_DMA		6
#घोषणा PNOC_MAS_BLSP_2			7
#घोषणा PNOC_MAS_USB_HSIC		8
#घोषणा PNOC_MAS_BLSP_1			9
#घोषणा PNOC_MAS_USB_HS			10
#घोषणा PNOC_TO_SNOC			11
#घोषणा PNOC_SLV_SDCC_1			12
#घोषणा PNOC_SLV_SDCC_3			13
#घोषणा PNOC_SLV_SDCC_2			14
#घोषणा PNOC_SLV_SDCC_4			15
#घोषणा PNOC_SLV_TSIF			16
#घोषणा PNOC_SLV_BAM_DMA		17
#घोषणा PNOC_SLV_BLSP_2			18
#घोषणा PNOC_SLV_USB_HSIC		19
#घोषणा PNOC_SLV_BLSP_1			20
#घोषणा PNOC_SLV_USB_HS			21
#घोषणा PNOC_SLV_PDM			22
#घोषणा PNOC_SLV_PERIPH_APU_CFG		23
#घोषणा PNOC_SLV_PNOC_MPU_CFG		24
#घोषणा PNOC_SLV_PRNG			25
#घोषणा PNOC_SLV_SERVICE_PNOC		26

#घोषणा SNOC_MAS_LPASS_AHB		0
#घोषणा SNOC_MAS_QDSS_BAM		1
#घोषणा SNOC_MAS_SNOC_CFG		2
#घोषणा SNOC_TO_BIMC			3
#घोषणा SNOC_TO_CNOC			4
#घोषणा SNOC_TO_PNOC			5
#घोषणा SNOC_TO_OCMEM_VNOC		6
#घोषणा SNOC_MAS_CRYPTO_CORE0		7
#घोषणा SNOC_MAS_CRYPTO_CORE1		8
#घोषणा SNOC_MAS_LPASS_PROC		9
#घोषणा SNOC_MAS_MSS			10
#घोषणा SNOC_MAS_MSS_NAV		11
#घोषणा SNOC_MAS_OCMEM_DMA		12
#घोषणा SNOC_MAS_WCSS			13
#घोषणा SNOC_MAS_QDSS_ETR		14
#घोषणा SNOC_MAS_USB3			15
#घोषणा SNOC_SLV_AMPSS			16
#घोषणा SNOC_SLV_LPASS			17
#घोषणा SNOC_SLV_USB3			18
#घोषणा SNOC_SLV_WCSS			19
#घोषणा SNOC_SLV_OCIMEM			20
#घोषणा SNOC_SLV_SNOC_OCMEM		21
#घोषणा SNOC_SLV_SERVICE_SNOC		22
#घोषणा SNOC_SLV_QDSS_STM		23

#पूर्ण_अगर
