<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0-only */
/*
 * DRA7xx Clock Management रेजिस्टर bits
 *
 * Copyright (C) 2013 Texas Instruments Incorporated - https://www.ti.com
 *
 * Generated by code originally written by:
 * Paul Walmsley (paul@pwsan.com)
 * Rajendra Nayak (rnayak@ti.com)
 * Benoit Cousson (b-cousson@ti.com)
 *
 * This file is स्वतःmatically generated from the OMAP hardware databases.
 * We respectfully ask that any modअगरications to this file be coordinated
 * with the खुला linux-omap@vger.kernel.org mailing list and the
 * authors above to ensure that the स्वतःgeneration scripts are kept
 * up-to-date with the file contents.
 */

#अगर_अघोषित __ARCH_ARM_MACH_OMAP2_CM_REGBITS_7XX_H
#घोषणा __ARCH_ARM_MACH_OMAP2_CM_REGBITS_7XX_H

#घोषणा DRA7XX_ATL_STATDEP_SHIFT				30
#घोषणा DRA7XX_CAM_STATDEP_SHIFT				9
#घोषणा DRA7XX_DSP1_STATDEP_SHIFT				1
#घोषणा DRA7XX_DSP2_STATDEP_SHIFT				18
#घोषणा DRA7XX_DSS_STATDEP_SHIFT				8
#घोषणा DRA7XX_EMIF_STATDEP_SHIFT				4
#घोषणा DRA7XX_EVE1_STATDEP_SHIFT				19
#घोषणा DRA7XX_EVE2_STATDEP_SHIFT				20
#घोषणा DRA7XX_EVE3_STATDEP_SHIFT				21
#घोषणा DRA7XX_EVE4_STATDEP_SHIFT				22
#घोषणा DRA7XX_GMAC_STATDEP_SHIFT				25
#घोषणा DRA7XX_GPU_STATDEP_SHIFT				10
#घोषणा DRA7XX_IPU1_STATDEP_SHIFT				23
#घोषणा DRA7XX_IPU2_STATDEP_SHIFT				0
#घोषणा DRA7XX_IPU_STATDEP_SHIFT				24
#घोषणा DRA7XX_IVA_STATDEP_SHIFT				2
#घोषणा DRA7XX_L3INIT_STATDEP_SHIFT				7
#घोषणा DRA7XX_L3MAIN1_STATDEP_SHIFT				5
#घोषणा DRA7XX_L4CFG_STATDEP_SHIFT				12
#घोषणा DRA7XX_L4PER2_STATDEP_SHIFT				26
#घोषणा DRA7XX_L4PER3_STATDEP_SHIFT				27
#घोषणा DRA7XX_L4PER_STATDEP_SHIFT				13
#घोषणा DRA7XX_L4SEC_STATDEP_SHIFT				14
#घोषणा DRA7XX_PCIE_STATDEP_SHIFT				29
#घोषणा DRA7XX_VPE_STATDEP_SHIFT				28
#घोषणा DRA7XX_WKUPAON_STATDEP_SHIFT				15
#पूर्ण_अगर
