<शैली गुरु>
/*
 * BIF_4_1 Register करोcumentation
 *
 * Copyright (C) 2014  Advanced Micro Devices, Inc.
 *
 * Permission is hereby granted, मुक्त of अक्षरge, to any person obtaining a
 * copy of this software and associated करोcumentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modअगरy, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to करो so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
 * AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#अगर_अघोषित BIF_4_1_D_H
#घोषणा BIF_4_1_D_H

#घोषणा mmMM_INDEX                                                              0x0
#घोषणा mmMM_INDEX_HI                                                           0x6
#घोषणा mmMM_DATA                                                               0x1
#घोषणा mmCC_BIF_BX_FUSESTRAP0							0x14D7
#घोषणा mmBUS_CNTL                                                              0x1508
#घोषणा mmCONFIG_CNTL                                                           0x1509
#घोषणा mmCONFIG_MEMSIZE                                                        0x150a
#घोषणा mmCONFIG_F0_BASE                                                        0x150b
#घोषणा mmCONFIG_APER_SIZE                                                      0x150c
#घोषणा mmCONFIG_REG_APER_SIZE                                                  0x150d
#घोषणा mmBIF_SCRATCH0                                                          0x150e
#घोषणा mmBIF_SCRATCH1                                                          0x150f
#घोषणा mmBX_RESET_EN                                                           0x1514
#घोषणा mmMM_CFGREGS_CNTL                                                       0x1513
#घोषणा mmHW_DEBUG                                                              0x1515
#घोषणा mmMASTER_CREDIT_CNTL                                                    0x1516
#घोषणा mmSLAVE_REQ_CREDIT_CNTL                                                 0x1517
#घोषणा mmBX_RESET_CNTL                                                         0x1518
#घोषणा mmINTERRUPT_CNTL                                                        0x151a
#घोषणा mmINTERRUPT_CNTL2                                                       0x151b
#घोषणा mmBIF_DEBUG_CNTL                                                        0x151c
#घोषणा mmBIF_DEBUG_MUX                                                         0x151d
#घोषणा mmBIF_DEBUG_OUT                                                         0x151e
#घोषणा mmHDP_REG_COHERENCY_FLUSH_CNTL                                          0x1528
#घोषणा mmHDP_MEM_COHERENCY_FLUSH_CNTL                                          0x1520
#घोषणा mmCLKREQB_PAD_CNTL                                                      0x1521
#घोषणा mmSMBUS_SLV_CNTL                                                        0x14fd
#घोषणा mmSMBUS_SLV_CNTL1                                                       0x14fe
#घोषणा mmSMBDAT_PAD_CNTL                                                       0x1522
#घोषणा mmSMBCLK_PAD_CNTL                                                       0x1523
#घोषणा mmBIF_XDMA_LO                                                           0x14c0
#घोषणा mmBIF_XDMA_HI                                                           0x14c1
#घोषणा mmBIF_FEATURES_CONTROL_MISC                                             0x14c2
#घोषणा mmBIF_DOORBELL_CNTL                                                     0x14c3
#घोषणा mmBIF_SLVARB_MODE                                                       0x14c4
#घोषणा mmBIF_FB_EN                                                             0x1524
#घोषणा mmBIF_BUSNUM_CNTL1                                                      0x1525
#घोषणा mmBIF_BUSNUM_LIST0                                                      0x1526
#घोषणा mmBIF_BUSNUM_LIST1                                                      0x1527
#घोषणा mmBIF_BUSNUM_CNTL2                                                      0x152b
#घोषणा mmBIF_BUSY_DELAY_CNTR                                                   0x1529
#घोषणा mmBIF_PERFMON_CNTL                                                      0x152c
#घोषणा mmBIF_PERFCOUNTER0_RESULT                                               0x152d
#घोषणा mmBIF_PERFCOUNTER1_RESULT                                               0x152e
#घोषणा mmSLAVE_HANG_PROTECTION_CNTL                                            0x1536
#घोषणा mmGPU_HDP_FLUSH_REQ                                                     0x1537
#घोषणा mmGPU_HDP_FLUSH_DONE                                                    0x1538
#घोषणा mmSLAVE_HANG_ERROR                                                      0x153b
#घोषणा mmCAPTURE_HOST_BUSNUM                                                   0x153c
#घोषणा mmHOST_BUSNUM                                                           0x153d
#घोषणा mmPEER_REG_RANGE0                                                       0x153e
#घोषणा mmPEER_REG_RANGE1                                                       0x153f
#घोषणा mmPEER0_FB_OFFSET_HI                                                    0x14f3
#घोषणा mmPEER0_FB_OFFSET_LO                                                    0x14f2
#घोषणा mmPEER1_FB_OFFSET_HI                                                    0x14f1
#घोषणा mmPEER1_FB_OFFSET_LO                                                    0x14f0
#घोषणा mmPEER2_FB_OFFSET_HI                                                    0x14ef
#घोषणा mmPEER2_FB_OFFSET_LO                                                    0x14ee
#घोषणा mmPEER3_FB_OFFSET_HI                                                    0x14ed
#घोषणा mmPEER3_FB_OFFSET_LO                                                    0x14ec
#घोषणा mmDBG_BYPASS_SRBM_ACCESS                                                0x14eb
#घोषणा mmSMBUS_BACO_DUMMY                                                      0x14c6
#घोषणा mmBIF_DEVFUNCNUM_LIST0                                                  0x14e8
#घोषणा mmBIF_DEVFUNCNUM_LIST1                                                  0x14e7
#घोषणा mmBACO_CNTL                                                             0x14e5
#घोषणा mmBF_ANA_ISO_CNTL                                                       0x14c7
#घोषणा mmMEM_TYPE_CNTL                                                         0x14e4
#घोषणा mmBIF_BACO_DEBUG                                                        0x14df
#घोषणा mmBIF_BACO_DEBUG_LATCH                                                  0x14dc
#घोषणा mmBACO_CNTL_MISC                                                        0x14db
#घोषणा mmBIF_SSA_PWR_STATUS                                                    0x14c8
#घोषणा mmBIF_SSA_GFX0_LOWER                                                    0x14ca
#घोषणा mmBIF_SSA_GFX0_UPPER                                                    0x14cb
#घोषणा mmBIF_SSA_GFX1_LOWER                                                    0x14cc
#घोषणा mmBIF_SSA_GFX1_UPPER                                                    0x14cd
#घोषणा mmBIF_SSA_GFX2_LOWER                                                    0x14ce
#घोषणा mmBIF_SSA_GFX2_UPPER                                                    0x14cf
#घोषणा mmBIF_SSA_GFX3_LOWER                                                    0x14d0
#घोषणा mmBIF_SSA_GFX3_UPPER                                                    0x14d1
#घोषणा mmBIF_SSA_DISP_LOWER                                                    0x14d2
#घोषणा mmBIF_SSA_DISP_UPPER                                                    0x14d3
#घोषणा mmBIF_SSA_MC_LOWER                                                      0x14d4
#घोषणा mmBIF_SSA_MC_UPPER                                                      0x14d5
#घोषणा mmIMPCTL_RESET                                                          0x14f5
#घोषणा mmGARLIC_FLUSH_CNTL                                                     0x1401
#घोषणा mmGARLIC_FLUSH_ADDR_START_0                                             0x1402
#घोषणा mmGARLIC_FLUSH_ADDR_START_1                                             0x1404
#घोषणा mmGARLIC_FLUSH_ADDR_START_2                                             0x1406
#घोषणा mmGARLIC_FLUSH_ADDR_START_3                                             0x1408
#घोषणा mmGARLIC_FLUSH_ADDR_START_4                                             0x140a
#घोषणा mmGARLIC_FLUSH_ADDR_START_5                                             0x140c
#घोषणा mmGARLIC_FLUSH_ADDR_START_6                                             0x140e
#घोषणा mmGARLIC_FLUSH_ADDR_START_7                                             0x1410
#घोषणा mmGARLIC_FLUSH_ADDR_END_0                                               0x1403
#घोषणा mmGARLIC_FLUSH_ADDR_END_1                                               0x1405
#घोषणा mmGARLIC_FLUSH_ADDR_END_2                                               0x1407
#घोषणा mmGARLIC_FLUSH_ADDR_END_3                                               0x1409
#घोषणा mmGARLIC_FLUSH_ADDR_END_4                                               0x140b
#घोषणा mmGARLIC_FLUSH_ADDR_END_5                                               0x140d
#घोषणा mmGARLIC_FLUSH_ADDR_END_6                                               0x140f
#घोषणा mmGARLIC_FLUSH_ADDR_END_7                                               0x1411
#घोषणा mmGARLIC_FLUSH_REQ                                                      0x1412
#घोषणा mmGPU_GARLIC_FLUSH_REQ                                                  0x1413
#घोषणा mmGPU_GARLIC_FLUSH_DONE                                                 0x1414
#घोषणा mmGARLIC_COHE_CP_RB0_WPTR                                               0x1415
#घोषणा mmGARLIC_COHE_CP_RB1_WPTR                                               0x1416
#घोषणा mmGARLIC_COHE_CP_RB2_WPTR                                               0x1417
#घोषणा mmGARLIC_COHE_UVD_RBC_RB_WPTR                                           0x1418
#घोषणा mmGARLIC_COHE_SDMA0_GFX_RB_WPTR                                         0x1419
#घोषणा mmGARLIC_COHE_SDMA1_GFX_RB_WPTR                                         0x141a
#घोषणा mmGARLIC_COHE_CP_DMA_ME_COMMAND                                         0x141b
#घोषणा mmGARLIC_COHE_CP_DMA_PFP_COMMAND                                        0x141c
#घोषणा mmGARLIC_COHE_SAM_SAB_RBI_WPTR                                          0x141d
#घोषणा mmGARLIC_COHE_SAM_SAB_RBO_WPTR                                          0x141e
#घोषणा mmGARLIC_COHE_VCE_OUT_RB_WPTR                                           0x141f
#घोषणा mmGARLIC_COHE_VCE_RB_WPTR2                                              0x1420
#घोषणा mmGARLIC_COHE_VCE_RB_WPTR                                               0x1421
#घोषणा mmBIOS_SCRATCH_0                                                        0x5c9
#घोषणा mmBIOS_SCRATCH_1                                                        0x5ca
#घोषणा mmBIOS_SCRATCH_2                                                        0x5cb
#घोषणा mmBIOS_SCRATCH_3                                                        0x5cc
#घोषणा mmBIOS_SCRATCH_4                                                        0x5cd
#घोषणा mmBIOS_SCRATCH_5                                                        0x5ce
#घोषणा mmBIOS_SCRATCH_6                                                        0x5cf
#घोषणा mmBIOS_SCRATCH_7                                                        0x5d0
#घोषणा mmBIOS_SCRATCH_8                                                        0x5d1
#घोषणा mmBIOS_SCRATCH_9                                                        0x5d2
#घोषणा mmBIOS_SCRATCH_10                                                       0x5d3
#घोषणा mmBIOS_SCRATCH_11                                                       0x5d4
#घोषणा mmBIOS_SCRATCH_12                                                       0x5d5
#घोषणा mmBIOS_SCRATCH_13                                                       0x5d6
#घोषणा mmBIOS_SCRATCH_14                                                       0x5d7
#घोषणा mmBIOS_SCRATCH_15                                                       0x5d8
#घोषणा mmVENDOR_ID                                                             0x0
#घोषणा mmDEVICE_ID                                                             0x0
#घोषणा mmCOMMAND                                                               0x1
#घोषणा mmSTATUS                                                                0x1
#घोषणा mmREVISION_ID                                                           0x2
#घोषणा mmPROG_INTERFACE                                                        0x2
#घोषणा mmSUB_CLASS                                                             0x2
#घोषणा mmBASE_CLASS                                                            0x2
#घोषणा mmCACHE_LINE                                                            0x3
#घोषणा mmLATENCY                                                               0x3
#घोषणा mmHEADER                                                                0x3
#घोषणा mmBIST                                                                  0x3
#घोषणा mmBASE_ADDR_1                                                           0x4
#घोषणा mmBASE_ADDR_2                                                           0x5
#घोषणा mmBASE_ADDR_3                                                           0x6
#घोषणा mmBASE_ADDR_4                                                           0x7
#घोषणा mmBASE_ADDR_5                                                           0x8
#घोषणा mmBASE_ADDR_6                                                           0x9
#घोषणा mmROM_BASE_ADDR                                                         0xc
#घोषणा mmCAP_PTR                                                               0xd
#घोषणा mmINTERRUPT_LINE                                                        0xf
#घोषणा mmINTERRUPT_PIN                                                         0xf
#घोषणा mmADAPTER_ID                                                            0xb
#घोषणा mmMIN_GRANT                                                             0xf
#घोषणा mmMAX_LATENCY                                                           0xf
#घोषणा mmVENDOR_CAP_LIST                                                       0x12
#घोषणा mmADAPTER_ID_W                                                          0x13
#घोषणा mmPMI_CAP_LIST                                                          0x14
#घोषणा mmPMI_CAP                                                               0x14
#घोषणा mmPMI_STATUS_CNTL                                                       0x15
#घोषणा mmPCIE_CAP_LIST                                                         0x16
#घोषणा mmPCIE_CAP                                                              0x16
#घोषणा mmDEVICE_CAP                                                            0x17
#घोषणा mmDEVICE_CNTL                                                           0x18
#घोषणा mmDEVICE_STATUS                                                         0x18
#घोषणा mmLINK_CAP                                                              0x19
#घोषणा mmLINK_CNTL                                                             0x1a
#घोषणा mmLINK_STATUS                                                           0x1a
#घोषणा mmDEVICE_CAP2                                                           0x1f
#घोषणा mmDEVICE_CNTL2                                                          0x20
#घोषणा mmDEVICE_STATUS2                                                        0x20
#घोषणा mmLINK_CAP2                                                             0x21
#घोषणा mmLINK_CNTL2                                                            0x22
#घोषणा mmLINK_STATUS2                                                          0x22
#घोषणा mmMSI_CAP_LIST                                                          0x28
#घोषणा mmMSI_MSG_CNTL                                                          0x28
#घोषणा mmMSI_MSG_ADDR_LO                                                       0x29
#घोषणा mmMSI_MSG_ADDR_HI                                                       0x2a
#घोषणा mmMSI_MSG_DATA_64                                                       0x2b
#घोषणा mmMSI_MSG_DATA                                                          0x2a
#घोषणा mmPCIE_VENDOR_SPECIFIC_ENH_CAP_LIST                                     0x40
#घोषणा mmPCIE_VENDOR_SPECIFIC_HDR                                              0x41
#घोषणा mmPCIE_VENDOR_SPECIFIC1                                                 0x42
#घोषणा mmPCIE_VENDOR_SPECIFIC2                                                 0x43
#घोषणा mmPCIE_VC_ENH_CAP_LIST                                                  0x44
#घोषणा mmPCIE_PORT_VC_CAP_REG1                                                 0x45
#घोषणा mmPCIE_PORT_VC_CAP_REG2                                                 0x46
#घोषणा mmPCIE_PORT_VC_CNTL                                                     0x47
#घोषणा mmPCIE_PORT_VC_STATUS                                                   0x47
#घोषणा mmPCIE_VC0_RESOURCE_CAP                                                 0x48
#घोषणा mmPCIE_VC0_RESOURCE_CNTL                                                0x49
#घोषणा mmPCIE_VC0_RESOURCE_STATUS                                              0x4a
#घोषणा mmPCIE_VC1_RESOURCE_CAP                                                 0x4b
#घोषणा mmPCIE_VC1_RESOURCE_CNTL                                                0x4c
#घोषणा mmPCIE_VC1_RESOURCE_STATUS                                              0x4d
#घोषणा mmPCIE_DEV_SERIAL_NUM_ENH_CAP_LIST                                      0x50
#घोषणा mmPCIE_DEV_SERIAL_NUM_DW1                                               0x51
#घोषणा mmPCIE_DEV_SERIAL_NUM_DW2                                               0x52
#घोषणा mmPCIE_ADV_ERR_RPT_ENH_CAP_LIST                                         0x54
#घोषणा mmPCIE_UNCORR_ERR_STATUS                                                0x55
#घोषणा mmPCIE_UNCORR_ERR_MASK                                                  0x56
#घोषणा mmPCIE_UNCORR_ERR_SEVERITY                                              0x57
#घोषणा mmPCIE_CORR_ERR_STATUS                                                  0x58
#घोषणा mmPCIE_CORR_ERR_MASK                                                    0x59
#घोषणा mmPCIE_ADV_ERR_CAP_CNTL                                                 0x5a
#घोषणा mmPCIE_HDR_LOG0                                                         0x5b
#घोषणा mmPCIE_HDR_LOG1                                                         0x5c
#घोषणा mmPCIE_HDR_LOG2                                                         0x5d
#घोषणा mmPCIE_HDR_LOG3                                                         0x5e
#घोषणा mmPCIE_TLP_PREFIX_LOG0                                                  0x62
#घोषणा mmPCIE_TLP_PREFIX_LOG1                                                  0x63
#घोषणा mmPCIE_TLP_PREFIX_LOG2                                                  0x64
#घोषणा mmPCIE_TLP_PREFIX_LOG3                                                  0x65
#घोषणा mmPCIE_BAR_ENH_CAP_LIST                                                 0x80
#घोषणा mmPCIE_BAR1_CAP                                                         0x81
#घोषणा mmPCIE_BAR1_CNTL                                                        0x82
#घोषणा mmPCIE_BAR2_CAP                                                         0x83
#घोषणा mmPCIE_BAR2_CNTL                                                        0x84
#घोषणा mmPCIE_BAR3_CAP                                                         0x85
#घोषणा mmPCIE_BAR3_CNTL                                                        0x86
#घोषणा mmPCIE_BAR4_CAP                                                         0x87
#घोषणा mmPCIE_BAR4_CNTL                                                        0x88
#घोषणा mmPCIE_BAR5_CAP                                                         0x89
#घोषणा mmPCIE_BAR5_CNTL                                                        0x8a
#घोषणा mmPCIE_BAR6_CAP                                                         0x8b
#घोषणा mmPCIE_BAR6_CNTL                                                        0x8c
#घोषणा mmPCIE_PWR_BUDGET_ENH_CAP_LIST                                          0x90
#घोषणा mmPCIE_PWR_BUDGET_DATA_SELECT                                           0x91
#घोषणा mmPCIE_PWR_BUDGET_DATA                                                  0x92
#घोषणा mmPCIE_PWR_BUDGET_CAP                                                   0x93
#घोषणा mmPCIE_DPA_ENH_CAP_LIST                                                 0x94
#घोषणा mmPCIE_DPA_CAP                                                          0x95
#घोषणा mmPCIE_DPA_LATENCY_INDICATOR                                            0x96
#घोषणा mmPCIE_DPA_STATUS                                                       0x97
#घोषणा mmPCIE_DPA_CNTL                                                         0x97
#घोषणा mmPCIE_DPA_SUBSTATE_PWR_ALLOC_0                                         0x98
#घोषणा mmPCIE_DPA_SUBSTATE_PWR_ALLOC_1                                         0x98
#घोषणा mmPCIE_DPA_SUBSTATE_PWR_ALLOC_2                                         0x98
#घोषणा mmPCIE_DPA_SUBSTATE_PWR_ALLOC_3                                         0x98
#घोषणा mmPCIE_DPA_SUBSTATE_PWR_ALLOC_4                                         0x99
#घोषणा mmPCIE_DPA_SUBSTATE_PWR_ALLOC_5                                         0x99
#घोषणा mmPCIE_DPA_SUBSTATE_PWR_ALLOC_6                                         0x99
#घोषणा mmPCIE_DPA_SUBSTATE_PWR_ALLOC_7                                         0x99
#घोषणा mmPCIE_SECONDARY_ENH_CAP_LIST                                           0x9c
#घोषणा mmPCIE_LINK_CNTL3                                                       0x9d
#घोषणा mmPCIE_LANE_ERROR_STATUS                                                0x9e
#घोषणा mmPCIE_LANE_0_EQUALIZATION_CNTL                                         0x9f
#घोषणा mmPCIE_LANE_1_EQUALIZATION_CNTL                                         0x9f
#घोषणा mmPCIE_LANE_2_EQUALIZATION_CNTL                                         0xa0
#घोषणा mmPCIE_LANE_3_EQUALIZATION_CNTL                                         0xa0
#घोषणा mmPCIE_LANE_4_EQUALIZATION_CNTL                                         0xa1
#घोषणा mmPCIE_LANE_5_EQUALIZATION_CNTL                                         0xa1
#घोषणा mmPCIE_LANE_6_EQUALIZATION_CNTL                                         0xa2
#घोषणा mmPCIE_LANE_7_EQUALIZATION_CNTL                                         0xa2
#घोषणा mmPCIE_LANE_8_EQUALIZATION_CNTL                                         0xa3
#घोषणा mmPCIE_LANE_9_EQUALIZATION_CNTL                                         0xa3
#घोषणा mmPCIE_LANE_10_EQUALIZATION_CNTL                                        0xa4
#घोषणा mmPCIE_LANE_11_EQUALIZATION_CNTL                                        0xa4
#घोषणा mmPCIE_LANE_12_EQUALIZATION_CNTL                                        0xa5
#घोषणा mmPCIE_LANE_13_EQUALIZATION_CNTL                                        0xa5
#घोषणा mmPCIE_LANE_14_EQUALIZATION_CNTL                                        0xa6
#घोषणा mmPCIE_LANE_15_EQUALIZATION_CNTL                                        0xa6
#घोषणा mmPCIE_ACS_ENH_CAP_LIST                                                 0xa8
#घोषणा mmPCIE_ACS_CAP                                                          0xa9
#घोषणा mmPCIE_ACS_CNTL                                                         0xa9
#घोषणा mmPCIE_ATS_ENH_CAP_LIST                                                 0xac
#घोषणा mmPCIE_ATS_CAP                                                          0xad
#घोषणा mmPCIE_ATS_CNTL                                                         0xad
#घोषणा mmPCIE_PAGE_REQ_ENH_CAP_LIST                                            0xb0
#घोषणा mmPCIE_PAGE_REQ_CNTL                                                    0xb1
#घोषणा mmPCIE_PAGE_REQ_STATUS                                                  0xb1
#घोषणा mmPCIE_OUTSTAND_PAGE_REQ_CAPACITY                                       0xb2
#घोषणा mmPCIE_OUTSTAND_PAGE_REQ_ALLOC                                          0xb3
#घोषणा mmPCIE_PASID_ENH_CAP_LIST                                               0xb4
#घोषणा mmPCIE_PASID_CAP                                                        0xb5
#घोषणा mmPCIE_PASID_CNTL                                                       0xb5
#घोषणा mmPCIE_TPH_REQR_ENH_CAP_LIST                                            0xb8
#घोषणा mmPCIE_TPH_REQR_CAP                                                     0xb9
#घोषणा mmPCIE_TPH_REQR_CNTL                                                    0xba
#घोषणा mmPCIE_MC_ENH_CAP_LIST                                                  0xbc
#घोषणा mmPCIE_MC_CAP                                                           0xbd
#घोषणा mmPCIE_MC_CNTL                                                          0xbd
#घोषणा mmPCIE_MC_ADDR0                                                         0xbe
#घोषणा mmPCIE_MC_ADDR1                                                         0xbf
#घोषणा mmPCIE_MC_RCV0                                                          0xc0
#घोषणा mmPCIE_MC_RCV1                                                          0xc1
#घोषणा mmPCIE_MC_BLOCK_ALL0                                                    0xc2
#घोषणा mmPCIE_MC_BLOCK_ALL1                                                    0xc3
#घोषणा mmPCIE_MC_BLOCK_UNTRANSLATED_0                                          0xc4
#घोषणा mmPCIE_MC_BLOCK_UNTRANSLATED_1                                          0xc5
#घोषणा mmPCIE_LTR_ENH_CAP_LIST                                                 0xc8
#घोषणा mmPCIE_LTR_CAP                                                          0xc9
#घोषणा mmPCIE_INDEX                                                            0xe
#घोषणा mmPCIE_DATA                                                             0xf
#घोषणा mmPCIE_INDEX_2                                                          0xc
#घोषणा mmPCIE_DATA_2                                                           0xd
#घोषणा ixPCIE_RESERVED                                                         0x1400000
#घोषणा ixPCIE_SCRATCH                                                          0x1400001
#घोषणा ixPCIE_HW_DEBUG                                                         0x1400002
#घोषणा ixPCIE_RX_NUM_NAK                                                       0x140000e
#घोषणा ixPCIE_RX_NUM_NAK_GENERATED                                             0x140000f
#घोषणा ixPCIE_CNTL                                                             0x1400010
#घोषणा ixPCIE_CONFIG_CNTL                                                      0x1400011
#घोषणा ixPCIE_DEBUG_CNTL                                                       0x1400012
#घोषणा ixPCIE_INT_CNTL                                                         0x140001a
#घोषणा ixPCIE_INT_STATUS                                                       0x140001b
#घोषणा ixPCIE_CNTL2                                                            0x140001c
#घोषणा ixPCIE_RX_CNTL2                                                         0x140001d
#घोषणा ixPCIE_TX_F0_ATTR_CNTL                                                  0x140001e
#घोषणा ixPCIE_TX_F1_F2_ATTR_CNTL                                               0x140001f
#घोषणा ixPCIE_CI_CNTL                                                          0x1400020
#घोषणा ixPCIE_BUS_CNTL                                                         0x1400021
#घोषणा ixPCIE_LC_STATE6                                                        0x1400022
#घोषणा ixPCIE_LC_STATE7                                                        0x1400023
#घोषणा ixPCIE_LC_STATE8                                                        0x1400024
#घोषणा ixPCIE_LC_STATE9                                                        0x1400025
#घोषणा ixPCIE_LC_STATE10                                                       0x1400026
#घोषणा ixPCIE_LC_STATE11                                                       0x1400027
#घोषणा ixPCIE_LC_STATUS1                                                       0x1400028
#घोषणा ixPCIE_LC_STATUS2                                                       0x1400029
#घोषणा ixPCIE_WPR_CNTL                                                         0x1400030
#घोषणा ixPCIE_RX_LAST_TLP0                                                     0x1400031
#घोषणा ixPCIE_RX_LAST_TLP1                                                     0x1400032
#घोषणा ixPCIE_RX_LAST_TLP2                                                     0x1400033
#घोषणा ixPCIE_RX_LAST_TLP3                                                     0x1400034
#घोषणा ixPCIE_TX_LAST_TLP0                                                     0x1400035
#घोषणा ixPCIE_TX_LAST_TLP1                                                     0x1400036
#घोषणा ixPCIE_TX_LAST_TLP2                                                     0x1400037
#घोषणा ixPCIE_TX_LAST_TLP3                                                     0x1400038
#घोषणा ixPCIE_I2C_REG_ADDR_EXPAND                                              0x140003a
#घोषणा ixPCIE_I2C_REG_DATA                                                     0x140003b
#घोषणा ixPCIE_CFG_CNTL                                                         0x140003c
#घोषणा ixPCIE_P_CNTL                                                           0x1400040
#घोषणा ixPCIE_P_BUF_STATUS                                                     0x1400041
#घोषणा ixPCIE_P_DECODER_STATUS                                                 0x1400042
#घोषणा ixPCIE_P_MISC_STATUS                                                    0x1400043
#घोषणा ixPCIE_P_RCV_L0S_FTS_DET                                                0x1400050
#घोषणा ixPCIE_OBFF_CNTL                                                        0x1400061
#घोषणा ixPCIE_TX_LTR_CNTL                                                      0x1400060
#घोषणा ixPCIE_PERF_COUNT_CNTL                                                  0x1400080
#घोषणा ixPCIE_PERF_CNTL_TXCLK                                                  0x1400081
#घोषणा ixPCIE_PERF_COUNT0_TXCLK                                                0x1400082
#घोषणा ixPCIE_PERF_COUNT1_TXCLK                                                0x1400083
#घोषणा ixPCIE_PERF_CNTL_MST_R_CLK                                              0x1400084
#घोषणा ixPCIE_PERF_COUNT0_MST_R_CLK                                            0x1400085
#घोषणा ixPCIE_PERF_COUNT1_MST_R_CLK                                            0x1400086
#घोषणा ixPCIE_PERF_CNTL_MST_C_CLK                                              0x1400087
#घोषणा ixPCIE_PERF_COUNT0_MST_C_CLK                                            0x1400088
#घोषणा ixPCIE_PERF_COUNT1_MST_C_CLK                                            0x1400089
#घोषणा ixPCIE_PERF_CNTL_SLV_R_CLK                                              0x140008a
#घोषणा ixPCIE_PERF_COUNT0_SLV_R_CLK                                            0x140008b
#घोषणा ixPCIE_PERF_COUNT1_SLV_R_CLK                                            0x140008c
#घोषणा ixPCIE_PERF_CNTL_SLV_S_C_CLK                                            0x140008d
#घोषणा ixPCIE_PERF_COUNT0_SLV_S_C_CLK                                          0x140008e
#घोषणा ixPCIE_PERF_COUNT1_SLV_S_C_CLK                                          0x140008f
#घोषणा ixPCIE_PERF_CNTL_SLV_NS_C_CLK                                           0x1400090
#घोषणा ixPCIE_PERF_COUNT0_SLV_NS_C_CLK                                         0x1400091
#घोषणा ixPCIE_PERF_COUNT1_SLV_NS_C_CLK                                         0x1400092
#घोषणा ixPCIE_PERF_CNTL_EVENT0_PORT_SEL                                        0x1400093
#घोषणा ixPCIE_PERF_CNTL_EVENT1_PORT_SEL                                        0x1400094
#घोषणा ixPCIE_PERF_CNTL_TXCLK2                                                 0x1400095
#घोषणा ixPCIE_PERF_COUNT0_TXCLK2                                               0x1400096
#घोषणा ixPCIE_PERF_COUNT1_TXCLK2                                               0x1400097
#घोषणा ixPCIE_STRAP_F0                                                         0x14000b0
#घोषणा ixPCIE_STRAP_F1                                                         0x14000b1
#घोषणा ixPCIE_STRAP_F2                                                         0x14000b2
#घोषणा ixPCIE_STRAP_F3                                                         0x14000b3
#घोषणा ixPCIE_STRAP_F4                                                         0x14000b4
#घोषणा ixPCIE_STRAP_F5                                                         0x14000b5
#घोषणा ixPCIE_STRAP_F6                                                         0x14000b6
#घोषणा ixPCIE_STRAP_F7                                                         0x14000b7
#घोषणा ixPCIE_STRAP_MISC                                                       0x14000c0
#घोषणा ixPCIE_STRAP_MISC2                                                      0x14000c1
#घोषणा ixPCIE_STRAP_PI                                                         0x14000c2
#घोषणा ixPCIE_STRAP_I2C_BD                                                     0x14000c4
#घोषणा ixPCIE_PRBS_CLR                                                         0x14000c8
#घोषणा ixPCIE_PRBS_STATUS1                                                     0x14000c9
#घोषणा ixPCIE_PRBS_STATUS2                                                     0x14000ca
#घोषणा ixPCIE_PRBS_FREERUN                                                     0x14000cb
#घोषणा ixPCIE_PRBS_MISC                                                        0x14000cc
#घोषणा ixPCIE_PRBS_USER_PATTERN                                                0x14000cd
#घोषणा ixPCIE_PRBS_LO_BITCNT                                                   0x14000ce
#घोषणा ixPCIE_PRBS_HI_BITCNT                                                   0x14000cf
#घोषणा ixPCIE_PRBS_ERRCNT_0                                                    0x14000d0
#घोषणा ixPCIE_PRBS_ERRCNT_1                                                    0x14000d1
#घोषणा ixPCIE_PRBS_ERRCNT_2                                                    0x14000d2
#घोषणा ixPCIE_PRBS_ERRCNT_3                                                    0x14000d3
#घोषणा ixPCIE_PRBS_ERRCNT_4                                                    0x14000d4
#घोषणा ixPCIE_PRBS_ERRCNT_5                                                    0x14000d5
#घोषणा ixPCIE_PRBS_ERRCNT_6                                                    0x14000d6
#घोषणा ixPCIE_PRBS_ERRCNT_7                                                    0x14000d7
#घोषणा ixPCIE_PRBS_ERRCNT_8                                                    0x14000d8
#घोषणा ixPCIE_PRBS_ERRCNT_9                                                    0x14000d9
#घोषणा ixPCIE_PRBS_ERRCNT_10                                                   0x14000da
#घोषणा ixPCIE_PRBS_ERRCNT_11                                                   0x14000db
#घोषणा ixPCIE_PRBS_ERRCNT_12                                                   0x14000dc
#घोषणा ixPCIE_PRBS_ERRCNT_13                                                   0x14000dd
#घोषणा ixPCIE_PRBS_ERRCNT_14                                                   0x14000de
#घोषणा ixPCIE_PRBS_ERRCNT_15                                                   0x14000df
#घोषणा ixPCIE_F0_DPA_CAP                                                       0x14000e0
#घोषणा ixPCIE_F0_DPA_LATENCY_INDICATOR                                         0x14000e4
#घोषणा ixPCIE_F0_DPA_CNTL                                                      0x14000e5
#घोषणा ixPCIE_F0_DPA_SUBSTATE_PWR_ALLOC_0                                      0x14000e7
#घोषणा ixPCIE_F0_DPA_SUBSTATE_PWR_ALLOC_1                                      0x14000e8
#घोषणा ixPCIE_F0_DPA_SUBSTATE_PWR_ALLOC_2                                      0x14000e9
#घोषणा ixPCIE_F0_DPA_SUBSTATE_PWR_ALLOC_3                                      0x14000ea
#घोषणा ixPCIE_F0_DPA_SUBSTATE_PWR_ALLOC_4                                      0x14000eb
#घोषणा ixPCIE_F0_DPA_SUBSTATE_PWR_ALLOC_5                                      0x14000ec
#घोषणा ixPCIE_F0_DPA_SUBSTATE_PWR_ALLOC_6                                      0x14000ed
#घोषणा ixPCIE_F0_DPA_SUBSTATE_PWR_ALLOC_7                                      0x14000ee
#घोषणा ixPCIEP_RESERVED                                                        0x10010000
#घोषणा ixPCIEP_SCRATCH                                                         0x10010001
#घोषणा ixPCIEP_HW_DEBUG                                                        0x10010002
#घोषणा ixPCIEP_PORT_CNTL                                                       0x10010010
#घोषणा ixPCIE_TX_CNTL                                                          0x10010020
#घोषणा ixPCIE_TX_REQUESTER_ID                                                  0x10010021
#घोषणा ixPCIE_TX_VENDOR_SPECIFIC                                               0x10010022
#घोषणा ixPCIE_TX_REQUEST_NUM_CNTL                                              0x10010023
#घोषणा ixPCIE_TX_SEQ                                                           0x10010024
#घोषणा ixPCIE_TX_REPLAY                                                        0x10010025
#घोषणा ixPCIE_TX_ACK_LATENCY_LIMIT                                             0x10010026
#घोषणा ixPCIE_TX_CREDITS_ADVT_P                                                0x10010030
#घोषणा ixPCIE_TX_CREDITS_ADVT_NP                                               0x10010031
#घोषणा ixPCIE_TX_CREDITS_ADVT_CPL                                              0x10010032
#घोषणा ixPCIE_TX_CREDITS_INIT_P                                                0x10010033
#घोषणा ixPCIE_TX_CREDITS_INIT_NP                                               0x10010034
#घोषणा ixPCIE_TX_CREDITS_INIT_CPL                                              0x10010035
#घोषणा ixPCIE_TX_CREDITS_STATUS                                                0x10010036
#घोषणा ixPCIE_TX_CREDITS_FCU_THRESHOLD                                         0x10010037
#घोषणा ixPCIE_P_PORT_LANE_STATUS                                               0x10010050
#घोषणा ixPCIE_FC_P                                                             0x10010060
#घोषणा ixPCIE_FC_NP                                                            0x10010061
#घोषणा ixPCIE_FC_CPL                                                           0x10010062
#घोषणा ixPCIE_ERR_CNTL                                                         0x1001006a
#घोषणा ixPCIE_RX_CNTL                                                          0x10010070
#घोषणा ixPCIE_RX_EXPECTED_SEQNUM                                               0x10010071
#घोषणा ixPCIE_RX_VENDOR_SPECIFIC                                               0x10010072
#घोषणा ixPCIE_RX_CNTL3                                                         0x10010074
#घोषणा ixPCIE_RX_CREDITS_ALLOCATED_P                                           0x10010080
#घोषणा ixPCIE_RX_CREDITS_ALLOCATED_NP                                          0x10010081
#घोषणा ixPCIE_RX_CREDITS_ALLOCATED_CPL                                         0x10010082
#घोषणा ixPCIE_LC_CNTL                                                          0x100100a0
#घोषणा ixPCIE_LC_CNTL2                                                         0x100100b1
#घोषणा ixPCIE_LC_CNTL3                                                         0x100100b5
#घोषणा ixPCIE_LC_CNTL4                                                         0x100100b6
#घोषणा ixPCIE_LC_CNTL5                                                         0x100100b7
#घोषणा ixPCIE_LC_BW_CHANGE_CNTL                                                0x100100b2
#घोषणा ixPCIE_LC_TRAINING_CNTL                                                 0x100100a1
#घोषणा ixPCIE_LC_LINK_WIDTH_CNTL                                               0x100100a2
#घोषणा ixPCIE_LC_N_FTS_CNTL                                                    0x100100a3
#घोषणा ixPCIE_LC_SPEED_CNTL                                                    0x100100a4
#घोषणा ixPCIE_LC_CDR_CNTL                                                      0x100100b3
#घोषणा ixPCIE_LC_LANE_CNTL                                                     0x100100b4
#घोषणा ixPCIE_LC_FORCE_COEFF                                                   0x100100b8
#घोषणा ixPCIE_LC_BEST_EQ_SETTINGS                                              0x100100b9
#घोषणा ixPCIE_LC_FORCE_EQ_REQ_COEFF                                            0x100100ba
#घोषणा ixPCIE_LC_STATE0                                                        0x100100a5
#घोषणा ixPCIE_LC_STATE1                                                        0x100100a6
#घोषणा ixPCIE_LC_STATE2                                                        0x100100a7
#घोषणा ixPCIE_LC_STATE3                                                        0x100100a8
#घोषणा ixPCIE_LC_STATE4                                                        0x100100a9
#घोषणा ixPCIE_LC_STATE5                                                        0x100100aa
#घोषणा ixPCIEP_STRAP_LC                                                        0x100100c0
#घोषणा ixPCIEP_STRAP_MISC                                                      0x100100c1
#घोषणा ixPCIEP_BCH_ECC_CNTL                                                    0x100100d0
#घोषणा ixPB0_GLB_CTRL_REG0                                                     0x1200004
#घोषणा ixPB0_GLB_CTRL_REG1                                                     0x1200008
#घोषणा ixPB0_GLB_CTRL_REG2                                                     0x120000c
#घोषणा ixPB0_GLB_CTRL_REG3                                                     0x1200010
#घोषणा ixPB0_GLB_CTRL_REG4                                                     0x1200014
#घोषणा ixPB0_GLB_CTRL_REG5                                                     0x1200018
#घोषणा ixPB0_GLB_SCI_STAT_OVRD_REG0                                            0x120001c
#घोषणा ixPB0_GLB_SCI_STAT_OVRD_REG1                                            0x1200020
#घोषणा ixPB0_GLB_SCI_STAT_OVRD_REG2                                            0x1200024
#घोषणा ixPB0_GLB_SCI_STAT_OVRD_REG3                                            0x1200028
#घोषणा ixPB0_GLB_SCI_STAT_OVRD_REG4                                            0x120002c
#घोषणा ixPB0_GLB_OVRD_REG0                                                     0x1200030
#घोषणा ixPB0_GLB_OVRD_REG1                                                     0x1200034
#घोषणा ixPB0_GLB_OVRD_REG2                                                     0x1200038
#घोषणा ixPB0_HW_DEBUG                                                          0x1202004
#घोषणा ixPB0_STRAP_GLB_REG0                                                    0x1202020
#घोषणा ixPB0_STRAP_TX_REG0                                                     0x1202024
#घोषणा ixPB0_STRAP_RX_REG0                                                     0x1202028
#घोषणा ixPB0_STRAP_RX_REG1                                                     0x120202c
#घोषणा ixPB0_STRAP_PLL_REG0                                                    0x1202030
#घोषणा ixPB0_STRAP_PIN_REG0                                                    0x1202034
#घोषणा ixPB0_DFT_JIT_INJ_REG0                                                  0x1203000
#घोषणा ixPB0_DFT_JIT_INJ_REG1                                                  0x1203004
#घोषणा ixPB0_DFT_JIT_INJ_REG2                                                  0x1203008
#घोषणा ixPB0_DFT_DEBUG_CTRL_REG0                                               0x120300c
#घोषणा ixPB0_DFT_JIT_INJ_STAT_REG0                                             0x1203010
#घोषणा ixPB0_PLL_RO_GLB_CTRL_REG0                                              0x1204000
#घोषणा ixPB0_PLL_RO_GLB_OVRD_REG0                                              0x1204010
#घोषणा ixPB0_PLL_RO0_CTRL_REG0                                                 0x1204440
#घोषणा ixPB0_PLL_RO0_OVRD_REG0                                                 0x1204450
#घोषणा ixPB0_PLL_RO0_OVRD_REG1                                                 0x1204454
#घोषणा ixPB0_PLL_RO0_SCI_STAT_OVRD_REG0                                        0x1204460
#घोषणा ixPB0_PLL_RO1_SCI_STAT_OVRD_REG0                                        0x1204464
#घोषणा ixPB0_PLL_RO2_SCI_STAT_OVRD_REG0                                        0x1204468
#घोषणा ixPB0_PLL_RO3_SCI_STAT_OVRD_REG0                                        0x120446c
#घोषणा ixPB0_PLL_LC0_CTRL_REG0                                                 0x1204480
#घोषणा ixPB0_PLL_LC0_OVRD_REG0                                                 0x1204490
#घोषणा ixPB0_PLL_LC0_OVRD_REG1                                                 0x1204494
#घोषणा ixPB0_PLL_LC0_SCI_STAT_OVRD_REG0                                        0x1204500
#घोषणा ixPB0_PLL_LC1_SCI_STAT_OVRD_REG0                                        0x1204504
#घोषणा ixPB0_PLL_LC2_SCI_STAT_OVRD_REG0                                        0x1204508
#घोषणा ixPB0_PLL_LC3_SCI_STAT_OVRD_REG0                                        0x120450c
#घोषणा ixPB0_RX_GLB_CTRL_REG0                                                  0x1206000
#घोषणा ixPB0_RX_GLB_CTRL_REG1                                                  0x1206004
#घोषणा ixPB0_RX_GLB_CTRL_REG2                                                  0x1206008
#घोषणा ixPB0_RX_GLB_CTRL_REG3                                                  0x120600c
#घोषणा ixPB0_RX_GLB_CTRL_REG4                                                  0x1206010
#घोषणा ixPB0_RX_GLB_CTRL_REG5                                                  0x1206014
#घोषणा ixPB0_RX_GLB_CTRL_REG6                                                  0x1206018
#घोषणा ixPB0_RX_GLB_CTRL_REG7                                                  0x120601c
#घोषणा ixPB0_RX_GLB_CTRL_REG8                                                  0x1206020
#घोषणा ixPB0_RX_GLB_SCI_STAT_OVRD_REG0                                         0x1206028
#घोषणा ixPB0_RX_GLB_OVRD_REG0                                                  0x1206030
#घोषणा ixPB0_RX_GLB_OVRD_REG1                                                  0x1206034
#घोषणा ixPB0_RX_LANE0_CTRL_REG0                                                0x1206440
#घोषणा ixPB0_RX_LANE0_SCI_STAT_OVRD_REG0                                       0x1206448
#घोषणा ixPB0_RX_LANE1_CTRL_REG0                                                0x1206480
#घोषणा ixPB0_RX_LANE1_SCI_STAT_OVRD_REG0                                       0x1206488
#घोषणा ixPB0_RX_LANE2_CTRL_REG0                                                0x1206500
#घोषणा ixPB0_RX_LANE2_SCI_STAT_OVRD_REG0                                       0x1206508
#घोषणा ixPB0_RX_LANE3_CTRL_REG0                                                0x1206600
#घोषणा ixPB0_RX_LANE3_SCI_STAT_OVRD_REG0                                       0x1206608
#घोषणा ixPB0_RX_LANE4_CTRL_REG0                                                0x1206800
#घोषणा ixPB0_RX_LANE4_SCI_STAT_OVRD_REG0                                       0x1206848
#घोषणा ixPB0_RX_LANE5_CTRL_REG0                                                0x1206880
#घोषणा ixPB0_RX_LANE5_SCI_STAT_OVRD_REG0                                       0x1206888
#घोषणा ixPB0_RX_LANE6_CTRL_REG0                                                0x1206900
#घोषणा ixPB0_RX_LANE6_SCI_STAT_OVRD_REG0                                       0x1206908
#घोषणा ixPB0_RX_LANE7_CTRL_REG0                                                0x1206a00
#घोषणा ixPB0_RX_LANE7_SCI_STAT_OVRD_REG0                                       0x1206a08
#घोषणा ixPB0_RX_LANE8_CTRL_REG0                                                0x1207440
#घोषणा ixPB0_RX_LANE8_SCI_STAT_OVRD_REG0                                       0x1207448
#घोषणा ixPB0_RX_LANE9_CTRL_REG0                                                0x1207480
#घोषणा ixPB0_RX_LANE9_SCI_STAT_OVRD_REG0                                       0x1207488
#घोषणा ixPB0_RX_LANE10_CTRL_REG0                                               0x1207500
#घोषणा ixPB0_RX_LANE10_SCI_STAT_OVRD_REG0                                      0x1207508
#घोषणा ixPB0_RX_LANE11_CTRL_REG0                                               0x1207600
#घोषणा ixPB0_RX_LANE11_SCI_STAT_OVRD_REG0                                      0x1207608
#घोषणा ixPB0_RX_LANE12_CTRL_REG0                                               0x1207840
#घोषणा ixPB0_RX_LANE12_SCI_STAT_OVRD_REG0                                      0x1207848
#घोषणा ixPB0_RX_LANE13_CTRL_REG0                                               0x1207880
#घोषणा ixPB0_RX_LANE13_SCI_STAT_OVRD_REG0                                      0x1207888
#घोषणा ixPB0_RX_LANE14_CTRL_REG0                                               0x1207900
#घोषणा ixPB0_RX_LANE14_SCI_STAT_OVRD_REG0                                      0x1207908
#घोषणा ixPB0_RX_LANE15_CTRL_REG0                                               0x1207a00
#घोषणा ixPB0_RX_LANE15_SCI_STAT_OVRD_REG0                                      0x1207a08
#घोषणा ixPB0_TX_GLB_CTRL_REG0                                                  0x1208000
#घोषणा ixPB0_TX_GLB_LANE_SKEW_CTRL                                             0x1208004
#घोषणा ixPB0_TX_GLB_SCI_STAT_OVRD_REG0                                         0x1208010
#घोषणा ixPB0_TX_GLB_COEFF_ACCEPT_TABLE_REG0                                    0x1208014
#घोषणा ixPB0_TX_GLB_COEFF_ACCEPT_TABLE_REG1                                    0x1208018
#घोषणा ixPB0_TX_GLB_COEFF_ACCEPT_TABLE_REG2                                    0x120801c
#घोषणा ixPB0_TX_GLB_COEFF_ACCEPT_TABLE_REG3                                    0x1208020
#घोषणा ixPB0_TX_GLB_OVRD_REG0                                                  0x1208030
#घोषणा ixPB0_TX_GLB_OVRD_REG1                                                  0x1208034
#घोषणा ixPB0_TX_GLB_OVRD_REG2                                                  0x1208038
#घोषणा ixPB0_TX_GLB_OVRD_REG3                                                  0x120803c
#घोषणा ixPB0_TX_GLB_OVRD_REG4                                                  0x1208040
#घोषणा ixPB0_TX_LANE0_CTRL_REG0                                                0x1208440
#घोषणा ixPB0_TX_LANE0_OVRD_REG0                                                0x1208444
#घोषणा ixPB0_TX_LANE0_SCI_STAT_OVRD_REG0                                       0x1208448
#घोषणा ixPB0_TX_LANE1_CTRL_REG0                                                0x1208480
#घोषणा ixPB0_TX_LANE1_OVRD_REG0                                                0x1208484
#घोषणा ixPB0_TX_LANE1_SCI_STAT_OVRD_REG0                                       0x1208488
#घोषणा ixPB0_TX_LANE2_CTRL_REG0                                                0x1208500
#घोषणा ixPB0_TX_LANE2_OVRD_REG0                                                0x1208504
#घोषणा ixPB0_TX_LANE2_SCI_STAT_OVRD_REG0                                       0x1208508
#घोषणा ixPB0_TX_LANE3_CTRL_REG0                                                0x1208600
#घोषणा ixPB0_TX_LANE3_OVRD_REG0                                                0x1208604
#घोषणा ixPB0_TX_LANE3_SCI_STAT_OVRD_REG0                                       0x1208608
#घोषणा ixPB0_TX_LANE4_CTRL_REG0                                                0x1208840
#घोषणा ixPB0_TX_LANE4_OVRD_REG0                                                0x1208844
#घोषणा ixPB0_TX_LANE4_SCI_STAT_OVRD_REG0                                       0x1208848
#घोषणा ixPB0_TX_LANE5_CTRL_REG0                                                0x1208880
#घोषणा ixPB0_TX_LANE5_OVRD_REG0                                                0x1208884
#घोषणा ixPB0_TX_LANE5_SCI_STAT_OVRD_REG0                                       0x1208888
#घोषणा ixPB0_TX_LANE6_CTRL_REG0                                                0x1208900
#घोषणा ixPB0_TX_LANE6_OVRD_REG0                                                0x1208904
#घोषणा ixPB0_TX_LANE6_SCI_STAT_OVRD_REG0                                       0x1208908
#घोषणा ixPB0_TX_LANE7_CTRL_REG0                                                0x1208a00
#घोषणा ixPB0_TX_LANE7_OVRD_REG0                                                0x1208a04
#घोषणा ixPB0_TX_LANE7_SCI_STAT_OVRD_REG0                                       0x1208a08
#घोषणा ixPB0_TX_LANE8_CTRL_REG0                                                0x1209440
#घोषणा ixPB0_TX_LANE8_OVRD_REG0                                                0x1209444
#घोषणा ixPB0_TX_LANE8_SCI_STAT_OVRD_REG0                                       0x1209448
#घोषणा ixPB0_TX_LANE9_CTRL_REG0                                                0x1209480
#घोषणा ixPB0_TX_LANE9_OVRD_REG0                                                0x1209484
#घोषणा ixPB0_TX_LANE9_SCI_STAT_OVRD_REG0                                       0x1209488
#घोषणा ixPB0_TX_LANE10_CTRL_REG0                                               0x1209500
#घोषणा ixPB0_TX_LANE10_OVRD_REG0                                               0x1209504
#घोषणा ixPB0_TX_LANE10_SCI_STAT_OVRD_REG0                                      0x1209508
#घोषणा ixPB0_TX_LANE11_CTRL_REG0                                               0x1209600
#घोषणा ixPB0_TX_LANE11_OVRD_REG0                                               0x1209604
#घोषणा ixPB0_TX_LANE11_SCI_STAT_OVRD_REG0                                      0x1209608
#घोषणा ixPB0_TX_LANE12_CTRL_REG0                                               0x1209840
#घोषणा ixPB0_TX_LANE12_OVRD_REG0                                               0x1209844
#घोषणा ixPB0_TX_LANE12_SCI_STAT_OVRD_REG0                                      0x1209848
#घोषणा ixPB0_TX_LANE13_CTRL_REG0                                               0x1209880
#घोषणा ixPB0_TX_LANE13_OVRD_REG0                                               0x1209884
#घोषणा ixPB0_TX_LANE13_SCI_STAT_OVRD_REG0                                      0x1209888
#घोषणा ixPB0_TX_LANE14_CTRL_REG0                                               0x1209900
#घोषणा ixPB0_TX_LANE14_OVRD_REG0                                               0x1209904
#घोषणा ixPB0_TX_LANE14_SCI_STAT_OVRD_REG0                                      0x1209908
#घोषणा ixPB0_TX_LANE15_CTRL_REG0                                               0x1209a00
#घोषणा ixPB0_TX_LANE15_OVRD_REG0                                               0x1209a04
#घोषणा ixPB0_TX_LANE15_SCI_STAT_OVRD_REG0                                      0x1209a08
#घोषणा ixPB1_GLB_CTRL_REG0                                                     0x2200004
#घोषणा ixPB1_GLB_CTRL_REG1                                                     0x2200008
#घोषणा ixPB1_GLB_CTRL_REG2                                                     0x220000c
#घोषणा ixPB1_GLB_CTRL_REG3                                                     0x2200010
#घोषणा ixPB1_GLB_CTRL_REG4                                                     0x2200014
#घोषणा ixPB1_GLB_CTRL_REG5                                                     0x2200018
#घोषणा ixPB1_GLB_SCI_STAT_OVRD_REG0                                            0x220001c
#घोषणा ixPB1_GLB_SCI_STAT_OVRD_REG1                                            0x2200020
#घोषणा ixPB1_GLB_SCI_STAT_OVRD_REG2                                            0x2200024
#घोषणा ixPB1_GLB_SCI_STAT_OVRD_REG3                                            0x2200028
#घोषणा ixPB1_GLB_SCI_STAT_OVRD_REG4                                            0x220002c
#घोषणा ixPB1_GLB_OVRD_REG0                                                     0x2200030
#घोषणा ixPB1_GLB_OVRD_REG1                                                     0x2200034
#घोषणा ixPB1_GLB_OVRD_REG2                                                     0x2200038
#घोषणा ixPB1_HW_DEBUG                                                          0x2202004
#घोषणा ixPB1_STRAP_GLB_REG0                                                    0x2202020
#घोषणा ixPB1_STRAP_TX_REG0                                                     0x2202024
#घोषणा ixPB1_STRAP_RX_REG0                                                     0x2202028
#घोषणा ixPB1_STRAP_RX_REG1                                                     0x220202c
#घोषणा ixPB1_STRAP_PLL_REG0                                                    0x2202030
#घोषणा ixPB1_STRAP_PIN_REG0                                                    0x2202034
#घोषणा ixPB1_DFT_JIT_INJ_REG0                                                  0x2203000
#घोषणा ixPB1_DFT_JIT_INJ_REG1                                                  0x2203004
#घोषणा ixPB1_DFT_JIT_INJ_REG2                                                  0x2203008
#घोषणा ixPB1_DFT_DEBUG_CTRL_REG0                                               0x220300c
#घोषणा ixPB1_DFT_JIT_INJ_STAT_REG0                                             0x2203010
#घोषणा ixPB1_PLL_RO_GLB_CTRL_REG0                                              0x2204000
#घोषणा ixPB1_PLL_RO_GLB_OVRD_REG0                                              0x2204010
#घोषणा ixPB1_PLL_RO0_CTRL_REG0                                                 0x2204440
#घोषणा ixPB1_PLL_RO0_OVRD_REG0                                                 0x2204450
#घोषणा ixPB1_PLL_RO0_OVRD_REG1                                                 0x2204454
#घोषणा ixPB1_PLL_RO0_SCI_STAT_OVRD_REG0                                        0x2204460
#घोषणा ixPB1_PLL_RO1_SCI_STAT_OVRD_REG0                                        0x2204464
#घोषणा ixPB1_PLL_RO2_SCI_STAT_OVRD_REG0                                        0x2204468
#घोषणा ixPB1_PLL_RO3_SCI_STAT_OVRD_REG0                                        0x220446c
#घोषणा ixPB1_PLL_LC0_CTRL_REG0                                                 0x2204480
#घोषणा ixPB1_PLL_LC0_OVRD_REG0                                                 0x2204490
#घोषणा ixPB1_PLL_LC0_OVRD_REG1                                                 0x2204494
#घोषणा ixPB1_PLL_LC0_SCI_STAT_OVRD_REG0                                        0x2204500
#घोषणा ixPB1_PLL_LC1_SCI_STAT_OVRD_REG0                                        0x2204504
#घोषणा ixPB1_PLL_LC2_SCI_STAT_OVRD_REG0                                        0x2204508
#घोषणा ixPB1_PLL_LC3_SCI_STAT_OVRD_REG0                                        0x220450c
#घोषणा ixPB1_RX_GLB_CTRL_REG0                                                  0x2206000
#घोषणा ixPB1_RX_GLB_CTRL_REG1                                                  0x2206004
#घोषणा ixPB1_RX_GLB_CTRL_REG2                                                  0x2206008
#घोषणा ixPB1_RX_GLB_CTRL_REG3                                                  0x220600c
#घोषणा ixPB1_RX_GLB_CTRL_REG4                                                  0x2206010
#घोषणा ixPB1_RX_GLB_CTRL_REG5                                                  0x2206014
#घोषणा ixPB1_RX_GLB_CTRL_REG6                                                  0x2206018
#घोषणा ixPB1_RX_GLB_CTRL_REG7                                                  0x220601c
#घोषणा ixPB1_RX_GLB_CTRL_REG8                                                  0x2206020
#घोषणा ixPB1_RX_GLB_SCI_STAT_OVRD_REG0                                         0x2206028
#घोषणा ixPB1_RX_GLB_OVRD_REG0                                                  0x2206030
#घोषणा ixPB1_RX_GLB_OVRD_REG1                                                  0x2206034
#घोषणा ixPB1_RX_LANE0_CTRL_REG0                                                0x2206440
#घोषणा ixPB1_RX_LANE0_SCI_STAT_OVRD_REG0                                       0x2206448
#घोषणा ixPB1_RX_LANE1_CTRL_REG0                                                0x2206480
#घोषणा ixPB1_RX_LANE1_SCI_STAT_OVRD_REG0                                       0x2206488
#घोषणा ixPB1_RX_LANE2_CTRL_REG0                                                0x2206500
#घोषणा ixPB1_RX_LANE2_SCI_STAT_OVRD_REG0                                       0x2206508
#घोषणा ixPB1_RX_LANE3_CTRL_REG0                                                0x2206600
#घोषणा ixPB1_RX_LANE3_SCI_STAT_OVRD_REG0                                       0x2206608
#घोषणा ixPB1_RX_LANE4_CTRL_REG0                                                0x2206800
#घोषणा ixPB1_RX_LANE4_SCI_STAT_OVRD_REG0                                       0x2206848
#घोषणा ixPB1_RX_LANE5_CTRL_REG0                                                0x2206880
#घोषणा ixPB1_RX_LANE5_SCI_STAT_OVRD_REG0                                       0x2206888
#घोषणा ixPB1_RX_LANE6_CTRL_REG0                                                0x2206900
#घोषणा ixPB1_RX_LANE6_SCI_STAT_OVRD_REG0                                       0x2206908
#घोषणा ixPB1_RX_LANE7_CTRL_REG0                                                0x2206a00
#घोषणा ixPB1_RX_LANE7_SCI_STAT_OVRD_REG0                                       0x2206a08
#घोषणा ixPB1_RX_LANE8_CTRL_REG0                                                0x2207440
#घोषणा ixPB1_RX_LANE8_SCI_STAT_OVRD_REG0                                       0x2207448
#घोषणा ixPB1_RX_LANE9_CTRL_REG0                                                0x2207480
#घोषणा ixPB1_RX_LANE9_SCI_STAT_OVRD_REG0                                       0x2207488
#घोषणा ixPB1_RX_LANE10_CTRL_REG0                                               0x2207500
#घोषणा ixPB1_RX_LANE10_SCI_STAT_OVRD_REG0                                      0x2207508
#घोषणा ixPB1_RX_LANE11_CTRL_REG0                                               0x2207600
#घोषणा ixPB1_RX_LANE11_SCI_STAT_OVRD_REG0                                      0x2207608
#घोषणा ixPB1_RX_LANE12_CTRL_REG0                                               0x2207840
#घोषणा ixPB1_RX_LANE12_SCI_STAT_OVRD_REG0                                      0x2207848
#घोषणा ixPB1_RX_LANE13_CTRL_REG0                                               0x2207880
#घोषणा ixPB1_RX_LANE13_SCI_STAT_OVRD_REG0                                      0x2207888
#घोषणा ixPB1_RX_LANE14_CTRL_REG0                                               0x2207900
#घोषणा ixPB1_RX_LANE14_SCI_STAT_OVRD_REG0                                      0x2207908
#घोषणा ixPB1_RX_LANE15_CTRL_REG0                                               0x2207a00
#घोषणा ixPB1_RX_LANE15_SCI_STAT_OVRD_REG0                                      0x2207a08
#घोषणा ixPB1_TX_GLB_CTRL_REG0                                                  0x2208000
#घोषणा ixPB1_TX_GLB_LANE_SKEW_CTRL                                             0x2208004
#घोषणा ixPB1_TX_GLB_SCI_STAT_OVRD_REG0                                         0x2208010
#घोषणा ixPB1_TX_GLB_COEFF_ACCEPT_TABLE_REG0                                    0x2208014
#घोषणा ixPB1_TX_GLB_COEFF_ACCEPT_TABLE_REG1                                    0x2208018
#घोषणा ixPB1_TX_GLB_COEFF_ACCEPT_TABLE_REG2                                    0x220801c
#घोषणा ixPB1_TX_GLB_COEFF_ACCEPT_TABLE_REG3                                    0x2208020
#घोषणा ixPB1_TX_GLB_OVRD_REG0                                                  0x2208030
#घोषणा ixPB1_TX_GLB_OVRD_REG1                                                  0x2208034
#घोषणा ixPB1_TX_GLB_OVRD_REG2                                                  0x2208038
#घोषणा ixPB1_TX_GLB_OVRD_REG3                                                  0x220803c
#घोषणा ixPB1_TX_GLB_OVRD_REG4                                                  0x2208040
#घोषणा ixPB1_TX_LANE0_CTRL_REG0                                                0x2208440
#घोषणा ixPB1_TX_LANE0_OVRD_REG0                                                0x2208444
#घोषणा ixPB1_TX_LANE0_SCI_STAT_OVRD_REG0                                       0x2208448
#घोषणा ixPB1_TX_LANE1_CTRL_REG0                                                0x2208480
#घोषणा ixPB1_TX_LANE1_OVRD_REG0                                                0x2208484
#घोषणा ixPB1_TX_LANE1_SCI_STAT_OVRD_REG0                                       0x2208488
#घोषणा ixPB1_TX_LANE2_CTRL_REG0                                                0x2208500
#घोषणा ixPB1_TX_LANE2_OVRD_REG0                                                0x2208504
#घोषणा ixPB1_TX_LANE2_SCI_STAT_OVRD_REG0                                       0x2208508
#घोषणा ixPB1_TX_LANE3_CTRL_REG0                                                0x2208600
#घोषणा ixPB1_TX_LANE3_OVRD_REG0                                                0x2208604
#घोषणा ixPB1_TX_LANE3_SCI_STAT_OVRD_REG0                                       0x2208608
#घोषणा ixPB1_TX_LANE4_CTRL_REG0                                                0x2208840
#घोषणा ixPB1_TX_LANE4_OVRD_REG0                                                0x2208844
#घोषणा ixPB1_TX_LANE4_SCI_STAT_OVRD_REG0                                       0x2208848
#घोषणा ixPB1_TX_LANE5_CTRL_REG0                                                0x2208880
#घोषणा ixPB1_TX_LANE5_OVRD_REG0                                                0x2208884
#घोषणा ixPB1_TX_LANE5_SCI_STAT_OVRD_REG0                                       0x2208888
#घोषणा ixPB1_TX_LANE6_CTRL_REG0                                                0x2208900
#घोषणा ixPB1_TX_LANE6_OVRD_REG0                                                0x2208904
#घोषणा ixPB1_TX_LANE6_SCI_STAT_OVRD_REG0                                       0x2208908
#घोषणा ixPB1_TX_LANE7_CTRL_REG0                                                0x2208a00
#घोषणा ixPB1_TX_LANE7_OVRD_REG0                                                0x2208a04
#घोषणा ixPB1_TX_LANE7_SCI_STAT_OVRD_REG0                                       0x2208a08
#घोषणा ixPB1_TX_LANE8_CTRL_REG0                                                0x2209440
#घोषणा ixPB1_TX_LANE8_OVRD_REG0                                                0x2209444
#घोषणा ixPB1_TX_LANE8_SCI_STAT_OVRD_REG0                                       0x2209448
#घोषणा ixPB1_TX_LANE9_CTRL_REG0                                                0x2209480
#घोषणा ixPB1_TX_LANE9_OVRD_REG0                                                0x2209484
#घोषणा ixPB1_TX_LANE9_SCI_STAT_OVRD_REG0                                       0x2209488
#घोषणा ixPB1_TX_LANE10_CTRL_REG0                                               0x2209500
#घोषणा ixPB1_TX_LANE10_OVRD_REG0                                               0x2209504
#घोषणा ixPB1_TX_LANE10_SCI_STAT_OVRD_REG0                                      0x2209508
#घोषणा ixPB1_TX_LANE11_CTRL_REG0                                               0x2209600
#घोषणा ixPB1_TX_LANE11_OVRD_REG0                                               0x2209604
#घोषणा ixPB1_TX_LANE11_SCI_STAT_OVRD_REG0                                      0x2209608
#घोषणा ixPB1_TX_LANE12_CTRL_REG0                                               0x2209840
#घोषणा ixPB1_TX_LANE12_OVRD_REG0                                               0x2209844
#घोषणा ixPB1_TX_LANE12_SCI_STAT_OVRD_REG0                                      0x2209848
#घोषणा ixPB1_TX_LANE13_CTRL_REG0                                               0x2209880
#घोषणा ixPB1_TX_LANE13_OVRD_REG0                                               0x2209884
#घोषणा ixPB1_TX_LANE13_SCI_STAT_OVRD_REG0                                      0x2209888
#घोषणा ixPB1_TX_LANE14_CTRL_REG0                                               0x2209900
#घोषणा ixPB1_TX_LANE14_OVRD_REG0                                               0x2209904
#घोषणा ixPB1_TX_LANE14_SCI_STAT_OVRD_REG0                                      0x2209908
#घोषणा ixPB1_TX_LANE15_CTRL_REG0                                               0x2209a00
#घोषणा ixPB1_TX_LANE15_OVRD_REG0                                               0x2209a04
#घोषणा ixPB1_TX_LANE15_SCI_STAT_OVRD_REG0                                      0x2209a08
#घोषणा ixPB0_PIF_SCRATCH                                                       0x1100001
#घोषणा ixPB0_PIF_HW_DEBUG                                                      0x1100002
#घोषणा ixPB0_PIF_PRG6                                                          0x1100003
#घोषणा ixPB0_PIF_PRG7                                                          0x1100004
#घोषणा ixPB0_PIF_CNTL                                                          0x1100010
#घोषणा ixPB0_PIF_PAIRING                                                       0x1100011
#घोषणा ixPB0_PIF_PWRDOWN_0                                                     0x1100012
#घोषणा ixPB0_PIF_PWRDOWN_1                                                     0x1100013
#घोषणा ixPB0_PIF_CNTL2                                                         0x1100014
#घोषणा ixPB0_PIF_TXPHYSTATUS                                                   0x1100015
#घोषणा ixPB0_PIF_SC_CTL                                                        0x1100016
#घोषणा ixPB0_PIF_PWRDOWN_2                                                     0x1100017
#घोषणा ixPB0_PIF_PWRDOWN_3                                                     0x1100018
#घोषणा ixPB0_PIF_SC_CTL2                                                       0x1100019
#घोषणा ixPB0_PIF_PRG0                                                          0x110001a
#घोषणा ixPB0_PIF_PRG1                                                          0x110001b
#घोषणा ixPB0_PIF_PRG2                                                          0x110001c
#घोषणा ixPB0_PIF_PRG3                                                          0x110001d
#घोषणा ixPB0_PIF_PRG4                                                          0x110001e
#घोषणा ixPB0_PIF_PRG5                                                          0x110001f
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_0                                               0x1100020
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_1                                               0x1100021
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_2                                               0x1100022
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_3                                               0x1100023
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_4                                               0x1100024
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_5                                               0x1100025
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_6                                               0x1100026
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_7                                               0x1100027
#घोषणा ixPB0_PIF_SEQ_STATUS_0                                                  0x1100028
#घोषणा ixPB0_PIF_SEQ_STATUS_1                                                  0x1100029
#घोषणा ixPB0_PIF_SEQ_STATUS_2                                                  0x110002a
#घोषणा ixPB0_PIF_SEQ_STATUS_3                                                  0x110002b
#घोषणा ixPB0_PIF_SEQ_STATUS_4                                                  0x110002c
#घोषणा ixPB0_PIF_SEQ_STATUS_5                                                  0x110002d
#घोषणा ixPB0_PIF_SEQ_STATUS_6                                                  0x110002e
#घोषणा ixPB0_PIF_SEQ_STATUS_7                                                  0x110002f
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_8                                               0x1100030
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_9                                               0x1100031
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_10                                              0x1100032
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_11                                              0x1100033
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_12                                              0x1100034
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_13                                              0x1100035
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_14                                              0x1100036
#घोषणा ixPB0_PIF_PDNB_OVERRIDE_15                                              0x1100037
#घोषणा ixPB0_PIF_SEQ_STATUS_8                                                  0x1100038
#घोषणा ixPB0_PIF_SEQ_STATUS_9                                                  0x1100039
#घोषणा ixPB0_PIF_SEQ_STATUS_10                                                 0x110003a
#घोषणा ixPB0_PIF_SEQ_STATUS_11                                                 0x110003b
#घोषणा ixPB0_PIF_SEQ_STATUS_12                                                 0x110003c
#घोषणा ixPB0_PIF_SEQ_STATUS_13                                                 0x110003d
#घोषणा ixPB0_PIF_SEQ_STATUS_14                                                 0x110003e
#घोषणा ixPB0_PIF_SEQ_STATUS_15                                                 0x110003f
#घोषणा ixPB1_PIF_SCRATCH                                                       0x2100001
#घोषणा ixPB1_PIF_HW_DEBUG                                                      0x2100002
#घोषणा ixPB1_PIF_PRG6                                                          0x2100003
#घोषणा ixPB1_PIF_PRG7                                                          0x2100004
#घोषणा ixPB1_PIF_CNTL                                                          0x2100010
#घोषणा ixPB1_PIF_PAIRING                                                       0x2100011
#घोषणा ixPB1_PIF_PWRDOWN_0                                                     0x2100012
#घोषणा ixPB1_PIF_PWRDOWN_1                                                     0x2100013
#घोषणा ixPB1_PIF_CNTL2                                                         0x2100014
#घोषणा ixPB1_PIF_TXPHYSTATUS                                                   0x2100015
#घोषणा ixPB1_PIF_SC_CTL                                                        0x2100016
#घोषणा ixPB1_PIF_PWRDOWN_2                                                     0x2100017
#घोषणा ixPB1_PIF_PWRDOWN_3                                                     0x2100018
#घोषणा ixPB1_PIF_SC_CTL2                                                       0x2100019
#घोषणा ixPB1_PIF_PRG0                                                          0x210001a
#घोषणा ixPB1_PIF_PRG1                                                          0x210001b
#घोषणा ixPB1_PIF_PRG2                                                          0x210001c
#घोषणा ixPB1_PIF_PRG3                                                          0x210001d
#घोषणा ixPB1_PIF_PRG4                                                          0x210001e
#घोषणा ixPB1_PIF_PRG5                                                          0x210001f
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_0                                               0x2100020
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_1                                               0x2100021
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_2                                               0x2100022
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_3                                               0x2100023
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_4                                               0x2100024
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_5                                               0x2100025
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_6                                               0x2100026
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_7                                               0x2100027
#घोषणा ixPB1_PIF_SEQ_STATUS_0                                                  0x2100028
#घोषणा ixPB1_PIF_SEQ_STATUS_1                                                  0x2100029
#घोषणा ixPB1_PIF_SEQ_STATUS_2                                                  0x210002a
#घोषणा ixPB1_PIF_SEQ_STATUS_3                                                  0x210002b
#घोषणा ixPB1_PIF_SEQ_STATUS_4                                                  0x210002c
#घोषणा ixPB1_PIF_SEQ_STATUS_5                                                  0x210002d
#घोषणा ixPB1_PIF_SEQ_STATUS_6                                                  0x210002e
#घोषणा ixPB1_PIF_SEQ_STATUS_7                                                  0x210002f
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_8                                               0x2100030
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_9                                               0x2100031
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_10                                              0x2100032
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_11                                              0x2100033
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_12                                              0x2100034
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_13                                              0x2100035
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_14                                              0x2100036
#घोषणा ixPB1_PIF_PDNB_OVERRIDE_15                                              0x2100037
#घोषणा ixPB1_PIF_SEQ_STATUS_8                                                  0x2100038
#घोषणा ixPB1_PIF_SEQ_STATUS_9                                                  0x2100039
#घोषणा ixPB1_PIF_SEQ_STATUS_10                                                 0x210003a
#घोषणा ixPB1_PIF_SEQ_STATUS_11                                                 0x210003b
#घोषणा ixPB1_PIF_SEQ_STATUS_12                                                 0x210003c
#घोषणा ixPB1_PIF_SEQ_STATUS_13                                                 0x210003d
#घोषणा ixPB1_PIF_SEQ_STATUS_14                                                 0x210003e
#घोषणा ixPB1_PIF_SEQ_STATUS_15                                                 0x210003f
#घोषणा mmBIF_RFE_SNOOP_REG                                                     0x27
#घोषणा mmBIF_RFE_WARMRST_CNTL                                                  0x1459
#घोषणा mmBIF_RFE_SOFTRST_CNTL                                                  0x1441
#घोषणा mmBIF_RFE_IMPRST_CNTL                                                   0x1458
#घोषणा mmBIF_RFE_CLIENT_SOFTRST_TRIGGER                                        0x1442
#घोषणा mmBIF_RFE_MASTER_SOFTRST_TRIGGER                                        0x1443
#घोषणा mmBIF_PWDN_COMMAND                                                      0x1444
#घोषणा mmBIF_PWDN_STATUS                                                       0x1445
#घोषणा mmBIF_RFE_MST_BU_CMDSTATUS                                              0x1446
#घोषणा mmBIF_RFE_MST_RWREG_RFEWDBIF_CMDSTATUS                                  0x1447
#घोषणा mmBIF_RFE_MST_BX_CMDSTATUS                                              0x1448
#घोषणा mmBIF_RFE_MST_TMOUT_STATUS                                              0x144b
#घोषणा mmBIF_RFE_MMCFG_CNTL                                                    0x144c
#घोषणा mmBIF_CC_RFE_IMP_OVERRIDECNTL                                           0x1455
#घोषणा mmBIF_IMPCTL_SMPLCNTL                                                   0x1450
#घोषणा mmBIF_IMPCTL_RXCNTL                                                     0x1451
#घोषणा mmBIF_IMPCTL_TXCNTL_pd                                                  0x1452
#घोषणा mmBIF_IMPCTL_TXCNTL_pu                                                  0x1453
#घोषणा mmBIF_IMPCTL_CONTINUOUS_CALIBRATION_PERIOD                              0x1454
#घोषणा mmBIF_CLOCKS_BITS                                                       0x1489
#घोषणा mmBIF_LNCNT_RESET                                                       0x1488
#घोषणा mmLNCNT_CONTROL                                                         0x1487
#घोषणा mmNEW_REFCLKB_TIMER                                                     0x1485
#घोषणा mmNEW_REFCLKB_TIMER_1                                                   0x1484
#घोषणा mmBIF_CLK_PDWN_DELAY_TIMER                                              0x1483
#घोषणा mmBIF_RESET_EN                                                          0x1482
#घोषणा mmBIF_PIF_TXCLK_SWITCH_TIMER                                            0x1481
#घोषणा mmBIF_BACO_MSIC                                                         0x1480
#घोषणा mmBIF_RESET_CNTL                                                        0x1486
#घोषणा mmBIF_RFE_CNTL_MISC                                                     0x148c

#पूर्ण_अगर /* BIF_4_1_D_H */
