<शैली गुरु>
/* SPDX-License-Identअगरier: GPL-2.0-only */
/* Copyright (C) 2020 ROHM Semiconductors */
#अगर_अघोषित BD99954_CHARGER_H
#घोषणा BD99954_CHARGER_H

#समावेश <linux/regmap.h>

#घोषणा BD9995X_MANUFACTURER "Rohm Semiconductor"
#घोषणा BD9995X_IRQ_PIN      "bd9995x_irq"

#घोषणा BD9995X_VSYS_PRECHARGE_OFFSET_MV 200

#घोषणा BD99954_ID            0x346
#घोषणा BD99955_ID            0x221
#घोषणा BD99956_ID            0x331

/* Battery Charger Commands */
#घोषणा    CHARGING_CURRENT   0x14
#घोषणा    CHARGING_VOLTAGE   0x15
#घोषणा    PROTECT_SET        0x3E
#घोषणा    MAP_SET            0x3F

/* Extended commands */
#घोषणा    CHGSTM_STATUS       0x100
#घोषणा    VBAT_VSYS_STATUS    0x101
#घोषणा    VBUS_VCC_STATUS     0x102
#घोषणा    CHGOP_STATUS        0x103
#घोषणा    WDT_STATUS          0x104
#घोषणा    CUR_ILIM_VAL        0x105
#घोषणा    SEL_ILIM_VAL        0x106
#घोषणा    IBUS_LIM_SET        0x107
#घोषणा    ICC_LIM_SET         0x108
#घोषणा    IOTG_LIM_SET        0x109
#घोषणा    VIN_CTRL_SET        0x10A
#घोषणा    CHGOP_SET1          0x10B
#घोषणा    CHGOP_SET2          0x10C
#घोषणा    VBUSCLPS_TH_SET     0x10D
#घोषणा    VCCCLPS_TH_SET      0x10E
#घोषणा    CHGWDT_SET          0x10F
#घोषणा    BATTWDT_SET         0x110
#घोषणा    VSYSREG_SET         0x111
#घोषणा    VSYSVAL_THH_SET     0x112
#घोषणा    VSYSVAL_THL_SET     0x113
#घोषणा    ITRICH_SET          0x114
#घोषणा    IPRECH_SET          0x115
#घोषणा    ICHG_SET            0x116
#घोषणा    ITERM_SET           0x117
#घोषणा    VPRECHG_TH_SET      0x118
#घोषणा    VRBOOST_SET         0x119
#घोषणा    VFASTCHG_REG_SET1   0x11A
#घोषणा    VFASTCHG_REG_SET2   0x11B
#घोषणा    VFASTCHG_REG_SET3   0x11C
#घोषणा    VRECHG_SET          0x11D
#घोषणा    VBATOVP_SET         0x11E
#घोषणा    IBATSHORT_SET       0x11F
#घोषणा    PROCHOT_CTRL_SET    0x120
#घोषणा    PROCHOT_ICRIT_SET   0x121
#घोषणा    PROCHOT_INORM_SET   0x122
#घोषणा    PROCHOT_IDCHG_SET   0x123
#घोषणा    PROCHOT_VSYS_SET    0x124
#घोषणा    PMON_IOUT_CTRL_SET  0x125
#घोषणा    PMON_DACIN_VAL      0x126
#घोषणा    IOUT_DACIN_VAL      0x127
#घोषणा    VCC_UCD_SET         0x128
#घोषणा    VCC_UCD_STATUS      0x129
#घोषणा    VCC_IDD_STATUS      0x12A
#घोषणा    VCC_UCD_FCTRL_SET   0x12B
#घोषणा    VCC_UCD_FCTRL_EN    0x12C
#घोषणा    VBUS_UCD_SET        0x130
#घोषणा    VBUS_UCD_STATUS     0x131
#घोषणा    VBUS_IDD_STATUS     0x132
#घोषणा    VBUS_UCD_FCTRL_SET  0x133
#घोषणा    VBUS_UCD_FCTRL_EN   0x134
#घोषणा    CHIP_ID             0x138
#घोषणा    CHIP_REV            0x139
#घोषणा    IC_SET1             0x13A
#घोषणा    IC_SET2             0x13B
#घोषणा    SYSTEM_STATUS       0x13C
#घोषणा    SYSTEM_CTRL_SET     0x13D
#घोषणा    VM_CTRL_SET         0x140
#घोषणा    THERM_WINDOW_SET1   0x141
#घोषणा    THERM_WINDOW_SET2   0x142
#घोषणा    THERM_WINDOW_SET3   0x143
#घोषणा    THERM_WINDOW_SET4   0x144
#घोषणा    THERM_WINDOW_SET5   0x145
#घोषणा    IBATP_TH_SET        0x146
#घोषणा    IBATM_TH_SET        0x147
#घोषणा    VBAT_TH_SET         0x148
#घोषणा    THERM_TH_SET        0x149
#घोषणा    IACP_TH_SET         0x14A
#घोषणा    VACP_TH_SET         0x14B
#घोषणा    VBUS_TH_SET         0x14C
#घोषणा    VCC_TH_SET          0x14D
#घोषणा    VSYS_TH_SET         0x14E
#घोषणा    EXTIADP_TH_SET      0x14F
#घोषणा    IBATP_VAL           0x150
#घोषणा    IBATP_AVE_VAL       0x151
#घोषणा    IBATM_VAL           0x152
#घोषणा    IBATM_AVE_VAL       0x153
#घोषणा    VBAT_VAL            0x154
#घोषणा    VBAT_AVE_VAL        0x155
#घोषणा    THERM_VAL           0x156
#घोषणा    VTH_VAL             0x157
#घोषणा    IACP_VAL            0x158
#घोषणा    IACP_AVE_VAL        0x159
#घोषणा    VACP_VAL            0x15A
#घोषणा    VACP_AVE_VAL        0x15B
#घोषणा    VBUS_VAL            0x15C
#घोषणा    VBUS_AVE_VAL        0x15D
#घोषणा    VCC_VAL             0x15E
#घोषणा    VCC_AVE_VAL         0x15F
#घोषणा    VSYS_VAL            0x160
#घोषणा    VSYS_AVE_VAL        0x161
#घोषणा    EXTIADP_VAL         0x162
#घोषणा    EXTIADP_AVE_VAL     0x163
#घोषणा    VACPCLPS_TH_SET     0x164
#घोषणा    INT0_SET            0x168
#घोषणा    INT1_SET            0x169
#घोषणा    INT2_SET            0x16A
#घोषणा    INT3_SET            0x16B
#घोषणा    INT4_SET            0x16C
#घोषणा    INT5_SET            0x16D
#घोषणा    INT6_SET            0x16E
#घोषणा    INT7_SET            0x16F
#घोषणा    INT0_STATUS         0x170
#घोषणा    INT1_STATUS         0x171
#घोषणा    INT2_STATUS         0x172
#घोषणा    INT3_STATUS         0x173
#घोषणा    INT4_STATUS         0x174
#घोषणा    INT5_STATUS         0x175
#घोषणा    INT6_STATUS         0x176
#घोषणा    INT7_STATUS         0x177
#घोषणा    OTPREG0             0x17A
#घोषणा    OTPREG1             0x17B
#घोषणा    SMBREG              0x17C
#घोषणा    DEBUG_MODE_SET      0x17F
#घोषणा    DEBUG0x14           0x214
#घोषणा    DEBUG0x1A           0x21A

क्रमागत bd9995x_fields अणु
	F_PREV_CHGSTM_STATE, F_CHGSTM_STATE,
	F_VBAT_VSYS_STATUS,
	F_VBUS_VCC_STATUS,
	F_BATTEMP, F_VRECHG_DET, F_RBOOST_UV, F_RBOOSTS,
	F_THERMWDT_VAL, F_CHGWDT_VAL,
	F_CUR_ILIM_VAL,
	F_SEL_ILIM_VAL,
	F_IBUS_LIM_SET,
	F_ICC_LIM_SET,
	F_IOTG_LIM_SET,
	F_OTG_BOTH_EN,
	F_VRBOOST_TRIG,
	F_VRBOOST_EN,
	F_PP_BOTH_THRU,
	F_VIN_ORD,
	F_VBUS_EN,
	F_VCC_EN,
	F_VSYS_PRIORITY,
	F_PPC_SUB_CAP,
	F_PPC_CAP,
	F_DCP_2500_SEL,
	F_SDP_500_SEL,
	F_ILIM_AUTO_DISEN,
	F_VCC_BC_DISEN,
	F_VBUS_BC_DISEN,
	F_SDP_CHG_TRIG_EN,
	F_SDP_CHG_TRIG,
	F_AUTO_TOF,
	F_AUTO_FST,
	F_AUTO_RECH,
	F_ILIM_RESET_EN,
	F_DCDC_1MS_SEL,
	F_SEL_ILIM_DIV,
	F_BATT_LEARN,
	F_CHG_EN,
	F_USB_SUS,
	F_CHOP_SS_INIT,
	F_CHOP_ALL_INIT,
	F_DCDC_CLK_SEL,
	F_CHOP_SS,
	F_CHOP_ALL,
	F_VBUSCLPS_TH_SET,
	F_VCCCLPS_TH_SET,
	F_WDT_FST,
	F_WDT_PRE,
	F_WDT_IBAT_SHORT,
	F_WDT_THERM,
	F_VSYSREG_SET,
	F_VSYSVAL_THH_SET,
	F_VSYSVAL_THL_SET,
	F_ITRICH_SET,
	F_IPRECH_SET,
	F_ICHG_SET,
	F_ITERM_SET,
	F_VPRECHG_TH_SET,
	F_VRBOOST_SET,
	F_VFASTCHG_REG_SET1,
	F_VFASTCHG_REG_SET2,
	F_VFASTCHG_REG_SET3,
	F_VRECHG_SET,
	F_VBATOVP_SET,
	F_IBATM_SHORT_SET,
	F_PROCHOT_DG_SET,
	F_PROCHOT_ICRIT_DG_SET,
	F_PROCHOT_IDCHG_DG_SET,
	F_PROCHOT_EN,
	F_PROCHOT_ICRIT_SET,
	F_PROCHOT_INORM_SET,
	F_PROCHOT_IDCHG_SET,
	F_PROCHOT_VSYS_SET,
	F_IMON_INSEL,
	F_PMON_INSEL,
	F_IOUT_OUT_EN,
	F_IOUT_SOURCE_SEL,
	F_IOUT_GAIN_SET,
	F_PMON_OUT_EN,
	F_PMON_GAIN_SET,
	F_PMON_DACIN_VAL,
	F_IOUT_DACIN_VAL,
	F_VCC_BCSRETRY,
	F_VCC_ADCRTRY,
	F_VCC_USBDETEN,
	F_VCC_IDRDETEN,
	F_VCC_ENUMRDY,
	F_VCC_ADCPOLEN,
	F_VCC_DCDMODE,
	F_VCC_USB_SW_EN,
	F_VCC_USB_SW,
	F_VCC_DCDFAIL,
	F_VCC_CHGPORT,
	F_VCC_PUPDET,
	F_VCC_VBUS_VLD,
	F_VCC_CHGDET,
	F_VCC_OTGDET,
	F_VCC_VBINOP,
	F_VCC_EXTID,
	F_VCC_IDRDET,
	F_VCC_INDO,
	F_VCC_UCDSWEN,
	F_VCC_RREF_EN,
	F_VCC_DPPU_EN,
	F_VCC_DPREF_EN,
	F_VCC_DMREF_EN,
	F_VCC_DPDET_EN,
	F_VCC_DMDET_EN,
	F_VCC_DPSINK_EN,
	F_VCC_DMSINK_EN,
	F_VCC_DP_BUFF_EN,
	F_VCC_DM_BUFF_EN,
	F_VCC_EXTCLKENBL,
	F_VCC_PLSTESTEN,
	F_VCC_UCDSWEN_TSTENB,
	F_VCC_RREF_EN_TSTENB,
	F_VCC_DPPU_EN_TSTENB,
	F_VCC_DPREF_EN_TSTENB,
	F_VCC_DMREF_EN_TSTENB,
	F_VCC_DPDET_EN_TSTENB,
	F_VCC_DMDET_EN_TSTENB,
	F_VCC_DPSINK_EN_TSTENB,
	F_VCC_DMSINK_EN_TSTENB,
	F_VCC_DP_BUFF_EN_TSTENB,
	F_VCC_DM_BUFF_EN_TSTENB,
	F_VBUS_BCSRETRY,
	F_VBUS_ADCRTRY,
	F_VBUS_USBDETEN,
	F_VBUS_IDRDETEN,
	F_VBUS_ENUMRDY,
	F_VBUS_ADCPOLEN,
	F_VBUS_DCDMODE,
	F_VBUS_USB_SW_EN,
	F_VBUS_USB_SW,
	F_VBUS_DCDFAIL,
	F_VBUS_CHGPORT,
	F_VBUS_PUPDET,
	F_VBUS_VBUS_VLD,
	F_VBUS_CHGDET,
	F_VBUS_OTGDET,
	F_VBUS_VBINOP,
	F_VBUS_EXTID,
	F_VBUS_IDRDET,
	F_VBUS_INDO,
	F_VBUS_UCDSWEN,
	F_VBUS_RREF_EN,
	F_VBUS_DPPU_EN,
	F_VBUS_DPREF_EN,
	F_VBUS_DMREF_EN,
	F_VBUS_DPDET_EN,
	F_VBUS_DMDET_EN,
	F_VBUS_DPSINK_EN,
	F_VBUS_DMSINK_EN,
	F_VBUS_DP_BUFF_EN,
	F_VBUS_DM_BUFF_EN,
	F_VBUS_EXTCLKENBL,
	F_VBUS_PLSTESTEN,
	F_VBUS_UCDSWEN_TSTENB,
	F_VBUS_RREF_EN_TSTENB,
	F_VBUS_DPPU_EN_TSTENB,
	F_VBUS_DPREF_EN_TSTENB,
	F_VBUS_DMREF_EN_TSTENB,
	F_VBUS_DPDET_EN_TSTENB,
	F_VBUS_DMDET_EN_TSTENB,
	F_VBUS_DPSINK_EN_TSTENB,
	F_VBUS_DMSINK_EN_TSTENB,
	F_VBUS_DP_BUFF_EN_TSTENB,
	F_VBUS_DM_BUFF_EN_TSTENB,
	F_CHIP_ID,
	F_CHIP_REV,
	F_ONE_CELL_MODE,
	F_cell,
	F_VACP_AUTO_DISCHG,
	F_VACP_LOAD,
	F_ACOK_POL,
	F_ACOK_DISEN,
	F_DEBUG_SET1,
	F_DEBUG_SET0,
	F_MONRST_STATE,
	F_ALMRST_STATE,
	F_CHGRST_STATE,
	F_OTPLD_STATE,
	F_ALLRST_STATE,
	F_PROTECT_SET,
	F_MAP_SET,
	F_ADCINTERVAL,
	F_ADCMOD,
	F_ADCTMOD,
	F_EXTIADPEN,
	F_VSYSENB,
	F_VCCENB,
	F_VBUSENB,
	F_VACPENB,
	F_IACPENB,
	F_THERMENB,
	F_VBATENB,
	F_IBATMENB,
	F_IBATPENB,
	F_TMPTHR1B,
	F_TMPTHR1A,
	F_TMPTHR2B,
	F_TMPTHR2A,
	F_TMPTHR3B,
	F_TMPTHR3A,
	F_TMPTHR4B,
	F_TMPTHR4A,
	F_TMPTHR5B,
	F_TMPTHR5A,
	F_IBATP_TH_SET,
	F_IBATM_TH_SET,
	F_VBAT_TH_SET,
	F_THERM_TH_SET,
	F_IACP_TH_SET,
	F_VACP_TH_SET,
	F_VBUS_TH_SET,
	F_VCC_TH_SET,
	F_VSYS_TH_SET,
	F_EXTIADP_TH_SET,
	F_IBATP_VAL,
	F_IBATP_AVE_VAL,
	F_IBATM_VAL,
	F_IBATM_AVE_VAL,
	F_VBAT_VAL,
	F_VBAT_AVE_VAL,
	F_THERM_VAL,
	F_VTH_VAL,
	F_IACP_VAL,
	F_IACP_AVE_VAL,
	F_VACP_VAL,
	F_VACP_AVE_VAL,
	F_VBUS_VAL,
	F_VBUS_AVE_VAL,
	F_VCC_VAL,
	F_VCC_AVE_VAL,
	F_VSYS_VAL,
	F_VSYS_AVE_VAL,
	F_EXTIADP_VAL,
	F_EXTIADP_AVE_VAL,
	F_VACPCLPS_TH_SET,
	F_INT7_SET,
	F_INT6_SET,
	F_INT5_SET,
	F_INT4_SET,
	F_INT3_SET,
	F_INT2_SET,
	F_INT1_SET,
	F_INT0_SET,
	F_VBUS_RBUV_DET,
	F_VBUS_RBUV_RES,
	F_VBUS_TH_DET,
	F_VBUS_TH_RES,
	F_VBUS_IIN_MOD,
	F_VBUS_OV_DET,
	F_VBUS_OV_RES,
	F_VBUS_CLPS_DET,
	F_VBUS_CLPS,
	F_VBUS_DET,
	F_VBUS_RES,
	F_VCC_RBUV_DET,
	F_VCC_RBUV_RES,
	F_VCC_TH_DET,
	F_VCC_TH_RES,
	F_VCC_IIN_MOD,
	F_VCC_OVP_DET,
	F_VCC_OVP_RES,
	F_VCC_CLPS_DET,
	F_VCC_CLPS_RES,
	F_VCC_DET,
	F_VCC_RES,
	F_TH_DET,
	F_TH_RMV,
	F_TMP_OUT_DET,
	F_TMP_OUT_RES,
	F_VBAT_TH_DET,
	F_VBAT_TH_RES,
	F_IBAT_SHORT_DET,
	F_IBAT_SHORT_RES,
	F_VBAT_OV_DET,
	F_VBAT_OV_RES,
	F_BAT_ASSIST_DET,
	F_BAT_ASSIST_RES,
	F_VSYS_TH_DET,
	F_VSYS_TH_RES,
	F_VSYS_OV_DET,
	F_VSYS_OV_RES,
	F_VSYS_SHT_DET,
	F_VSYS_SHT_RES,
	F_VSYS_UV_DET,
	F_VSYS_UV_RES,
	F_OTP_LOAD_DONE,
	F_PWR_ON,
	F_EXTIADP_TRNS,
	F_EXTIADP_TH_DET,
	F_EXIADP_TH_RES,
	F_BAT_MNT_DET,
	F_BAT_MNT_RES,
	F_TSD_DET,
	F_TSD_RES,
	F_CHGWDT_EXP,
	F_THERMWDT_EXP,
	F_TMP_TRNS,
	F_CHG_TRNS,
	F_VBUS_UCD_PORT_DET,
	F_VBUS_UCD_UCHG_DET,
	F_VBUS_UCD_URID_RMV,
	F_VBUS_UCD_OTG_DET,
	F_VBUS_UCD_URID_MOD,
	F_VCC_UCD_PORT_DET,
	F_VCC_UCD_UCHG_DET,
	F_VCC_UCD_URID_RMV,
	F_VCC_UCD_OTG_DET,
	F_VCC_UCD_URID_MOD,
	F_PROCHOT_DET,
	F_PROCHOT_RES,
	F_VACP_DET,
	F_VACP_RES,
	F_VACP_TH_DET,
	F_VACP_TH_RES,
	F_IACP_TH_DET,
	F_IACP_THE_RES,
	F_THERM_TH_DET,
	F_THERM_TH_RES,
	F_IBATM_TH_DET,
	F_IBATM_TH_RES,
	F_IBATP_TH_DET,
	F_IBATP_TH_RES,
	F_INT7_STATUS,
	F_INT6_STATUS,
	F_INT5_STATUS,
	F_INT4_STATUS,
	F_INT3_STATUS,
	F_INT2_STATUS,
	F_INT1_STATUS,
	F_INT0_STATUS,
	F_ILIM_DECREASE,
	F_RESERVE_OTPREG1,
	F_POWER_SAVE_MODE,
	F_DEBUG_MODE_SET,
	F_DEBUG0x14,
	F_DEBUG0x1A,
	F_MAX_FIELDS
पूर्ण;

अटल स्थिर काष्ठा reg_field bd9995x_reg_fields[] = अणु
	    [F_PREV_CHGSTM_STATE] = REG_FIELD(CHGSTM_STATUS, 8, 14),
	    [F_CHGSTM_STATE] = REG_FIELD(CHGSTM_STATUS, 0, 6),
	    [F_VBAT_VSYS_STATUS] = REG_FIELD(VBAT_VSYS_STATUS, 0, 15),
	    [F_VBUS_VCC_STATUS] = REG_FIELD(VBUS_VCC_STATUS, 0, 12),
	    [F_BATTEMP] = REG_FIELD(CHGOP_STATUS, 8, 10),
	    [F_VRECHG_DET] = REG_FIELD(CHGOP_STATUS, 6, 6),
	    [F_RBOOST_UV] = REG_FIELD(CHGOP_STATUS, 1, 1),
	    [F_RBOOSTS] = REG_FIELD(CHGOP_STATUS, 0, 0),
	    [F_THERMWDT_VAL] = REG_FIELD(WDT_STATUS, 8, 15),
	    [F_CHGWDT_VAL] = REG_FIELD(WDT_STATUS, 0, 7),
	    [F_CUR_ILIM_VAL] = REG_FIELD(CUR_ILIM_VAL, 0, 13),
	    [F_SEL_ILIM_VAL] = REG_FIELD(SEL_ILIM_VAL, 0, 13),
	    [F_IBUS_LIM_SET] = REG_FIELD(IBUS_LIM_SET, 5, 13),
	    [F_ICC_LIM_SET] = REG_FIELD(ICC_LIM_SET, 5, 13),
	    [F_IOTG_LIM_SET] = REG_FIELD(IOTG_LIM_SET, 5, 13),
	    [F_OTG_BOTH_EN] = REG_FIELD(VIN_CTRL_SET, 15, 15),
	    [F_VRBOOST_TRIG] = REG_FIELD(VIN_CTRL_SET, 14, 14),
	    [F_VRBOOST_EN] = REG_FIELD(VIN_CTRL_SET, 12, 13),
	    [F_PP_BOTH_THRU] = REG_FIELD(VIN_CTRL_SET, 11, 11),
	    [F_VIN_ORD] = REG_FIELD(VIN_CTRL_SET, 7, 7),
	    [F_VBUS_EN] = REG_FIELD(VIN_CTRL_SET, 6, 6),
	    [F_VCC_EN] = REG_FIELD(VIN_CTRL_SET, 5, 5),
	    [F_VSYS_PRIORITY] = REG_FIELD(VIN_CTRL_SET, 4, 4),
	    [F_PPC_SUB_CAP] = REG_FIELD(VIN_CTRL_SET, 2, 3),
	    [F_PPC_CAP] = REG_FIELD(VIN_CTRL_SET, 0, 1),
	    [F_DCP_2500_SEL] = REG_FIELD(CHGOP_SET1, 15, 15),
	    [F_SDP_500_SEL] = REG_FIELD(CHGOP_SET1, 14, 14),
	    [F_ILIM_AUTO_DISEN] = REG_FIELD(CHGOP_SET1, 13, 13),
	    [F_VCC_BC_DISEN] = REG_FIELD(CHGOP_SET1, 11, 11),
	    [F_VBUS_BC_DISEN] = REG_FIELD(CHGOP_SET1, 10, 10),
	    [F_SDP_CHG_TRIG_EN] = REG_FIELD(CHGOP_SET1, 9, 9),
	    [F_SDP_CHG_TRIG] = REG_FIELD(CHGOP_SET1, 8, 8),
	    [F_AUTO_TOF] = REG_FIELD(CHGOP_SET1, 6, 6),
	    [F_AUTO_FST] = REG_FIELD(CHGOP_SET1, 5, 5),
	    [F_AUTO_RECH] = REG_FIELD(CHGOP_SET1, 3, 3),
	    [F_ILIM_RESET_EN] = REG_FIELD(CHGOP_SET2, 14, 14),
	    [F_DCDC_1MS_SEL] = REG_FIELD(CHGOP_SET2, 12, 13),
	    [F_SEL_ILIM_DIV] = REG_FIELD(CHGOP_SET2, 10, 10),
	    [F_BATT_LEARN] = REG_FIELD(CHGOP_SET2, 8, 8),
	    [F_CHG_EN] = REG_FIELD(CHGOP_SET2, 7, 7),
	    [F_USB_SUS] = REG_FIELD(CHGOP_SET2, 6, 6),
	    [F_CHOP_SS_INIT] = REG_FIELD(CHGOP_SET2, 5, 5),
	    [F_CHOP_ALL_INIT] = REG_FIELD(CHGOP_SET2, 4, 4),
	    [F_DCDC_CLK_SEL] = REG_FIELD(CHGOP_SET2, 2, 3),
	    [F_CHOP_SS] = REG_FIELD(CHGOP_SET2, 1, 1),
	    [F_CHOP_ALL] = REG_FIELD(CHGOP_SET2, 0, 0),
	    [F_VBUSCLPS_TH_SET] = REG_FIELD(VBUSCLPS_TH_SET, 7, 14),
	    [F_VCCCLPS_TH_SET] = REG_FIELD(VCCCLPS_TH_SET, 7, 14),
	    [F_WDT_FST] = REG_FIELD(CHGWDT_SET, 8, 15),
	    [F_WDT_PRE] = REG_FIELD(CHGWDT_SET, 0, 7),
	    [F_WDT_IBAT_SHORT] = REG_FIELD(BATTWDT_SET, 8, 15),
	    [F_WDT_THERM] = REG_FIELD(BATTWDT_SET, 0, 7),
	    [F_VSYSREG_SET] = REG_FIELD(VSYSREG_SET, 6, 14),
	    [F_VSYSVAL_THH_SET] = REG_FIELD(VSYSVAL_THH_SET, 6, 14),
	    [F_VSYSVAL_THL_SET] = REG_FIELD(VSYSVAL_THL_SET, 6, 14),
	    [F_ITRICH_SET] = REG_FIELD(ITRICH_SET, 6, 10),
	    [F_IPRECH_SET] = REG_FIELD(IPRECH_SET, 6, 10),
	    [F_ICHG_SET] = REG_FIELD(ICHG_SET, 6, 13),
	    [F_ITERM_SET] = REG_FIELD(ITERM_SET, 6, 10),
	    [F_VPRECHG_TH_SET] = REG_FIELD(VPRECHG_TH_SET, 6, 14),
	    [F_VRBOOST_SET] = REG_FIELD(VRBOOST_SET, 6, 14),
	    [F_VFASTCHG_REG_SET1] = REG_FIELD(VFASTCHG_REG_SET1, 4, 14),
	    [F_VFASTCHG_REG_SET2] = REG_FIELD(VFASTCHG_REG_SET2, 4, 14),
	    [F_VFASTCHG_REG_SET3] = REG_FIELD(VFASTCHG_REG_SET3, 4, 14),
	    [F_VRECHG_SET] = REG_FIELD(VRECHG_SET, 4, 14),
	    [F_VBATOVP_SET] = REG_FIELD(VBATOVP_SET, 4, 14),
	    [F_IBATM_SHORT_SET] = REG_FIELD(IBATSHORT_SET, 0, 14),
	    [F_PROCHOT_DG_SET] = REG_FIELD(PROCHOT_CTRL_SET, 14, 15),
	    [F_PROCHOT_ICRIT_DG_SET] = REG_FIELD(PROCHOT_CTRL_SET, 10, 11),
	    [F_PROCHOT_IDCHG_DG_SET] = REG_FIELD(PROCHOT_CTRL_SET, 8, 9),
	    [F_PROCHOT_EN] = REG_FIELD(PROCHOT_CTRL_SET, 0, 4),
	    [F_PROCHOT_ICRIT_SET] = REG_FIELD(PROCHOT_ICRIT_SET, 0, 14),
	    [F_PROCHOT_INORM_SET] = REG_FIELD(PROCHOT_INORM_SET, 0, 14),
	    [F_PROCHOT_IDCHG_SET] = REG_FIELD(PROCHOT_IDCHG_SET, 0, 14),
	    [F_PROCHOT_VSYS_SET] = REG_FIELD(PROCHOT_VSYS_SET, 0, 14),
	    [F_IMON_INSEL] = REG_FIELD(PMON_IOUT_CTRL_SET, 9, 9),
	    [F_PMON_INSEL] = REG_FIELD(PMON_IOUT_CTRL_SET, 8, 8),
	    [F_IOUT_OUT_EN] = REG_FIELD(PMON_IOUT_CTRL_SET, 7, 7),
	    [F_IOUT_SOURCE_SEL] = REG_FIELD(PMON_IOUT_CTRL_SET, 6, 6),
	    [F_IOUT_GAIN_SET] = REG_FIELD(PMON_IOUT_CTRL_SET, 4, 5),
	    [F_PMON_OUT_EN] = REG_FIELD(PMON_IOUT_CTRL_SET, 3, 3),
	    [F_PMON_GAIN_SET] = REG_FIELD(PMON_IOUT_CTRL_SET, 0, 2),
	    [F_PMON_DACIN_VAL] = REG_FIELD(PMON_DACIN_VAL, 0, 9),
	    [F_IOUT_DACIN_VAL] = REG_FIELD(IOUT_DACIN_VAL, 0, 11),
	    [F_VCC_BCSRETRY] = REG_FIELD(VCC_UCD_SET, 12, 12),
	    [F_VCC_ADCRTRY] = REG_FIELD(VCC_UCD_SET, 8, 8),
	    [F_VCC_USBDETEN] = REG_FIELD(VCC_UCD_SET, 7, 7),
	    [F_VCC_IDRDETEN] = REG_FIELD(VCC_UCD_SET, 6, 6),
	    [F_VCC_ENUMRDY] = REG_FIELD(VCC_UCD_SET, 5, 5),
	    [F_VCC_ADCPOLEN] = REG_FIELD(VCC_UCD_SET, 4, 4),
	    [F_VCC_DCDMODE] = REG_FIELD(VCC_UCD_SET, 3, 3),
	    [F_VCC_USB_SW_EN] = REG_FIELD(VCC_UCD_SET, 1, 1),
	    [F_VCC_USB_SW] = REG_FIELD(VCC_UCD_SET, 0, 0),
	    [F_VCC_DCDFAIL] = REG_FIELD(VCC_UCD_STATUS, 15, 15),
	    [F_VCC_CHGPORT] = REG_FIELD(VCC_UCD_STATUS, 12, 13),
	    [F_VCC_PUPDET] = REG_FIELD(VCC_UCD_STATUS, 11, 11),
	    [F_VCC_VBUS_VLD] = REG_FIELD(VCC_UCD_STATUS, 7, 7),
	    [F_VCC_CHGDET] = REG_FIELD(VCC_UCD_STATUS, 6, 6),
	    [F_VCC_OTGDET] = REG_FIELD(VCC_UCD_STATUS, 3, 3),
	    [F_VCC_VBINOP] = REG_FIELD(VCC_IDD_STATUS, 6, 6),
	    [F_VCC_EXTID] = REG_FIELD(VCC_IDD_STATUS, 5, 5),
	    [F_VCC_IDRDET] = REG_FIELD(VCC_IDD_STATUS, 4, 4),
	    [F_VCC_INDO] = REG_FIELD(VCC_IDD_STATUS, 0, 3),
	    [F_VCC_UCDSWEN] = REG_FIELD(VCC_UCD_FCTRL_SET, 10, 10),
	    [F_VCC_RREF_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 9, 9),
	    [F_VCC_DPPU_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 8, 8),
	    [F_VCC_DPREF_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 7, 7),
	    [F_VCC_DMREF_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 6, 6),
	    [F_VCC_DPDET_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 5, 5),
	    [F_VCC_DMDET_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 4, 4),
	    [F_VCC_DPSINK_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 3, 3),
	    [F_VCC_DMSINK_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 2, 2),
	    [F_VCC_DP_BUFF_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 1, 1),
	    [F_VCC_DM_BUFF_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 0, 0),
	    [F_VCC_EXTCLKENBL] = REG_FIELD(VCC_UCD_FCTRL_EN, 15, 15),
	    [F_VCC_PLSTESTEN] = REG_FIELD(VCC_UCD_FCTRL_EN, 14, 14),
	    [F_VCC_UCDSWEN_TSTENB] = REG_FIELD(VCC_UCD_FCTRL_EN, 10, 10),
	    [F_VCC_RREF_EN_TSTENB] = REG_FIELD(VCC_UCD_FCTRL_EN, 9, 9),
	    [F_VCC_DPPU_EN_TSTENB] = REG_FIELD(VCC_UCD_FCTRL_EN, 8, 8),
	    [F_VCC_DPREF_EN_TSTENB] = REG_FIELD(VCC_UCD_FCTRL_EN, 7, 7),
	    [F_VCC_DMREF_EN_TSTENB] = REG_FIELD(VCC_UCD_FCTRL_EN, 6, 6),
	    [F_VCC_DPDET_EN_TSTENB] = REG_FIELD(VCC_UCD_FCTRL_EN, 5, 5),
	    [F_VCC_DMDET_EN_TSTENB] = REG_FIELD(VCC_UCD_FCTRL_EN, 4, 4),
	    [F_VCC_DPSINK_EN_TSTENB] = REG_FIELD(VCC_UCD_FCTRL_EN, 3, 3),
	    [F_VCC_DMSINK_EN_TSTENB] = REG_FIELD(VCC_UCD_FCTRL_EN, 2, 2),
	    [F_VCC_DP_BUFF_EN_TSTENB] = REG_FIELD(VCC_UCD_FCTRL_EN, 1, 1),
	    [F_VCC_DM_BUFF_EN_TSTENB] = REG_FIELD(VCC_UCD_FCTRL_EN, 0, 0),

	    [F_VBUS_BCSRETRY] = REG_FIELD(VBUS_UCD_SET, 12, 12),
	    [F_VBUS_ADCRTRY] = REG_FIELD(VBUS_UCD_SET, 8, 8),
	    [F_VBUS_USBDETEN] = REG_FIELD(VBUS_UCD_SET, 7, 7),
	    [F_VBUS_IDRDETEN] = REG_FIELD(VBUS_UCD_SET, 6, 6),
	    [F_VBUS_ENUMRDY] = REG_FIELD(VBUS_UCD_SET, 5, 5),
	    [F_VBUS_ADCPOLEN] = REG_FIELD(VBUS_UCD_SET, 4, 4),
	    [F_VBUS_DCDMODE] = REG_FIELD(VBUS_UCD_SET, 3, 3),
	    [F_VBUS_USB_SW_EN] = REG_FIELD(VBUS_UCD_SET, 1, 1),
	    [F_VBUS_USB_SW] = REG_FIELD(VBUS_UCD_SET, 0, 0),
	    [F_VBUS_DCDFAIL] = REG_FIELD(VBUS_UCD_STATUS, 15, 15),
	    [F_VBUS_CHGPORT] = REG_FIELD(VBUS_UCD_STATUS, 12, 13),
	    [F_VBUS_PUPDET] = REG_FIELD(VBUS_UCD_STATUS, 11, 11),
	    [F_VBUS_VBUS_VLD] = REG_FIELD(VBUS_UCD_STATUS, 7, 7),
	    [F_VBUS_CHGDET] = REG_FIELD(VBUS_UCD_STATUS, 6, 6),
	    [F_VBUS_OTGDET] = REG_FIELD(VBUS_UCD_STATUS, 3, 3),
	    [F_VBUS_VBINOP] = REG_FIELD(VBUS_IDD_STATUS, 6, 6),
	    [F_VBUS_EXTID] = REG_FIELD(VBUS_IDD_STATUS, 5, 5),
	    [F_VBUS_IDRDET] = REG_FIELD(VBUS_IDD_STATUS, 4, 4),
	    [F_VBUS_INDO] = REG_FIELD(VBUS_IDD_STATUS, 0, 3),
	    [F_VBUS_UCDSWEN] = REG_FIELD(VCC_UCD_FCTRL_SET, 10, 10),
	    [F_VBUS_RREF_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 9, 9),
	    [F_VBUS_DPPU_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 8, 8),
	    [F_VBUS_DPREF_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 7, 7),
	    [F_VBUS_DMREF_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 6, 6),
	    [F_VBUS_DPDET_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 5, 5),
	    [F_VBUS_DMDET_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 4, 4),
	    [F_VBUS_DPSINK_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 3, 3),
	    [F_VBUS_DMSINK_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 2, 2),
	    [F_VBUS_DP_BUFF_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 1, 1),
	    [F_VBUS_DM_BUFF_EN] = REG_FIELD(VCC_UCD_FCTRL_SET, 0, 0),

	    [F_VBUS_EXTCLKENBL] = REG_FIELD(VBUS_UCD_FCTRL_EN, 15, 15),
	    [F_VBUS_PLSTESTEN] = REG_FIELD(VBUS_UCD_FCTRL_EN, 14, 14),
	    [F_VBUS_UCDSWEN_TSTENB] = REG_FIELD(VBUS_UCD_FCTRL_EN, 10, 10),
	    [F_VBUS_RREF_EN_TSTENB] = REG_FIELD(VBUS_UCD_FCTRL_EN, 9, 9),
	    [F_VBUS_DPPU_EN_TSTENB] = REG_FIELD(VBUS_UCD_FCTRL_EN, 8, 8),
	    [F_VBUS_DPREF_EN_TSTENB] = REG_FIELD(VBUS_UCD_FCTRL_EN, 7, 7),
	    [F_VBUS_DMREF_EN_TSTENB] = REG_FIELD(VBUS_UCD_FCTRL_EN, 6, 6),
	    [F_VBUS_DPDET_EN_TSTENB] = REG_FIELD(VBUS_UCD_FCTRL_EN, 5, 5),
	    [F_VBUS_DMDET_EN_TSTENB] = REG_FIELD(VBUS_UCD_FCTRL_EN, 4, 4),
	    [F_VBUS_DPSINK_EN_TSTENB] = REG_FIELD(VBUS_UCD_FCTRL_EN, 3, 3),
	    [F_VBUS_DMSINK_EN_TSTENB] = REG_FIELD(VBUS_UCD_FCTRL_EN, 2, 2),
	    [F_VBUS_DP_BUFF_EN_TSTENB] = REG_FIELD(VBUS_UCD_FCTRL_EN, 1, 1),
	    [F_VBUS_DM_BUFF_EN_TSTENB] = REG_FIELD(VBUS_UCD_FCTRL_EN, 0, 0),

	    [F_CHIP_ID] = REG_FIELD(CHIP_ID, 0, 15),
	    [F_CHIP_REV] = REG_FIELD(CHIP_REV, 0, 15),
	    [F_ONE_CELL_MODE] = REG_FIELD(IC_SET1, 11, 11),
	    [F_cell] = REG_FIELD(IC_SET1, 1, 1),
	    [F_VACP_AUTO_DISCHG] = REG_FIELD(IC_SET1, 9, 9),
	    [F_VACP_LOAD] = REG_FIELD(IC_SET1, 8, 8),
	    [F_ACOK_POL] = REG_FIELD(IC_SET1, 1, 1),
	    [F_ACOK_DISEN] = REG_FIELD(IC_SET1, 0, 0),
	    [F_DEBUG_SET1] = REG_FIELD(IC_SET2, 4, 8),
	    [F_DEBUG_SET0] = REG_FIELD(IC_SET2, 0, 0),
	    [F_MONRST_STATE] = REG_FIELD(SYSTEM_STATUS, 6, 6),
	    [F_ALMRST_STATE] = REG_FIELD(SYSTEM_STATUS, 5, 5),
	    [F_CHGRST_STATE] = REG_FIELD(SYSTEM_STATUS, 4, 4),
	    [F_OTPLD_STATE] = REG_FIELD(SYSTEM_STATUS, 1, 1),
	    [F_ALLRST_STATE] = REG_FIELD(SYSTEM_STATUS, 0, 0),
	    [F_PROTECT_SET] = REG_FIELD(PROTECT_SET, 0, 15),
	    [F_MAP_SET] = REG_FIELD(MAP_SET, 0, 15),
	    [F_ADCINTERVAL] = REG_FIELD(VM_CTRL_SET, 14, 15),
	    [F_ADCMOD] = REG_FIELD(VM_CTRL_SET, 12, 13),
	    [F_ADCTMOD] = REG_FIELD(VM_CTRL_SET, 10, 11),
	    [F_EXTIADPEN] = REG_FIELD(VM_CTRL_SET, 9, 9),
	    [F_VSYSENB] = REG_FIELD(VM_CTRL_SET, 8, 8),
	    [F_VCCENB] = REG_FIELD(VM_CTRL_SET, 7, 7),
	    [F_VBUSENB] = REG_FIELD(VM_CTRL_SET, 6, 6),
	    [F_VACPENB] = REG_FIELD(VM_CTRL_SET, 5, 5),
	    [F_IACPENB] = REG_FIELD(VM_CTRL_SET, 4, 4),
	    [F_THERMENB] = REG_FIELD(VM_CTRL_SET, 3, 3),
	    [F_VBATENB] = REG_FIELD(VM_CTRL_SET, 2, 2),
	    [F_IBATMENB] = REG_FIELD(VM_CTRL_SET, 1, 1),
	    [F_IBATPENB] = REG_FIELD(VM_CTRL_SET, 0, 0),
	    [F_TMPTHR1B] = REG_FIELD(THERM_WINDOW_SET1, 8, 15),
	    [F_TMPTHR1A] = REG_FIELD(THERM_WINDOW_SET1, 0, 7),
	    [F_TMPTHR2B] = REG_FIELD(THERM_WINDOW_SET2, 8, 15),
	    [F_TMPTHR2A] = REG_FIELD(THERM_WINDOW_SET2, 0, 7),
	    [F_TMPTHR3B] = REG_FIELD(THERM_WINDOW_SET3, 8, 15),
	    [F_TMPTHR3A] = REG_FIELD(THERM_WINDOW_SET3, 0, 7),
	    [F_TMPTHR4B] = REG_FIELD(THERM_WINDOW_SET4, 8, 15),
	    [F_TMPTHR4A] = REG_FIELD(THERM_WINDOW_SET4, 0, 7),
	    [F_TMPTHR5B] = REG_FIELD(THERM_WINDOW_SET5, 8, 15),
	    [F_TMPTHR5A] = REG_FIELD(THERM_WINDOW_SET5, 0, 7),
	    [F_IBATP_TH_SET] = REG_FIELD(IBATP_TH_SET, 0, 14),
	    [F_IBATM_TH_SET] = REG_FIELD(IBATM_TH_SET, 0, 14),
	    [F_VBAT_TH_SET] = REG_FIELD(VBAT_TH_SET, 0, 14),
	    [F_THERM_TH_SET] = REG_FIELD(THERM_TH_SET, 0, 7),
	    [F_IACP_TH_SET] = REG_FIELD(IACP_TH_SET, 0, 14),
	    [F_VACP_TH_SET] = REG_FIELD(VACP_TH_SET, 0, 14),
	    [F_VBUS_TH_SET] = REG_FIELD(VBUS_TH_SET, 0, 14),
	    [F_VCC_TH_SET] = REG_FIELD(VCC_TH_SET, 0, 14),
	    [F_VSYS_TH_SET] = REG_FIELD(VSYS_TH_SET, 0, 14),
	    [F_EXTIADP_TH_SET] = REG_FIELD(EXTIADP_TH_SET, 0, 11),
	    [F_IBATP_VAL] = REG_FIELD(IBATP_VAL, 0, 14),
	    [F_IBATP_AVE_VAL] = REG_FIELD(IBATP_AVE_VAL, 0, 14),
	    [F_IBATM_VAL] = REG_FIELD(IBATM_VAL, 0, 14),
	    [F_IBATM_AVE_VAL] = REG_FIELD(IBATM_AVE_VAL, 0, 14),
	    [F_VBAT_VAL] = REG_FIELD(VBAT_VAL, 0, 14),
	    [F_VBAT_AVE_VAL] = REG_FIELD(VBAT_AVE_VAL, 0, 14),
	    [F_THERM_VAL] = REG_FIELD(THERM_VAL, 0, 7),
	    [F_VTH_VAL] = REG_FIELD(VTH_VAL, 0, 11),
	    [F_IACP_VAL] = REG_FIELD(IACP_VAL, 0, 14),
	    [F_IACP_AVE_VAL] = REG_FIELD(IACP_AVE_VAL, 0, 14),
	    [F_VACP_VAL] = REG_FIELD(VACP_VAL, 0, 14),
	    [F_VACP_AVE_VAL] = REG_FIELD(VACP_AVE_VAL, 0, 14),
	    [F_VBUS_VAL] = REG_FIELD(VBUS_VAL, 0, 14),
	    [F_VBUS_AVE_VAL] = REG_FIELD(VBUS_AVE_VAL, 0, 14),
	    [F_VCC_VAL] = REG_FIELD(VCC_VAL, 0, 14),
	    [F_VCC_AVE_VAL] = REG_FIELD(VCC_AVE_VAL, 0, 14),
	    [F_VSYS_VAL] = REG_FIELD(VSYS_VAL, 0, 14),
	    [F_VSYS_AVE_VAL] = REG_FIELD(VSYS_AVE_VAL, 0, 14),
	    [F_EXTIADP_VAL] = REG_FIELD(EXTIADP_VAL, 0, 11),
	    [F_EXTIADP_AVE_VAL] = REG_FIELD(EXTIADP_AVE_VAL, 0, 11),
	    [F_VACPCLPS_TH_SET] = REG_FIELD(VACPCLPS_TH_SET, 7, 14),
	    [F_INT7_SET] = REG_FIELD(INT7_SET, 0, 15),
	    [F_INT6_SET] = REG_FIELD(INT6_SET, 0, 13),
	    [F_INT5_SET] = REG_FIELD(INT5_SET, 0, 13),
	    [F_INT4_SET] = REG_FIELD(INT4_SET, 0, 9),
	    [F_INT3_SET] = REG_FIELD(INT3_SET, 0, 15),
	    [F_INT2_SET] = REG_FIELD(INT2_SET, 0, 15),
	    [F_INT1_SET] = REG_FIELD(INT1_SET, 0, 15),
	    [F_INT0_SET] = REG_FIELD(INT0_SET, 0, 7),
	    [F_VBUS_RBUV_DET] = REG_FIELD(INT1_SET, 15, 15),
	    [F_VBUS_RBUV_RES] = REG_FIELD(INT1_SET, 14, 14),
	    [F_VBUS_TH_DET] = REG_FIELD(INT1_SET, 9, 9),
	    [F_VBUS_TH_RES] = REG_FIELD(INT1_SET, 8, 8),
	    [F_VBUS_IIN_MOD] = REG_FIELD(INT1_SET, 6, 6),
	    [F_VBUS_OV_DET] = REG_FIELD(INT1_SET, 5, 5),
	    [F_VBUS_OV_RES] = REG_FIELD(INT1_SET, 4, 4),
	    [F_VBUS_CLPS_DET] = REG_FIELD(INT1_SET, 3, 3),
	    [F_VBUS_CLPS] = REG_FIELD(INT1_SET, 2, 2),
	    [F_VBUS_DET] = REG_FIELD(INT1_SET, 1, 1),
	    [F_VBUS_RES] = REG_FIELD(INT1_SET, 0, 0),
	    [F_VCC_RBUV_DET] = REG_FIELD(INT2_SET, 15, 15),
	    [F_VCC_RBUV_RES] = REG_FIELD(INT2_SET, 14, 14),
	    [F_VCC_TH_DET] = REG_FIELD(INT2_SET, 9, 9),
	    [F_VCC_TH_RES] = REG_FIELD(INT2_SET, 8, 8),
	    [F_VCC_IIN_MOD] = REG_FIELD(INT2_SET, 6, 6),
	    [F_VCC_OVP_DET] = REG_FIELD(INT2_SET, 5, 5),
	    [F_VCC_OVP_RES] = REG_FIELD(INT2_SET, 4, 4),
	    [F_VCC_CLPS_DET] = REG_FIELD(INT2_SET, 3, 3),
	    [F_VCC_CLPS_RES] = REG_FIELD(INT2_SET, 2, 2),
	    [F_VCC_DET] = REG_FIELD(INT2_SET, 1, 1),
	    [F_VCC_RES] = REG_FIELD(INT2_SET, 0, 0),
	    [F_TH_DET] = REG_FIELD(INT3_SET, 15, 15),
	    [F_TH_RMV] = REG_FIELD(INT3_SET, 14, 14),
	    [F_TMP_OUT_DET] = REG_FIELD(INT3_SET, 11, 11),
	    [F_TMP_OUT_RES] = REG_FIELD(INT3_SET, 10, 10),
	    [F_VBAT_TH_DET] = REG_FIELD(INT3_SET, 9, 9),
	    [F_VBAT_TH_RES] = REG_FIELD(INT3_SET, 8, 8),
	    [F_IBAT_SHORT_DET] = REG_FIELD(INT3_SET, 7, 7),
	    [F_IBAT_SHORT_RES] = REG_FIELD(INT3_SET, 6, 6),
	    [F_VBAT_OV_DET] = REG_FIELD(INT3_SET, 5, 5),
	    [F_VBAT_OV_RES] = REG_FIELD(INT3_SET, 4, 4),
	    [F_BAT_ASSIST_DET] = REG_FIELD(INT3_SET, 3, 3),
	    [F_BAT_ASSIST_RES] = REG_FIELD(INT3_SET, 2, 2),
	    [F_VSYS_TH_DET] = REG_FIELD(INT4_SET, 9, 9),
	    [F_VSYS_TH_RES] = REG_FIELD(INT4_SET, 8, 8),
	    [F_VSYS_OV_DET] = REG_FIELD(INT4_SET, 5, 5),
	    [F_VSYS_OV_RES] = REG_FIELD(INT4_SET, 4, 4),
	    [F_VSYS_SHT_DET] = REG_FIELD(INT4_SET, 3, 3),
	    [F_VSYS_SHT_RES] = REG_FIELD(INT4_SET, 2, 2),
	    [F_VSYS_UV_DET] = REG_FIELD(INT4_SET, 1, 1),
	    [F_VSYS_UV_RES] = REG_FIELD(INT4_SET, 0, 0),
	    [F_OTP_LOAD_DONE] = REG_FIELD(INT5_SET, 13, 13),
	    [F_PWR_ON] = REG_FIELD(INT5_SET, 12, 12),
	    [F_EXTIADP_TRNS] = REG_FIELD(INT5_SET, 11, 11),
	    [F_EXTIADP_TH_DET] = REG_FIELD(INT5_SET, 9, 9),
	    [F_EXIADP_TH_RES] = REG_FIELD(INT5_SET, 8, 8),
	    [F_BAT_MNT_DET] = REG_FIELD(INT5_SET, 7, 7),
	    [F_BAT_MNT_RES] = REG_FIELD(INT5_SET, 6, 6),
	    [F_TSD_DET] = REG_FIELD(INT5_SET, 5, 5),
	    [F_TSD_RES] = REG_FIELD(INT5_SET, 4, 4),
	    [F_CHGWDT_EXP] = REG_FIELD(INT5_SET, 3, 3),
	    [F_THERMWDT_EXP] = REG_FIELD(INT5_SET, 2, 2),
	    [F_TMP_TRNS] = REG_FIELD(INT5_SET, 1, 1),
	    [F_CHG_TRNS] = REG_FIELD(INT5_SET, 0, 0),
	    [F_VBUS_UCD_PORT_DET] = REG_FIELD(INT6_SET, 13, 13),
	    [F_VBUS_UCD_UCHG_DET] = REG_FIELD(INT6_SET, 12, 12),
	    [F_VBUS_UCD_URID_RMV] = REG_FIELD(INT6_SET, 11, 11),
	    [F_VBUS_UCD_OTG_DET] = REG_FIELD(INT6_SET, 10, 10),
	    [F_VBUS_UCD_URID_MOD] = REG_FIELD(INT6_SET, 8, 8),
	    [F_VCC_UCD_PORT_DET] = REG_FIELD(INT6_SET, 5, 5),
	    [F_VCC_UCD_UCHG_DET] = REG_FIELD(INT6_SET, 4, 4),
	    [F_VCC_UCD_URID_RMV] = REG_FIELD(INT6_SET, 3, 3),
	    [F_VCC_UCD_OTG_DET] = REG_FIELD(INT6_SET, 2, 2),
	    [F_VCC_UCD_URID_MOD] = REG_FIELD(INT6_SET, 0, 0),
	    [F_PROCHOT_DET] = REG_FIELD(INT7_SET, 15, 15),
	    [F_PROCHOT_RES] = REG_FIELD(INT7_SET, 14, 14),
	    [F_VACP_DET] = REG_FIELD(INT7_SET, 11, 11),
	    [F_VACP_RES] = REG_FIELD(INT7_SET, 10, 10),
	    [F_VACP_TH_DET] = REG_FIELD(INT7_SET, 9, 9),
	    [F_VACP_TH_RES] = REG_FIELD(INT7_SET, 8, 8),
	    [F_IACP_TH_DET] = REG_FIELD(INT7_SET, 7, 7),
	    [F_IACP_THE_RES] = REG_FIELD(INT7_SET, 6, 6),
	    [F_THERM_TH_DET] = REG_FIELD(INT7_SET, 5, 5),
	    [F_THERM_TH_RES] = REG_FIELD(INT7_SET, 4, 4),
	    [F_IBATM_TH_DET] = REG_FIELD(INT7_SET, 3, 3),
	    [F_IBATM_TH_RES] = REG_FIELD(INT7_SET, 2, 2),
	    [F_IBATP_TH_DET] = REG_FIELD(INT7_SET, 1, 1),
	    [F_IBATP_TH_RES] = REG_FIELD(INT7_SET, 0, 0),
	    [F_INT7_STATUS] = REG_FIELD(INT7_STATUS, 0, 15),
	    [F_INT6_STATUS] = REG_FIELD(INT6_STATUS, 0, 13),
	    [F_INT5_STATUS] = REG_FIELD(INT5_STATUS, 0, 13),
	    [F_INT4_STATUS] = REG_FIELD(INT4_STATUS, 0, 9),
	    [F_INT3_STATUS] = REG_FIELD(INT3_STATUS, 0, 15),
	    [F_INT2_STATUS] = REG_FIELD(INT2_STATUS, 0, 15),
	    [F_INT1_STATUS] = REG_FIELD(INT1_STATUS, 0, 15),
	    [F_INT0_STATUS] = REG_FIELD(INT0_STATUS, 0, 7),
	    [F_ILIM_DECREASE] = REG_FIELD(OTPREG0, 0, 15),
	    [F_RESERVE_OTPREG1] = REG_FIELD(OTPREG1, 0, 15),
	    [F_POWER_SAVE_MODE] = REG_FIELD(SMBREG, 0, 15),
	    [F_DEBUG_MODE_SET] = REG_FIELD(DEBUG_MODE_SET, 0, 15),
	    [F_DEBUG0x14] = REG_FIELD(DEBUG0x14, 0, 15),
	    [F_DEBUG0x1A] = REG_FIELD(DEBUG0x1A, 0, 15),
पूर्ण;

/* CHGSTM_STATEs */
#घोषणा CHGSTM_SUSPEND 0x00
#घोषणा CHGSTM_TRICKLE_CHARGE 0x01
#घोषणा CHGSTM_PRE_CHARGE 0x02
#घोषणा CHGSTM_FAST_CHARGE 0x03
#घोषणा CHGSTM_TOP_OFF 0x04
#घोषणा CHGSTM_DONE 0x05
#घोषणा CHGSTM_OTG 0x08
#घोषणा CHGSTM_OTG_DONE 0x09
#घोषणा CHGSTM_TEMPERATURE_ERROR_1 0x10
#घोषणा CHGSTM_TEMPERATURE_ERROR_2 0x11
#घोषणा CHGSTM_TEMPERATURE_ERROR_3 0x12
#घोषणा CHGSTM_TEMPERATURE_ERROR_4 0x13
#घोषणा CHGSTM_TEMPERATURE_ERROR_5 0x14
#घोषणा CHGSTM_TEMPERATURE_ERROR_6 0x15
#घोषणा CHGSTM_TEMPERATURE_ERROR_7 0x18
#घोषणा CHGSTM_THERMAL_SHUT_DOWN_1 0x20
#घोषणा CHGSTM_THERMAL_SHUT_DOWN_2 0x21
#घोषणा CHGSTM_THERMAL_SHUT_DOWN_3 0x22
#घोषणा CHGSTM_THERMAL_SHUT_DOWN_4 0x23
#घोषणा CHGSTM_THERMAL_SHUT_DOWN_5 0x24
#घोषणा CHGSTM_THERMAL_SHUT_DOWN_6 0x25
#घोषणा CHGSTM_THERMAL_SHUT_DOWN_7 0x28
#घोषणा CHGSTM_BATTERY_ERROR 0x40

/* VBAT_VSYS_STATUS */
#घोषणा STATUS_VSYS_OV BIT(15)
#घोषणा STATUS_VSYS_SSD BIT(14)
#घोषणा STATUS_VSYS_SCP BIT(13)
#घोषणा STATUS_VSYS_UVN BIT(12)
#घोषणा STATUS_IBAT_SHORT BIT(6)
#घोषणा STATUS_VBAT_OV BIT(3)
#घोषणा STATUS_DEAD_BAT BIT(0)

/* VBUS_VCC_STATUS */
#घोषणा STATUS_VACP_DET BIT(12)
#घोषणा STATUS_VCC_OVP BIT(11)
#घोषणा STATUS_ILIM_VCC_MOD BIT(10)
#घोषणा STATUS_VCC_CLPS BIT(9)
#घोषणा STATUS_VCC_DET BIT(8)
#घोषणा STATUS_VBUS_OVP BIT(3)
#घोषणा STATUS_ILIM_VBUS_MOD BIT(2)
#घोषणा STATUS_VBUS_CLPS BIT(1)
#घोषणा STATUS_VBUS_DET BIT(0)

/* Interrupt set/status definitions */

/* INT 0 */
#घोषणा INT0_INT7_STATUS BIT(7)
#घोषणा INT0_INT6_STATUS BIT(6)
#घोषणा INT0_INT5_STATUS BIT(5)
#घोषणा INT0_INT4_STATUS BIT(4)
#घोषणा INT0_INT3_STATUS BIT(3)
#घोषणा INT0_INT2_STATUS BIT(2)
#घोषणा INT0_INT1_STATUS BIT(1)
#घोषणा INT0_INT0_STATUS BIT(0)
#घोषणा INT0_ALL 0xff

/* INT 1 */
#घोषणा VBUS_RBUV_DET BIT(15)
#घोषणा VBUS_RBUV_RES BIT(14)
#घोषणा VBUS_TH_DET BIT(9)
#घोषणा VBUS_TH_RES BIT(8)
#घोषणा VBUS_IIN_MOD BIT(6)
#घोषणा VBUS_OV_DET BIT(5)
#घोषणा VBUS_OV_RES BIT(4)
#घोषणा VBUS_CLPS_DET BIT(3)
#घोषणा VBUS_CLPS BIT(2)
#घोषणा VBUS_DET BIT(1)
#घोषणा VBUS_RES BIT(0)
#घोषणा INT1_ALL (VBUS_RBUV_DET|\
		 VBUS_RBUV_RES|\
		 VBUS_TH_DET |\
		 VBUS_TH_RES |\
		 VBUS_IIN_MOD|\
		 VBUS_OV_DET |\
		 VBUS_OV_RES |\
		 VBUS_CLPS_DET |\
		 VBUS_CLPS |\
		 VBUS_DET |\
		 VBUS_RES)

/* INT 2 */
#घोषणा VCC_RBUV_DET BIT(15)
#घोषणा VCC_RBUV_RES BIT(14)
#घोषणा VCC_TH_DET BIT(9)
#घोषणा VCC_TH_RES BIT(8)
#घोषणा VCC_IIN_MOD BIT(6)
#घोषणा VCC_OVP_DET BIT(5)
#घोषणा VCC_OVP_RES BIT(4)
#घोषणा VCC_CLPS_DET BIT(3)
#घोषणा VCC_CLPS_RES BIT(2)
#घोषणा VCC_DET BIT(1)
#घोषणा VCC_RES BIT(0)
#घोषणा INT2_ALL (VCC_RBUV_DET |\
		 VCC_RBUV_RES |\
		 VCC_TH_DET |\
		 VCC_TH_RES |\
		 VCC_IIN_MOD |\
		 VCC_OVP_DET |\
		 VCC_OVP_RES |\
		 VCC_CLPS_DET |\
		 VCC_CLPS_RES |\
		 VCC_DET |\
		 VCC_RES)
/* INT 3 */
#घोषणा TH_DET BIT(15)
#घोषणा TH_RMV BIT(14)
#घोषणा TMP_OUT_DET BIT(11)
#घोषणा TMP_OUT_RES BIT(10)
#घोषणा VBAT_TH_DET BIT(9)
#घोषणा VBAT_TH_RES BIT(8)
#घोषणा IBAT_SHORT_DET BIT(7)
#घोषणा IBAT_SHORT_RES BIT(6)
#घोषणा VBAT_OV_DET BIT(5)
#घोषणा VBAT_OV_RES BIT(4)
#घोषणा BAT_ASSIST_DET BIT(3)
#घोषणा BAT_ASSIST_RES BIT(2)
#घोषणा INT3_ALL (TH_DET |\
		 TH_RMV |\
		 TMP_OUT_DET |\
		 TMP_OUT_RES |\
		 VBAT_TH_DET |\
		 VBAT_TH_RES |\
		 IBAT_SHORT_DET |\
		 IBAT_SHORT_RES |\
		 VBAT_OV_DET |\
		 VBAT_OV_RES |\
		 BAT_ASSIST_DET |\
		 BAT_ASSIST_RES)

/* INT 4 */
#घोषणा VSYS_TH_DET BIT(9)
#घोषणा VSYS_TH_RES BIT(8)
#घोषणा VSYS_OV_DET BIT(5)
#घोषणा VSYS_OV_RES BIT(4)
#घोषणा VSYS_SHT_DET BIT(3)
#घोषणा VSYS_SHT_RES BIT(2)
#घोषणा VSYS_UV_DET BIT(1)
#घोषणा VSYS_UV_RES BIT(0)
#घोषणा INT4_ALL (VSYS_TH_DET |\
		 VSYS_TH_RES |\
		 VSYS_OV_DET |\
		 VSYS_OV_RES |\
		 VSYS_SHT_DET |\
		 VSYS_SHT_RES |\
		 VSYS_UV_DET |\
		 VSYS_UV_RES)

/* INT 5*/
#घोषणा OTP_LOAD_DONE BIT(13)
#घोषणा PWR_ON BIT(12)
#घोषणा EXTIADP_TRNS BIT(11)
#घोषणा EXTIADP_TH_DET BIT(9)
#घोषणा EXIADP_TH_RES BIT(8)
#घोषणा BAT_MNT_DET BIT(7)
#घोषणा BAT_MNT_RES BIT(6)
#घोषणा TSD_DET BIT(5)
#घोषणा TSD_RES BIT(4)
#घोषणा CHGWDT_EXP BIT(3)
#घोषणा THERMWDT_EXP BIT(2)
#घोषणा TMP_TRNS BIT(1)
#घोषणा CHG_TRNS BIT(0)
#घोषणा INT5_ALL (OTP_LOAD_DONE |\
		 PWR_ON |\
		 EXTIADP_TRNS |\
		 EXTIADP_TH_DET |\
		 EXIADP_TH_RES |\
		 BAT_MNT_DET |\
		 BAT_MNT_RES |\
		 TSD_DET |\
		 TSD_RES |\
		 CHGWDT_EXP |\
		 THERMWDT_EXP |\
		 TMP_TRNS |\
		 CHG_TRNS)

/* INT 6*/
#घोषणा VBUS_UCD_PORT_DET BIT(13)
#घोषणा VBUS_UCD_UCHG_DET BIT(12)
#घोषणा VBUS_UCD_URID_RMV BIT(11)
#घोषणा VBUS_UCD_OTG_DET BIT(10)
#घोषणा VBUS_UCD_URID_MOD BIT(8)
#घोषणा VCC_UCD_PORT_DET BIT(5)
#घोषणा VCC_UCD_UCHG_DET BIT(4)
#घोषणा VCC_UCD_URID_RMV BIT(3)
#घोषणा VCC_UCD_OTG_DET BIT(2)
#घोषणा VCC_UCD_URID_MOD BIT(0)
#घोषणा INT6_ALL (VBUS_UCD_PORT_DET |\
		 VBUS_UCD_UCHG_DET |\
		 VBUS_UCD_URID_RMV |\
		 VBUS_UCD_OTG_DET |\
		 VBUS_UCD_URID_MOD |\
		 VCC_UCD_PORT_DET |\
		 VCC_UCD_UCHG_DET |\
		 VCC_UCD_URID_RMV |\
		 VCC_UCD_OTG_DET |\
		 VCC_UCD_URID_MOD)

/* INT 7 */
#घोषणा PROCHOT_DET BIT(15)
#घोषणा PROCHOT_RES BIT(14)
#घोषणा VACP_DET BIT(11)
#घोषणा VACP_RES BIT(10)
#घोषणा VACP_TH_DET BIT(9)
#घोषणा VACP_TH_RES BIT(8)
#घोषणा IACP_TH_DET BIT(7)
#घोषणा IACP_THE_RES BIT(6)
#घोषणा THERM_TH_DET BIT(5)
#घोषणा THERM_TH_RES BIT(4)
#घोषणा IBATM_TH_DET BIT(3)
#घोषणा IBATM_TH_RES BIT(2)
#घोषणा IBATP_TH_DET BIT(1)
#घोषणा IBATP_TH_RES BIT(0)
#घोषणा INT7_ALL (PROCHOT_DET |\
		 PROCHOT_RES |\
		 VACP_DET |\
		 VACP_RES |\
		 VACP_TH_DET |\
		 VACP_TH_RES |\
		 IACP_TH_DET |\
		 IACP_THE_RES |\
		 THERM_TH_DET |\
		 THERM_TH_RES |\
		 IBATM_TH_DET |\
		 IBATM_TH_RES |\
		 IBATP_TH_DET |\
		 IBATP_TH_RES)

/* SYSTEM_CTRL_SET*/
#घोषणा MONRST BIT(6)
#घोषणा ALMRST BIT(5)
#घोषणा CHGRST BIT(4)
#घोषणा OTPLD  BIT(1)
#घोषणा ALLRST BIT(0)

/* F_BATTEMP */
#घोषणा ROOM		0x0
#घोषणा HOT1		0x1
#घोषणा HOT2		0x2
#घोषणा HOT3		0x3
#घोषणा COLD1		0x4
#घोषणा COLD2		0x5
#घोषणा TEMP_DIS	0x6
#घोषणा BATT_OPEN	0x7

#पूर्ण_अगर
