<शैली गुरु>
// SPDX-License-Identअगरier: GPL-2.0-or-later
/*
 * This file was generated स्वतःmatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of Context.xs. Do not edit this file, edit Context.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 */
#समावेश <stdbool.h>
#अगर_अघोषित HAS_BOOL
# define HAS_BOOL 1
#पूर्ण_अगर
#पंक्ति 1 "Context.xs"
/*
 * Context.xs.  XS पूर्णांकerfaces क्रम perf script.
 *
 * Copyright (C) 2009 Tom Zanussi <tzanussi@gmail.com>
 */

#समावेश "EXTERN.h"
#समावेश "perl.h"
#समावेश "XSUB.h"
#समावेश "../../../util/trace-event.h"

#अगर_अघोषित PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) अगर (0) var = var
#पूर्ण_अगर

#पंक्ति 42 "Context.c"

XS(XS_Perf__Trace__Context_common_pc); /* prototype to pass -Wmissing-prototypes */
XS(XS_Perf__Trace__Context_common_pc)
अणु
#अगर_घोषित dVAR
    dVAR; dXSARGS;
#अन्यथा
    dXSARGS;
#पूर्ण_अगर
    अगर (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Perf::Trace::Context::common_pc", "context");
    PERL_UNUSED_VAR(cv); /* -W */
    अणु
	काष्ठा scripting_context *	context = INT2PTR(काष्ठा scripting_context *,SvIV(ST(0)));
	पूर्णांक	RETVAL;
	dXSTARG;

	RETVAL = common_pc(context);
	XSprePUSH; PUSHi((IV)RETVAL);
    पूर्ण
    XSRETURN(1);
पूर्ण


XS(XS_Perf__Trace__Context_common_flags); /* prototype to pass -Wmissing-prototypes */
XS(XS_Perf__Trace__Context_common_flags)
अणु
#अगर_घोषित dVAR
    dVAR; dXSARGS;
#अन्यथा
    dXSARGS;
#पूर्ण_अगर
    अगर (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Perf::Trace::Context::common_flags", "context");
    PERL_UNUSED_VAR(cv); /* -W */
    अणु
	काष्ठा scripting_context *	context = INT2PTR(काष्ठा scripting_context *,SvIV(ST(0)));
	पूर्णांक	RETVAL;
	dXSTARG;

	RETVAL = common_flags(context);
	XSprePUSH; PUSHi((IV)RETVAL);
    पूर्ण
    XSRETURN(1);
पूर्ण


XS(XS_Perf__Trace__Context_common_lock_depth); /* prototype to pass -Wmissing-prototypes */
XS(XS_Perf__Trace__Context_common_lock_depth)
अणु
#अगर_घोषित dVAR
    dVAR; dXSARGS;
#अन्यथा
    dXSARGS;
#पूर्ण_अगर
    अगर (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "Perf::Trace::Context::common_lock_depth", "context");
    PERL_UNUSED_VAR(cv); /* -W */
    अणु
	काष्ठा scripting_context *	context = INT2PTR(काष्ठा scripting_context *,SvIV(ST(0)));
	पूर्णांक	RETVAL;
	dXSTARG;

	RETVAL = common_lock_depth(context);
	XSprePUSH; PUSHi((IV)RETVAL);
    पूर्ण
    XSRETURN(1);
पूर्ण

#अगर_घोषित __cplusplus
बाह्य "C"
#पूर्ण_अगर
XS(boot_Perf__Trace__Context); /* prototype to pass -Wmissing-prototypes */
XS(boot_Perf__Trace__Context)
अणु
#अगर_घोषित dVAR
    dVAR; dXSARGS;
#अन्यथा
    dXSARGS;
#पूर्ण_अगर
    स्थिर अक्षर* file = __खाता__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXSproto("Perf::Trace::Context::common_pc", XS_Perf__Trace__Context_common_pc, file, "$");
        newXSproto("Perf::Trace::Context::common_flags", XS_Perf__Trace__Context_common_flags, file, "$");
        newXSproto("Perf::Trace::Context::common_lock_depth", XS_Perf__Trace__Context_common_lock_depth, file, "$");
    अगर (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
पूर्ण

